        PROGRAM OLMCON
          IMPLICIT NONE

          INCLUDE 'INCLIB:DESTRA.DEF'
          
          INTEGER*4 I4TEMP
          INTEGER*2 I2TEMP(2)
          BYTE      I1TEMP(4)
          EQUIVALENCE(I4TEMP,I2TEMP,I1TEMP) 
          INTEGER*4 LOGBUF(16*3)     
          INTEGER*8  MESSID
          REAL*16     OVER8BYTES
          PARAMETER  (OVER8BYTES = 18446744073709551616.0)        
          REAL*16     SERIALNUM_OLM
          REAL*16     SERIALNUM_OLM_INIT
          CHARACTER*24  SERIALNUM_OLMSTR,  SERIAL_AUX    
          INTEGER*4  PUNIT  

          INTEGER*4 I4TEMP_AUX
          INTEGER*2 I2TEMP_AUX(2)
          BYTE      I1TEMP_AUX(4)
          EQUIVALENCE (I4TEMP_AUX,I2TEMP_AUX,I1TEMP_AUX)     
          
          INTEGER*8  I8TMP
          INTEGER*4  I4TMP(2)
          EQUIVALENCE (I8TMP,I4TMP)
          
          DATA PUNIT/7/
          
C          I4TEMP = 65535

C          PRINT *, '1 Value of I1TEMP pos 1',I1TEMP(1) 
C          PRINT *, '1 Value of I1TEMP pos 2',I1TEMP(2) 
C          PRINT *, '1 Value of I1TEMP pos 3',I1TEMP(3) 
C          PRINT *, '1 Value of I1TEMP pos 4',I1TEMP(4)
C          PRINT *, '1 Integer Value of I1TEMP pos',I4TEMP
C
C          I4TEMP = 1
C          PRINT *, 'Value of I1TEMP pos 1',I1TEMP(1) 
C          PRINT *, 'Value of I1TEMP pos 2',I1TEMP(2) 
C          PRINT *, 'Value of I1TEMP pos 3',I1TEMP(3) 
C          PRINT *, 'Value of I1TEMP pos 4',I1TEMP(4)


CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
ccc       B6831AF4316DB4162 - 210422159567289532770
          TRABUF(TVOLMSERL_IL) = 383467874 !16DB4162
          TRABUF(TVOLMSERM_IL) = 1748086595 !6831AF43
          TRABUF(TVOLMSERH_IL) = 11 !B      
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          TRABUF(TIVENV) = 98      
C          I4TEMP = 558528
          I4TEMP = TRABUF(TVOLMSERL_IL)
          I1TEMP(4) = I1TEMP(3) 
          I1TEMP(3) = I1TEMP(2)             
          I1TEMP(2) = I1TEMP(1)
          I1TEMP(1) = TRABUF(TIVENV)

          PRINT *, '3Bytes Serial:',I4TEMP
          TRABUF(TVOLMCOMF_IL) = 1
          I1TEMP(1)  = IOR( ISHFT( TRABUF(TVOLMCOMF_IL), 7),
     *                       IAND( I1TEMP(1),'7F'X) )
          PRINT *, 'flag 1:',ISHFT( TRABUF(TVOLMCOMF_IL), 7)  
          PRINT *, 'TIVENV:',IAND( I1TEMP(1),'7F'X)   
C          PRINT *, 'tudo:',I1TEMP(1)
          LOGBUF(9) = I4TEMP
          PRINT *, '3Bytes Serial:',LOGBUF(9)      
          PRINT *, 'flag:',ISHFT(I1TEMP(1), -7)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          I4TEMP = TRABUF(TVOLMSERL_IL)    
          I1TEMP_AUX(1) = I1TEMP(4)
          I4TEMP = TRABUF(TVOLMSERM_IL)
C          I1TEMP(4) = 0
          I1TEMP(4) = 1234
          I1TEMP(3) = I1TEMP(2)
          I1TEMP(2) = I1TEMP(1)
          I1TEMP(1) = I1TEMP_AUX(1)
          LOGBUF(32) = I4TEMP

          I4TEMP = TRABUF(TVOLMSERM_IL)       
          I1TEMP_AUX(1) = I1TEMP(3)
          I1TEMP_AUX(2) = I1TEMP(4)
          I1TEMP_AUX(3) = TRABUF(TVOLMSERH_IL)
          I1TEMP(1) = I1TEMP_AUX(1)
          I1TEMP(2) = I1TEMP_AUX(2)
          I1TEMP(3) = I1TEMP_AUX(3)
          I1TEMP(4) = 0
          LOGBUF(31) = I4TEMP
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          TRABUF(TVOLMSERL_IL) = 0
          TRABUF(TVOLMSERM_IL) = 0
          TRABUF(TVOLMSERH_IL) = 0       
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          I4TEMP =  LOGBUF(9)
          IF(ISHFT(I1TEMP(1), -7) .EQ. 1) THEN
                TRABUF(TVOLMSERL_IL) =  ISHFT(I4TEMP, -8)
                TRABUF(TVOLMCOMF_IL) =  ISHFT(ZEXT(I1TEMP(1)), -7) 
                TRABUF(TIVENV) = IAND(I1TEMP(1),'7F'X)

                PRINT *, 'Channel flag value:',TRABUF(TVOLMCOMF_IL)
                PRINT *, 'Value of TIVENV:',TRABUF(TIVENV)
                PRINT *, 'Value of TVOLMSERL_IL:',TRABUF(TVOLMSERL_IL)
          ELSE
                PRINT *, 'Error'
          ENDIF
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          I4TEMP = LOGBUF(32)
          TRABUF(TVOLMSERL_IL) = IOR( TRABUF(TVOLMSERL_IL), ISHFT( IAND( I4TEMP,'FF'X), 24) )
          TRABUF(TVOLMSERM_IL) = ISHFT(I4TEMP, -8)
          I4TEMP = LOGBUF(31)
          TRABUF(TVOLMSERM_IL) = IOR( ISHFT(IAND( I4TEMP,'FFFF'X), 16), TRABUF(TVOLMSERM_IL) )
          TRABUF(TVOLMSERH_IL) = ZEXT( I1TEMP(3) )    
          
          PRINT *, 'Value of TVOLMSERL_IL:',TRABUF(TVOLMSERL_IL)
          PRINT *, 'Value of TVOLMSERM_IL:',TRABUF(TVOLMSERM_IL)
          PRINT *, 'Value of TVOLMSERH_IL:',TRABUF(TVOLMSERH_IL)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        I4TMP(1) = ZEXT(TRABUF(TVOLMSERL_IL))
        I4TMP(2) = ZEXT(TRABUF(TVOLMSERM_IL))

        SERIALNUM_OLM = DFLOAT(ZEXT(TRABUF(TVOLMSERH_IL)))*OVER8BYTES+DFLOAT(I8TMP)
        WRITE(SERIAL_AUX,990) SERIALNUM_OLM          
        SERIALNUM_OLMSTR = SERIAL_AUX(1:6)//'-'//SERIAL_AUX(7:8)//'-'//SERIAL_AUX(9:18)//'-'//SERIAL_AUX(19:21)           

        PRINT 980, SERIALNUM_OLMSTR
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC          

C          CALL OPS_AUX('Value of I1TEMP pos 1',I1TEMP(1),I1TEMP(1)) 
C          CALL OPS_AUX('Value of I1TEMP pos 2',I1TEMP(2),I1TEMP(2)) 
C          CALL OPS_AUX('Value of I1TEMP pos 3',I1TEMP(3),I1TEMP(3)) 
C          CALL OPS_AUX('Value of I1TEMP pos 4',I1TEMP(4),I1TEMP(4))
980     FORMAT('OLM Serial # > ',A)
990     FORMAT(F22.0)
          
        END

        SUBROUTINE OPS_AUX(STRING,INTVAL,HEXVAL)
          IMPLICIT NONE  

          CHARACTER*(*) STRING
          INTEGER*4     INTVAL
          INTEGER*4     HEXVAL

          CHARACTER*132 BUFFER
          CHARACTER*50  TEXT   
          
          TEXT=STRING

          WRITE(UNIT=BUFFER,FMT=900) TEXT, INTVAL,HEXVAL
900	  FORMAT(A,':I[',I11,']H[',Z8,']')

        END