GRANT SELECT, INSERT, UPDATE ON HERA.T_reason_entity_status TO RL_HERA_BATCH;
GRANT SELECT, INSERT, UPDATE ON HERA.T_game_parameter TO RL_HERA_BATCH;
GRANT SELECT, INSERT, UPDATE ON HERA.T_game_parameter_hist TO RL_HERA_BATCH;
GRANT SELECT, INSERT, UPDATE ON HERA.T_terminal_session_hist TO RL_HERA_BATCH;
GRANT SELECT, INSERT, UPDATE ON HERA.T_terminal_sequence TO RL_HERA_BATCH;

GRANT SELECT, INSERT, UPDATE ON HERA.T_reason_entity_status TO RL_HERA_SEARCH;
GRANT SELECT, INSERT, UPDATE ON HERA.T_game_parameter TO RL_HERA_SEARCH;
GRANT SELECT, INSERT, UPDATE ON HERA.T_game_parameter_hist TO RL_HERA_SEARCH;
GRANT SELECT, INSERT, UPDATE ON HERA.T_terminal_session_hist TO RL_HERA_SEARCH;
GRANT SELECT, INSERT, UPDATE ON HERA.T_terminal_sequence TO RL_HERA_SEARCH;