code --install-extension asf.apache-netbeans-java --force &
code --install-extension batisteo.vscode-django --force &
code --install-extension bdavs.expect --force &
code --install-extension cschlosser.doxdocgen --force &
code --install-extension eamodio.gitlens --force &
code --install-extension Gimly81.fortran --force &
code --install-extension hansec.fortran-ls --force &
code --install-extension iSorp.macro-executor --force &
code --install-extension James-Yu.latex-workshop --force &
code --install-extension jeff-hykin.better-cpp-syntax --force &
code --install-extension krvajalm.linter-gfortran --force &
code --install-extension mikestead.dotenv --force &
code --install-extension ms-vscode-remote.remote-containers --force &
code --install-extension ms-vscode-remote.remote-ssh --force &
code --install-extension ms-vscode-remote.remote-ssh-edit --force &
code --install-extension ms-vscode-remote.remote-wsl --force &
code --install-extension ms-vscode-remote.vscode-remote-extensionpack --force &
code --install-extension ms-vscode.cmake-tools --force &
code --install-extension ms-vscode.cpptools --force &
code --install-extension ms-vscode.cpptools-extension-pack --force &
code --install-extension ms-vscode.cpptools-themes --force &
code --install-extension ms-vscode.notepadplusplus-keybindings --force &
code --install-extension ms-vscode.powershell --force &
code --install-extension ms-vscode.vscode-typescript-tslint-plugin --force &
code --install-extension nobuhito.printcode --force &
code --install-extension qrti.funclist --force &
code --install-extension redhat.java --force &
code --install-extension tomesparon.openvms-syntax --force &
code --install-extension tomoki1207.pdf --force &
code --install-extension twxs.cmake --force &
code --install-extension VisualStudioExptTeam.vscodeintellicode --force &
code --install-extension VMSSoftwareInc.vms-ide --force &
code --install-extension vscjava.vscode-java-debug --force &
code --install-extension vscjava.vscode-java-dependency --force &
code --install-extension vscjava.vscode-java-pack --force &
code --install-extension vscjava.vscode-java-test --force &
code --install-extension vscjava.vscode-maven --force &
code --install-extension yukiuuh2936.vscode-modern-fortran-formatter --force
