C
C SUBROUTINE BLD_GETPRZ
C $Log:   GXAFXT:[GOLS]BLD_GETPRZ.FOV  $
C  
C     Rev 1.0   17 Apr 1996 12:20:12   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 15:45:04   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - bldnbr.for **
C
C
C
C SUBROUTINE TO GET PRIZE VALUES FOR FIXED PAYOUT GAMES
C
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE BLD_GETPRZ(NTYP,BETOPT,PRZTAB,CDISPLAY)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:TNAMES.DEF'
	CHARACTER*30 STRING
	CHARACTER*28 CDISPLAY(NBGPOL)
	INTEGER*4 PRZTAB(NBGPOL)
C
	INTEGER*4 EXT, I, OFF, BETOPT, NTYP
C
C
C
	CALL FASTSET(0,PRZTAB,NBGPOL)
	IF(NTYP.EQ.NB3TYP)GOTO 1000
	IF(NTYP.EQ.NB4TYP)GOTO 2000
	RETURN
C
C
1000	CONTINUE
	OFF=1
	DO 1100 I=1,NUMPL3
	IF(IAND(BETOPT,PARACT).EQ.0.AND.I.LT.TNB3ST) GOTO 1100
	IF(IAND(BETOPT,BOXACT).EQ.0.AND.I.GE.TNB3B6.AND.
     *     I.LE.TNB3B3) GOTO 1100
	IF(IAND(BETOPT,CMBACT).EQ.0.AND.I.GE.TNB3C6.AND.
     *     I.LE.TNB3C3) GOTO 1100
	IF(IAND(BETOPT,WHLACT).EQ.0.AND.I.GE.TNB3W6) GOTO 1100
	WRITE (STRING,900) P3NAMES(I)
	CALL INPMONY(STRING,PRZTAB(I),VALUNIT,EXT)
	IF(EXT.LT.0) GOTO 1000
	WRITE (CDISPLAY(OFF),902) P3NAMES(I),CMONY(PRZTAB(I),7,VALUNIT)
	OFF=OFF+1
1100	CONTINUE
	RETURN
C
C
2000	CONTINUE
	OFF=1
	DO 2100 I=1,NUMPL4
        IF(IAND(BETOPT,PARACT).EQ.0.AND.I.LT.TNB4ST) GOTO 2100
        IF(IAND(BETOPT,BOXACT).EQ.0.AND.I.GE.TNB4B24.AND.
     *     I.LE.TNB4B4) GOTO 2100
        IF(IAND(BETOPT,CMBACT).EQ.0.AND.I.GE.TNB4C24.AND.
     *     I.LE.TNB4C4) GOTO 2100
        IF(IAND(BETOPT,WHLACT).EQ.0.AND.I.GE.TNB4W24) GOTO 2100
	WRITE (STRING,900) P4NAMES(I)
	CALL INPMONY(STRING,PRZTAB(I),VALUNIT,EXT)
	IF(EXT.LT.0) GOTO 2000
	WRITE (CDISPLAY(OFF),902) P4NAMES(I),CMONY(PRZTAB(I),7,VALUNIT)
	OFF=OFF+1
2100	CONTINUE
	RETURN
C
C
900	FORMAT('Enter ',A4,' base prize value ')
902	FORMAT(A4,' base prize ',A7)
	END
