C
C PROGRAM CHECKLIST
C $Log:   GXAFXT:[GOLS]CHECKLIST.FOV  $
C  
C     Rev 1.0   17 Apr 1996 12:30:50   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 15:47:48   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - checklist.for **
C
C CHECKLIST.FOR
C
C V02 14-JUL-92 WLM  CHECKED AND RELEASED FOR THE NETHERLANDS
C V01 18-APR-91 TKO  Initial release
C
C
	PROGRAM CHECKLIST
	IMPLICIT NONE
C
	INCLUDE	'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:PRMAGT.DEF'
	INCLUDE 'INCLIB:PROCOM.DEF'
	INCLUDE 'INCLIB:ENCCOM.DEF'
	INCLUDE 'INCLIB:QUECOM.DEF'
	INCLUDE 'INCLIB:SIMCOM.DEF'
	INCLUDE 'INCLIB:X2XCOM.DEF'
	INCLUDE 'INCLIB:X2XQUE.DEF'
	INCLUDE 'INCLIB:X2XREL.DEF'
	INCLUDE 'INCLIB:GLIST.DEF'
	INCLUDE 'INCLIB:TASKID.DEF'
C
	INTEGER*4   BUFCHK(NUMPRO)
C
	INTEGER*4   K
C
	CALL COPYRITE
C
	CALL FASTSET(0,BUFCHK,NUMPRO)
C
C Scan through each queue to see if all buffers are accounted for
C
	CALL SCANLIST(1,SOFT_ENCQUE,BUFCHK)
	CALL SCANLIST(2,FREEQ, BUFCHK)
	CALL SCANLIST(3,INQUE, BUFCHK)
	CALL SCANLIST(4,GAME_OUTQUE,BUFCHK)
	CALL SCANLIST(6,SIM_SIMQUE_IN,BUFCHK)
	CALL SCANLIST(7,SIM_SIMQUE_OUT,BUFCHK)
	CALL SCANLIST(8,X2X_OUTPUT,BUFCHK)
	CALL SCANLIST(9,X2XR_APP_QUEUE,BUFCHK)
	CALL SCANLIST(10,X2XR_INPUT_QUEUE,BUFCHK)
C
	DO 1700 K = 1, NUMAPPQUE
	  CALL SCANLIST(100+K, QUETAB(1,K), BUFCHK)
1700	CONTINUE
C
	DO 1900 K = 1, NUMPRO
	  IF(BUFCHK(K).EQ.0)THEN
	    TYPE *,'BUFFER ',K,' NOT FOUND'
	  ENDIF
1900	CONTINUE
C
	TYPE *,'END OF SCAN'
	END
