C
C SUBROUTINE CHKEXP
C $Log:   GXAFXT:[GOLS]CHKEXP.FOV  $
C  
C     Rev 1.0   17 Apr 1996 12:32:00   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 15:49:18   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - valupd.for **
C
C
C SUBROUTINE TO CHECK IF VALIDATION HAS EXPIRED.
C
C CALLING SEQUENCE:
C     CALL CHKEXP(VALREC,STATUS)
C INPUT
C     VALREC - VALIDATION RECORD
C OUTPUT
C     STATUS - 0 - OK, -1 VALIDATION HAS EXPIRED.
C
C
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE CHKEXP(VALREC,STATUS)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:DESVAL.DEF'
C
	INTEGER*4 STATUS, GAME, NUMDAY
C
	STATUS=0
	GAME=VALREC(VGAM)
	NUMDAY=PRGDAY(GAME)
	IF(VALREC(VWCDC).LT.DAYCDC-NUMDAY) STATUS=-1
	RETURN
	END
