C
C SUBROUTINE CHKNBR
C $Log:   GXAFXT:[GOLS]CHKNBR.FOV  $
C  
C     Rev 1.0   17 Apr 1996 12:32:34   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 15:49:58   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - chknbr.for **
C
C CHKNBR.FOR
C
C V02 12-NOV-91 MTK INITAL RELEASE FOR NETHERLANDS
C V01 01-AUG-90 XXX RELEASED FOR VAX
C
C
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C This item is the property of GTECH Corporation, Providence, Rhode
C Island, and contains confidential and trade secret information. It
C may not be transferred from the custody or control of GTECH except
C as authorized in writing by an officer of GTECH. Neither this item
C nor the information it contains may be used, transferred,
C reproduced, published, or disclosed, in whole or in part, and
C directly or indirectly, except as expressly authorized by an
C officer of GTECH, pursuant to written agreement.
C
C Copyright 1991 GTECH Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE CHKNBR(TRABUF,AMTWON,EFLAG,DRAW,PRVFLG)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:NBRCOM.DEF'
	INCLUDE 'INCLIB:DESTRA.DEF'
	INTEGER*4 AMTWON, BOXNUM, TEMP, FLAG, POL, AMT, K, N, I, ST, GIND
	INTEGER*4 NUM, DRAW
	LOGICAL EFLAG,PRVFLG
	INTEGER*4 DIG(4)
C
C
	PRVFLG=.FALSE.
	AMTWON=0
	EFLAG=.FALSE.
	ST=TRABUF(TSTAT)
	GIND=TRABUF(TGAMIND)
	IF(TRABUF(TTYP).NE.TWAG) RETURN
	IF(TRABUF(TGAMTYP).NE.TNBR) RETURN
        IF(NBRSTS(GIND).LT.GAMDON) RETURN
	IF(ST.NE.GOOD.AND.ST.NE.EXCH.AND.ST.NE.CLAM.AND.ST.NE.XCLM) RETURN
C
        IF(TRABUF(TWEND).GT.NBRDRW(GIND)) THEN
	  IF(ST.NE.CLAM.AND.ST.NE.XCLM) EFLAG=.TRUE.
          DRAW=NBRDRW(GIND)+1
        ENDIF
C
C
        IF(TRABUF(TWNAND).NE.0) THEN
          IF(TRABUF(TWBEG).NE.NBRDRW(GIND).AND.
     *       TRABUF(TWEND).NE.NBRDRW(GIND)) RETURN
        ELSE
          IF(TRABUF(TWBEG).GT.NBRDRW(GIND)) RETURN
          IF(TRABUF(TWEND).LT.NBRDRW(GIND)) RETURN
        ENDIF
C
C
	IF(TRABUF(TWNTYP).EQ.NB4TYP) GOTO 1000
	IF(TRABUF(TWNTYP).NE.NB3TYP) RETURN
C
C THREE DIGIT GAME
C
	DO 110 K=0,TRABUF(TWNBET)-1
	NUM=TRABUF(TWNNUM1+K*3)
	AMT=TRABUF(TWNAMT1+K*3)/NBRPRC(GIND)
	POL=TRABUF(TWNPOL1+K*3)
	IF(POL.GT.TNB3ST) THEN
	  N=NUM
	  DO 10 I=1,3
	  DIG(I)=MOD(N,10)
	  N=N/10
10	  CONTINUE
20	  CONTINUE
	  FLAG=0
	  DO 30 I=2,3
	  IF(DIG(I).GE.DIG(I-1)) GOTO 30
	  TEMP=DIG(I)
	  DIG(I)=DIG(I-1)
	  DIG(I-1)=TEMP
	  FLAG=1
30	  CONTINUE
	  IF(FLAG.NE.0) GOTO 20
	  BOXNUM=DIG(3)+DIG(2)*10+DIG(1)*100
	ENDIF
C
C CHECK STRAIGHT BETS
C
	IF(POL.LE.TNB3ST) THEN
	  IF(NUM.EQ.NBRWIN(POL,1,GIND))
     *       AMTWON=AMTWON+NBRPRZ(POL,1,GIND)*AMT
	  GOTO 100
	ENDIF
C
C CHECK BOX BETS
C
	IF(POL.EQ.TNB3B3.OR.POL.EQ.TNB3B6) THEN
	  IF(BOXNUM.EQ.NBRWIN(POL,1,GIND))
     *       AMTWON=AMTWON+NBRPRZ(POL,1,GIND)*AMT
	  GOTO 100
	ENDIF
C
C CHECK COMBO BETS
C
	IF(POL.EQ.TNB3C6.OR.POL.EQ.TNB3C3) THEN
	  AMT=AMT/2
	  IF(BOXNUM.EQ.NBRWIN(POL-2,1,GIND))
     *       AMTWON=AMTWON+NBRPRZ(POL-2,1,GIND)*AMT
	  IF(NUM.EQ.NBRWIN(TNB3ST,1,GIND))
     *       AMTWON=AMTWON+NBRPRZ(TNB3ST,1,GIND)*AMT
	  GOTO 100
	ENDIF
C
C CHECK WHEEL BETS
C
	IF(POL.EQ.TNB3W6.OR.POL.EQ.TNB3W3) THEN
	  IF(POL.EQ.TNB3W3) AMT=AMT/3
	  IF(POL.EQ.TNB3W6) AMT=AMT/6
	  IF(BOXNUM.EQ.NBRWIN(POL,1,GIND))
     *       AMTWON=AMTWON+NBRPRZ(POL,1,GIND)*AMT
	  GOTO 100
	ENDIF
100	CONTINUE
110	CONTINUE
        IF(AMTWON.GT.REDMAX(TRABUF(TGAM))) PRVFLG=.TRUE.
        IF(NBRBDR(GIND).NE.0) CALL CHKBON(TRABUF,AMTWON,PRVFLG)
	RETURN
C
C FOUR DIGIT GAME
C
1000	CONTINUE
        DO 1110 K=0,TRABUF(TWNBET)-1
        NUM=TRABUF(TWNNUM1+K*3)
        AMT=TRABUF(TWNAMT1+K*3)/NBRPRC(GIND)
        POL=TRABUF(TWNPOL1+K*3)
        IF(POL.GT.TNB3ST) THEN
	  N=NUM
          DO 1010 I=1,4
          DIG(I)=MOD(N,10)
          N=N/10
1010      CONTINUE
1020      CONTINUE
          FLAG=0
          DO 1030 I=2,4
          IF(DIG(I).GE.DIG(I-1)) GOTO 1030
          TEMP=DIG(I)
          DIG(I)=DIG(I-1)
          DIG(I-1)=TEMP
          FLAG=1
1030      CONTINUE
          IF(FLAG.NE.0) GOTO 1020
          BOXNUM=DIG(4)+DIG(3)*10+DIG(2)*100+DIG(1)*1000
        ENDIF
C
C CHECK STRAIGHT BETS
C
        IF(POL.LE.TNB4ST) THEN
          IF(NUM.EQ.NBRWIN(POL,1,GIND))
     *    AMTWON=AMTWON+NBRPRZ(POL,1,GIND)*AMT
          GOTO 1100
        ENDIF
C
C CHECK BOX BETS
C
        IF(POL.GE.TNB4B24.AND.POL.LE.TNB4B4) THEN
          IF(BOXNUM.EQ.NBRWIN(POL,1,GIND))
     *       AMTWON=AMTWON+NBRPRZ(POL,1,GIND)*AMT
          GOTO 1100
        ENDIF
 
C
C CHECK COMBO BETS
C
        IF(POL.GE.TNB4C24.OR.POL.LE.TNB4C4) THEN
          AMT=AMT/2
          IF(BOXNUM.EQ.NBRWIN(POL-4,1,GIND))
     *       AMTWON=AMTWON+NBRPRZ(POL-4,1,GIND)*AMT
          IF(NUM.EQ.NBRWIN(TNB4ST,1,GIND))
     *       AMTWON=AMTWON+NBRPRZ(TNB4ST,1,GIND)*AMT
          GOTO 1100
        ENDIF
C
C CHECK WHEEL BETS
C
        IF(POL.GE.TNB4W24.AND.POL.LE.TNB4W4) THEN
          IF(POL.EQ.TNB4W4) AMT=AMT/4
          IF(POL.EQ.TNB4W6) AMT=AMT/6
	  IF(POL.EQ.TNB4W12) AMT=AMT/12
	  IF(POL.EQ.TNB4W24) AMT=AMT/24
          IF(BOXNUM.EQ.NBRWIN(POL,1,GIND))
     *       AMTWON=AMTWON+NBRPRZ(POL,1,GIND)*AMT
          GOTO 1100
        ENDIF
1100    CONTINUE
1110	CONTINUE
	IF(AMTWON.GT.REDMAX(TRABUF(TGAM))) PRVFLG=.TRUE.
	IF(NBRBDR(GIND).NE.0) CALL CHKBON(TRABUF,AMTWON,PRVFLG)
        RETURN
	END
