C
C SUBROUTINE CHKNUM
C $Log:   GXAFXT:[GOLS]CHKNUM.FOV  $
C  
C     Rev 1.0   17 Apr 1996 12:32:40   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 15:50:10   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - chknum.for **
C
C CHKNUM.FOR
C
C V02 12-NOV-91 MTK INITIAL RELEASE FOR NETHERLANDS
C V01 01-AUG-90 XXX RELEASED FOR VAX
C
C
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C This item is the property of GTECH Corporation, Providence, Rhode
C Island, and contains confidential and trade secret information. It
C may not be transferred from the custody or control of GTECH except
C as authorized in writing by an officer of GTECH. Neither this item
C nor the information it contains may be used, transferred,
C reproduced, published, or disclosed, in whole or in part, and
C directly or indirectly, except as expressly authorized by an
C officer of GTECH, pursuant to written agreement.
C
C Copyright 1991 GTECH Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE CHKNUM(TRABUF,UPDCNT,DAYS,LIMIT,BETOFF,WARN)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:NBRCOM.DEF'
	INCLUDE 'INCLIB:POLCOM.DEF'
	INCLUDE 'INCLIB:DESTRA.DEF'
C
	LOGICAL LIMIT,WARN
	INTEGER*4 CMBTAB(100),DAYS(POLDAY)
	INTEGER*4 N, TOTLIB, DAY, S2OFF, B2OFF, F2OFF, STOFF, BOXOFF
	INTEGER*4 BOXTYP, I, TYPE,NUM, OFF, GIND, BETOFF, UPDCNT, J
C
C
	LIMIT=.FALSE.
	GIND=TRABUF(TGAMIND)
	IF(TRABUF(TWNTYP).EQ.NB3TYP) GOTO 1000
	IF(TRABUF(TWNTYP).EQ.NB4TYP) GOTO 2000
	RETURN
C
C PROCESS 3-DIGIT GAME
C
1000	CONTINUE
	DO 1100 OFF=0,TRABUF(TWNBET)-1
	NUM=TRABUF(TWNNUM1+OFF*3)
	TYPE=TRABUF(TWNPOL1+OFF*3)
C
C CHECK 2 DIGIT WAGER
C
	IF(TYPE.EQ.TNB3F2.OR.TYPE.EQ.TNB3S2.OR.TYPE.EQ.TNB3B2) THEN
	  DO 1010 I=1,10
	  IF(TYPE.EQ.TNB3F2) CMBTAB(I)=NUM*10+(I-1)
	  IF(TYPE.EQ.TNB3B2) CMBTAB(I)=NUM+(I-1)*100
	  IF(TYPE.EQ.TNB3S2) CMBTAB(I)=
     *	    NUM/10*100+(I-1)*10+MOD(NUM,10)
1010	  CONTINUE
	  DO 1030 I=1,10
	  F2OFF=CMBTAB(I)/10+PFP2
	  B2OFF=MOD(CMBTAB(I),100)+PBP2
	  S2OFF=(CMBTAB(I)/100)*10+MOD(CMBTAB(I),10)+PSM2
	  DO 1020 J=1,UPDCNT
	  DAY=DAYS(J)
	  TOTLIB=POOLT(F2OFF,DAY,GIND)*NBRPRZ(TNB3F2,1,GIND)+
     *	         POOLT(B2OFF,DAY,GIND)*NBRPRZ(TNB3B2,1,GIND)+
     *	         POOLT(S2OFF,DAY,GIND)*NBRPRZ(TNB3S2,1,GIND)
	  IF(TOTLIB.GT.NBRLIM(LIM2ST,GIND)) THEN
	    LIMIT=.TRUE.
	    WARN=.FALSE.
	    BETOFF=OFF
	    RETURN
	  ENDIF
	  IF(TOTLIB.GT.NBRLIM(LIM2ST,GIND)*CALPER(P(WRNPER))) THEN
	    WARN=.TRUE.
	    BETOFF=OFF
	  ENDIF
1020	  CONTINUE
1030	  CONTINUE
	ENDIF
C
C CHECK 3 DIGIT STRAIGHT/COMBO WAGER
C
	IF(TYPE.EQ.TNB3ST.OR.TYPE.EQ.TNB3C3.OR.TYPE.EQ.TNB3C6) THEN
	  STOFF=NUM+PSTR
	  DO 1040 J=1,UPDCNT
	  DAY=DAYS(J)
          TOTLIB=POOLT(STOFF,DAY,GIND)*NBRPRZ(TNB3ST,1,GIND)
	  IF(TOTLIB.GT.NBRLIM(LIMSTR,GIND)) THEN
	    LIMIT=.TRUE.
	    WARN=.FALSE.
	    BETOFF=OFF
	    RETURN
	  ENDIF
          IF(TOTLIB.GT.NBRLIM(LIMSTR,GIND)*CALPER(P(WRNPER))) THEN
            WARN=.TRUE.
            BETOFF=OFF
          ENDIF
1040	  CONTINUE
	ENDIF
C
C CHECK 3 DIGIT BOX/COMBO WAGER
C
        IF(TYPE.EQ.TNB3B6.OR.TYPE.EQ.TNB3B3.OR.
     *     TYPE.EQ.TNB3C6.OR.TYPE.EQ.TNB3C3)THEN
          BOXTYP=P3OFF(NUM+1,BOXPOL)
          BOXOFF=P3OFF(NUM+1,BOXADR)
	  DO 1050 J=1,UPDCNT
	  DAY=DAYS(J)
	  TOTLIB=POOLT(BOXOFF,DAY,GIND)*NBRPRZ(BOXTYP,1,GIND)
          IF(TOTLIB.GT.NBRLIM(LIMBOX,GIND)) THEN
            LIMIT=.TRUE.
	    WARN=.FALSE.
            BETOFF=OFF
            RETURN
	  ENDIF
          IF(TOTLIB.GT.NBRLIM(LIMBOX,GIND)*CALPER(P(WRNPER))) THEN
            WARN=.TRUE.
            BETOFF=OFF
          ENDIF
1050	  CONTINUE
	ENDIF
C
C CHECK 3 DIGIT WHEEL WAGER
C
	IF(TYPE.EQ.TNB3W6.OR.TYPE.EQ.TNB3W3) THEN
	  CALL PERM3(NUM,CMBTAB,N)
	  DO 1070 I=1,N
	    STOFF=CMBTAB(I)+PSTR
	    DO 1060 J=1,UPDCNT
	    DAY=DAYS(J)
	    TOTLIB=POOLT(STOFF,DAY,GIND)*NBRPRZ(TNB3ST,1,GIND)
	    IF(TOTLIB.GT.NBRLIM(LIMSTR,GIND)) THEN
	      LIMIT=.TRUE.
	      WARN=.FALSE.
	      BETOFF=OFF
	      RETURN
	    ENDIF
            IF(TOTLIB.GT.NBRLIM(LIMSTR,GIND)*CALPER(P(WRNPER))) THEN
              WARN=.TRUE.
              BETOFF=OFF
            ENDIF
1060	    CONTINUE
1070	  CONTINUE
	ENDIF
C
1100	CONTINUE
	IF(P(WRNPER).EQ.0) WARN=.FALSE.
	RETURN
C
C PROCESS 4 DIGIT GAME
C
2000	CONTINUE
	DO 2100 OFF=0,TRABUF(TWNBET)-1
	NUM=TRABUF(TWNNUM1+OFF*3)
	TYPE=TRABUF(TWNPOL1+OFF*3)
C
C CHECK 2 DIGIT WAGER
C
        IF(TYPE.EQ.TNB4F2.OR.TYPE.EQ.TNB4M2.OR.TYPE.EQ.TNB4B2) THEN
          DO 2010 I=1,100
          IF(TYPE.EQ.TNB4F2) CMBTAB(I)=NUM*100+(I-1)
          IF(TYPE.EQ.TNB4B2) CMBTAB(I)=NUM+(I-1)*100
          IF(TYPE.EQ.TNB4M2) CMBTAB(I)=
     *      MOD((I-1),10)+NUM*10+(I-1)/10*1000
2010      CONTINUE
          DO 2030 I=1,100
          F2OFF=CMBTAB(I)/100+PFP2
          B2OFF=MOD(CMBTAB(I),100)+PBP2
C***      M2OFF=MOD(CMBTAB(I),1000)/10+PSM2
          DO 2020 J=1,UPDCNT
          DAY=DAYS(J)
          TOTLIB=POOLT(F2OFF,DAY,GIND)*NBRPRZ(TNB4F2,1,GIND)+
     *           POOLT(B2OFF,DAY,GIND)*NBRPRZ(TNB4B2,1,GIND)+
     *           POOLT(S2OFF,DAY,GIND)*NBRPRZ(TNB4M2,1,GIND)
          IF(TOTLIB.GT.NBRLIM(LIM2ST,GIND)) THEN
            LIMIT=.TRUE.
	    WARN=.FALSE.
            BETOFF=OFF
            RETURN
	  ENDIF
          IF(TOTLIB.GT.NBRLIM(LIM2ST,GIND)*CALPER(P(WRNPER))) THEN
            WARN=.TRUE.
            BETOFF=OFF
          ENDIF
2020 	  CONTINUE
2030	  CONTINUE
	ENDIF
C
C CHECK 4 DIGIT STRAIGHT/COMBO WAGERS
C
	IF(TYPE.EQ.TNB4ST.OR.(TYPE.GE.TNB4C24.AND.TYPE.LE.TNB4C4)) THEN
	  STOFF=NUM+PSTR
	  DO 2040 J=1,UPDCNT
	  DAY=DAYS(J)
	  TOTLIB=POOLT(STOFF,DAY,GIND)*NBRPRZ(TNB4ST,1,GIND)
	  IF(TOTLIB.GT.NBRLIM(LIMSTR,GIND)) THEN
	    LIMIT=.TRUE.
	    WARN=.FALSE.
	    BETOFF=OFF
	    RETURN
	  ENDIF
          IF(TOTLIB.GT.NBRLIM(LIMSTR,GIND)*CALPER(P(WRNPER))) THEN
            WARN=.TRUE.
            BETOFF=OFF
          ENDIF
2040	  CONTINUE
	ENDIF
C
C CHECK 4 DIGIT BOX/COMBO WAGERS
C
        IF(TYPE.GE.TNB4B24.AND.TYPE.LE.TNB4C4) THEN
          BOXTYP=P4OFF(NUM+1,BOXPOL)
          BOXOFF=P4OFF(NUM+1,BOXADR)
          DO 2050 J=1,UPDCNT
          DAY=DAYS(J)
          TOTLIB=POOLT(BOXOFF,DAY,GIND)*NBRPRZ(BOXTYP,1,GIND)
          IF(TOTLIB.GT.NBRLIM(LIMBOX,GIND)) THEN
            LIMIT=.TRUE.
	    WARN=.FALSE.
            BETOFF=OFF
            RETURN
          ENDIF
          IF(TOTLIB.GT.NBRLIM(LIMBOX,GIND)*CALPER(P(WRNPER))) THEN
            WARN=.TRUE.
            BETOFF=OFF
          ENDIF
2050      CONTINUE
	ENDIF
C
C CHECK 4 DIGIT WHEEL WAGERS
C
	IF(TYPE.GE.TNB4W24.AND.TYPE.LE.TNB4W4) THEN
	  CALL PERM4(NUM,CMBTAB,N)
	  DO 2070 I=1,N
	  STOFF=CMBTAB(I)+PSTR
	  DO 2060 J=1,UPDCNT
	  DAY=DAYS(J)
	  TOTLIB=POOLT(STOFF,DAY,GIND)*NBRPRZ(TNB4ST,1,GIND)
	  IF(TOTLIB.GT.NBRLIM(LIMSTR,GIND)) THEN
	    LIMIT=.TRUE.
	    WARN=.FALSE.
	    BETOFF=OFF
	    RETURN
	  ENDIF
          IF(TOTLIB.GT.NBRLIM(LIMSTR,GIND)*CALPER(P(WRNPER))) THEN
            WARN=.TRUE.
            BETOFF=OFF
          ENDIF
2060	  CONTINUE
2070	  CONTINUE
	ENDIF
C
2100	CONTINUE
	IF(P(WRNPER).EQ.0) WARN=.FALSE.
	RETURN
	END
