C SUBROUTINE CHKSYS
C
C CHKSYS.FOR
C 
C V17 01-JAN-2010 FJG ePASSIVE
C V16 05-JAN-2000 CS  PASCOM added.
C V15 29-NOV-2000 UXN TGLCOM ADDEDD.
C V14 05-JUN-2000 OXK SSOCOM added.
C V13 26-NOV-1999 OXK TSPCOM added.
C V12 13-OCT-1999 RXK World Tour added.
C V11 13-MAY-1999 UXN SUPER TRIPLE ADDED.
C V10 17-APR-1996 HXK Release of Finland for X.25, Telephone Betting, 
C                     Instant Pass Thru Phase 1
C V09 10-NOV-1995 HXK Further changes for Double, Couple
C V08 15-OCT-1994 HXK Adding /developing Bingo (15.Oct.94)
C V07 24-AUG-1993 GXA Added S234COM and SCNCOM to be checkpointed.
C V06 10-JUL-1993 GXA Include order change.
C V05 10-JUL-1993 GXA Released for Finland Dec Conversion / Oddset.
C V04 09-JUL-1993 GXA Released for Finland Dec Conversion / Oddset.
C                     (It might be bigger then it needs to be).
C V03 21-JAN-1993 DAB Initial Release
C                     Based on Netherlands Bible, 12/92, and Comm 1/93 update
C                     DEC Baseline
C V02 07-OCT-1991 MTK INITAL RELEASE FOR NETHERLANDS
C V01 01-AUG-1990 XXX RELEASED FOR VAX
C
C
C
C SUBROUTINE TO CHECKPOINT SYSTEM COMMONS
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C This item is the property of GTECH Corporation, Providence, Rhode
C Island, and contains confidential and trade secret information. It
C may not be transferred from the custody or control of GTECH except
C as authorized in writing by an officer of GTECH. Neither this item
C nor the information it contains may be used, transferred,
C reproduced, published, or disclosed, in whole or in part, and
C directly or indirectly, except as expressly authorized by an
C officer of GTECH, pursuant to written agreement.
C
C Copyright 2000 GTECH Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++C
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE CHKSYS(FILNR)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:AGTINF.DEF'
	INCLUDE 'INCLIB:AGTCOM.DEF'
	INCLUDE 'INCLIB:PROCOM.DEF'
	INCLUDE 'INCLIB:CHKPNT.DEF'
	INCLUDE 'INCLIB:LTOCOM.DEF'
	INCLUDE 'INCLIB:SPTCOM.DEF'
	INCLUDE 'INCLIB:TGLCOM.DEF'
	INCLUDE 'INCLIB:KIKCOM.DEF'
C	INCLUDE 'INCLIB:NBRCOM.DEF'
C====== INCLUDE 'INCLIB:WITCOM.DEF'
C====== INCLUDE 'INCLIB:TSLCOM.DEF'
C====== INCLUDE 'INCLIB:SCRCOM.DEF'
C====== INCLUDE 'INCLIB:BNGCOM.DEF'
C====== INCLUDE 'INCLIB:DBLCOM.DEF'
C====== INCLUDE 'INCLIB:CPLCOM.DEF'
C====== INCLUDE 'INCLIB:SSCCOM.DEF'
C====== INCLUDE 'INCLIB:SSPCOM.DEF'
C====== INCLUDE 'INCLIB:TRPCOM.DEF'
C====== INCLUDE 'INCLIB:TROCOM.DEF'
C====== INCLUDE 'INCLIB:STRCOM.DEF'
C====== INCLUDE 'INCLIB:STROCOM.DEF'
C====== INCLUDE 'INCLIB:SLOCOM.DEF'
C	INCLUDE 'INCLIB:POLCOM.DEF'
	INCLUDE 'INCLIB:POOLLTO.DEF'
	INCLUDE 'INCLIB:CHKCOM.DEF'
	INCLUDE 'INCLIB:TASKID.DEF'
	INCLUDE 'INCLIB:CTLCOM.DEF'
	INCLUDE 'INCLIB:DESNET.DEF'
	INCLUDE 'INCLIB:X2XCOM.DEF'
	INCLUDE 'INCLIB:SLOCOM1.DEF'
	INCLUDE 'INCLIB:X2FCOM.DEF'
	INCLUDE 'INCLIB:X2NETCOM.DEF'
	INCLUDE 'INCLIB:X2XREL.DEF'
C====== INCLUDE 'INCLIB:STACOM.DEF'
C====== INCLUDE 'INCLIB:HASHMEM.DEF'
C====== INCLUDE 'INCLIB:SSOCOM.DEF'
        INCLUDE 'INCLIB:PASCOM.DEF'
C
	INTEGER*4 ST, FILNR, IND
C
C CHECK IF PREVIOUS CHECKPOINT IS COMPLETED
C
10	CONTINUE
	IF(FILNR.LT.0) THEN
	  IF(P(CHKFLG).NE.0) THEN
	    CALL XWAIT(50,1,ST)
	    GOTO 10
	  ENDIF
	ELSE
	  IF(P(CHKFLG).NE.0.AND.MOD(FILNR,2).NE.0) THEN
	    FILNR=0   !CHANGE FILE FOR CMDPRO IF FAILURE
	    RETURN
	  ENDIF
	ENDIF
	IF(MOD(IABS(FILNR),2).EQ.0) GOTO 100
C
C CHECKPOINT CONCOM
C
	IND=2
	CALL FASTMOV(CONBLK, CHKTAB(1,IND),CONCSB*2048)
	IND=IND+CONCSB
C
C CHECKPOINT AGENT COMMON
C
	CALL FASTMOV(AGTBLK,CHKTAB(1,IND),AGTCSB*2048)
	IND=IND+AGTCSB
C
C CHECKPOINT SLOCOM
C
C       CALL FASTMOV(SLOBLK,CHKTAB(1,IND),SLOCSB*2048)
C       IND=IND+SLOCSB
C
C CHECKPOINT LTOCOM
C
	CALL FASTMOV(LTOBLK,CHKTAB(1,IND),LTOCSB*2048)
	IND=IND+LTOCSB
C
C CHECKPOINT SPTCOM
C
	CALL FASTMOV(SPTBLK,CHKTAB(1,IND),SPTCSB*2048)
	IND=IND+SPTCSB
C
C CHECKPOINT TGLCOM
C
	CALL FASTMOV(TGLBLK,CHKTAB(1,IND),TGLCSB*2048)
	IND=IND+TGLCSB
C
C CHECKPOINT KIKCOM
C
	CALL FASTMOV(KIKBLK,CHKTAB(1,IND),KIKCSB*2048)
	IND=IND+KIKCSB
C
C CHECKPOINT NBRCOM
C
C	CALL FASTMOV(NBRBLK,CHKTAB(1,IND),NBRCSB*2048)
C	IND=IND+NBRCSB
C
C CHECKPOINT SCRCOM
C
C       CALL FASTMOV(SCRBLK,CHKTAB(1,IND),SCRCSB*2048)
C       IND=IND+SCRCSB
C
C CHECKPOINT WITCOM
C
C       CALL FASTMOV(WITBLK,CHKTAB(1,IND),WITCSB*2048)
C       IND=IND+WITCSB
C
C CHECKPOINT TSLCOM
C
C       CALL FASTMOV(TSLBLK,CHKTAB(1,IND),TSLCSB*2048)
C       IND=IND+TSLCSB
C
C CHECKPOINT BNGCOM
C
C       CALL FASTMOV(BNGBLK,CHKTAB(1,IND),BNGCSB*2048)
C       IND=IND+BNGCSB
C
C CHECKPOINT DBLCOM
C
C       CALL FASTMOV(DBLBLK,CHKTAB(1,IND),DBLCSB*2048)
C       IND=IND+DBLCSB
C
C CHECKPOINT CPLCOM
C
C       CALL FASTMOV(CPLBLK,CHKTAB(1,IND),CPLCSB*2048)
C       IND=IND+CPLCSB
C
C CHECKPOINT POLCOM
C
C        CALL FASTMOV(POLBLK,CHKTAB(1,IND),POLCSB*2048)
C	IND=IND+POLCSB              
C
C CHECKPOINT SSCCOM
C
C       CALL FASTMOV(SSCBLK,CHKTAB(1,IND),SSCCSB*2048)
C       IND=IND+SSCCSB              
C
C CHECKPOINT SSPCOM
C
C       CALL FASTMOV(SSPBLK,CHKTAB(1,IND),SSPCSB*2048)
C       IND=IND+SSPCSB              
C
C CHECKPOINT TRPCOM
C
C       CALL FASTMOV(TRPBLK,CHKTAB(1,IND),TRPCSB*2048)
C       IND=IND+TRPCSB              
C
C CHECKPOINT TROCOM
C
C       CALL FASTMOV(TROBLK,CHKTAB(1,IND),TROCSB*2048)
C       IND=IND+TROCSB              
C
C CHECKPOINT STACOM
C
C       CALL FASTMOV(STABLK,CHKTAB(1,IND),STACSB*2048)
C       IND=IND+STACSB              
C
C CHECKPOINT STRCOM
C
C       CALL FASTMOV(STRBLK,CHKTAB(1,IND),STRCSB*2048)
C       IND=IND+STRCSB              
C
C CHECKPOINT STROCOM
C
C       CALL FASTMOV(STROBLK,CHKTAB(1,IND),STROCSB*2048)
C       IND=IND+STROCSB              
C
C CHECKPOINT TSPCOM
C
C       CALL FASTMOV(TSPBLK,CHKTAB(1,IND),TSPCSB*2048)
C       IND=IND+TSPCSB
C
C CHECKPOINT SSOCOM
C
C       CALL FASTMOV(SSOCOMBLK,CHKTAB(1,IND),SSOCOMCSB*2048)
C       IND=IND+SSOCOMCSB
C
C CHECKPOINT PASCOM
C
        CALL FASTMOV(PASBLK,CHKTAB(1,IND),PASCSB*2048)
        IND=IND+PASCSB
C
C SET HEADER INFORMATION
C
	CHKHEADER(CHKPNTSER)=NXTSER
	CHKHEADER(CHKPNTBAL)=P(LSTCMD)
	CHKHEADER(CHKPNTTYP)=CHKPNTREG
	CHKHEADER(CHKPNTDAY)=DAYCDC
	CHKHEADER(CHKGAMLEN)=IND-1
	CALL FASTMOV(CHKHEADER,CHKTAB(1,1),2048)
C
C SET CHECKPOINT WRITE FLAG AND KICK THE CHECKPOINT TASK
C
	P(CHKFLG)=FILNR
	CALL RELSE(TSKNAM(CHK),ST)
	RETURN
C
C LOTTO POOL CHECKPOINT
C
100	CONTINUE
	IF (LCHKPNT.NE.0.OR.LCHKSTOP.NE.0) THEN  !IF CHECKPOINT IN
	  FILNR=0   !CHANGE FILE FOR CMDPRO IF FAILURE
	  RETURN
	ENDIF
	LCHKFIL=FILNR                !FILE TO LOAD TO
	LCHKSER = NXTSER
	LCHKPNT=LCMDCHK
	LTQNUM = MOD(LTQNUM,2) + 1
	RETURN
	END
