C
C SUBROUTINE CMDROU
C
C CMDROU.FOR
C
C V14 16-DEC-2000 CS  INCLUDED PASSIVE COMMANDS
C V13 29-NOV-2000 UXN CMDTGL added.
C V12 16-OCT-2000 UXN Initial release for Portugal.
C V11 13-OCT-1999 RXK World Tour added.
C V10 25-MAY-1999 UXN Super Triple added.
C V09 23-NOV-1995 HXK Merge of post 65 stuff; changes for Double/Couple
C V08 05-DEC-1994 HXK Merging from 25-Nov -> 5 Dec
C V07 28-NOV-1994 HXK Fixed Spede /Bingo game closing bug
C V06 15-OCT-1994 HXK Adding /developing Bingo (15.Oct.94)
C V05 29-JUL-1993 JWE FIXED BUG WITH V65 PROF LIST COMMANDS
C V04 18-JUN-1993 HXK ADDED RAVI, SPEDE GAMES
C V03 21-JAN-1993 DAB Initial Release
C                     Based on Netherlands Bible, 12/92, and Comm 1/93 update
C                     DEC Baseline
C V02 07-OCT-1991 MTK INITAL RELEASE FOR NETHERLANDS
C V01 01-AUG-1990 XXX RELEASED FOR VAX
C
C SUBROUTINE TO PROCESS SYSTEM COMMANDS.
C
C
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C This item is the property of GTECH Corporation, Providence, Rhode
C Island, and contains confidential and trade secret information. It
C may not be transferred from the custody or control of GTECH except
C as authorized in writing by an officer of GTECH. Neither this item
C nor the information it contains may be used, transferred,
C reproduced, published, or disclosed, in whole or in part, and
C directly or indirectly, except as expressly authorized by an
C officer of GTECH, pursuant to written agreement.
C
C Copyright 1999 GTECH Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE CMDROU(TRABUF,MESS)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
C
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:DESTRA.DEF'
	INCLUDE 'INCLIB:NAMCMD.DEF'
C
	INTEGER*4 MESS(EDLEN), CMDNUM, CTYPE
C
C
	MESS(2)=TECMD
	CTYPE=TRABUF(TCMTYP)
	CMDNUM =TRABUF(TCMNUM)
	GOTO (10,20,30,40,50,60,70,80,90,100,110,120,
     *        130,140,150,160,170,180,190,200,210,220,230) CTYPE
	MESS(3)=1
	MESS(4)=CTYPE
	MESS(5)=CMDNUM
	RETURN
C
C SYSTEM PARAMETERS
C
10	CONTINUE
	CALL CMDPAR(TRABUF,MESS)
	IF(TRABUF(TSTAT).EQ.GOOD) THEN
	  CALL FASTMOV(NAMTYP(CTYPE),MESS(4),2)
	  CALL FASTMOV(NAMPAR(CMDNUM),MESS(6),2)
	ENDIF
	RETURN
C
C GENERAL COMMANDS
C
20	CONTINUE
	CALL CMDGEN(TRABUF,MESS)
	IF(TRABUF(TSTAT).EQ.GOOD) THEN
	  CALL FASTMOV(NAMTYP(CTYPE),MESS(4),2)
	  CALL FASTMOV(NAMGEN(CMDNUM),MESS(6),2)
	ENDIF
	RETURN
C
C SPECIAL COMMANDS (NO FREEZE)
C
30	CONTINUE
	CALL CMDSPE(TRABUF,MESS)
	IF(TRABUF(TSTAT).EQ.GOOD) THEN
	  CALL FASTMOV(NAMTYP(CTYPE),MESS(4),2)
	  CALL FASTMOV(NAMSPE(CMDNUM),MESS(6),2)
	ENDIF
	RETURN
C
C SYSTEM NETWORK COMMANDS
C
40	CONTINUE
	CALL CMDNMG(TRABUF,MESS)
	IF(TRABUF(TSTAT).EQ.GOOD) THEN
	  CALL FASTMOV(NAMTYP(CTYPE),MESS(4),2)
	  CALL FASTMOV(NAMNET(CMDNUM),MESS(6),2)
	ENDIF
	RETURN
C
C COMMUNICATIONS COMMANDS
C
50	CONTINUE
	CALL CMDCOM(TRABUF,MESS)
	IF(TRABUF(TSTAT).EQ.GOOD) THEN
	  CALL FASTMOV(NAMTYP(CTYPE),MESS(4),2)
	  CALL FASTMOV(NAMCOM(CMDNUM),MESS(6),2)
	ENDIF
	RETURN
C
C AGENT COMMANDS
C
60	CONTINUE
	CALL CMDAGT(TRABUF,MESS)
	IF(TRABUF(TSTAT).EQ.GOOD) THEN
	  CALL FASTMOV(NAMTYP(CTYPE),MESS(4),2)
	  CALL FASTMOV(NAMAGT(CMDNUM),MESS(6),2)
	ENDIF
	RETURN
C
C LOTTO COMMANDS
C
70	CONTINUE
	CALL CMDLTO(TRABUF,MESS)
	IF(TRABUF(TSTAT).EQ.GOOD) THEN
	  CALL FASTMOV(NAMTYP(CTYPE),MESS(4),2)
	  CALL FASTMOV(NAMLTO(CMDNUM),MESS(7),2)
	ENDIF
	RETURN
C
C SPORTS COMMANDS
C
80	CONTINUE
	CALL CMDSPT(TRABUF,MESS)
	IF(TRABUF(TSTAT).EQ.GOOD) THEN
	  CALL FASTMOV(NAMTYP(CTYPE),MESS(4),2)
	  CALL FASTMOV(NAMSPT(CMDNUM),MESS(7),2)
	ENDIF
	RETURN
C
C KICKER COMMANDS
C
90	CONTINUE
	CALL CMDKIK(TRABUF,MESS)
	IF(TRABUF(TSTAT).EQ.GOOD) THEN
	  CALL FASTMOV(NAMTYP(CTYPE),MESS(4),2)
	  CALL FASTMOV(NAMKIK(CMDNUM),MESS(7),2)
	ENDIF
	RETURN
C
C X2X COMMANDS.
C
100	CONTINUE
	CALL CMDX2X(TRABUF,MESS)
	RETURN
C
C NUMBERS COMMANDS
C
110     CONTINUE
        CALL CMDNBR(TRABUF,MESS)
        IF(TRABUF(TSTAT).EQ.GOOD) THEN
          CALL FASTMOV(NAMTYP(CTYPE),MESS(4),2)
          CALL FASTMOV(NAMNBR(CMDNUM),MESS(7),2)
        ENDIF
        RETURN
C
C MATRIX SWITCH COMMANDS
C
120	CONTINUE
        CALL CMDMSC(TRABUF,MESS)
        IF(TRABUF(TSTAT).EQ.GOOD) THEN
           CALL FASTMOV(NAMTYP(CTYPE),MESS(4),2)
           CALL FASTMOV(NAMMSC(CMDNUM),MESS(6),2)
        ENDIF
        RETURN
C
C SCORE COMMANDS
C
130     CONTINUE
        CALL CMDSCR(TRABUF,MESS)
        IF(TRABUF(TSTAT).EQ.GOOD) THEN
          CALL FASTMOV(NAMTYP(CTYPE),MESS(4),2)
          CALL FASTMOV(NAMSCR(CMDNUM),MESS(7),2)
        ENDIF
        RETURN
C
C WINNERS TIP COMMANDS
C
140     CONTINUE
        CALL CMDWIT(TRABUF,MESS)
        IF(TRABUF(TSTAT).EQ.GOOD) THEN
          CALL FASTMOV(NAMTYP(CTYPE),MESS(4),2)
          CALL FASTMOV(NAMWIT(CMDNUM),MESS(7),2)
        ENDIF
        RETURN
C
C TOTO SELECT COMMANDS
C
150     CONTINUE
        CALL CMDTSL(TRABUF,MESS)
        IF(TRABUF(TSTAT).EQ.GOOD) THEN
          CALL FASTMOV(NAMTYP(CTYPE),MESS(4),2)
          CALL FASTMOV(NAMTSL(CMDNUM),MESS(7),2)
        ENDIF
        RETURN
C
C BINGO COMMANDS
C
160     CONTINUE
        CALL CMDBNG(TRABUF,MESS)
        IF(TRABUF(TSTAT).EQ.GOOD) THEN
          CALL FASTMOV(NAMTYP(CTYPE),MESS(4),2)
          CALL FASTMOV(NAMBNG(CMDNUM),MESS(7),2)
        ENDIF
	RETURN
C
C DOUBLE COMMANDS
C
170     CONTINUE
        CALL CMDDBL(TRABUF,MESS)
        IF(TRABUF(TSTAT).EQ.GOOD) THEN
          CALL FASTMOV(NAMTYP(CTYPE),MESS(4),2)
          CALL FASTMOV(NAMDBL(CMDNUM),MESS(7),2)
        ENDIF
        RETURN
C
C COUPLE COMMANDS
C
180     CONTINUE
        CALL CMDCPL(TRABUF,MESS)
        IF(TRABUF(TSTAT).EQ.GOOD) THEN
          CALL FASTMOV(NAMTYP(CTYPE),MESS(4),2)
          CALL FASTMOV(NAMCPL(CMDNUM),MESS(7),2)
        ENDIF
        RETURN
C
C SUPERSCORE COMMANDS
C
190     CONTINUE
        CALL CMDSSC(TRABUF,MESS)
        IF(TRABUF(TSTAT).EQ.GOOD) THEN
          CALL FASTMOV(NAMTYP(CTYPE),MESS(4),2)
          CALL FASTMOV(NAMSSC(CMDNUM),MESS(7),2)
        ENDIF
        RETURN
C
C TRIO COMMANDS
C
200     CONTINUE
        CALL CMDTRP(TRABUF,MESS)
        IF(TRABUF(TSTAT).EQ.GOOD) THEN
          CALL FASTMOV(NAMTYP(CTYPE),MESS(4),2)
          CALL FASTMOV(NAMTRP(CMDNUM),MESS(7),2)
        ENDIF
        RETURN
C
C SUPER TRIPLE COMMANDS
C
210     CONTINUE
        CALL CMDSTR(TRABUF,MESS)
        IF(TRABUF(TSTAT).EQ.GOOD) THEN
          CALL FASTMOV(NAMTYP(CTYPE),MESS(4),2)
          CALL FASTMOV(NAMSTR(CMDNUM),MESS(7),2)
        ENDIF
        RETURN
C
C TOTOGOLA COMMANDS
C
220     CONTINUE
        CALL CMDTGL(TRABUF,MESS)
        IF(TRABUF(TSTAT).EQ.GOOD) THEN
          CALL FASTMOV(NAMTYP(CTYPE),MESS(4),2)
          CALL FASTMOV(NAMSTR(CMDNUM),MESS(7),2)
        ENDIF
        RETURN
C
C PASSIVE COMMANDS
C
230     CONTINUE
        CALL CMDPAS(TRABUF,MESS)
        IF(TRABUF(TSTAT).EQ.GOOD) THEN
          CALL FASTMOV(NAMTYP(CTYPE),MESS(4),2)
          CALL FASTMOV(NAMPAS(CMDNUM),MESS(7),2)
        ENDIF
        RETURN
C
	END
