C  GXSRC:CRRPT.FOR
C  
C V17 14-JUN-2005 FRP Modify for IPS Distribution.
C V16 05-OCT-2000 UXN AlphaIPS release.
C V15 05-FEB-1997 RXK Some things revbyted
C V14 02-FEB-1997 WPW Next Game Number changed.
C V13 28-JAN-1997 HXK Changes for LOTGEN (IPS=
C V12 19-JAN-1997 HXK Revbyted several variables
C V11 28-JAN-1995 JJOLY ADDED REPORT REQUEST TYPE FOR MULTIPLES
C V10 24-OCT-1994 DJO Changed to handle TRSUB value of 6 for divisions.
C V09 01-OCT-1994 MCM SET THE REQUESTED RETAILER NUMBER FOR ADJUSTMENT 
C                     AND PACK SETTLED REPORTS
C V08 22-SEP-1994 MCM START INDEX AT 2 (BYTE IS RESERVED)
C V07 17-SEP-1994 MCM CHECK TYPE NOT SUBTYPE TO SEND CONTINUATION INFORMATION
C V06 08-SEP-1994 MCM SWAPPING BYTES IS NO LONGER NECESSARY ON THE DEC LMS
C V05 30-AUG-1994 MCM MODIFIED THE ADJUSTMENT REPORT AS PER LMS
C V04 19-JUL-1994 MCM ADDED PACK SETTLED, ADJUSTMENT TEXT AND REPORT
C V03 05-MAY-1993 MCM RELEASED FOR GEORGIA
C V02 11-FEB-1992 JPJ ADDED (GVT)
C V01 13-NOV-1991 JPJ RELEASED FOR VAX (INSTANTS)
C
C SUBROUTINE TO BUILD CROSS SYSTEM REPORT MESSAGE.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C This item is the property of GTECH Corporation, Providence, Rhode
C Island, and contains confidential and trade secret information. It
C may not be transferred from the custody or control of GTECH except
C as authorized in writing by an officer of GTECH. Neither this item
C nor the information it contains may be used, transferred,
C reproduced, published, or disclosed, in whole or in part, and
C directly or indirectly, except as expressly authorized by an
C officer of GTECH, pursuant to written agreement.
C
C Copyright 2000 GTECH Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE CRRPT(OUTTAB,TRABUF,BUF,CHNPAS)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:DESTRA.DEF'
C
        INTEGER*4 IND, BUF, CROSS, CHNPAS
	BYTE      OUTTAB(*)
C
	INTEGER*4   I4TEMP
	INTEGER*2   I2TEMP(2)
	BYTE	    I1TEMP(4)
	EQUIVALENCE (I4TEMP,I2TEMP,I1TEMP)
C
C SET LENGTH
C
	IND=2
	I4TEMP=28
        IF(TRABUF(TITYP).EQ.IFIN) THEN
          IF(TRABUF(TRTYP).EQ.IPSET) I4TEMP=24          !PACK SETTLED REPORT
          IF(TRABUF(TRTYP).EQ.IADJR) I4TEMP=26          !ADJUSTMENT REPORT
          IF(TRABUF(TRTYP).EQ.IADJT) I4TEMP=16          !ADJUSTMENT TEXT
        ENDIF
	IF(TRABUF(TITYP).EQ.IINV) I4TEMP=24
	IF(TRABUF(TITYP).EQ.IQTA) I4TEMP=20
	OUTTAB(IND+0) = I1TEMP(1)
	OUTTAB(IND+1) = I1TEMP(2)
	IND=IND+2
C
C SET GTECH BUFFER NUMBER
C
	I4TEMP=BUF
	OUTTAB(IND+0) = I1TEMP(1)
	OUTTAB(IND+1) = I1TEMP(2)
	IND=IND+2
C
C SET GTECH CROSS REFERENCE NUMBER
C
	CALL GETXRF(CROSS)
	TRABUF(TIXRF)=CROSS
	I4TEMP=CROSS
	OUTTAB(IND+0) = I1TEMP(1)
	OUTTAB(IND+1) = I1TEMP(2)
	OUTTAB(IND+2) = I1TEMP(3)
	OUTTAB(IND+3) = I1TEMP(4)
	IND=IND+4
C
C SET TRANSACTION TYPE CODE
C
	I4TEMP=3
        IF(TRABUF(TITYP).EQ.IFIN) THEN
	  I4TEMP=5
          IF(TRABUF(TRTYP).EQ.IPSET) I4TEMP=25         !PACK SETTLED REPORT
          IF(TRABUF(TRTYP).EQ.IADJR) I4TEMP=26         !ADJUSTMENT REPORT
          IF(TRABUF(TRTYP).EQ.IADJT) I4TEMP=24         !ADJUSTMENT TEXT
        ENDIF
	IF(TRABUF(TITYP).EQ.IINV) I4TEMP=4
	OUTTAB(IND+0) = I1TEMP(1)
	OUTTAB(IND+1) = I1TEMP(2)
	IND=IND+2
C
C SET CLASS
C
	IF(TRABUF(TITYP).EQ.IQTA) I4TEMP=TRABUF(TRCLS)
	IF(TRABUF(TITYP).EQ.IINV) I4TEMP=TRABUF(TRCLS)
	IF(TRABUF(TITYP).EQ.IFIN) I4TEMP=TRABUF(TRSUB)
	OUTTAB(IND+0) = I1TEMP(1)
	OUTTAB(IND+1) = I1TEMP(2)
	IND=IND+2
C
C SET RETAILER NUMBER
C
	I4TEMP=TRABUF(TAGT)
	OUTTAB(IND+0) = I1TEMP(1)
	OUTTAB(IND+1) = I1TEMP(2)
	OUTTAB(IND+2) = I1TEMP(3)
	OUTTAB(IND+3) = I1TEMP(4)
	IND=IND+4
C
C SET GAME NUMBER
C
	IF(TRABUF(TITYP).NE.IFIN) THEN
	  I4TEMP=TRABUF(TRGAM)
	  OUTTAB(IND+0) = I1TEMP(1)
	  OUTTAB(IND+1) = I1TEMP(2)
	  IND=IND+2
C
C SET NEXT GAME NUMBER
C
	  I4TEMP=TRABUF(TRNXT1)
	  OUTTAB(IND+0) = I1TEMP(1)
	  OUTTAB(IND+1) = I1TEMP(2)
	  IND=IND+2
        ENDIF
C
C SET NEXT PACK NUMBER
C
	IF(TRABUF(TITYP).EQ.IINV) THEN
	  I4TEMP=TRABUF(TRNXT2)
	  OUTTAB(IND+0) = I1TEMP(1)
	  OUTTAB(IND+1) = I1TEMP(2)
	  OUTTAB(IND+2) = I1TEMP(3)
	  OUTTAB(IND+3) = I1TEMP(4)
	  IND=IND+4
	ENDIF
C
C SET SUB CLASS FOR FINANCIAL REPORT
C
	IF(TRABUF(TITYP).EQ.IFIN) THEN
          IF(TRABUF(TRTYP).EQ.IPSET) THEN                        !PACK SETTLED 
            IND=14

C
C           SET REQUESTED AGENT NUMBER
C
            I4TEMP=TRABUF(TRCHN)
	    OUTTAB(IND+0) = I1TEMP(1)
	    OUTTAB(IND+1) = I1TEMP(2)
	    OUTTAB(IND+2) = I1TEMP(3)
	    OUTTAB(IND+3) = I1TEMP(4)
	    IND=IND+4
C
C           CONTINUATION GAME NUMBER
C
            I4TEMP=TRABUF(TRCON1)
	    OUTTAB(IND+0) = I1TEMP(1)
	    OUTTAB(IND+1) = I1TEMP(2)
	    IND=IND+2
C
C           FILLER
C 
            IND=IND+2
C
C           CONTINUATION PACK NUMBER
C
            I4TEMP=TRABUF(TRCON2)
	    OUTTAB(IND+0) = I1TEMP(1)
	    OUTTAB(IND+1) = I1TEMP(2)
	    OUTTAB(IND+2) = I1TEMP(3)
	    OUTTAB(IND+3) = I1TEMP(4)
	    IND=IND+4
          ELSEIF(TRABUF(TRTYP).EQ.IADJR) THEN
            IND=14

C
C           SET REQUESTED AGENT NUMBER
C
            IF(TRABUF(TRSUB).EQ.4.OR.TRABUF(TRSUB).EQ.5)THEN !CHAIN INDIVIDUAL
      	      I4TEMP=TRABUF(TRCON)
            ELSEIF(TRABUF(TRSUB).EQ.2.OR.TRABUF(TRSUB).EQ.6) THEN
	      I4TEMP=TRABUF(TRCHN)
            ELSE                                !INDEPENDENT RETAILER
              I4TEMP=TRABUF(TAGT)
            ENDIF
	    OUTTAB(IND+0) = I1TEMP(1)
	    OUTTAB(IND+1) = I1TEMP(2)
	    OUTTAB(IND+2) = I1TEMP(3)
	    OUTTAB(IND+3) = I1TEMP(4)
	    IND=IND+4
C
C           CONTINUATION ADJUSTMENT DATE
C
            I4TEMP=TRABUF(TRCON1)
	    OUTTAB(IND+0) = I1TEMP(1)
	    OUTTAB(IND+1) = I1TEMP(2)
	    OUTTAB(IND+2) = I1TEMP(3)
	    OUTTAB(IND+3) = I1TEMP(4)
	    IND=IND+4
C
C           CONTINUATION ADJUSTMENT TIME
C
            I4TEMP=TRABUF(TRCON2)
	    OUTTAB(IND+0) = I1TEMP(1)
	    OUTTAB(IND+1) = I1TEMP(2)
	    OUTTAB(IND+2) = I1TEMP(3)
	    OUTTAB(IND+3) = I1TEMP(4)
	    IND=IND+4
C
C           CONTINUATION ADJUSTMENT TYPE
C
            I4TEMP=TRABUF(TRCON3)
	    OUTTAB(IND+0) = I1TEMP(1)
	    OUTTAB(IND+1) = I1TEMP(2)
	    IND=IND+2
          ELSEIF(TRABUF(TRTYP).NE.IADJT) THEN
	    I4TEMP=TRABUF(TRTYP)
	    OUTTAB(IND+0) = I1TEMP(1)
	    OUTTAB(IND+1) = I1TEMP(2)
	    IND=IND+2
C
C           SET REPORT REQUEST TYPE
C  
	    I4TEMP=TRABUF(TRCON1)
	    OUTTAB(IND+0) = I1TEMP(1)
	    OUTTAB(IND+1) = I1TEMP(2)
	    IND=IND+2
C
C           SET NEXT AGENT NUMBER
C
            I4TEMP=0
	    OUTTAB(IND+0) = I1TEMP(1)
	    OUTTAB(IND+1) = I1TEMP(2)
	    OUTTAB(IND+2) = I1TEMP(3)
	    OUTTAB(IND+3) = I1TEMP(4)
	    IND=IND+4
C
C           SET CHAIN PASSWORD
C
	    I4TEMP=CHNPAS
	    OUTTAB(IND+0) = I1TEMP(1)
	    OUTTAB(IND+1) = I1TEMP(2)
	    OUTTAB(IND+2) = I1TEMP(3)
	    OUTTAB(IND+3) = I1TEMP(4)
	    IND=IND+4
          ENDIF
	ENDIF
C
C
C
	RETURN
	END
