C
C SUBROUTINE DELMSG
C $Log:   GXAFXT:[GOLS]DELMSG.FOV  $
C  
C     Rev 1.0   17 Apr 1996 12:50:46   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 16:03:46   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - msgsub.for **
C
C
C
C *** DELMSG: DELETE A MESSAGE
C
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE DELMSG(MSGNUM)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
C
	INCLUDE 'INCLIB:MSGCOM.DEF'
C
	INTEGER*4 LOCMSG, LINK, MSGNUM
C
	I4MSGTAB(SEGLEN,MSGNUM)=0                 !FREE BASE SEGMENT
	LINK=I4MSGTAB(MSGLNK,MSGNUM)              !GET LINK, IF ANY
	I4MSGTAB(MSGLNK,MSGNUM)=0                 !CLEAR LINK
C
C     NOW FREE UP ALL LINKS
C
	LOCMSG=MSGNUM
10	CONTINUE
	IF(LINK.GT.0) THEN
	  IF(LINK.LE.MSGS .OR. LINK.GE.MSGCTL)THEN
	    TYPE *,'MESSAGE ',LOCMSG,' HAS BAD LINK= ',LINK
	    TYPE *,'THIS LINK IGNORED'
	    GO TO 50
	  ENDIF
C
	  LOCMSG=LINK
	  LINK=I4MSGTAB(MSGLNK,LOCMSG)            !SAVE NEXT LINK
	  I4MSGTAB(MFRLNK,LOCMSG)=I4MSGTAB(MFRLNK,MSGCTL) !ADD TO CHAIN
	  I4MSGTAB(MFRLNK,MSGCTL)=LOCMSG
	  I4MSGTAB(MFRCNT,MSGCTL)=I4MSGTAB(MFRCNT,MSGCTL)+1 !INC COUNT
	  GO TO 10
	ENDIF
C
50	CONTINUE
	RETURN
	END
