CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C File      : DIGSODSCAN.FOR
C Change Log:
C
C Ver Date       Author  Comment
C --- ---------- ------- ----------------------------------------------
C V01 2014.02.24 SCML    PLACARD PROJECT - Created - Decodes terminal
C                        cancelation input messages for IGS;
C
C THIS ROUTINE CAN GENERATE THE FOLLOWING 'SYNTERRCOD'
C         5     GAME INDEX NOT PLACARD
C
C++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C                 THIS ITEM IS THE PROPERTY OF SCML.
C
C             COPYRIGHT 2014 SCML. ALL RIGHTS RESERVED.
C++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C=======OPTIONS /CHECK=NOOVERFLOW/EXT
        SUBROUTINE DIGSODSCAN(TERMES,TRABUF)
        IMPLICIT NONE

        INCLUDE 'INCLIB:SYSPARAM.DEF'
        INCLUDE 'INCLIB:SYSEXTRN.DEF'
        INCLUDE 'INCLIB:GLOBAL.DEF'
        INCLUDE 'INCLIB:CONCOM.DEF'
        INCLUDE 'INCLIB:DESTRA.DEF'
        INCLUDE 'INCLIB:CHKSUMCM.DEF'

C DEBUG - START /*
        INCLUDE 'INCLIB:IGSDEBUG.DEF'
C DEBUG - END */

        BYTE        TERMES(*)



C
C IGS CANCELATION TRANSACTION BODY
C
C       GAME INDEX (1 - Placard)                                    (12)
        TRABUF(TGAMIND) = ZEXT(TERMES(7))
C DEBUG - START /*
        IF(IGSDEBUG(IA_INIGS)) THEN
           CALL OPS('TGAMIND',TRABUF(TGAMIND),TRABUF(TGAMIND))
        ENDIF
C DEBUG - END */

C       VALIDATE GAME INDEX
        IF(TRABUF(TGAMIND) .EQ. 1) THEN !PLACARD

C          BET REFERENCE DATE YEAR                                  (32)
           TRABUF(TIGSC_WRDY) = ZEXT(TERMES(20))
C DEBUG - START /*
        IF(IGSDEBUG(IA_INIGS)) THEN
           CALL OPS('TIGSC_WRDY',TRABUF(TIGSC_WRDY),TRABUF(TIGSC_WRDY))
        ENDIF
C DEBUG - END */

C          BET REFERENCE DATE MONTH                                 (33)
           TRABUF(TIGSC_WRDM) = ZEXT(TERMES(21))
C DEBUG - START /*
        IF(IGSDEBUG(IA_INIGS)) THEN
           CALL OPS('TIGSC_WRDM',TRABUF(TIGSC_WRDM),TRABUF(TIGSC_WRDM))
        ENDIF
C DEBUG - END */

C          BET REFERENCE DATE DAY                                   (34)
           TRABUF(TIGSC_WRDD) = ZEXT(TERMES(22))
C DEBUG - START /*
        IF(IGSDEBUG(IA_INIGS)) THEN
           CALL OPS('TIGSC_WRDD',TRABUF(TIGSC_WRDD),TRABUF(TIGSC_WRDD))
        ENDIF
C DEBUG - END */

C          BET REFERENCE GAME                                       (35)
           TRABUF(TIGSC_WRGM) = ZEXT(TERMES(23))
C DEBUG - START /*
        IF(IGSDEBUG(IA_INIGS)) THEN
           CALL OPS('TIGSC_WRGM',TRABUF(TIGSC_WRGM),TRABUF(TIGSC_WRGM))
        ENDIF
C DEBUG - END */

C          BET REFERENCE SERIAL NUMBER (HIGH ONE BYTE)              (37)
           TRABUF(TIGSC_WRSH) = ZEXT(TERMES(24))
C DEBUG - START /*
        IF(IGSDEBUG(IA_INIGS)) THEN
           CALL OPS('TIGSC_WRSH',TRABUF(TIGSC_WRSH),TRABUF(TIGSC_WRSH))
        ENDIF
C DEBUG - END */

C          BET REFERENCE SERIAL NUMBER (LOW FOUR BYTES)             (36)
           CALL TERM_TO_HOST(TERMES(25), TRABUF(TIGSC_WRSL), 4)
C DEBUG - START /*
        IF(IGSDEBUG(IA_INIGS)) THEN
           CALL OPS('TIGSC_WRSL',TRABUF(TIGSC_WRSL),TRABUF(TIGSC_WRSL))
        ENDIF
C DEBUG - END */

C          BET REFERENCE CHECK DIGITS                               (38)
           CALL TERM_TO_HOST(TERMES(29), TRABUF(TIGSC_WRCD), 2)
C DEBUG - START /*
        IF(IGSDEBUG(IA_INIGS)) THEN
           CALL OPS('TIGSC_WRCD',TRABUF(TIGSC_WRCD),TRABUF(TIGSC_WRCD))
        ENDIF
C DEBUG - END */

C DEBUG - START /*
        IF(IGSDEBUG(IA_INIGS)) THEN
           CALL OPS('P(SUPCAN): ',P(SUPCAN),P(SUPCAN))
           TYPE*,'P(SUPCAN): ',P(SUPCAN)
        ENDIF
C DEBUG - END */

C DEBUG - START /*
        IF(IGSDEBUG(IA_INIGS)) THEN
           CALL OPS('P(IGSPPLA): ',P(IGSPPLA),P(IGSPPLA))
           TYPE*,'P(IGSPPLA): ',P(IGSPPLA)
        ENDIF
C DEBUG - END */

C DEBUG - START /*
        IF(IGSDEBUG(IA_INIGS)) THEN
           CALL OPS('P(IGSPCAN): ',P(IGSPCAN),P(IGSPCAN))
           TYPE*,'P(IGSPCAN): ',P(IGSPCAN)
        ENDIF
C DEBUG - END */

C DEBUG - START /*
        IF(IGSDEBUG(IA_INIGS)) THEN
           CALL OPS('P(IGSPGCAN): ',P(IGSPGCAN),P(IGSPGCAN))
           TYPE*,'P(IGSPGCAN): ',P(IGSPGCAN)
        ENDIF
C DEBUG - END */

C
C IF FUNCTION SUPRESSED THEN SET ERROR MESSAGE
C
           IF((P(SUPCAN) .NE. 0) .OR. P(IGSPPLA) .NE. 0
     *                           .OR. P(IGSPCAN) .NE. 0
     *                           .OR. IGSGAMFLG(P(IGSPGCAN),
     *                                          IGS_GAMNUM(TRABUF(TGAMTYP),
     *                                                     TRABUF(TGAMIND))))
     *     THEN
              TRABUF(TERR)  = SUPR
              TRABUF(TSTAT) = REJT
C DEBUG - START /*
        IF(IGSDEBUG(IA_INIGS)) THEN
           CALL OPS('FUNCTION SUPRESSED!!!',0,0)
           TYPE*,'FUNCTION SUPRESSED!!!'
        ENDIF
C DEBUG - END */
           ENDIF
        ELSE
           TRABUF(TSTAT) = REJT
           TRABUF(TERR)  = SYNT
           SYNTERRCOD=5
C DEBUG - START /*
        IF(IGSDEBUG(IA_INIGS)) THEN
           CALL OPS('INVALID GAME INDEX: ',TRABUF(TGAMIND),TRABUF(TGAMIND))
           TYPE*,'INVALID GAME INDEX: ',TRABUF(TGAMIND)
        ENDIF
C DEBUG - END */
        ENDIF


        RETURN
       END
