C
C V02 17-MAR-2016 SCML M16 PROJECT
C V01 13-NOV-2003 FRP Initial release.
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C This item is the property of GTECH Corporation, W.Greenwich, Rhode
C Island, and contains confidential and trade secret information. It
C may not be transferred from the custody or control of GTECH except
C as authorized in writing by an officer of GTECH. Neither this item
C nor the information it contains may be used, transferred,
C reproduced, published, or disclosed, in whole or in part, and
C directly or indirectly, except as expressly authorized by an
C officer of GTECH, pursuant to written agreement.
C
C Copyright 1999 GTECH Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW/EXT
        SUBROUTINE DMP_RECSCF(RLU,FILE,MONEY_UNIT)
        IMPLICIT NONE
C
        INCLUDE 'INCLIB:SYSPARAM.DEF'
        INCLUDE 'INCLIB:SYSEXTRN.DEF'
        INCLUDE 'INCLIB:GLOBAL.DEF'
        INCLUDE 'INCLIB:RECSCF.DEF'
C
        INTEGER*4 RLU
        INTEGER*4 FILE(5)
        INTEGER*4 MONEY_UNIT
C
        INTEGER*4 ST,I,J
C
        CHARACTER*16 C16TMP
        CHARACTER*20 C20TMP
C
        CHARACTER DESCR(39)*30
C
        DATA DESCR/
     *            'SYSTEM CONTROL PARAMETERS     ',                             !FIELD 1
     *            'GAME TYPE->NUMBER TABLE       ',                             !FIELD 2
     *            'GAME NUMBER->TYPE TABLE       ',                             !FIELD 3
     *            'KICKER GAME NUMBER            ',                             !FIELD 4
     *            'LONG GAME NAMES               ',                             !FIELD 5
     *            'SHORT GAME NAMES              ',                             !FIELD 6
     *            'GAME FILE NAMES               ',                             !FIELD 7
     *            'SYSTEM FILE NAMES             ',                             !FIELD 8
     *            'SYSTEM FILE SIZES             ',                             !FIELD 9
     *            'GAME FILE SIZES               ',                             !FIELD 10
     *            'COMMISSION RATES (BY GAME)    ',                             !FIELD 11
     *            'COMMISSION RATES (BY TYPE)    ',                             !FIELD 12
     *            'TICKET CHARGE BY GAME         ',                             !FIELD 13
     *            'PURGE DAYS BY GAME            ',                             !FIELD 14
     *            'REDMAX BY GAME                ',                             !FIELD 15
     *            'FLEX DOWN LOAD FILE NAMES     ',                             !FIELD 16
     *            'DLL FILE ATTRIBUTES (I*2)     ',                             !FIELD 17
     *            'SPECIAL SPORTS GAME FLAGS     ',                             !FIELD 18
     *            'GAME DATA VERIFY FILE NAMES   ',                             !FIELD 19
     *            'GAME DATA VERIFY FILE SIZES   ',                             !FIELD 20
     *            'HIGH TIER WINNER COMM LEVEL   ',                             !FIELD 21
     *            'HIGH TIER WINNER COMM RATE    ',                             !FIELD 22
     *            'HIGH TIER WINNER TAX LEVEL    ',                             !FIELD 23
     *            'HIGH TIER WINNER TAX RATE     ',                             !FIELD 24
     *            'REDEMPTION MINIMUM BY GAME    ',                             !FIELD 25
     *            'COMMISSION TAX                ',                             !FIELD 26
     *            'MAX FRACTIONS BY GAME         ',                             !FIELD 27
     *            'INSTANT GAMES VALIDATION CAP  ',                             !FIELD 28
     *            'OPINION POLL ID''S            ',                             !FIELD 29
     *            'OPINION POLL SEEDS            ',                             !FIELD 30
     *            'OPINION POLL START/END DATES  ',                             !FIELD 31
     *            'WIN HOLDING LIMITS            ',                             !FIELD 32
     *            'WIN HOLDING DAYS              ',                             !FIELD 33
     *            'PORT NUMBERS FOR TCPASST      ',                             !FIELD 34
     *            'IP ADDRESS PREF. FOR TCPASST  ',                             !FIELD 35
     *            'IP ADDRESS SUFF. FOR TCPASST  ',                             !FIELD 36
     *            'PAYMENT ORDER SEQUENTIAL NUM  ',                             !FIELD 37
     *            'RET DISCOUNT/COMISSION PASSIVE',                             !FIELD 38
     *            'FREE SPACE                    '/                             !FIELD 39
C
        CALL GETSCONF(SCFREC,ST)                                                !READ SCF FILE RECORD
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFPAR(NUMPAR)                 SYSTEM CONTROL PARAMETERS
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 100 I=1,NUMPAR
          WRITE(RLU,899) SCFPAROFF+I-1, SCFPAR(I), ' SCFPAR', I, DESCR(1)
100     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFGTN(MAXTYP,MAXIND)          GAME TYPE->NUMBER TABLE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 110 I=1,MAXTYP
          DO 120 J=1,MAXIND
            WRITE(RLU,903) SCFGTNOFF+(I-1)*MAXIND+J-1, SCFGTN(I,J),
     *                   'SCFGTN', I, J, DESCR(2)
120     CONTINUE
110     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFGNT(2,MAXGAM)               GAME NUMBER->TYPE TABLE                  
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 130 I=1,2
          DO 140 J=1,MAXGAM
            WRITE(RLU,903) SCFGNTOFF+(I-1)*MAXGAM+J-1, SCFGNT(I,J),
     *                   'SCFGNT', I, J, DESCR(3)
140     CONTINUE
130     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFKGN(MAXGAM)                 KICKER GAME NUMBER
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 150 I=1,MAXGAM
          WRITE(RLU,901) SCFKGNOFF+I-1, SCFKGN(I), 'SCFKGN', I, DESCR(4)
150     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFLGN(4,MAXGAM)               LONG GAME NAMES
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 160 I=1,MAXGAM
          WRITE(C16TMP, '(4A4)') (SCFLGN(J,I),J=1,4)
          DO J=1,16
            IF(C16TMP(J:J).EQ.CHAR(0)) C16TMP(J:J) = ' '
          ENDDO
          WRITE(RLU,9161) SCFLGNOFF+(I-1)*4, C16TMP,
     *                    'SCFLGN', I, DESCR(5)
160     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFSGN(MAXGAM)                 SHORT GAME NAMES
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 170 I=1,MAXGAM
          WRITE(C16TMP, '(A4)') SCFSGN(I)
          DO J=1,4
            IF(C16TMP(J:J).EQ.CHAR(0)) C16TMP(J:J) = ' '
          ENDDO
          WRITE(RLU,9170) SCFSGNOFF+I-1, C16TMP, 'SCFSGN', I, DESCR(6)
170     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFGFN(5,MAXGAM)               GAME FILE NAMES
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 180 I=1,MAXGAM
          WRITE(C20TMP, '(5A4)') (SCFGFN(J,I),J=1,5)
          DO J=1,20
            IF(C20TMP(J:J).EQ.CHAR(0)) C20TMP(J:J) = ' '
          ENDDO
          WRITE(RLU,9181) SCFGFNOFF+(I-1)*5, C20TMP, 
     *                    'SCFGFN', I, DESCR(7)
180     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFSFN(5,MAXFIL)               SYSTEM FILE NAMES
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 190 I=1,MAXFIL
          WRITE(C20TMP, '(5A4)') (SCFSFN(J,I),J=1,5)
          DO J=1,20
            IF(C20TMP(J:J).EQ.CHAR(0)) C20TMP(J:J) = ' '
          ENDDO
          WRITE(RLU,9181) SCFSFNOFF+(I-1)*5, C20TMP, 
     *                    'SCFSFN', I, DESCR(8)
190     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFFSZ(MAXFIL)                 SYSTEM FILE SIZES
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 200 I=1,MAXFIL
          WRITE(RLU,901) SCFFSZOFF+I-1, SCFFSZ(I), 'SCFFSZ', I, DESCR(9)
200     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFGSZ(MAXGAM)                 GAME FILE SIZES
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 210 I=1,MAXGAM
          WRITE(RLU,901) SCFGSZOFF+I-1, SCFGSZ(I), 'SCFGSZ', I, DESCR(10)
210     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFCOG(MAXGAM)                 COMMISSION RATES (BY GAME)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 220 I=1,MAXGAM
          WRITE(RLU,901) SCFCOGOFF+I-1, SCFCOG(I), 'SCFCOG', I, DESCR(11)
220     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFCOT(NUMFIN)                 COMMISSION RATES (BY TYPE)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 230 I=1,NUMFIN
          WRITE(RLU,901) SCFCOTOFF+I-1, SCFCOT(I), 'SCFCOT', I, DESCR(12)
230     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFTKC(MAXGAM)                 TICKET CHARGE BY GAME
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 240 I=1,MAXGAM
          WRITE(RLU,901) SCFTKCOFF+I-1, SCFTKC(I), 'SCFTKC', I, DESCR(13)
240     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFPRG(MAXGAM)                 PURGE DAYS BY GAME
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 250 I=1,MAXGAM
          WRITE(RLU,901) SCFPRGOFF+I-1, SCFPRG(I), 'SCFPRG', I, DESCR(14)
250     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFRED(MAXGAM)                 REDMAX BY GAME
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 260 I=1,MAXGAM
          WRITE(RLU,9260) SCFREDOFF+I-1, SCFRED(I), 
     *                   CSMONY(SCFRED(I),14,MONEY_UNIT), 'SCFRED', I, DESCR(15)
260     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFDLNAM(MAXLOADS)             FLEX DOWN LOAD FILE NAMES
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 270 I=1,MAXLOADS
          WRITE(C16TMP, '(A4)') SCFDLNAM(I)
          DO J=1,4
            IF(C16TMP(J:J).EQ.CHAR(0)) C16TMP(J:J) = ' '
          ENDDO
          WRITE(RLU,9270) SCFDLNAMOFF+I-1, 
     *                    C16TMP, 'SCFDLNAM', I, DESCR(16)
270     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFDLTAB(MAXLOADS,5)           DLL FILE ATTRIBUTES (I*2)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 280 I=1,MAXLOADS
          DO 285 J=1,5
            WRITE(RLU,9280) SCFDLTABOFF+(I-1)*5+J-1, 
     *                      SCFDLTAB(I,J), 'SCFDLTAB', I, J, DESCR(17)
285     CONTINUE
280     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFSTP(MAXIND)                 SPECIAL SPORTS GAME FLAGS
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 290 I=1,MAXIND
          WRITE(RLU,9290) SCFSTPOFF+I-1, SCFSTP(I), SCFSTP(I), 
     *                    'SCFSTP', I, DESCR(18)
290     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFGVN(5,MAXGAM)               GAME DATA VERIFY FILE NAMES
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 300 I=1,MAXGAM
          WRITE(C20TMP, '(5A4)') (SCFGVN(J,I),J=1,5)
          DO J=1,20
            IF(C20TMP(J:J).EQ.CHAR(0)) C20TMP(J:J) = ' '
          ENDDO
          WRITE(RLU,9181) SCFGVNOFF+(I-1)*5, C20TMP, 
     *                   'SCFGVN', I, DESCR(19)
300     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFGSZ(MAXGAM)                 GAME FILE SIZES
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 310 I=1,MAXGAM
          WRITE(RLU,901) SCFGVSOFF+I-1, SCFGVS(I), 'SCFGVS', I, DESCR(20)
310     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFHVL                         HIGH TIER WINNER COMM LEVEL
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        WRITE(RLU,900) SCFHVLOFF, SCFHVL, 'SCFHVL', DESCR(21)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFHVR                         HIGH TIER WINNER COMM RATE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        WRITE(RLU,900) SCFHVROFF, SCFHVR, 'SCFHVR', DESCR(22)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFTAL                         HIGH TIER WINNER TAX LEVEL
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        WRITE(RLU,900) SCFTALOFF, SCFTAL, 'SCFTAL', DESCR(23)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFTAR                         HIGH TIER WINNER TAX RATE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        WRITE(RLU,900) SCFTAROFF, SCFTAR, 'SCFTAR', DESCR(24)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFRMI(MAXGAM)                 REDEMPTION MINIMUM BY GAME
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 320 I=1,MAXGAM
          WRITE(RLU,901) SCFRMIOFF+I-1, SCFRMI(I), 'SCFRMI', I, DESCR(25)
320     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFCTX                         COMMISSION TAX
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        WRITE(RLU,900) SCFCTXOFF, SCFCTX, 'SCFCTX', DESCR(26)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFFRC(MAXGAM)                 MAX FRACTIONS BY GAME
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 330 I=1,MAXGAM
          WRITE(RLU,901) SCFFRCOFF+I-1, SCFFRC(I), 'SCFFRC', I, DESCR(27)
330     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFIVC                         INSTANT GAMES VALIDATION CAP
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        WRITE(RLU,900) SCFIVCOFF, SCFIVC, 'SCFIVC', DESCR(28)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCF_OPNID(PRM_NUMOPN)          OPINION POLL ID'S
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 340 I=1,PRM_NUMOPN
          WRITE(RLU,9340) SCF_OPNIDOFF+I-1, SCF_OPNID(I),
     *                    'SCF_OPNID', I, DESCR(29)
340     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCF_OPNSEED(PRM_NUMOPN)        OPINION POLL SEEDS
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 350 I=1,PRM_NUMOPN
          WRITE(RLU,9350) SCF_OPNSEEDOFF+I-1, SCF_OPNSEED(I), 
     *                    'SCF_OPNSEED', I, DESCR(30)
350     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCF_OPNDATE(PRM_ENDDAT,PRM_NUMOPN)        OPINION POLL START/END DATES
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 360 I=1,PRM_ENDDAT
          DO 370 J=1,PRM_NUMOPN
            WRITE(RLU,9360) SCF_OPNDATEOFF+(I-1)*PRM_NUMOPN+J-1, 
     *                      SCF_OPNDATE(I,J), 'SCF_OPNDATE', I, J, DESCR(31)
370     CONTINUE
360     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCF_HLDLIM(MAXGAM,3)           WIN HOLDING LIMITS
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 380 I=1,MAXGAM
          DO 390 J=1,3
            WRITE(RLU,9380) SCF_HLDLIMOFF+(I-1)*3+J-1, SCF_HLDLIM(I,J),
     *                      'SCF_HLDLIM', I, J, DESCR(32)
390     CONTINUE
380     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCF_HLDDAY(MAXGAM,3)           WIN HOLDING DAYS
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 400 I=1,MAXGAM
          DO 410 J=1,3
            WRITE(RLU,9380) SCF_HLDDAYOFF+(I-1)*3+J-1, SCF_HLDDAY(I,J),
     *                      'SCF_HLDDAY', I, J, DESCR(33)
410     CONTINUE
400     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCF_TCPPORTS(2,2)              PORT NUMBERS FOR TCPASST
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 420 I=1,2
          DO 430 J=1,2
            WRITE(RLU,9420) SCF_TCPPORTSOFF+(I-1)*2+J-1, SCF_TCPPORTS(I,J),
     *                      'SCF_TCPPORTS', I, J, DESCR(34)
430     CONTINUE
420     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCF_TCPPREFIX(2)               IP ADDRESS PREFIXES FOR TCPASST
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 440 I=1,2
          WRITE(RLU,9440) SCF_TCPPREFIXOFF+I-1, SCF_TCPPREFIX(I), 
     *                    'SCF_TCPPREFIX', I, DESCR(35)
440     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCF_TCPSUFFIX(2,4)             IP ADDRESS SUFFIXES FOR TCPASST
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 450 I=1,2
          DO 460 J=1,4
            WRITE(RLU,9450) SCF_TCPSUFFIXOFF+(I-1)*4+J-1, SCF_TCPSUFFIX(I,J),
     *                      'SCF_TCPSUFFIX', I, J, DESCR(36)
460     CONTINUE
450     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCF_ORDER(MAXGAM)              PAYMENT ORDER SEQUENTIAL NUMBER
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 470 I=1,MAXGAM
          WRITE(RLU,9340) SCF_ORDEROFF+I-1, SCF_ORDER(I), 
     *                    'SCF_ORDER', I, DESCR(37)
470     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFRETCOM(NUMPAS)              RETURN DISCOUNT/COMISSION PASSIVE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 480 I=1,NUMPAS
          WRITE(RLU,9340) SCFRETCOMOFF+I-1, SCFRETCOM(I), 
     *                    'SCFRETCOM', I, DESCR(38)
480     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SCFFRE(SCFFRESIZ)              FREE SPACE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        DO 490 I=1,SCFFRESIZ
          WRITE(RLU,901) SCFFREOFF+I-1, SCFFRE(I),   'SCFFRE', I, DESCR(39)
490     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       FORMAT STATEMENTS
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
899     FORMAT(1X,I5,1X,I12,1X,14X,A6,'(',I3,')',4X,A30)
900     FORMAT(1X,I5,1X,I12,1X,15X,A6,9X,A30)

901     FORMAT(1X,I5,1X,I12,1X,15X,A6,'(',I2,')',5X,A30)
9260    FORMAT(1X,I5,1X,I12,1X,A14,1X,A6,'(',I2,')',5X,A30)

903     FORMAT(1X,I5,1X,I12,1X,12X,3X,A6,'(',I2,',',I2,')',2X,A30)

9160    FORMAT(1X,I5,1X,4A4,1X,11X,A6,'(',I2,')',5X,A30)
9161    FORMAT(1X,I5,1X,A16,1X,11X,A6,'(',I2,')',5X,A30)
9162    FORMAT(1X,I5,1X,A16,1X,TR50,A6,'(',I2,')',5X,A30)
9163    FORMAT(1X,I5,1X,A16,1X,T80,A6,'(',I2,')',5X,A30)

9170    FORMAT(1X,I5,1X,A4,9X,15X,A6,'(',I2,')',5X,A30)

9180    FORMAT(1X,I5,1X,5A4,1X,7X,A6,'(',I2,')',5X,A30)
9181    FORMAT(1X,I5,1X,A20,1X,7X,A6,'(',I2,')',5X,A30)


9270    FORMAT(1X,I5,1X,A4,8X,1X,14X,1X,A8,'(',I2,')',3X,A30)
9280    FORMAT(1X,I5,1X,I12,1X,12X,3X,A8,'(',I2,',',I2,')',2X,A30)

9290    FORMAT(1X,I5,1X,I12,1X,Z14.8,1X,A6,'(',I2,')',7X,A30)

9340    FORMAT(1X,I5,1X,I12,1X,15X,A9,'(',I2,')',5X,A30)
9350    FORMAT(1X,I5,1X,I12,1X,15X,A11,'(',I2,')',5X,A30)
9360    FORMAT(1X,I5,1X,I12,1X,12X,3X,A11,'(',I2,',',I2,')',2X,A30)
9380    FORMAT(1X,I5,1X,I12,1X,12X,3X,A10,'(',I2,',',I2,')',2X,A30)
9420    FORMAT(1X,I5,1X,I12,1X,12X,3X,A12,'(',I2,',',I2,')',2X,A30)
9440    FORMAT(1X,I5,1X,I12,1X,12X,3X,A13,'(',I2,')',2X,A30)
9450    FORMAT(1X,I5,1X,I12,1X,12X,3X,A13,'(',I2,',',I2,')',2X,A30)
C
        END
C
C END DMP_RECSCF.FOR
C
