C
C SUBROUTINE DWN_FUTURE
C $Log:   GXAFXT:[GOLS]DWN_FUTURE.FOV  $
C  
C     Rev 1.0   17 Apr 1996 13:03:22   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 16:11:34   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - dwnsub.for **
C
C
C
C
C SUBROUTINE TO DETERMINE IF A TRANSACTION EXPIRES THIS DRAW.
C
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE DWN_FUTURE(TRABUF,SAVE)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:DWNCOM.DEF'
	INCLUDE 'INCLIB:DESTRA.DEF'
	INTEGER*4 SAVE, ST, GIND, GTYP
C
	SAVE=0
	ST=TRABUF(TSTAT)
	IF(ST.NE.GOOD.AND.ST.NE.VOID.AND.ST.NE.INCA.AND.
     *	   ST.NE.EXCH) RETURN
C
C
	GIND=TRABUF(TGAMIND)
	GTYP=TRABUF(TGAMTYP)
	IF(GTYP.NE.TNBR) SAVE=1
	IF(GTYP.EQ.TNBR.AND.TRABUF(TWEND).GT.LNBDRW(GIND)) SAVE=1
	RETURN
	END
