C
C SUBROUTINE ENCSLM
C $Log:   GXAFXT:[GOLS]ENCSLM.FOV  $
C  
C     Rev 1.0   17 Apr 1996 13:05:00   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 16:13:36   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - vis_oussnp.for **
C
C
C
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE ENCSLM(LINE,ASAL,I)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INTEGER*4 ASAL(2,72)
	INTEGER*4 K,OFF,I
	CHARACTER*20 LINE(4)
C
C
	DO 10 K=1,4
	OFF=I+K-1
	IF(ASAL(1,OFF).EQ.0) RETURN
	WRITE(LINE(K),900) ASAL(1,OFF),CSMONY(ASAL(2,OFF),10,BETUNIT)
10	CONTINUE
	RETURN
900	FORMAT(2X,I8.8,A10)
	END
