C
C     FILE   : ESTPRIZES.FOR
C     AUTHOR : J.H.R
C     VERSION: 01            DATE: 01 / 06 / 2001
C
C
C V01 JHR INITIAL RELEASE FOR PORTUGAL PROJECT
C
C BITMAP OF ESTIMATED / FINAL PRIZES BY DIVISION FOR RESULTS REPORTS IN PORTUGAL
C
C     **************************************************************************
C
C        THIS ITEM IS THE PROPERTY OF GTECH CORPORATION, POVIDENCE, RHODE
C     ISLAND, AND CONTAINS CONFIDENTIAL AND TRADE SECRET INFORMATION. IT MAY
C     NOT BE TRANSFERRED FROM THE CUSTODY OR CONTROL OF GTECH EXCEPT AS AUTO -
C     RIZED IN WRITING BY AN OFFICER OF GTECH. NEITHER THIS ITEM NOR THE
C     INFORMATION IT CONTAINS MAY BE USED, TRANSFERRED, REPRODUCED, PUBLISHED
C     OR DISCLOSED, IN WHOLE OR IN PART, AND DIRECTLY OR INDIRECTLY, EXCEPT AS
C     EXPRESSLY AUTHORIZED BY AN OFFICER OR GTECH, PURSUANT TO WRITTEN AGREEMENT
C
C     Copyright 2000 GTECH Corporation. All Rigth Reserved
C
C     **************************************************************************
C
C THIS FUNCTION GENERATE BITMAP OF ESTIMATED PRIZES OR FINAL PRIZES BY DIVISION
C
C=======OPTIONS /CHECK = NOOVERFLOW /EXT
      SUBROUTINE ESTPRIZES(INPMSG, SHAREPOS, DRWCDC, DIVBITMAP, ESTPRZPOS)
      IMPLICIT NONE
C
C INCLUDES DEFINITION TO GENERATE ESTIMATED / FINAL PRIZES
C
      INCLUDE 'INCLIB:SYSPARAM.DEF'
      INCLUDE 'INCLIB:SYSEXTRN.DEF'
      INCLUDE 'INCLIB:GLOBAL.DEF'
      INCLUDE 'INCLIB:CONCOM.DEF'
C
C CONSTANT PARAMETERS DEFINITION TO GENERATE ESTIMATED / FINAL PRIZES
C
      INTEGER * 4 NUMBITS        ! NUMBER OF BITS IN ONE INTEGER * 4
C
C INITIATE CONSTANT PARAMETERS DEFINITION TO GENERATE ESTIMATED / FINAL PRIZES
C
      PARAMETER(NUMBITS = 32)    ! NUMBER OF BITS IN ONE INTEGER * 4
C
C PARAMETRES DEFINITION TO GENERATE ESTIMATED / FINAL PRIZES
C
      INTEGER * 4 SHAREPOS        ! SHARE COUNTS / VALUES POSITION IN MESSAGE
      INTEGER * 4 DRWCDC          ! DRAW CDC DATE
      INTEGER * 4 DIVBITMAP       ! DIVISIONS BIT MAP
      INTEGER * 4 ESTPRZPOS       ! ESTIMATED PRIZES POSITION IN MESSAGE
C
      BYTE INPMSG(*)              ! IMPUT / OUTPUT MESSAGE
C
C VARIABLES DEFINITION TO GENERATE ESTIMATED / FINAL PRIZES
C
      INTEGER * 4 BITCNT          ! BIT COUNTER
      INTEGER * 4 ESTPRZBITMAP    ! ESTIMATED PRIZE BITMAP
      INTEGER * 4 SHRPOS          ! SHARES POSITION
      INTEGER * 4 SHRVAL          ! SHARES VALUES
C
C INITIATE LOCAL VARIABLES TO GENERATE ESTIMATED / FINAL PRIZES
C
      ESTPRZBITMAP = 0
      SHRPOS = SHAREPOS
C
C INITIATE ESTIMATE / FINAL BIT MAP WITH ZEROS
C
      CALL HOST_TO_TERM(INPMSG(ESTPRZPOS), ESTPRZBITMAP, 2)
C
C LOOP TO KNOW IF IN THE GAME WE ARE SENDIG INFORMATION FOR DIVISION
C
      DO 1000 BITCNT =  NUMBITS - 1, 0, -1
C
C CHECK IF WE ARE SINDING THIS DIVISION INFORMATION TO THE TERMINAL
C
        IF(TSBIT(DIVBITMAP, BITCNT) .EQ. .FALSE.) GOTO 1000
C
C GET SHARE VALUE FOR ACTUAL DIVISION ( WE DO NOT NEED SHARE COUNTERS, SO JUMP )
C
        SHRPOS = SHRPOS + 4
        CALL TERM_TO_HOST(INPMSG(SHRPOS), SHRVAL, 4)
        SHRPOS = SHRPOS + 4
C
C CHECK IF SHARE VALUES IS GREATER THAN VALUE FOR HIGH PRIZES
C
        IF(SHRVAL .LT. P(VALPRZHI)) GOTO 1000
C
C CHECK IF NUMBER OF DAYS FOR PAY HIGH VALUES HAVE PAST 
C
        IF(DAYCDC - DRWCDC .GT. P(DAYHDPHI)) GOTO 1000 
C
C SET BIT MAP OF ESTIMATED / FINAL PRIZES OF THIS DIVISION
C
        CALL BSET(ESTPRZBITMAP, BITCNT)
C
C END OF LOOP TO KNOW IF IN THE GAME WE ARE SENDIG INFORMATION FOR DIVISION
C
1000  CONTINUE
C
C PUT BITMAP OF ESTIMATED / FINAL PRIZES IN OUTPUT MESSAGE
C
      CALL HOST_TO_TERM(INPMSG(ESTPRZPOS), ESTPRZBITMAP, 2)
C
C THIS IS THE END TO GENERATE ESTIMATED / FINAL PRIZES
C
      END
