C
C SUBROUTINE EXTNUM
C $Log:   GXAFXT:[GOLS]EXTNUM.FOV  $
C  
C     Rev 1.0   17 Apr 1996 13:07:12   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 16:14:18   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - lod1x2pol.for **
C
C++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C EXTNUM (CHAR_ARRAY, MAX_SIZE, NUM, NUMPOS)
C 	EXTRACTS A NUMBER FROM THE INPUT STRING
C	INPUTS:
C	    CHAR_ARRAY, MAX_SIZE, NUMPOS
C	OUTPUTS:
C	    NUM, NUMPOS
C--------------------------------------------------------------------------
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE  EXTNUM (CHAR_ARRAY, MAX_SIZE, NUM, NUMPOS)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
C
	CHARACTER*1	CHAR_ARRAY(*)
	INTEGER*4	NUM, MAX_SIZE, NUMPOS, IND, IND1
	CHARACTER*1	CHARX, CHAR0/'0'/
	BYTE		BYTEX, BYTE0
	EQUIVALENCE	(CHARX, BYTEX)
	EQUIVALENCE	(CHAR0, BYTE0)
C
C	FIND THE BEGINNING OF THE NUMBER
C
	DO 10 IND=NUMPOS,MAX_SIZE
	    CHARX = CHAR_ARRAY(IND)
	    IF (CHARX .GE. '0' .AND. CHARX .LE. '9') GOTO 20
10	CONTINUE
C
C	THERE IS NO NUMBER -- REPORT AN ERROR
C
	TYPE *, IAM(), 'THRE IS NO NUMBER WHERE EXPECTED:',
     1		NUMPOS
	NUMPOS = IND
	RETURN
C
20	CONTINUE
C
C	EXTRACT THE NUMBER
C
	NUM = 0
	DO 30 IND1=IND,MAX_SIZE
	    CHARX = CHAR_ARRAY(IND1)
	    IF (CHARX .LT. '0' .OR. CHARX .GT. '9') GOTO 40
	    NUM = NUM * 10 + (BYTEX - BYTE0)
30	CONTINUE
C
C	END OF THE NUMBER -- UPDATE THE NUMPOS AND RETURN
C
40	CONTINUE
C
	NUMPOS = IND1
C
	RETURN
	END
