C
C PROGRAM FAULTANL
C $Log:   GXAFXT:[GOLS]FAULTANL.FOV  $
C  
C     Rev 1.0   17 Apr 1996 13:07:44   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 16:15:24   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - faultanl.for **
C
C FAULTANL.FOR
C
C V03 30-JUN-92 GCAN FIXED REVERSING OF FAULT CODE,PCPOINTER AND PROC. ID.
C V02 10-FEB-92 GCAN INITIAL RELEASED FOR THE NETHERLANDS
C V01 01-AUG-90 XXX  RELEASED FOR VAX
C
C V01 04-APR-90 LOU R.  INITIAL RELEASE FOR FINLAND
C
C PRINT REPORT ON TERMINAL STATISTICS.
C
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C This item is the property of GTECH Corporation, Providence, Rhode
C Island, and contains confidential and trade secret information. It
C may not be transferred from the custody or control of GTECH except
C as authorized in writing by an officer of GTECH. Neither this item
C nor the information it contains may be used, transferred,
C reproduced, published, or disclosed, in whole or in part, and
C directly or indirectly, except as expressly authorized by an
C officer of GTECH, pursuant to written agreement.
C
C Copyright 1991 GTECH Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW
	PROGRAM FAULTANL
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
C
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:DESTRA.DEF'
	INCLUDE 'INCLIB:PRMLOG.DEF'
	INCLUDE 'INCLIB:PRMAGT.DEF'
	INCLUDE 'INCLIB:DATBUF.DEF'
C
	INTEGER*2   DATE(LDATE_LEN)
	INTEGER*4   LOGREC(LMUREC)
	INTEGER*4   XX, EXT, COPY, ST, SER
	INTEGER*4   PAGE, LINCNT, REPLU
C
	INTEGER*4   TER			    !Terminal Number.
	INTEGER*4   STACK		    !Stcak Pointer.
	INTEGER*4   LNENO		    !Line Number.
	INTEGER*4   FAULT		    !Fault Code.
	INTEGER*4   PCPNT		    !PC Pointer.
	INTEGER*4   PRCID		    !Process ID.
C
	CHARACTER HEAD*40
C
	LOGICAL EOF    /.FALSE./
C
	DATA REPLU/07/
	DATA LINCNT/70/
C
	CALL COPYRITE
C
C
C CLEAR/SET VARIABLES
C
	PAGE=0
	SER=1
C
C GET NUMBER OF REPORT COPIES
C
	TYPE *
	TYPE *,'<<<<< FAULTANL Spectra Fault Tracking >>>>>'
	TYPE *
	CALL INPNUM('Enter number of report copies   ',COPY,0,20,EXT)
	IF(EXT.NE.0) CALL GSTOP(GEXIT_OPABORT)
C
C GET TODAYS DATE FROM MEMORY
C
	DATE(VCDC)=DAYCDC
	CALL LCDATE(DATE)
C
	CALL ROPEN('FAULTANL.REP',REPLU,ST)
	IF(ST.NE.0) THEN
	   TYPE*,'Error opening FAULTANL.REP > ',ST
	   CALL USRCLOS1(REPLU)
	   CALL GSTOP(GEXIT_SUCCESS)
	ENDIF
C
C ENCODE REPORT HEADER
C
	WRITE (HEAD,8001) DATE(VMON),DATE(VDAY),DATE(VYEAR2)
C
C OPEN THE TMF FILE
C
	CALL OPENW(PTMF,SFNAMES(1,PTMF),4,0,0,ST)
	IF(ST.NE.0) CALL FILERR(SFNAMES(1,PTMF),1,ST,0)
	CALL TOPEN(PTMF)
C
C LOOP AND READ THE TM FILE
C
	TYPE*,'Scanning the Transaction Master File'
100	CONTINUE
	CALL READTMF(LOGREC,SER,EOF)
	IF(EOF) GOTO 1000
C
	CALL LOGTRA(TRABUF,LOGREC)
	IF(TRABUF(TSTAT).NE.GOOD) GOTO 100
	IF(TRABUF(TTYP).NE.TSPE) GOTO 100
	IF(TRABUF(TSFUN).NE.TFAULT) GOTO 100
	TER=TRABUF(TTER)
C
C REPORT DETAILS
C
	IF(LINCNT.GT.55) THEN
	  CALL TITLE(HEAD,'FAULTANL',1,REPLU,PAGE,DAYCDC)
	  WRITE(REPLU,9000)
	  LINCNT=5
	ENDIF
C
	STACK=0     !STACK POINTER 2 BYTES
	CALL MOVBYTN(TRABUF(TSDT1),1,STACK,3,2)
	LNENO=0     !CODE LINE NUMBER
	CALL MOVBYTN(TRABUF(TSDT1),3,LNENO,3,2)
	FAULT=0	    !FAULT CODE
	CALL MOVBYTN(TRABUF(TSOLD),1,FAULT,1,4)
	PCPNT=0	    !PC POINTER
	CALL MOVBYTN(TRABUF(TSNEW),1,PCPNT,1,4)
	PRCID=0	    !PROCESS ID
C
	CALL MOVBYTN(TRABUF(TSSGN),1,PRCID,1,4)
	WRITE(REPLU,9001)TER,FAULT,PCPNT,PRCID,
     *	   STACK,LNENO,(TRABUF(XX),XX=TSDT2,TSDT6)
	LINCNT=LINCNT+1
	GOTO 100
C
1000	CONTINUE
	CALL USRCLOS1 (     PTMF)
	CALL USRCLOS1(REPLU)
	CALL SPOOL('FAULTANL.REP',COPY,ST)
	CALL GSTOP(GEXIT_SUCCESS)
C
C     ======================= FORMAT STATEMENTS ====================
C
8001	FORMAT('SPECTRA FAULT TRACKING ----> ',I2.2,'/',I2.2,'/',I4.4)
C
9000	FORMAT(/,1X,' TERM',3X,'FAULT',3X,'PC POINTER',4X,'PROCESS ID',
     *	       4X,'S. R.',5X,'LINE',4X,'16 BYTES OF SOURCE DATA',//)
9001	FORMAT(1X,I4,1X,Z8.8,3X,Z8.8,10X,A4,3X,Z8.8,3X,I6.6,3X,4(4A4))
C
	END
