C
C SUBROUTINE GAMECMD
C $Log:   GXAFXT:[GOLS]GAMECMD.FOV  $
C  
C     Rev 1.0   17 Apr 1996 13:16:10   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 16:21:58   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - net_netsub.for;1 **
C
C
C     SUBROUTINE TO QUEUE A NETWORK COMMAND (INTO THE INP QUEUE)
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE GAMECMD(CMD,NODE,VALUE,WAY)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
C
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:DESNET.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
C
	INTEGER*4 BUF(CDLEN), ST, WAY, VALUE, NODE, CMD
C
	IF (DAYSTS.EQ.DSCLOS)THEN
D       TYPE *,'gamecmd ',CMD,' node ',NODE,' value ',VALUE,' way',WAY
	  RETURN
	ENDIF
C
C ADD LINK COMMAND
C
	IF(CMD.EQ.1) THEN
	  BUF(1)=4
	  BUF(2)=VALUE
	  BUF(3)=TCNET
	  BUF(8)=NODE
	  BUF(9)=WAY
	ENDIF
C
C REMOVE LINK COMMAND
C
	IF(CMD.EQ.2) THEN
	  BUF(1)=5
	  BUF(2)=VALUE
	  BUF(3)=TCNET
	  BUF(8)=NODE
	  BUF(9)=WAY
	ENDIF
C
C RESYNC COMMAND
C
	IF(CMD.EQ.3) THEN
	  BUF(1)=1
	  BUF(2)=VALUE
	  BUF(3)=TCSPE
	  BUF(8)=NODE
	  BUF(9)=WAY
	ENDIF
C
C SET MASTER COMMAND
C
	IF(CMD.EQ.4) THEN
	  BUF(1)=7
	  BUF(2)=VALUE
	  BUF(3)=TCNET
	  BUF(8)=NODE
	  BUF(9)=WAY
	ENDIF
C
	CALL QUECMD(BUF,ST)
	IF(ST.NE.0) THEN
D	  TYPE *,'CANNOT QUEUE COMMAND ',BUF
	ENDIF
C
	RETURN
	END
