C
C GENAGTMIL.FOR
C
C V02 18-DEC-2015 FRP CR31 PIN for Owner and Clerk
C V01 14-APR-2011 FRP INITIAL RELEASE FOR PORTUGAL
C
C PROGRAM TOOL TO GENERATE AN AGTMIL FILE.
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++            
C This item is the property of GTECH Corporation, W.Greenwich, Rhode            
C Island, and contains confidential and trade secret information. It            
C may not be transferred from the custody or control of GTECH except            
C as authorized in writing by an officer of GTECH. Neither this item            
C nor the information it contains may be used, transferred,                     
C reproduced, published, or disclosed, in whole or in part, and                 
C directly or indirectly, except as expressly authorized by an                  
C officer of GTECH, pursuant to written agreement.                              
C                                                                               
C Copyright 1993 GTECH Corporation. All rights reserved.                        
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++            
C                                                                               
      PROGRAM GENAGTMIL
      IMPLICIT NONE
C
      INCLUDE 'INCLIB:SYSPARAM.DEF'
      INCLUDE 'INCLIB:SYSEXTRN.DEF'
      INCLUDE 'INCLIB:GLOBAL.DEF'
      INCLUDE 'INCLIB:PRMAGT.DEF'
C
      INTEGER*4 ST
      INTEGER*4 SYSDATE(3)
      INTEGER*4 AGTMIL_LUN/TMP1_LUN/
      INTEGER*4 AGENT_CODE_STA,AGENT_CODE_END,AGENT_CODE
      CHARACTER RECORD_TYPE*2,AGENT_TYPE*1,AGENT_NAME*55,MANAGER_NAME*55,STORE_NAME*55
      CHARACTER BUSINESS_TYPE*6,LOCATION_CODE*6,ADRESS*45,ZIP_CODE*6,ZIP_NAME*30
      CHARACTER AGENT_PHONE*9,AGENT_FAX*9,BUSINESS_BRANCH*2,MANAGER_PHONE*9
      CHARACTER WAGER_STATUS*1,INSTANT_STATUS*1,PASSIVE_STATUS*1
      CHARACTER WAGER_BEGIN_SALES*6,WAGER_BEGIN_SUPPRESS*6,WAGER_END_SUPPRESS*6,WAGER_END_SALES*6
      CHARACTER INSTANT_BEGIN_SALES*6,INSTANT_BEGIN_SUPPRESS*6,INSTANT_END_SUPPRESS*6
      CHARACTER PASSIVE_BEGIN_SALES*6,PASSIVE_BEGIN_SUPPRESS*6,PASSIVE_END_SUPPRESS*6,PASSIVE_END_SALES*6
      CHARACTER WAGER_ACCOUNT*21,INSTANT_ACCOUNT*21,PASSIVE_ACCOUNT*21
      CHARACTER AGENT_SAP*6,OP_BANK_CODE*8,AGENT_PASSWORD*4,AGENT_X25_ADRESS*9,STORE_CODE*2
      CHARACTER DISTRIBUTION_LINE_CODE*2,AGENT_SPECIAL_CODE*7,DISTRIBUTION_TYPE*1,MANAGER_PASSWORD*4
C
      CALL CLRSCR(6)
      TYPE*,IAM()
      CALL COPYRITE
      TYPE*,IAM()
      TYPE*,IAM(),'<<< Program to Generate an AGTMIL File For Adding Agents >>>'
      TYPE*,IAM()
C
C Ask for Start/End Agents
111   CONTINUE
      TYPE*,IAM()
      CALL INPNUM('Enter Start Agent Number: ',AGENT_CODE_STA,1,9999999,ST)
      IF(ST.LT.0) CALL GSTOP(GEXIT_OPABORT)
C
      TYPE*,IAM()
      CALL INPNUM('Enter End   Agent Number: ',AGENT_CODE_END,AGENT_CODE_STA,9999999,ST)
      IF(ST.LT.0) CALL GSTOP(GEXIT_OPABORT)
C
      IF(AGENT_CODE_END-AGENT_CODE_STA+1 .GT. NUMAGT) THEN
        TYPE*,IAM()
        TYPE*,IAM(),'Error: There Are More Than ',NUMAGT,' Agents'
        GOTO 111
      ENDIF
C
C Open AGTMIL file
      OPEN(UNIT            = AGTMIL_LUN,
     *     FILE            = 'FILE:AGTMIL.ASC',
     *     STATUS          = 'NEW',
     *     CARRIAGECONTROL = 'LIST',
     *     RECL            = 469,
     *     IOSTAT          = ST)
      IF(ST.NE.0) THEN
        TYPE*,IAM(),'AGTMIL Open Error ',ST
        CALL GSTOP(GEXIT_FATAL)
      ENDIF
C
C Write AGTMIL header
      CALL XDAT(SYSDATE)
      WRITE(AGTMIL_LUN,1000) 2000+SYSDATE(1),SYSDATE(2),SYSDATE(3)
C
C Write AGTMIL records
      RECORD_TYPE = '01'  !Add
      AGENT_TYPE = '1'  !Online
      AGENT_NAME = 'JOSE PEREIRA DE MATOS'
      MANAGER_NAME = 'JOSE PEREIRA DE MATOS'
      STORE_NAME = 'SCML TESTING LAB @ PRAT'
      BUSINESS_TYPE = '000000'
      LOCATION_CODE = '060322'
      ADRESS = 'R.DR.ALVARO MONTEIRO,LT-11 * MARZOVELOS'
      ZIP_CODE = '0000001'
      ZIP_NAME = 'EL PRAT DE LLOBREGAT'
      AGENT_PHONE = '232416903'
      AGENT_FAX = '         '
      BUSINESS_BRANCH = '16'
      MANAGER_PHONE = '232416903'
      WAGER_STATUS = 'V'
      WAGER_BEGIN_SALES = '300901'
      WAGER_BEGIN_SUPPRESS = '000000'
      WAGER_END_SUPPRESS = '000000'
      WAGER_END_SALES = '000000'
      WAGER_ACCOUNT = '001111111110002000322'
      INSTANT_STATUS = 'V'
      INSTANT_BEGIN_SALES = '01012010'
      INSTANT_BEGIN_SUPPRESS = '00000000'
      INSTANT_END_SUPPRESS = '00000000'
      INSTANT_ACCOUNT = '002222222220002000322'
      PASSIVE_STATUS = 'V'
      PASSIVE_BEGIN_SALES = '300901'
      PASSIVE_BEGIN_SUPPRESS = '000000'
      PASSIVE_END_SUPPRESS = '000000'
      PASSIVE_END_SALES = '000000'
      PASSIVE_ACCOUNT = '003333333330002000322'
      AGENT_SAP = '000322'
      OP_BANK_CODE = '00100000'
      AGENT_PASSWORD = '9999'
      AGENT_X25_ADRESS = '000000000'
      STORE_CODE = '00'
      DISTRIBUTION_LINE_CODE = '01'
      AGENT_SPECIAL_CODE = '9900999'
      DISTRIBUTION_TYPE = '0'
      MANAGER_PASSWORD = '1111'
C
      DO AGENT_CODE = AGENT_CODE_STA,AGENT_CODE_END
        WRITE(AGTMIL_LUN,2000)
     *    RECORD_TYPE,AGENT_CODE,AGENT_TYPE,AGENT_NAME, MANAGER_NAME,STORE_NAME,
     *    BUSINESS_TYPE,LOCATION_CODE,ADRESS,ZIP_CODE,ZIP_NAME,AGENT_PHONE,
     *    AGENT_FAX,BUSINESS_BRANCH,MANAGER_PHONE,WAGER_STATUS,WAGER_BEGIN_SALES,
     *    WAGER_BEGIN_SUPPRESS,WAGER_END_SUPPRESS,WAGER_END_SALES,WAGER_ACCOUNT,
     *    INSTANT_STATUS,INSTANT_BEGIN_SALES,INSTANT_BEGIN_SUPPRESS,INSTANT_END_SUPPRESS,
     *    INSTANT_ACCOUNT,PASSIVE_STATUS,PASSIVE_BEGIN_SALES,PASSIVE_BEGIN_SUPPRESS,
     *    PASSIVE_END_SUPPRESS,PASSIVE_END_SALES,PASSIVE_ACCOUNT,AGENT_SAP,OP_BANK_CODE,
     *    AGENT_PASSWORD,AGENT_X25_ADRESS,STORE_CODE,DISTRIBUTION_LINE_CODE,
     *    AGENT_SPECIAL_CODE,DISTRIBUTION_TYPE,MANAGER_PASSWORD
      ENDDO
2000  FORMAT(A2,I7.7,A1,A55,A55,A45,A6,A6,A45,A7,A30,A9,A9,A2,A9,A1,A6,A6,A6,A6,A21,A1,
     *       A8,A8,A8,A21,A1,A6,A6,A6,A6,A21,A6,A8,A4,A9,A2,A2,A7,A1,A4)
C
C Write AGTMIL trailer
      CALL XDAT(SYSDATE)
      WRITE(AGTMIL_LUN,3000) AGENT_CODE_END-AGENT_CODE_STA+1
C
C Close AGTMIL
      CLOSE(AGTMIL_LUN)
C
      TYPE*,IAM()
      TYPE*,IAM(),'AGTMIL File Generated Containing ',AGENT_CODE_END-AGENT_CODE_STA+1,' Agents'
      CALL GSTOP(GEXIT_SUCCESS)
C
1000  FORMAT('HA',I4.4,I2.2,I2.2,459('0'))
3000  FORMAT('TA',I6.6,461('0'))
C
      END
