C
C SUBROUTINE GETLIB4
C $Log:   GXAFXT:[GOLS]GETLIB4.FOV  $
C  
C     Rev 1.0   17 Apr 1996 13:20:44   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 16:26:30   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - vis_libsnp.for **
C
C
C
C
C  GETLIB4.FTN
C
C
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE GETLIB4(NUM,GIND,LIABLE)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:NBRCOM.DEF'
	INCLUDE 'INCLIB:POLCOM.DEF'
C
	INTEGER*4 LIABLE(5,POLDAY),DIG(4)
	INTEGER*4 IND4S, IND4B, IND2MS, IND2MB, IND2BS, IND2BB, GIND
	INTEGER*4 IND2FS, IND2FB, TYPE, NUMM2, NUMB2, NUMF2, I, N, NUM
C
	N=NUM
	DO 10 I=1,4
	DIG(I)=MOD(N,10)
	N=N/10
10	CONTINUE
C
	NUMF2=DIG(4)*10+DIG(3)
	NUMB2=DIG(2)*10+DIG(1)
	NUMM2=DIG(3)*10+DIG(2)
C
C
	TYPE=TNB4B24
	CALL BOXTYP(DIG,TYPE,NB4TYP)
C
C GET POOL ADDRESSES
C
	CALL VNUMOD(NUMF2,TNB4F2,NB4TYP,IND2FB,IND2FS)
	CALL VNUMOD(NUMB2,TNB4B2,NB4TYP,IND2BB,IND2BS)
	CALL VNUMOD(NUMM2,TNB4M2,NB4TYP,IND2MB,IND2MS)
	CALL VNUMOD(NUM,TNB4ST,NB4TYP,IND4B,IND4S)
C
C CALCULATE LIABILITY
C
	DO 40 I=1,POLDAY
	LIABLE(1,I)=POOLT(IND2FS,I,GIND)
	LIABLE(2,I)=POOLT(IND2BS,I,GIND)
	LIABLE(3,I)=POOLT(IND2MS,I,GIND)
	LIABLE(4,I)=POOLT(IND4S,I,GIND)
	LIABLE(5,I)=POOLT(IND4B,I,GIND)
40	CONTINUE
C
	DO 50 I=1,POLDAY
	IF(NBRLIM(1,GIND).GT.0.OR.NBRLIM(2,GIND).GT.0.OR.
     *     NBRLIM(3,GIND).GT.0) THEN
	  LIABLE(1,I)=LIABLE(1,I)*NBRPRZ(TNB4F2,1,GIND)
	  LIABLE(2,I)=LIABLE(2,I)*NBRPRZ(TNB4B2,1,GIND)
	  LIABLE(3,I)=LIABLE(3,I)*NBRPRZ(TNB4M2,1,GIND)
	  LIABLE(4,I)=LIABLE(4,I)*NBRPRZ(TNB4ST,1,GIND)
	  IF(TYPE.NE.0) LIABLE(5,I)=LIABLE(5,I)*NBRPRZ(TYPE,1,GIND)
	ELSE
	  LIABLE(1,I)=LIABLE(1,I)*NBRPRC(GIND)
	  LIABLE(2,I)=LIABLE(2,I)*NBRPRC(GIND)
	  LIABLE(3,I)=LIABLE(3,I)*NBRPRC(GIND)
	  LIABLE(4,I)=LIABLE(4,I)*NBRPRC(GIND)
	  LIABLE(5,I)=LIABLE(5,I)*NBRPRC(GIND)
	ENDIF
50	CONTINUE
	RETURN
	END
