C
C SUBROUTINE GETLIB3
C $Log:   GXAFXT:[GOLS]GETLIB3.FOV  $
C  
C     Rev 1.0   17 Apr 1996 13:20:40   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 16:26:24   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - vis_libsnp.for **
C
C
C
C
C  GETLIB3.FTN
C
C
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE GETLIB3(NUM,GIND,LIABLE)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:NBRCOM.DEF'
	INCLUDE 'INCLIB:POLCOM.DEF'
	INTEGER*4 LIABLE(5,POLDAY),DIG(3)
	INTEGER*4 IND3S, IND3B, IND2SS, IND2SB, IND2BS, IND2BB, GIND
	INTEGER*4 IND2FS, IND2FB, TYPE, NUMS2, NUMB2, NUMF2, I, N, NUM
C
C
	N=NUM
	DO 10 I=1,3
	DIG(I)=MOD(N,10)
	N=N/10
10	CONTINUE
C
	NUMF2=DIG(3)*10+DIG(2)
	NUMB2=DIG(2)*10+DIG(1)
	NUMS2=DIG(3)*10+DIG(1)
C
C
	TYPE=TNB3B6
	CALL BOXTYP(DIG,TYPE,NB3TYP)
C
C GET POOL ADDRESSES
C
	CALL VNUMOD(NUMF2,TNB3F2,NB3TYP,IND2FB,IND2FS)
	CALL VNUMOD(NUMB2,TNB3B2,NB3TYP,IND2BB,IND2BS)
	CALL VNUMOD(NUMS2,TNB3S2,NB3TYP,IND2SB,IND2SS)
	CALL VNUMOD(NUM,TNB3ST,NB3TYP,IND3B,IND3S)
C
C CACULATE LIABILITY
C
	DO 40 I=1,POLDAY
	LIABLE(1,I)=POOLT(IND2FS,I,GIND)
	LIABLE(2,I)=POOLT(IND2BS,I,GIND)
	LIABLE(3,I)=POOLT(IND2SS,I,GIND)
	LIABLE(4,I)=POOLT(IND3S,I,GIND)
	LIABLE(5,I)=POOLT(IND3B,I,GIND)
40	CONTINUE
C
	DO 50 I=1,POLDAY
	IF(NBRLIM(1,GIND).GT.0.OR.NBRLIM(2,GIND).GT.0.OR.
     *     NBRLIM(3,GIND).GT.0) THEN
	  LIABLE(1,I)=LIABLE(1,I)*NBRPRZ(TNB3F2,1,GIND)
	  LIABLE(2,I)=LIABLE(2,I)*NBRPRZ(TNB3B2,1,GIND)
	  LIABLE(3,I)=LIABLE(3,I)*NBRPRZ(TNB3S2,1,GIND)
	  LIABLE(4,I)=LIABLE(4,I)*NBRPRZ(TNB3ST,1,GIND)
	  IF(TYPE.NE.0) LIABLE(5,I)=LIABLE(5,I)*NBRPRZ(TYPE,1,GIND)
	ELSE
	  LIABLE(1,I)=LIABLE(1,I)*NBRPRC(GIND)
	  LIABLE(2,I)=LIABLE(2,I)*NBRPRC(GIND)
	  LIABLE(3,I)=LIABLE(3,I)*NBRPRC(GIND)
	  LIABLE(4,I)=LIABLE(4,I)*NBRPRC(GIND)
	  LIABLE(5,I)=LIABLE(5,I)*NBRPRC(GIND)
	ENDIF
50	CONTINUE
	RETURN
	END
