C
C SUBROUTINE GETOVR
C $Log:   GXAFXT:[GOLS]GETOVR.FOV  $
C  
C     Rev 1.0   17 Apr 1996 13:21:40   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 16:27:12   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - poolupd.for **
C
C====================================================================
C    SUBROUTINE GETOVR-GET THE NUMBER OF REPEATS FOR OVERFLOWS
C
C    CALL SEQUENCE:   CALL GETOVR(OFFSET,TIMES,GAM)
C    IN-OFFSET=OFFSET OF NUMBER SEQUENCE OF LOTTO BOARD
C        GAM - GAM OFFSET BELONGS TO
C    OUT-TIMES=NUMBER OF TIMES OFFSET WAS BET ON.
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE GETOVR(OFFSET,TIMES,GAM)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
C
	INCLUDE 'INCLIB:POOLLTO.DEF'
C
	INTEGER*4 OFFSET,TIMES, OFF1, BLOCK, ST, OFF, GAM
	INTEGER*4 FDB(7)            !FDB BLOCK FOR WRITE
	INTEGER*4 OVERFLOWS(2,MAXOVR)!TABLE TO READ OVERFLOWS FROM FILE
C
	TIMES=0
	DO 100, OFF=1,MAXOVR-1
	IF (LTOVR(2,OFF,GAM).EQ.0) GOTO 200
	IF (LTOVR(1,OFF,GAM).EQ.OFFSET) THEN
	   TIMES=LTOVR(2,OFF,GAM)
	   GOTO 200
	ENDIF
100	CONTINUE
C
200	CONTINUE       !GET DATA LOADED TO OVERFLOW FILE
C
	IF (OVRBLK.EQ.0) RETURN
C
210	CONTINUE
	CALL OPENW(1,SFNAMES(1,LO1),4,0,0,ST)   !OPEN OVERFLOW FILE
	IF (ST.NE.0) THEN
C
C	  'FILERR' DOES PAUSE
C
	  TYPE *,IAM(),' Correct the problem to continue '
	  CALL FILERR(SFNAMES(1,LO1),1,ST,0)
	  GOTO 210
	ENDIF
	CALL IOINIT(FDB,1,MAXOVR*8/256*256)     !INITIALISE FOR I/O
C
C     READ FROM POOLOVR.FIL      ;READ OVERFLOWS FROM FILE
C
	DO 230, BLOCK=1,OVRBLK
	  CALL READW(FDB,BLOCK,OVERFLOWS(1,1),ST)
	  IF (ST.NE.0) THEN
C
C	  'FILERR' DOES PAUSE
C
	    TYPE *,IAM(),'Will not read overflow file if continued. '
	    CALL FILERR(SFNAMES(1,LO1),2,ST,BLOCK)
	    GOTO 8000
	  ENDIF
	  IF (OVERFLOWS(1,MAXOVR).NE.GAM) GOTO 230
	  DO 220, OFF1=1,MAXOVR-1
	   IF (OVERFLOWS(2,OFF1).EQ.0) GOTO 230
	   IF (OVERFLOWS(1,OFF1).EQ.OFFSET) THEN
	     TIMES=TIMES+OVERFLOWS(2,OFF1)
	     GOTO 230
	  ENDIF
220	CONTINUE
230	CONTINUE
C
8000	CONTINUE
	CALL CLOSEFIL(FDB)
	RETURN
	END
