C
C SUBROUTINE GETSHR3
C $Log:   GXAFXT:[GOLS]GETSHR3.FOV  $
C  
C     Rev 1.0   17 Apr 1996 13:22:48   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 16:28:26   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - poolshr3.for **
C
C
C-------------------------------------------------
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE GETSHR3(FDB,BET,MAXNR,WIN,BONUS_MASK,TOT3,TOT3P,
     *	                   IND3,GAM)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:POOLLTO.DEF'
	INCLUDE 'INCLIB:POOLSEE.DEF'
C
	INTEGER*4 OVR3P, OVR3, ST, OFFSET, OFF2, BONUS, OFF1
	INTEGER*4 NEXT, OFF, MISSED, HIT, FASTBIN, GAM, TOT3P, TOT3
	INTEGER*4 MAXNR, BET
C
	INTEGER*4 FDB(7)
	INTEGER*4 IND3(BET-3,*)  !INDEXES FOR
	INTEGER*4 MISSIND(3,SEEMAX3) !3 OUT OF LTPOOLNR(GAM)-POOLBET NOT WON
	INTEGER*4 BOARD(SEEBET)     !SORTED TABLE WITH OFFSETS
	INTEGER*4 WIN(*)              !WINNING NUMBERS
	INTEGER*4 BONUS_MASK(*)       !BIT MASK OF BONUS NRS
	INTEGER*4 NOWIN_NUM(SEEMXNR)      !NOT WINNING NUMBERS
	INTEGER*4 TAB(SEEMXNR)
C
	HIT=FASTBIN(BET,BET-3)
	MISSED=FASTBIN(MAXNR-BET,3)
C
C
	DO 50, OFF=1,MAXNR
	   TAB(OFF)=OFF
50	CONTINUE
C
	DO 60, OFF=1,BET
	   TAB(WIN(OFF))=0
60	CONTINUE
C
	NEXT=1
C
	DO 70, OFF=1,MAXNR
	   IF (TAB(OFF).EQ.0) GOTO 70
	   NOWIN_NUM(NEXT)=TAB(OFF)
	   NEXT=NEXT+1
70	CONTINUE
C
C     GET INDEXES FOR COMBINATIONS
C
	CALL COMB3(IND3,MISSIND,MAXNR-BET,BET)
C
	TOT3=0
C
	DO 100, OFF=1,HIT
	DO 100, OFF1=1,MISSED
C
	  BONUS=0
C
C       GET NEW COMBINATION
C
	  DO 80, OFF2=1,BET-3
	     TAB(OFF2)=WIN(IND3(OFF2,OFF))
80	  CONTINUE
	  IF (LTPOOLFLAG(6,GAM).NE.0) THEN
	     DO 90, OFF2=1,3
	        TAB(BET-2+OFF2)=NOWIN_NUM(MISSIND(OFF2,OFF1))
	        IF (TSBIT(BONUS_MASK(1),TAB(BET-2+OFF2)-1)) BONUS=-1
90	     CONTINUE
	  ELSE
	     DO 95, OFF2=1,3
	        TAB(BET-2+OFF2)=NOWIN_NUM(MISSIND(OFF2,OFF1))
95	     CONTINUE
	  ENDIF
C
	  CALL SRT3(TAB,BOARD,BET)         !SORT COMBINATION
	  CALL CMBOFF(BOARD,OFFSET,BET)
C
	  IF (BONUS.NE.0) OFFSET=-OFFSET
	  CALL ABL(OFFSET,SORTQ,ST)
	  IF (ST.NE.0) THEN
	      CALL CMBSORT(FDB,TOT3,TOT3P,GAM)
	      CALL ABL(OFFSET,SORTQ,ST)
	  ENDIF
C
100	CONTINUE
C
	CALL CMBSORT(FDB,TOT3,TOT3P,GAM)
C
	CALL MATOVR3(FDB,WIN,BONUS_MASK,OVR3,OVR3P,GAM,BET) !OVERFLOWS
	TOT3=TOT3+OVR3
	TOT3P=TOT3P+OVR3P
	IF (LTPOOLFLAG(6,GAM).EQ.0) TOT3=TOT3+TOT3P
	IF (LTPOOLFLAG(7,GAM).EQ.0) TOT3=0
	RETURN
	END
