C
C SUBROUTINE GETVDATA
C $Log:   GXAFXT:[GOLS]GETVDATA.FOV  $
C  
C     Rev 1.0   17 Apr 1996 13:23:38   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 16:29:28   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - valpro.for **
C
C
C     GET DATA FROM REPVQUE
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE GETVDATA(DATA)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
C
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:TASKID.DEF'
	INCLUDE 'INCLIB:PRMPRO.DEF'
	INCLUDE 'INCLIB:QUECOM.DEF'
C
	INTEGER*4 ST, DATA
C
10	CONTINUE
	CALL RTL(DATA,REPVQUE,ST)
	IF (ST.NE.2) RETURN
	CALL XWAIT(20,1,ST)
	GOTO 10
	END
