C
C     FILE   : GSALTSK.FOR
C     AUTHOR : J.H.R
C     VERSION: 01            DATE: 19 / 02 / 2001
C
C
C V01 JHR INITIAL RELEASE FOR PORTUGAL PROJECT
C
C
C THIS PROGRAM START ALL PROGRAMS TO GENERATE ALL LOADERS FOR GSALES
C
C ( THIS PROGRAM IS GSALES MANAGER TASK )
C
C     **************************************************************************
C
C        THIS ITEM IS THE PROPERTY OF GTECH CORPORATION, POVIDENCE, RHODE
C     ISLAND, AND CONTAINS CONFIDENTIAL AND TRADE SECRET INFORMATION. IT MAY
C     NOT BE TRANSFERRED FROM THE CUSTODY OR CONTROL OF GTECH EXCEPT AS AUTO -
C     RIZED IN WRITING BY AN OFFICER OF GTECH. NEITHER THIS ITEM NOR THE
C     INFORMATION IT CONTAINS MAY BE USED, TRANSFERRED, REPRODUCED, PUBLISHED
C     OR DISCLOSED, IN WHOLE OR IN PART, AND DIRECTLY OR INDIRECTLY, EXCEPT AS
C     EXPRESSLY AUTHORIZED BY AN OFFICER OR GTECH, PURSUANT TO WRITTEN AGREEMENT
C
C     Copyright 2000 GTECH Corporation. All Rigth Reserved
C
C     **************************************************************************
C
C THIS PROGRAM START ALL PORGRAMS TO GENERATES ALL GSALES LOADERS
C
C=======OPTIONS /CHECK = NOOVERFLOW /EXT
      PROGRAM GSALTSK
      IMPLICIT NONE
C
C INCLUDES DEFINITION TO RUN GSALES MANAGER TASK
C
      INCLUDE 'INCLIB:SYSPARAM.DEF'
      INCLUDE 'INCLIB:SYSEXTRN.DEF'
C
C CONSTANTS DEFINITIONS TO RUN GSALES MANAGER TASK
C
      INTEGER * 4 MAXGSLLST          ! MAXIMUM NUMBER OF TASK TO START
C
C INITIATE CONSTANTS DEFINITIONS TO RUN GSALES MANAGER TASK
C
      PARAMETER(MAXGSLLST = 8)       ! MAXIMUM NUMBER OF TASK TO START
C
C VARIABLES DEFINITION TO RUN GSALES MANAGER TASK
C
      INTEGER * 4 FSTS               ! FUNCTION STATUS
      INTEGER * 4 TSKSTS             ! TASK STATUS
      INTEGER * 4 TSKCNT             ! TASK COUNTER
C
      REAL * 8 GSLLST(MAXGSLLST)     ! GSALES LIST TASKS PROCEDURES
C
C INITIATE VARIABLES TO RUN GSALES MANAGER TASK
C
      DATA GSLLST /  'GSONLTRN',     ! GSALES ON LINE TRANSACTIONS LOADER
     *               'GSONLGAM',     ! GSALES ON LINE GAMES LOADER
     *               'GSDRWRES',     ! GSALES DRAW RESULTS LOADER
     *               'GSDRWDRW',     ! GSALES DRAWS DRAW LOADER
     *               'GSDRWDIV',     ! GSALES DRAW DIVISION LOADER 
     *               'GSDRWMAP',     ! GSALES DRAW MAP LOADER
     *               'GSPAYORD',     ! GSALES PAYMENT ORDERS LOADER
     *               'GSPOPAID'  /   ! GSALES PAYMENT ORDERS PAID
C
C DISPLAY USER INFORMATION ( RUNNING GSALES MANAGER TASK )
C
      CALL COPYRITE
      TYPE *, IAM()
      TYPE *, IAM(), 'Gsales Manager Task Is Starting All Loaders'
      TYPE *, IAM()
C
C SUBRUN ALL GSALES TASKS TO GENERATE ALL LOADERS FOR GSALES
C
      DO TSKCNT = 1, MAXGSLLST
        CALL NRUNTSK(GSLLST(TSKCNT))
      ENDDO
C
C WE HAVE ONE TASK OF GSALES THAT HAVE NOT FINISHED YET HIS/HER WORKING
C
1000  CONTINUE
C
C CHECK IF ALL GSALES TASKS HAVE BEEN FINISHED HIS/HER WORKING
C
      CALL XWAIT(2, 2, FSTS)
      DO TSKCNT = 1, MAXGSLLST
        CALL STTSK(GSLLST(TSKCNT), TSKSTS, FSTS)
        IF(FSTS .NE. 4) GOTO 1000
      ENDDO
C
C DISPLAY MESSAGE TO USER ( END FOR GSALES MANAGER TASK )
C
      TYPE *, IAM()
      TYPE *, IAM(), 'Gsales Has Generated All Files Loaders For Today'
      TYPE *, IAM()
C
C GSALES MANAGER TASK ENDS OK ( NO ERRORS DETECTED )
C
      CALL GSTOP(GEXIT_SUCCESS)
C
C THIS IS THE END TO RUN GSALES MANAGER TASK
C
      END

