C
C SUBROUTINE GUTSTAT
C
C V05 13-NOV-97 LOGICAL UNIT NUMBER ARE DETERMINED BY LIB$GET_LUN ROUTINE.
C
C $Log:   GXAFXT:[GOLS]GUTSTAT.FOV  $
C  
C     Rev 1.0   17 Apr 1996 13:28:34   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.1   07 Jun 1993 15:43:16   HXN
C  Included AGTINF.DEF
C  
C     Rev 1.0   21 Jan 1993 16:33:54   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - gutstat.for **
C
C GUTSTAT.FOR
C
C V03 07-JUN-93 HHN INCLUDED AGTINF.DEF
C V02 03-JUN-91 TKO Flip bytes for GLITS
C V01 28-MAR-91 JPJ INITAL RELEASE FOR MARYLAND
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C This item is the property of GTECH Corporation, Providence, Rhode
C Island, and contains confidential and trade secret information. It
C may not be transferred from the custody or control of GTECH except
C as authorized in writing by an officer of GTECH. Neither this item
C nor the information it contains may be used, transferred,
C reproduced, published, or disclosed, in whole or in part, and
C directly or indirectly, except as expressly authorized by an
C officer of GTECH, pursuant to written agreement.
C
C Copyright 1991 GTECH Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE GUTSTAT
	IMPLICIT NONE
C
	INCLUDE '(LIB$ROUTINES)'
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
C
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:AGTCOM.DEF'
	INCLUDE 'INCLIB:AGTINF.DEF'
	INCLUDE 'INCLIB:RECAGT.DEF'
	INCLUDE 'INCLIB:PRMLOG.DEF'
	INCLUDE 'INCLIB:DESTRA.DEF'
	INCLUDE 'INCLIB:DATBUF.DEF'
	INCLUDE 'INCLIB:RECGUT.DEF'
	INCLUDE 'INCLIB:X2XPRM.DEF'
	INCLUDE 'INCLIB:TMSAGT.DEF'
	INCLUDE 'INCLIB:TMFREP.DEF'
C
	INTEGER*4   LUN
C
	BYTE      GLTSTAB(NUMAGT,50), LOCTAB(NUMAGT)
	INTEGER*4 TERMINAL, J, IND, I4TEMP
	INTEGER*4 ST, DMY,I
	INTEGER*2 DATE(12)
	INTEGER*4 MM,DD,YY
	BYTE      I1TEMP(4)
	LOGICAL     FIRST/.TRUE./
	EQUIVALENCE (I4TEMP,I1TEMP)
	CHARACTER*20 TERSTAT
	EQUIVALENCE (TERSTAT,SFNAMES(1,GTFL))
C
C IF FIRST CALL OPEN SWAP.FIL AND OPEN GUTS.FIL
C
	IF(FIRST)THEN
	  FIRST=.FALSE.
          CALL FASTSET(0,LOCTAB,NUMAGT/4)
	  DATE(VCDC)=DAYCDC
	  CALL CDATE(DATE)
	  MM = DATE(VDAY)
	  DD = DATE(VMON)
	  YY = DATE(VYEAR)
	  DMY= DD*10000 + MM*100 + DATE(VYEAR)
C
C OPEN GUTS TERSTAT FILE
C
	  ST = LIB$GET_LUN(LUN)
	  IF(.NOT.ST) CALL LIB$SIGNAL(%VAL(ST))
	  CALL ROPEN1(TERSTAT,LUN,50,ST)
	  IF(ST.NE.0) CALL FILERR(SFNAMES(1,GTFL),1,ST,0)
C
C PUT AGENT NUMBER INTO TERSTAT.FIL
C
	  DO 200 I=1,NUMAGT
		IND=1
		I4TEMP=GTSAGTN(I)
		GLTSTAB(I,IND+0)=I1TEMP(4)
		GLTSTAB(I,IND+1)=I1TEMP(3)
		GLTSTAB(I,IND+2)=I1TEMP(2)
		GLTSTAB(I,IND+3)=I1TEMP(1)
		IND=IND+4
C
C PUT TERMINAL NUMBER INTO TERSTAT.FIL
C
		I4TEMP=I
		GLTSTAB(I,IND+0)=I1TEMP(4)
		GLTSTAB(I,IND+1)=I1TEMP(3)
		GLTSTAB(I,IND+2)=I1TEMP(2)
		GLTSTAB(I,IND+3)=I1TEMP(1)
		IND=IND+4
C
C PUT DATE INTO GUTS ARRAY
C
		I4TEMP=DMY
		GLTSTAB(I,IND+0)=I1TEMP(3)
		GLTSTAB(I,IND+1)=I1TEMP(2)
		GLTSTAB(I,IND+2)=I1TEMP(1)
		IND=IND+3
C
C PUT TIME INTO GUTS ARRAY
C
	        I4TEMP=0
		GLTSTAB(I,IND+0)=I1TEMP(3)
		GLTSTAB(I,IND+1)=I1TEMP(2)
		GLTSTAB(I,IND+2)=I1TEMP(1)
	        IND=IND+3
210	     CONTINUE
200	  CONTINUE
	ENDIF
C
C     ====================== Main Processing ========================
C
	IF(EOF) GOTO 1000
	IND=15
	DO 500 I=TSOLD,TSOLD+7
	   I4TEMP=TRABUF(I)
	   GLTSTAB(TRABUF(TTER),IND+0)=I1TEMP(4)
	   GLTSTAB(TRABUF(TTER),IND+1)=I1TEMP(3)
	   GLTSTAB(TRABUF(TTER),IND+2)=I1TEMP(2)
	   GLTSTAB(TRABUF(TTER),IND+3)=I1TEMP(1)
	   IND=IND+4
500     CONTINUE
	I4TEMP=TRABUF(TSOLD+8)
	GLTSTAB(TRABUF(TTER),IND+0)=I1TEMP(4)
	GLTSTAB(TRABUF(TTER),IND+1)=I1TEMP(3)
	LOCTAB(TRABUF(TTER))=1
	GOTO 9000
C
C     ==================== End of Main Processing ===================
C
1000	CONTINUE
C
C WRITE OUT REMAINDER OF CONFIGURATIONS TO SWAP.FIL
C
	DO 2000 TERMINAL=1,NUMAGT
	   IF(LOCTAB(TERMINAL).GT.0) THEN
	     WRITE(LUN,10000) (GLTSTAB(TERMINAL,J),J=1,50)
	   ENDIF
2000	CONTINUE
C
	CLOSE(LUN)
	ST = LIB$FREE_LUN(LUN)
C
9000	CONTINUE
	RETURN
C
10000	FORMAT(50A1)
	END
