C  GXSRC:ISBLDCMD.FOR
C
C V07 06-OCT-2000 UXN AlphaIPS release.
C V06 01-SEP-1994 MCM SWAPPING BYTES IS NO LONGER NECESSARY FOR THE DEC LMS
C V05 21-JUN-1994 MCM SEND PASSWORD AND PASSWORD OFFSET TO INSTANT SYSTEM
C V04 28-SEP-1993 TZK ADDED DOUBLE TERMINAL NUMBER DECODE.
C V03 20-JUL-1993 TZK FIXED GVTID PROBLEM - PER MCM.
C V02 12-JUL-1993 MCM ADDED GVTID UPDATES
C V01 05-MAY-1993 TJR INITIAL RELEASE FOR GEORGIA REF DSGN DOC CDH0001
C
C SUBROUTINE TO BUILD AND QUEUE AGENT COMMANDS TO CRSPRO 
C
C CALLING SEQUENCE:
C     CALL ISBLDCMD(CBUF,STATUS)
C INPUT
C     CBUF   - COMMAND BUFFER
C OUTPUT
C     STATUS - QUEUEING STATUS (0 = GOOD, -1 = NO BUFFERS AVAILABLE)
C
C
C AGENT CHANGE COMMAND BUFFER FORMAT 
C
C WORD                     CONTENTS
C   1                 COMMAND NUMBER
C   2                 COMMAND NEW VALUE
C   3                 COMMAND TYPE
C   4                 COMMAND LINE
C   5                 COMMAND TERMINAL
C   6                 COMMAND SOURCE
C   7                 COMMAND AGENT
C   8                 COMMAND DATA 1
C   9                 COMMAND DATA 2
C
C
C GVTID COMMAND BUFFER FORMAT
C
C WORD                     CONTENTS             VALUE
C   1                 COMMAND NUMBER            1
C   2                 COMMAND NEW VALUE         1
C   3                 COMMAND TYPE              TCX2X
C   4                 COMMAND LINE              VALUE BYTE 4
C   5                 COMMAND TERMINAL          VALUE BYTE 3
C   6                 COMMAND SOURCE
C   7                 COMMAND AGENT             0
C   8                 COMMAND DATA 1            STATION FILE NUMBER
C   9                 COMMAND DATA 2            46
C  10                 COMMAND DATA 3            GVTID BYTE 1 
C  11                 COMMAND DATA 4            GVTID BYTE 2 
C  12                 RECORD                    STATION NUMBER
C
C
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C This item is the property of GTECH Corporation, Providence, Rhode
C Island, and contains confidential and trade secret information. It
C may not be transferred from the custody or control of GTECH except
C as authorized in writing by an officer of GTECH. Neither this item
C nor the information it contains may be used, transferred,
C reproduced, published, or disclosed, in whole or in part, and
C directly or indirectly, except as expressly authorized by an
C officer of GTECH, pursuant to written agreement.
C
C Copyright 1994 GTECH Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
        OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE ISBLDCMD(CBUF,STATUS)	
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:PROCOM.DEF'
	INCLUDE 'INCLIB:PRMLOG.DEF'
	INCLUDE 'INCLIB:QUECOM.DEF'
	INCLUDE 'INCLIB:TASKID.DEF'
	INCLUDE 'INCLIB:DATBUF.DEF'
	INCLUDE 'INCLIB:AGTCOM.DEF'
C
	INTEGER*4 IND, BUF, STATUS, BLEN, TER,K
	INTEGER*4 CBUF(CDLEN), HBUF(4), ERR1,STATTEMP
        INTEGER*4 KK
	BYTE      B_AGTBUF(30)
	INTEGER*4 IGVTID(3)
	CHARACTER AGVTID(12)
        CHARACTER*12 AGVTID2
        EQUIVALENCE(AGVTID(1),AGVTID2,IGVTID(1))
C
	INTEGER*4   I4TEMP
	INTEGER*2   I2TEMP(2)
	BYTE	    I1TEMP(4)
	EQUIVALENCE (I4TEMP,I2TEMP,I1TEMP)
C									
C       BUILD CROSS SYSTEM MSG 11.15.1 IN B_AGTBUF
C   
C
C
C       GET BUFFER, IF AVAILABLE
C
	CALL GETBUF(BUF)
	IF(BUF.EQ.0) THEN
	   STATUS=-1 
	   RETURN
	ENDIF
C
C       BUILD HEADER
C       SET LENGTH
C
	IND=1
	I4TEMP=30
	B_AGTBUF(IND+0) = I1TEMP(1)
	B_AGTBUF(IND+1) = I1TEMP(2)
	IND=IND+2
C
C       SET GTECH SLOT ID
C
	I4TEMP=BUF
	B_AGTBUF(IND+0) = I1TEMP(1)
	B_AGTBUF(IND+1) = I1TEMP(2)
	IND=IND+2
C
C       SET GTECH CROSS REFERENCE NUMBER
C
	I4TEMP=P(ACTTIM)+ISSOFF			!SYSTEM TIME + UNIQUE OFFSET
	B_AGTBUF(IND+0) = I1TEMP(1)
	B_AGTBUF(IND+1) = I1TEMP(2)
	B_AGTBUF(IND+2) = I1TEMP(3)
	B_AGTBUF(IND+3) = I1TEMP(4)
	IND=IND+4
C
C       SET TRANSACTION TYPE CODE
C
        IF(CBUF(3).EQ.TCX2X) THEN
	  I4TEMP=22               !GVTID UPDATE
          STATTEMP=CBUF(12)
          CALL VALIDTER(STATTEMP,TER)
        ELSE
	  I4TEMP=18               !AGENT STATUS UPDATE
          TER=CBUF(5)         
        ENDIF
	B_AGTBUF(IND+0) = I1TEMP(1)
	B_AGTBUF(IND+1) = I1TEMP(2)
	IND=IND+2
C
C       BUILD MSG BODY
C       SET RETAILER NUMBER
C
	I4TEMP= AGTTAB(AGTNUM,TER)
	B_AGTBUF(IND+0) = I1TEMP(1)
	B_AGTBUF(IND+1) = I1TEMP(2)
	B_AGTBUF(IND+2) = I1TEMP(3)
	B_AGTBUF(IND+3) = I1TEMP(4)
	IND=IND+4
C
C       SET TERMINAL NUMBER
C
	I4TEMP=TER
	B_AGTBUF(IND+0) = I1TEMP(1)
	B_AGTBUF(IND+1) = I1TEMP(2)
	B_AGTBUF(IND+2) = I1TEMP(3)
	B_AGTBUF(IND+3) = I1TEMP(4)
	IND=IND+4
C
C       SET GVTID
C
        IF(CBUF(3).EQ.TCX2X) THEN
	  HBUF(1)=CBUF(10)
	  HBUF(2)=CBUF(11)
	  CALL HTOA(AGVTID,1,12,HBUF(1),ERR1)
C
	  DO 221,K=1,12
            KK=IND+K-1
            B_AGTBUF(KK) = ICHAR(AGVTID(K))    
221       CONTINUE
	  IND=IND+12
        ELSE

C
C         SET AGENT TYPE
C         IF COMMAND IS CHANGING AGENT TYPE, USE INPUT BUFFER VALUE, 
C	  OTHERWISE USE EXISTING AGTTAB VALUE
C
	  IF (CBUF(1).EQ.3) THEN
	     I4TEMP=CBUF(2)
	  ELSE
	     I4TEMP=AGTTAB(AGTTYP,TER)
	  ENDIF
	  B_AGTBUF(IND+0) = I1TEMP(1)
	  B_AGTBUF(IND+1) = I1TEMP(2)
	  B_AGTBUF(IND+2) = I1TEMP(3)
	  B_AGTBUF(IND+3) = I1TEMP(4)
	  IND=IND+4
C
C         SET PASSNUMBER OFFSET
C
C         IF COMMAND IS CHANGING AGENT PASSNUMBER, USE INPUT BUFFER VALUE,
C         OTHERWISE SEND 0
C
          IF (CBUF(1).EQ.2) THEN
             I4TEMP=CBUF(4)
          ELSE
             I4TEMP=0
          ENDIF
	  B_AGTBUF(IND+0) = I1TEMP(1)
	  B_AGTBUF(IND+1) = I1TEMP(2)
	  B_AGTBUF(IND+2) = I1TEMP(3)
	  B_AGTBUF(IND+3) = I1TEMP(4)
	  IND=IND+4
C
C         SET PASSNUMBER MODIFIED
C
C         IF COMMAND IS CHANGING AGENT PASSNUMBER, USE INPUT BUFFER VALUE,
C         OTHERWISE SEND 0
C
          IF (CBUF(1).EQ.2) THEN
             I4TEMP=CBUF(2)
          ELSE
             I4TEMP=0
          ENDIF
	  B_AGTBUF(IND+0) = I1TEMP(1)
	  B_AGTBUF(IND+1) = I1TEMP(2)
	  B_AGTBUF(IND+2) = I1TEMP(3)
	  B_AGTBUF(IND+3) = I1TEMP(4)
        ENDIF
C
C       CLEAR AND INITIALIZE PROCOM BUFFER
C
	HPRO(TRCODE,BUF)=TYPSSI						
	HPRO(INPLEN,BUF)=OUTLEN_MAX					
C
C       QUEUE TRANSACTION TO CRSPRO
C       FIRST BYTE ON INSTAB IS USED FOR CRSPRO
C
	BLEN=30
	CALL MOVBYT(B_AGTBUF,1,BPRO(BINSTAB,BUF),2,BLEN)
	CALL QUETRA(CRS, BUF)
	STATUS = 0
C
	RETURN
	END
