C
C SUBROUTINE LNWINLOS
C
C V01 30-NOV-2010 MAC LUCKY NUMBER
C
C
	OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE LNWINLOS(TRABUF,SHARES,WIN)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:WINCOM.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:DESTRA.DEF'
C
C
	INTEGER*4 SHARES(LTGDIV,2), SHARES_TMP(LTGDIV,2)
	INTEGER*4 GIND, WIN, I, J, OFF, DIV_CNV, DIV_LUCKY
C
	GIND=TRABUF(TGAMIND)
        IF (LLTLFL(GIND).LE.0) RETURN
C
	CALL FASTMOV(SHARES,SHARES_TMP,LTGDIV*2)
	CALL FASTSET(0,SHARES,LTGDIV*2)
C
C
C                  LLTLNC(2,LTGDIV,NUMLTO)
C                          1 - WITH    LUCKY NUMBER
C                          2 - WITH NO LUCKY NUMBER
C
C        LLNMMAP(1,MAXBDR,NUMLTO) - WINNING LUCKY NUMBER
C        TRABUF(TWLUCK)           - LUCKY NUMBER ON A TICKET
C
        DO I=0,LLTBDR(GIND)
C
          IF ( (TRABUF(TWLUCK).EQ.LLNMMAP(1,I+1,GIND)) .AND.
     *          LLNMMAP(1,I+1,GIND).GT.0  ) THEN
            OFF=1
            WIN=1
          ELSE
            OFF=2
          ENDIF
C
          DO J=1,LTGDIV
            DIV_CNV = LLTLNC(OFF,J,GIND)
            IF (DIV_CNV.EQ.0) CYCLE
            SHARES(DIV_CNV,I+1) = SHARES_TMP(J,I+1)
          ENDDO
C
          IF (SHARES(1,I+1).GT.1) THEN
            SHARES(2,I+1)=SHARES(2,I+1)+SHARES(1,I+1)-1
            SHARES(1,I+1)=1
          ENDIF
C
          DIV_LUCKY=LLTLDV(GIND)
          IF (OFF.EQ.1.AND.DIV_LUCKY.GT.0) SHARES(DIV_LUCKY,I+1) = TRABUF(TWSIMP)
C
        ENDDO
C
	RETURN
	END
C
