C
C PROGRAM LODIMG2
C
C V10 10-FEB-2000 UXN SNIF_AND_WRKSET added.
C V09 13-OCT-1999 RXK World Tour added.
C V08 25-MAY-1999 UXN CHKCOM moved to LODIMG6. Part of AGTCOM added here.
C                     LTOPOL ADDED.
C V07 08-JAN-1997 HXK Moved TSPCOM out to LODIMG4
C V06 07-JAN-1997 HXK Switched some .def's from LODIMG2 to LODIMG4
C V05 07-JAN-1997 HXK removed ENCCOM
C V04 13-NOV-1995 HXK Rearranged LODIMG, LODIMG2, LODIMG3
C V03 10-NOV-1995 HXK Further changes for Double, Couple
C V02 15-OCT-1994 HXK Adding /developing Bingo (15.Oct.94)
C V01 24-AUG-1993 GXA Initial revision.
C  
C  DEC Baseline
C
C
C This program exists solely to lock global pages in memory.
C It is run by reset.
C LODIMG2 exists so you can lock more than 65000 pages (Limit for one task).
C
C
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C This item is the property of GTECH Corporation, Providence, Rhode
C Island, and contains confidential and trade secret information. It
C may not be transferred from the custody or control of GTECH except
C as authorized in writing by an officer of GTECH. Neither this item
C nor the information it contains may be used, transferred,
C reproduced, published, or disclosed, in whole or in part, and
C directly or indirectly, except as expressly authorized by an
C officer of GTECH, pursuant to written agreement.
C
C Copyright 1999 GTECH Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW
	PROGRAM LODIMG2
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'

	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:PROCOM.DEF'
	INCLUDE 'INCLIB:CTLCOM.DEF'
	INCLUDE 'INCLIB:DESNET.DEF'
	INCLUDE 'INCLIB:AGTCOM.DEF'
	INCLUDE 'INCLIB:LANCOM.DEF'
	INCLUDE 'INCLIB:LOGCOM.DEF'
	INCLUDE 'INCLIB:LSYSCOM.DEF'
	INCLUDE 'INCLIB:X2XCOM.DEF'
	INCLUDE 'INCLIB:SLOCOM1.DEF'
	INCLUDE 'INCLIB:QUECOM.DEF'
	INCLUDE 'INCLIB:WINCOM.DEF'
        INCLUDE 'INCLIB:BNGCOM.DEF'
        INCLUDE 'INCLIB:DBLCOM.DEF'
        INCLUDE 'INCLIB:CPLCOM.DEF'
        INCLUDE 'INCLIB:SSCCOM.DEF'
        INCLUDE 'INCLIB:TRPCOM.DEF'
        INCLUDE 'INCLIB:TROCOM.DEF'
        INCLUDE 'INCLIB:STRCOM.DEF'
        INCLUDE 'INCLIB:STROCOM.DEF'
	INCLUDE 'INCLIB:LTOPOL.DEF'
	INCLUDE 'INCLIB:SPTCOM.DEF'
	INCLUDE 'INCLIB:TGLCOM.DEF'
C
C
	INTEGER*4   ST
C
	CALL COPYRITE
	CALL SNIF_AND_WRKSET
C
	CALL LOCKPAGES('AGTCOM', FRST_AGTCOM, LAST_AGTCOM)
	CALL LOCKPAGES('CTLCOM', FRST_CTLCOM, LAST_CTLCOM)
	CALL LOCKPAGES('NETCOM', FRST_NETCOM, LAST_NETCOM)
	CALL LOCKPAGES('LANCOM', FRST_LANCOM, LAST_LANCOM)
	CALL LOCKPAGES('LOGCOM', FRST_LOGCOM, LAST_LOGCOM)
	CALL LOCKPAGES('LSYSCOM', FRST_LSYSCOM, LAST_LSYSCOM)
        CALL LOCKPAGES('SLOCOM1', FRST_SLOCOM1, LAST_SLOCOM1)
        CALL LOCKPAGES('LTOPOL', FRST_LTOPOL, LAST_LTOPOL)
C
	CALL LOCKPAGES('QUECOM', FRST_QUECOM, LAST_QUECOM)
	CALL LOCKPAGES('WINCOM', FRST_WINCOM, LAST_WINCOM)

        CALL LOCKPAGES('BNGCOM', FRST_BNGCOM, LAST_BNGCOM)
        CALL LOCKPAGES('DBLCOM', FRST_DBLCOM, LAST_DBLCOM)
        CALL LOCKPAGES('CPLCOM', FRST_CPLCOM, LAST_CPLCOM)
        CALL LOCKPAGES('SSCCOM', FRST_SSCCOM, LAST_SSCCOM)
        CALL LOCKPAGES('TRPCOM', FRST_TRPCOM, LAST_TRPCOM)
        CALL LOCKPAGES('TROCOM', FRST_TROCOM, LAST_TROCOM)
        CALL LOCKPAGES('STRCOM', FRST_STRCOM, LAST_STRCOM)
        CALL LOCKPAGES('STROCOM', FRST_STROCOM, LAST_STROCOM)
        CALL LOCKPAGES('SPTCOM', FRST_SPTCOM, LAST_SPTCOM)
        CALL LOCKPAGES('TGLCOM', FRST_TGLCOM, LAST_TGLCOM)
C
	CALL LOCKPAGES('???TOTAL???',0,0)
C
1000	CONTINUE
	CALL XWAIT(5,2,ST)		!WAIT 5 SECONDS
	IF(DAYSTS.NE.DSCLOS) GOTO 1000
C
	CALL GSTOP(GEXIT_SUCCESS)

	END
