C
C SUBROUTINE LTSKTRAP
C
C*************************** START X2X PVCS HEADER ****************************
C
C  $Logfile::   GXAFXT:[GOLS]LTSKTRAP.FOV                                 $
C  $Date::   17 Apr 1996 13:59:24                                         $
C  $Revision::   1.0                                                      $
C  $Author::   HXK                                                        $
C
C**************************** END X2X PVCS HEADER *****************************
C
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - ltsktrap.for;1 **
C

C LTSKTRAP.FOR
C
C V02 27-MAY-03 UXN SET LOCLAN TO LANUP BEFORE CALLING GOLAN. SET LANSAPSTS
C                   TO SAPUP IF STATUS SAPQSCED
C V01 10-SEP-90 MRM RELEASED FOR VAX
C
C TASK TRAP SERVICE ROUTINE:
C
C  1. BEFORE YOU'RE TRAPED HERE, SOMEONE HAD PUT A BUFEFR INTO YOUR EXEC QUEUE
C  2. GET THE BUFFER. IF DATA, CHECK AND PROVIDE EDA, ESA, DSAP, SSAP.
C     PUT THE LENGTH IN AND SEND IT ON A CURRENT ETHER. THE WRITE ROUTINE
C     SHOULD CALL SVC 15 ONLY IF IT IS NOT ACTIVE.
C     IF COMMAND , EXECUTE IT.
C
C        ACTIVATE/DISACTIVATE STATION - CHANGE STATUS
C                                       OPEN LUNS TO ETHERNETS
C                                       START READ PROCEED ON ALL
C        OPEN/CLOSE SAP               - CHANGE LANSAPSTS
C                                     - SET QUESAP(SAP) AND MODE/TYPE
C        ACTIVATE/DIS ETHERNET        - CHANGE ETHER STATUS IN
C                                       LOCLAN(LAN) FOR LOCAL ADAPT
C                                       AND LANLAN(DSAP,LAN) FOR REMOTE
C                                       ALLOWED ONLY IF NO CONNECTIONS OPEN
C                                       THRU THIS ETHER
C                                       MAC SERVICES LOCLAN, DLL SERV LANLAN
C        CONNECT REQ / DIS REQ        - GENERATE FIND REQUEST, CONNECT REQUEST
C                                       TO REMOTE STATIONS(S) AND FINALLY
C                                       CONNECT INDICATION TO THE APPLICATION.
C                                       CONNCET AND DISCONNECT INDICATIONS
C                                       MAY COME TO THE APPLICATION ALSO WHEN:
C                                          * REMOTE SIDE OPENS OR CLOSES
C                                          * LOCAL SAP IS CLOSED
C        RUN LAN/STOP LAN             - EVEN IF LOCLAN(LAN)=UP THE ACTUAL LUNS
C                                       DONT HAVE TO BE STARTED FOR THIS LAN
C                                       OR MAYBE LTERTRAP CLOSED THEM.
C
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C This item is the property of GTECH Corporation, Providence, Rhode
C Island, and contains confidential and trade secret information. It
C may not be transferred from the custody or control of GTECH except
C as authorized in writing by an officer of GTECH. Neither this item
C nor the information it contains may be used, transferred,
C reproduced, published, or disclosed, in whole or in part, and
C directly or indirectly, except as expressly authorized by an
C officer of GTECH, pursuant to written agreement.
C
C Copyright 1994 GTECH Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE LTSKTRAP(PARAM)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE '($SYSSRVNAM)'
C
	INCLUDE 'INCLIB:LANCOM.DEF'
	INCLUDE 'INCLIB:LANEVN.DEF'
C
	INTEGER*4 OK, XBUF, ST, BNUM, C, TYPE, MODE, COUNT, QUE, CONN
        INTEGER*4 SAP, OFF, LAN, REPLY, COMMAND, DSAP, SSAP, STATUS
        INTEGER*4 BUF, PARAM
	CHARACTER*1 ZERO /Z00/
C
D	IF(LANTEST.NE.0) THEN
D	   TYPE*,'**** TASK TRAP **** [',PARAM,']'
D	ENDIF
C
C GET THE BUFEFR FROM THE EXEC QUE
C
100	CONTINUE
	CALL RTL(BUF,LANEXEC,STATUS)
	IF(STATUS.EQ.2) THEN
          RETURN
	ENDIF
C
	IF(LANTEST.NE.0) THEN
	   TYPE*,'**** BUF TYPE ****[',LANBUF(LANBTYP,BUF),BUF,']'
	ENDIF
	LANBUF(LANOWN,BUF)=OWNFEXEC
C
	IF(LANBUF(LANBTYP,BUF).EQ.LTYPDATA) THEN     !SET UP A BUFEFR FOR SV15
C
	   CALL ILBYTE(SSAP,LANBUF(1,BUF),SSAPBEG-1)
	   CALL ILBYTE(DSAP,LANBUF(1,BUF),DSAPBEG-1)
C
	   CALL LANACT(EVNDTAREQ,SSAP,DSAP,BUF)     !DATA REQUEST
C                          ;WILL START SVC15 IN NOT ACTIVE AND ALWAYS
C                          ;ADD THE BUFF TO THE IOWRITE QUE OF THE RIGHT LAN
C                          ;IF CONDITIONS NOT OK - JUST DUMP THE BUFFER
C                          ;CURRENT LAN IS CURLAN(SSAP,DSAP)
C
	ELSEIF(LANBUF(LANBTYP,BUF).EQ.LTYPCMD) THEN  !EXEC A COMMAND
C
	   COMMAND=LANBUF(LANDATAF,BUF)
D	   TYPE *,'**** COMMAND TRAP ***** [',COMMAND,' ]'
	   REPLY=LANBUF(LANDATAF+1,BUF)
	   IF(REPLY.NE.CCOMMAND) THEN
D	      TYPE*,'**** ILLEGAL COMMAND ****[',COMMAND,REPLY,']'
	      CALL OPS('**** TSKTRAP ILLEGAL CMD ****',COMMAND,REPLY)
	      CALL LANRELB(BUF)
	      GOTO 100
	   ENDIF
C
	   GOTO(1100,1200,1300,1400,1500,1600,1700,1800,1900,2000,
     *	        2100,2200),COMMAND
C
C INVALID COMMAND
C
	   CALL LANRELB(BUF)
D	   TYPE*,'**** INVALID COMAMND **** [',COMMAND,' ]'
	   CALL OPS('**** LTSKTRAP:... ILLEGAL COMMAND ****',COMMAND,0)
	   GOTO 100
C
C CONNECT REQUEST
C
1100	   CONTINUE
C
	   SSAP=LANBUF(LANDATAF+2,BUF)
	   DSAP=LANBUF(LANDATAF+3,BUF)
C
	   CALL LANACT(EVNCREQ,SSAP,DSAP,BUF)         !CHK IT, NACK IT
C                                                   ;WITH CLEAR IND IF
C                                                   ;NECESSARY, ACK IT
C                                                   ;WITH CONN IND
	   GOTO 100
C
C DISCONNECT REQUEST
C
1200	   CONTINUE
	   IF(REPLY.NE.CCOMMAND) THEN
D	     TYPE*,'**** ILLEGAL COMMAND ****[',COMMAND,REPLY,']'
           CALL OPS('**** LTSKTRAP:... ILLEGAL COMMAND ****',COMMAND,0)
	     CALL OPS('**** LTSKTRAP:... ILLEGAL REPLY ****',REPLY,0)
	     CALL LANRELB(BUF)
	     GOTO 100
	   ENDIF
	   SSAP=LANBUF(LANDATAF+2,BUF)
	   DSAP=LANBUF(LANDATAF+3,BUF)
C
	   CALL LANACT(EVNDREQ,SSAP,DSAP,BUF)        !CHK IT, NACK IT
C                                                     ;WITH CLEAR IND IF
C                                                     ;NECESSARY, ACK IT
C                                                     ;WITH DIS IND
	   GOTO 100
C
C INVALID - IND GOES FROM LANPRO TO APPL
C
1300	   CONTINUE
D	   TYPE*,'**** INVALID COMAMND **** [',COMMAND,' ]'
	   CALL OPS('**** LTSKTRAP:... ILLEGAL COMMAND ****',COMMAND,0)
	   CALL LANRELB(BUF)
	   GOTO 100
C
C INVALID - IND GOES FROM LANPRO TO APPL
C
1400	   CONTINUE
D	   TYPE*,'**** INVALID COMAMND **** [',COMMAND,' ]'
	   CALL OPS('**** LTSKTRAP:... ILLEGAL COMMAND ****',COMMAND,0)
	   CALL LANRELB(BUF)
	   GOTO 100
C
C ACTIVATE ETHERNET (ON/OFF, NOT GO/STOP TERMS)
C
1500	   CONTINUE
C
	   SSAP=LANBUF(LANDATAF+2,BUF)
	   DSAP=LANBUF(LANDATAF+3,BUF)   !IF ZERO LOCAL ONLY REQUEST
	   LAN=LANBUF(LANDATAF+4,BUF)
C
C IF WE DONT KNOW THE ADDREESS - REJECT
C
	   DO 1510 OFF=1,6
	     IF(CLANHOME(OFF,LAN).NE.ZERO) GOTO 1520 !WE HAVE IT
1510	   CONTINUE
C
	   GOTO 1540                                !WE DONT HAVE IT
C
1520	   CONTINUE
	   IF(DSAP.EQ.0) THEN
	      GOTO 1540
	   ENDIF
C
	   DO 1530 SAP=1,MAXSAP
	      LANLAN(SAP,LAN)=LANUP
	      LANOPN(SAP,LAN)=LSOPN
	      LOCLAN(SAP,LAN)=LANUP
1530	   CONTINUE
	
C
C
D	   TYPE*,'**** LANUP ****[',LAN,SSAP,LANLAN,']'
	   CALL OPS('**** LAN ACTIVATED ****',LAN,DSAP)
1540	   CONTINUE
C
	   CALL LANRELB(BUF)
	   GOTO 100
C
C DISACTIVATE ETHERNET  (IN ON/OFF TERMS)
C
1600	   CONTINUE
C
	   SSAP=LANBUF(LANDATAF+2,BUF)
	   DSAP=LANBUF(LANDATAF+3,BUF) !LOCAL ONLY REQUEST IF 0
	   LAN=LANBUF(LANDATAF+4,BUF)
C
C IF THIS IS A CURRENT ETHR FOR SOME SAP - REJECT
C
	   DO 1610 CONN=1,MAXCON
	   IF(CURLAN(CONN).EQ.LAN) THEN
	      GOTO 1620
	   ENDIF
1610	   CONTINUE
	   LOCLAN(SSAP,LAN)=LANDOWN
C
	   IF(DSAP.NE.0) THEN
	      DO 1630 DSAP=1,MAXSAP
	      LANLAN(DSAP,LAN)=LANDOWN
1630	      CONTINUE
	   ENDIF
C
	   CALL OPS('**** LAN DEACTIVATED ****',LAN,DSAP)
D	   TYPE*,'**** LANDOWN ****[',LAN,SSAP,DSAP,']'
1620	   CONTINUE
C
	   CALL LANRELB(BUF)
	   GOTO 100
C
C OPEN SAP
C
1700	   CONTINUE
C
	   SSAP=LANBUF(LANDATAF+2,BUF)
	   QUE=LANBUF(LANDATAF+3,BUF)
	   COUNT=LANBUF(LANDATAF+4,BUF)
	   MODE=LANBUF(LANDATAF+5,BUF)
	   TYPE=LANBUF(LANDATAF+6,BUF)
D	   TYPE *,'**** OPEN SAP REQUEST *** [',SSAP,QUE,COUNT, ']'
C
	   QUESAP(SSAP)=QUE
C
	   IF(QUE.LE.0.OR.QUE.GT.LANMAXTSK) THEN
D	      TYPE*,'**** ILLEGAL APPLICATION QUEUE ****[',QUE,SSAP,']'
            CALL OPS('**** LTSKTRAP:... ILLEGAL QUEUE ****',COMMAND,0)
	      CALL LANRELB(BUF)
	      GOTO 100
	   ENDIF
C
C ALLOCATE THE BUFFERS
C
D	   TYPE *,'*** NUMBER OF BUFFERS TO GET:  ',COUNT,'***'
	   DO 1710 C=1,COUNT
D	
	   CALL LANGETB(BNUM,STATUS)
	   IF(STATUS.EQ.2) THEN
	      IF(C.EQ.1) THEN
D		 TYPE *,'*** NO BUFFERS FIRST TRY ***'
	         LANBUF(LANDATAF+1,BUF)=CREPLYBAD
	         LANBUF(LANDATAF+4,BUF)=0
C
	         LANBUF(LANOWN,BUF)=OWNAPPL
	         CALL ABL(BUF,LANAPP(1,QUE),ST)
	         IF(LANTRPTSK(QUE).EQ.1) THEN
	         CALL QUEUE(LANTASKS(QUE),BUF,ST)
	         IF(ST.NE.0) THEN
                  CALL OPS('**** LTSKTRAP:... TRAP FAILURE ****',QUE,ST)
	         ENDIF
	         ENDIF
	         GOTO 100
	      ELSE
D	         TYPE *,'*** NOT ENOUGH BUFFERS ****'
	      ENDIF
	      COUNT=C-1       !ONLY THAT MANY
	      GOTO 1720
	   ELSE
D	      TYPE *,'*** LANGETB RETURNED ST=2 ***'
	   ENDIF
	   LANBUF(LANLIST,BNUM)=QUE
	   CALL LANRELB(BNUM)
1710	   CONTINUE
C
1720	   CONTINUE
	   IF(LANSAPSTS(SSAP).EQ.SAPDOWN) THEN
	      NUMSAP=NUMSAP+1
	      LANSAPSTS(SSAP)=SAPUP
D	      TYPE *,'**** SAP MODE SET TO UP *** [',SSAP,QUE,']'
	   ENDIF
	   IF(LANSAPSTS(SSAP).EQ.SAPQSCED) LANSAPSTS(SSAP)=SAPUP      ! V02
C
	   LANMODE(SSAP)=MODE
	   LANTYPE(SSAP)=TYPE
	   LANBUF(LANDATAF+1,BUF)=CREPLYOK
	   LANBUF(LANDATAF+4,BUF)=COUNT
C
C STARTUP ETHERNET FOR THE NEW SAP.
C
	   DO 1730 LAN=1,MAXLAN    !ACTUAL NUMBER OF LANS HERE  WOULD BE BETTER
	     IF(LANOPN(SSAP,LAN).EQ.LSOPN) THEN
		LOCLAN(SSAP,LAN) = LANUP	    ! V02
                CALL GOLAN(LAN,SSAP,REPLY)
	     ENDIF
1730	   CONTINUE
C
	   LANBUF(LANOWN,BUF)=OWNAPPL
	   CALL ABL(BUF,LANAPP(1,QUE),ST)
	   IF(LANTRPTSK(QUE).EQ.1) THEN
 	     CALL QUEUE(LANTASKS(QUE),BUF,ST)
	     IF(ST.NE.0) THEN
	      CALL OPS('**** LTSKTRAP:... TRAP FAILURE ****',QUE,ST)
	     ENDIF
	   ENDIF
	   GOTO 100
C
C CLOSE SAP
C
1800	   CONTINUE
C
	   SSAP=LANBUF(LANDATAF+2,BUF)
	   QUE=LANBUF(LANDATAF+3,BUF)
C
	   IF(QUE.LE.0.OR.QUE.GT.LANMAXTSK) THEN
            CALL OPS('**** LTSKTRAP:... ILLEGAL QUEUE ****',COMMAND,0)
	      CALL LANRELB(BUF)
	      GOTO 1890
	   ENDIF
	   IF(LANSAPSTS(SSAP).EQ.SAPDOWN) THEN
	      LANBUF(LANDATAF+1,BUF)=CREPLYOK
	      LANBUF(LANOWN,BUF)=OWNAPPL
	      CALL ABL(BUF,LANAPP(1,QUE),ST)
	      IF(LANTRPTSK(QUE).EQ.1) THEN
	      CALL QUEUE(LANTASKS(QUE),BUF,ST)
	      IF(ST.NE.0) THEN
	         CALL OPS('**** LTSKTRAP:... TRAP FAILURE ****',QUE,ST)
	      ENDIF
	      ENDIF
	      GOTO 1890
	   ENDIF
C
C CHECK THAT THERE ARE NOT ACTIVE CONNECTIONS
C
	   DO 1810 DSAP=1,MAXSAP
	   CONN=CONNECTION(SSAP,DSAP)
	   IF(LANCONN(CONN).NE.CSAPCLO) THEN
	      LANSAPSTS(SSAP)=SAPQSCED
	      CALL LANGETX(XBUF,ST)
	         IF (ST.EQ.2) THEN
	            CALL OPS('**** NO BUFFERS (QSC) ****',SSAP,DSAP)
	            LANCONN(CONN)=CSAPCLO
	            GOTO 1810
	      ENDIF
	      LANBUF(LANBTYP,XBUF)=LTYPCMD
	      LANBUF(LANDATAF,XBUF)=CDISREQ
	      LANBUF(LANDATAF+1,XBUF)=CCOMMAND
	      LANBUF(LANDATAF+2,XBUF)=SSAP
	      LANBUF(LANDATAF+3,XBUF)=DSAP
	      LANBUF(LANDATAF+4,XBUF)=0
	      LANBUF(LANOWN,XBUF)=OWNEXEC
	      CALL ABL(XBUF,LANEXEC,ST)
	      IF(LANTRPTSK(QUE).EQ.1) THEN
	      CALL QUEUE(LANTASKS(0),XBUF,ST)
	      IF(ST.NE.0) THEN
	         CALL OPS('**** LTSKTRAP:... TRAP FAILURE ****',0,ST)
	      ENDIF
	      ENDIF
	   ENDIF
1810	   CONTINUE
C
	   CALL CHKQSCE(SSAP)                !WILL CLOSE SAP AND SEND A RESP
C                                          ;IF QSCED AND NO CONNS ACTIVE
C LEAVE IF QUIESCED  OR CLOSED
C
	   IF(LANSAPSTS(SSAP).EQ.SAPQSCED.OR.
     *	      LANSAPSTS(SSAP).EQ.SAPDOWN)     THEN
	      CALL LANRELB(BUF)
	      GOTO 1890
	   ENDIF
C
C MARK HIS BUFFERS AS DESIGNATED TO FREE LIST
C
	   DO 1820 BNUM=1,LANBNUM
         IF(LANBUF(LANLIST,BNUM).EQ.QUE) LANBUF(LANLIST,BNUM)=LISTFREE
1820	   CONTINUE
C
C FLUSH HIS FRAP QUE AND APPL QUE
C
	   CALL FLUSHAPP(QUE)
	   CALL FLUSHFRA(QUE)
C
	   LANBUF(LANDATAF+1,BUF)=CREPLYOK
	   LANBUF(LANOWN,BUF)=OWNAPPL
	   CALL ABL(BUF,LANAPP(1,QUE),ST)
	   IF(LANTRPTSK(QUE).EQ.1) THEN
	   CALL QUEUE(LANTASKS(QUE),BUF,ST)
	   IF(ST.NE.0) THEN
	      CALL OPS('**** LTSKTRAP:... TRAP FAILURE ****',QUE,ST)
	   ENDIF
	   ENDIF
	   IF(LANSAPSTS(SSAP).EQ.SAPUP) THEN
	      NUMSAP=NUMSAP-1
	      LANSAPSTS(SSAP)=SAPDOWN
	   ENDIF
C
C CLOSE THE OPEN CHANNELS.
C
1890	   CONTINUE
	   CALL LCLOSESAP(SSAP,ST)
	   GOTO 100
C
C ACTIVATE STATION    (WILL CHANGE GO/STOP STATUS OF ALL "ON"
C                      LANS TO "GO", IE. WILL OPEN LOGICAL UNITS
C                      AND START READ IO'S.)
C
1900	   CONTINUE
C
	   IF(THISSTA.EQ.STAUP) THEN
	      CALL  LANRELB(BUF)
	      CALL OPS('**** STATION ALREADY UP ****',THISSTA,LANGO)
	      GOTO 100
	   ENDIF
C
	   OK=0
C***	   DO 1910 LAN=1,MAXLAN    !ACTUAL NUMBER OF LANS HERE  WOULD BE BETTER
C***	   CALL GOLAN(LAN,REPLY)
C***	   IF(REPLY.EQ.0) OK=OK+1
C***1910	   CONTINUE
C
	   OK=1
	   IF(OK.GT.0) THEN
	      THISSTA=STAUP
	      CALL OPS('**** LAN STATION IS UP NOW ****',THISSTA,
     *	               LANGO)
	   ENDIF
C
	   CALL  LANRELB(BUF)              ! NO RESPONSE FOR THIS ONE
	   GOTO 100
C
C DISACTIVATE THE STATION   (WILL CHANGE GO/STOP STATUS OF ALL LANS
C                            TO "STOP")
C
2000	   CONTINUE
C
	   IF(THISSTA.EQ.STADOWN) THEN
	      CALL  LANRELB(BUF)
	      CALL OPS('**** STATION ALREADY DOWN ****',THISSTA,LANGO)
	      GOTO 100
	   ENDIF
C
	   DO 2010 LAN=1,MAXLAN      !ACTUAL NUMBER OF LANS HERE
	   CALL STOPLAN(LAN,REPLY)
2010	   CONTINUE
C
	   THISSTA=STADOWN
C
	   CALL OPS('**** LAN STATION IS UP NOW ****',THISSTA,
     *	            LANGO)
C
	   CALL  LANRELB(BUF)              ! NO RESPONSE FOR THIS ONE
	   GOTO 100
C
2100	   CONTINUE
C
	   IF(THISSTA.EQ.STADOWN) THEN
	      CALL  LANRELB(BUF)
D	      TYPE*,'**** INVALID STATION STATE ****[',THISSTA,']'
	      GOTO 100
	   ENDIF
	   CALL  LANRELB(BUF)              ! NO RESPONSE FOR THIS ONE
	   GOTO 100
C
C STOP LAN
C
2200	   CONTINUE
C
	   IF(THISSTA.EQ.STADOWN) THEN
	      CALL  LANRELB(BUF)
	      TYPE*,'**** INVALID STATION STATE ****[',THISSTA,']'
	      GOTO 100
	   ENDIF
C
C GET PARAMETER (LAN)
C
	   LAN=LANBUF(LANDATAF+2,BUF)
C
C IF THIS IS A CURRENT ETHR FOR SOME SAP - REJECT
C
	   DO 2210 CONN=1,MAXCON
	   IF(CURLAN(CONN).EQ.LAN) THEN
	      CALL LANRELB(BUF)       !NO WAY
	      GOTO 100
	   ENDIF
2210	   CONTINUE
C
	   CALL STOPLAN(LAN,REPLY)
C
	   CALL  LANRELB(BUF)              ! NO RESPONSE FOR THIS ONE
C
	ELSE
D	   TYPE*,'**** ILLEGAL BUFFER TYPE ****'
	   CALL OPS('**** LTSKTRAP:... BUFFER INVALID ****',
     *	             LANBUF(LANBTYP,BUF),0)
	ENDIF
C
C CLEAN THEM ALL
C
	GOTO 100
	END
