C
C SUBROUTINE MESOLM
C
C MESOLM.FOR
C
C V01 26-AUG-2021 SCML New Terminal Project
C
C
C SUBROUTINE TO FORMAT COMOLM MESSAGES FOR ERRLOG
C
C MESSAGE #   MESSAGE FORMAT
C ---------   ----------------------------------------------------------
C   1         CONNECTED TO MESSAGEQ OF OLIMPO
C   2         NO CONNECTION TO MESSAGEQ OF OLIMPO
C   3         <TIME OUT MESSAGE> BUF:{BUFFER NUMBER},TER:{TERMINAL NUMBER},MSG T/S: 0x{MESSAGE TYPE/SUBTYPE},XR
F:{MESSAGE QUEUE SEQUENCE NUMBER}
C   4         <ERROR WHILE PUT INTO QUEUE OF MESSAGEQ> STATUS:{STATUS NUMBER}
C  99         DEBUG MESSAGE
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C Copyright 2021 SCML Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW
        SUBROUTINE MESOLM(MNUM,DBUF,MBUF,ALARM)
        IMPLICIT NONE
C
        INCLUDE 'INCLIB:SYSPARAM.DEF'
        INCLUDE 'INCLIB:SYSEXTRN.DEF'
C
        INCLUDE 'INCLIB:GLOBAL.DEF'
        INCLUDE 'INCLIB:CONCOM.DEF'
C
        INTEGER*4     DBUF(*), K, MNUM
        CHARACTER*140 MBUF
        LOGICAL       ALARM
C
        GOTO (1,2,3,4) MNUM
        GOTO 99
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
1       CONTINUE
        WRITE (MBUF,901)
901     FORMAT('CONNECTED TO MESSAGEQ OF OLIMPO')
        RETURN
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
2       CONTINUE
        WRITE (MBUF,902)
902     FORMAT('NO CONNECTION TO MESSAGEQ OF OLIMPO')
        RETURN
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
3       CONTINUE
        WRITE (MBUF,903) DBUF(1), DBUF(2), DBUF(3), DBUF(4)
903     FORMAT('<TIME OUT MESSAGE> BUF:',I0,                                    !BUFFER NUMBER
     *         ',TER:',I0,                                                      !TERMINAL NUMBER
     *         ',MSG T/S: 0x',Z0,                                               !MESSAGE TYPE/SUBTYPE
     *         ',ISER:',I0)                                                     !INTERNAL SERIAL NUMBER
        ALARM=.TRUE.
        RETURN
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
4       CONTINUE
        WRITE (MBUF,904) DBUF(1)
904     FORMAT('<ERROR WHILE PUT INTO QUEUE OF MESSAGEQ> STATUS: ',I10)
        ALARM=.TRUE.
        RETURN
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C5       CONTINUE
C        WRITE (MBUF,905) 'VISION PASSWORD ERROR WHILE TRYING TO ' //
C     *                   'CHANGE EM TIMEOUT'
C905     FORMAT(A)
C        ALARM=.TRUE.
C        RETURN
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C6       CONTINUE
C        WRITE (MBUF,906) 'VISION PASSWORD ERROR WHILE TRYING TO '//
C     *                   'CHANGE EM FIN TIMEOUT'
C906     FORMAT(A)
C        ALARM=.TRUE.
C        RETURN
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C INVALID MESSAGE NUMBER
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
99      CONTINUE
        IF(MNUM.NE.99) THEN
          ALARM=.TRUE.
          WRITE(MBUF,999) MNUM
999       FORMAT('INVALID GENERAL MESSAGE NUMBER> ',I4,'    ')
        ELSE
          WRITE(MBUF,998) DBUF(1), DBUF(2), DBUF(2)
998       FORMAT('DEBUG: ',I4,' - ',I10,'[',Z8,']')
        ENDIF
        RETURN
C
        END
C
C END MESOLM.FOR
