C
C SUBROUTINE NCHKWIN
C $Log:   GXAFXT:[GOLS]NCHKWIN.FOV  $
C  
C     Rev 1.0   17 Apr 1996 14:09:38   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 17:05:34   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C SUBROUTINE TO CHECK IF A NUMBERS TICKET IS A WINNER
C AND UPDATE VALIDATION RECORDS
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C This item is the property of GTECH Corporation, Providence, Rhode
C Island, and contains confidential and trade secret information. It
C may not be transferred from the custody or control of GTECH except
C as authorized in writing by an officer of GTECH. Neither this item
C nor the information it contains may be used, transferred,
C reproduced, published, or disclosed, in whole or in part, and
C directly or indirectly, except as expressly authorized by an
C officer of GTECH, pursuant to written agreement.
C
C Copyright 2000 GTECH Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE NCHKWIN(TRABUF,V4BUF,WIN)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:DESTRA.DEF'
	INCLUDE 'INCLIB:DWNCOM.DEF'
	INCLUDE 'INCLIB:DESVAL.DEF'
	INCLUDE 'INCLIB:PRMLOG.DEF'
	INCLUDE 'INCLIB:VALFIL.DEF'
	INCLUDE 'INCLIB:VDETAIL.DEF'
C
	INTEGER*4 SHARES(3,NMAXBT)
	INTEGER*4 WIN, ST, I, GIND, AMTWON, AMT, POL
	INTEGER*4 PRZIND, BNS, BIND, TOTWON, TAXAMT, NETAMT
	LOGICAL CXLED,UPDATE,PRVFLG
C
C
	UPDATE=.TRUE.
	GOTO 10
C
C ENTRY TO CHECK IF WINNER ONLY (NO UPDATE)
C
	ENTRY NIFWIN(TRABUF,WIN)
	UPDATE=.FALSE.
C
C
10	CONTINUE
	WIN=0
	CXLED=.FALSE.
	PRVFLG=.FALSE.
	TOTWON=0
	ST=TRABUF(TSTAT)
	GIND=TRABUF(TGAMIND)
	IF(LNBDRW(GIND).LT.0) RETURN
	IF(ST.NE.GOOD.AND.ST.NE.VOID.AND.
     *	   ST.NE.INCA.AND.ST.NE.EXCH.AND.
     *	   ST.NE.CASH.AND.ST.NE.XCSH.AND.
     *     ST.NE.CLAM.AND.ST.NE.XCLM) RETURN
        IF(TRABUF(TWNAND).NE.0) THEN
          IF(TRABUF(TWBEG).NE.LNBDRW(GIND).AND.
     *       TRABUF(TWEND).NE.LNBDRW(GIND)) RETURN
        ELSE
          IF(TRABUF(TWBEG).GT.LNBDRW(GIND)) RETURN
          IF(TRABUF(TWEND).LT.LNBDRW(GIND)) RETURN
        ENDIF
	IF(TRABUF(TSTAT).EQ.VOID.OR.TRABUF(TSTAT).EQ.INCA) CXLED=.TRUE.
C
C CHECK IF TICKET IS A WINNER
C
	CALL NWINLOS(TRABUF,SHARES,WIN)
	IF(WIN.EQ.0.OR..NOT.UPDATE) RETURN
C
C UPDATE VALIDATION RECORD
C
	IF(V4BUF(VFSSER).NE.0) THEN
	  CALL LOGVAL(VALREC,V4BUF)
	  CALL DLOGVAL(VALREC,VDETAIL)
	ELSE
	  CALL FASTSET(0,VALREC,VALLEN)
	  CALL FASTSET(0,VDETAIL,VPLEN*VMAX)
	ENDIF
C
C
	DO 100 I=1,LNBMAX(GIND)
	POL=SHARES(1,I)
	AMT=SHARES(2,I)
	BNS=SHARES(3,I)
	BIND=BNS+1
	IF(POL.EQ.0) GOTO 200
	AMTWON=AMT*LNBPRZ(POL,BIND,GIND)
	TOTWON=TOTWON+AMTWON
	IF(.NOT.CXLED) THEN
	  LNBWON(TRACNT,POL,BIND,GIND)=LNBWON(TRACNT,POL,BIND,GIND)+1
	  LNBWON(DOLAMT,POL,BIND,GIND)=
     *          LNBWON(DOLAMT,POL,BIND,GIND)+AMTWON
	ENDIF
	VALREC(VPZOFF)=VALREC(VPZOFF)+1
	PRZIND=VALREC(VPZOFF)
	IF(PRZIND.GT.VMAX) THEN
	  TYPE*,IAM(),' Prize table overflow ',TRABUF(TCDC),TRABUF(TSER)
	  CALL GPAUSE
	  VALREC(VSTAT)=VHOLD
	  VALREC(VPZOFF)=VMAX
	  GOTO 20
	ENDIF
C
C
	VDETAIL(VUPD,PRZIND)=1
	VDETAIL(VBDR,PRZIND)=BNS
	VDETAIL(VDIV,PRZIND)=POL
	VDETAIL(VSHR,PRZIND)=AMT
	VDETAIL(VDRW,PRZIND)=LNBDRW(GIND)
20	CONTINUE
100	CONTINUE
C
C GET TAXES AND SET PRIV PAY FLAG
C AND UPDATE BIG WINNER COMMISSION TABLE
C
200	CONTINUE
        CALL GETTAX(TOTWON,TAXAMT,NETAMT)
        IF(NETAMT.GT.REDMAX(TRABUF(TGAM))) PRVFLG=.TRUE.
        IF(.NOT.CXLED) THEN
          LNBTAX(GIND)=LNBTAX(GIND)+TAXAMT
          IF(HVCLVL.NE.0) THEN
            IF(NETAMT.GE.HVCLVL) THEN
              WINTAB(1,TRABUF(TTER))=WINTAB(1,TRABUF(TTER))+1
              WINTAB(2,TRABUF(TTER))=WINTAB(2,TRABUF(TTER))+NETAMT
            ENDIF
          ENDIF
        ENDIF
        VALREC(VPAMT)=VALREC(VPAMT)+NETAMT
	VALREC(VTAMT)=VALREC(VTAMT)+TAXAMT
	VALREC(VWCDC)=DAYCDC
C
C UPDATE HEADTER IF NEW WINNER
C
	IF(VALREC(VSTAT).EQ.VNOWIN) THEN
	  VALREC(VSCDC)=TRABUF(TCDC)
	  VALREC(VSTER)=TRABUF(TTER)
	  VALREC(VSSER)=TRABUF(TSER)
	  VALREC(VEXP )=TRABUF(TWEND)
	  VALREC(VGAM )=TRABUF(TGAM)
	  VALREC(VGTYP)=TRABUF(TGAMTYP)
	  VALREC(VGIND)=TRABUF(TGAMIND)
	ENDIF
C
	IF(PRVFLG) VALREC(VSTAT)=VPRPAY
	IF(VALREC(VSTAT).NE.VPRPAY) VALREC(VSTAT)=VUNCSH
	IF(TRABUF(TSTAT).EQ.VOID)   VALREC(VSTAT)=VCXL
	IF(TRABUF(TSTAT).EQ.INCA)   VALREC(VSTAT)=VDEL
C
C IF TICKET WAS CASHED THEN UPDATE CASHING INFORMATION
C
	IF(TRABUF(TSTAT).EQ.CASH.OR.TRABUF(TSTAT).EQ.XCSH) THEN
	  VALREC(VCTER)=TRABUF(TWCTER)
	  VALREC(VCSER)=TRABUF(TWCSER)
	  VALREC(VSTAT)=TRABUF(TWVSTS)
	  VALREC(VCCDC)=DAYCDC
	ENDIF
        IF(TRABUF(TSTAT).EQ.CLAM.OR.TRABUF(TSTAT).EQ.XCLM) THEN
	  VALREC(VLTER)=TRABUF(TWCTER)
	  VALREC(VLSER)=TRABUF(TWCSER)
	  VALREC(VSTAT)=TRABUF(TWVSTS)
	  VALREC(VLCDC)=DAYCDC
	ENDIF
	CALL DVALLOG(VALREC,VDETAIL)
	CALL VALLOG (VALREC,V4BUF  )
	RETURN
	END
