C
C SUBROUTINE NLIABLE
C $Log:   GXAFXT:[GOLS]NLIABLE.FOV  $
C  
C     Rev 1.0   17 Apr 1996 14:12:30   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.1   02 Sep 1994 18:08:48   HXK
C  Merge of May,June RFSS batch 
C  
C     Rev 1.1   27 Apr 1994 17:24:58   JXP
C  COPY=0
C  
C     Rev 1.0   21 Jan 1993 17:07:16   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - nliable.for **
C
C NLIABLE.FOR
C
C V02 12-NOV-91 MTK INITIAL RELEASE FOR NETHERLANDS
C V01 01-AUG-90 XXX RELEASED FOR VAX
C
C
C SUBROUTINE TO GENERATE LIABILITY REPORTS FOR ALL
C AVAILABLE NUMBERS GAMES
C
C
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C This item is the property of GTECH Corporation, Providence, Rhode
C Island, and contains confidential and trade secret information. It
C may not be transferred from the custody or control of GTECH except
C as authorized in writing by an officer of GTECH. Neither this item
C nor the information it contains may be used, transferred,
C reproduced, published, or disclosed, in whole or in part, and
C directly or indirectly, except as expressly authorized by an
C officer of GTECH, pursuant to written agreement.
C
C Copyright 1991 GTECH Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE NLIABLE(NLIB,NPAY,GAMTAB)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
C
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:DNBREC.DEF'
	INCLUDE 'INCLIB:DATBUF.DEF'
C
	INTEGER*4 MDRAW,RDRAW, BNS, B
	PARAMETER(MDRAW=400)
	PARAMETER(RDRAW=365)
C
	CHARACTER*16 BSTAT(2)
	INTEGER*4 NLIB(NBGPOL,2,MDRAW,NUMNBR)
	INTEGER*4 NPAY(NBGPOL,2,MDRAW,NUMNBR)
	INTEGER*4 GAMTAB(2,MAXGAM)
	INTEGER*4 TOTWON, GRNWON
	INTEGER*4 TOTPAD, GRNPAD
	INTEGER*4 TOTLIB, GRNLIB
	INTEGER*4 TOTPRG, GRNPRG
	INTEGER*4 TOTDAY, GRNDAY/0/
C
	INTEGER*4 I, DRAW, DRWIND, LINCNT, PAGE, ST, K
	INTEGER*4 GNUM, GIND, COPY
	INTEGER*4 DNBFDB(7), REPLU/7/
	INTEGER*2 DATE(LDATE_LEN) /LDATE_LEN*0/
	CHARACTER REPHDR*40
	CHARACTER REPNAM*12
	DATA BSTAT/'                ','<<<BONUS DRAW>>>'/
C
C
	DO 1000  GIND=1,NUMNBR
	DATE(5) = DAYCDC
	CALL LCDATE(DATE)
	GNUM=GTNTAB(TNBR,GIND)
	IF(GNUM.LT.1) GOTO 1000
	IF(DAYHDR(GNUM).LT.1) GOTO 1000
        WRITE(5,8000) IAM(),(GLNAMES(K,GNUM),K=1,4)
C       CALL INPNUM('Enter number of report copies ',COPY,0,20,EXT)
	COPY=0
C
	CALL OPENW(3,GFNAMES(1,GNUM),4,0,0,ST)
	CALL IOINIT(DNBFDB,3,DNBSEC*256)
	IF(ST.NE.0) CALL FILERR(GFNAMES(1,GNUM),1,ST,0)
	WRITE (REPHDR,8001) GSNAMES(GNUM),(DATE(K),K=7,13)
	WRITE (REPNAM,8002) GIND
	CALL ROPEN(REPNAM,REPLU,ST)
	IF(ST.NE.0) THEN
	   TYPE*,REPNAM,' report file open error > ',ST
	   CALL GPAUSE
	ENDIF
C
C CLEAR TOTALS
C
	PAGE=0
	LINCNT=70
	GRNWON=0
	GRNDAY=0
	GRNLIB=0
	GRNPRG=0
	GRNPAD=0
C
C
	DO 300 DRWIND=1,RDRAW
	DRAW=DAYHDR(GNUM)-DRWIND+1
	IF(DRAW.LT.1) GOTO 310
	CALL READW(DNBFDB,DRAW,DNBREC,ST)
	IF(ST.NE.0) CALL FILERR(GFNAMES(1,GNUM),1,ST,DRAW)
	IF(DNBUPD.GT.DAYCDC) GOTO 300
	BNS=1
	IF(DNBBDR.NE.0) BNS=2
C
C
	DO 100 B=1,BNS
	TOTWON=0
	TOTPAD=0
	TOTLIB=0
	TOTPRG=0
	TOTDAY=0
	DO 30 K=1,DNBPOL
	TOTWON=TOTWON+DNBWON(DOLAMT,K,B)
        TOTLIB=TOTLIB+NLIB(K,B,DRWIND,GIND)*DNBPRZ(K,B)
        TOTPAD=TOTPAD+DNBPAD(DOLAMT,K,B)
	TOTDAY=TOTDAY+NPAY(K,B,DRWIND,GIND)*DNBPRZ(K,B)
30	CONTINUE
	IF(DAYCDC.EQ.DNBUPD) TOTPAD=TOTPAD-TOTDAY
	TOTPRG=TOTWON-TOTLIB-TOTPAD-TOTDAY
C
C
	IF(LINCNT.GT.LINSPP) THEN
	  CALL TITLE(REPHDR,REPNAM,GIND,REPLU,PAGE,DAYCDC)
	  WRITE(REPLU,9000)
          WRITE(REPLU,9001)
	  LINCNT=7
	ENDIF
	LINCNT=LINCNT+1
	DATE(5)=DNBDAT(CURDRW)
	CALL LCDATE(DATE)
	WRITE(REPLU,9002)DRAW,(DATE(I),I=7,13),
     *			 CSMONY(TOTWON,13,VALUNIT),
     *                   CSMONY(TOTPAD,13,VALUNIT),
     *                   CSMONY(TOTDAY,13,VALUNIT),
     *                   CSMONY(TOTLIB,13,VALUNIT),
     *                   CSMONY(TOTPRG,13,VALUNIT),
     *                   BSTAT(B)
C
C CALCULATE GRAND TOTALS
C
	GRNWON = GRNWON + TOTWON
	GRNPAD = GRNPAD + TOTPAD
	GRNLIB = GRNLIB + TOTLIB
	GRNPRG = GRNPRG + TOTPRG
	GRNDAY = GRNDAY + TOTDAY
100	CONTINUE
300	CONTINUE
310	CONTINUE
C
C
        WRITE(REPLU,9003)  CSMONY(GRNWON,13,VALUNIT),
     *                     CSMONY(GRNPAD,13,VALUNIT),
     *                     CSMONY(GRNDAY,13,VALUNIT),
     *                     CSMONY(GRNLIB,13,VALUNIT),
     *                     CSMONY(GRNPRG,13,VALUNIT)
	WRITE(REPLU,9004)  CSMONY(GAMTAB(1,GNUM),13,VALUNIT),
     *                     CSMONY(GAMTAB(2,GNUM),13,VALUNIT)
	CALL USRCLOS1(     3)
	CALL USRCLOS1(REPLU)
	CALL SPOOL(REPNAM,COPY,ST)
1000	CONTINUE
C
C     ===================== Format Statements =================
C
8000    FORMAT(1X,A,' Generating ',4A4,' liability report')
8001	FORMAT(A4,' LIABILITY REPORT FOR ',7A2)
8002	FORMAT('NLIABLE',I1,'.REP')
8003	FORMAT(1X,A)
C
9000	FORMAT(1X,131('='))
9001	FORMAT(//,2X,'DRAW',5X,'DRAW DATE',6X,'TOTAL WON',6X,
     *         'PREV PAID',5X,'PAID TODAY',4X,'OUTSTANDING',
     *         9X,'PURGED',/)
9002	FORMAT(2X,I4,2X,7A2,5(2X,A13),A16)
9003	FORMAT(/,2X,'TOTAL',13X,5(2X,A13))
9004	FORMAT(41X,'    TAXES  ',A13,/,
     *         41X,' NET PAID  ',A13)
	RETURN
	END
