C
C SUBROUTINE QLOGTRA
C 
C V04 02-FEB-2000 UXN T5P3FLG defined locally, TGAMTYP2 removed. 
C V03 18-MAR-1999 RXK Gtyp+gind in 5+3 bits change.
C V02 17-APR-1996 HXK Release of Finland for X.25, Telephone Betting,
C                     Instant Pass Thru Phase 1
C V01 21-JAN-1993 DAB Initial Release
C                     Based on Netherlands Bible, 12/92, and Comm 1/93 update
C                     DEC Baseline
C
C ** Source - nrm_logtra.for **
C
C SUBROUTINE TO DECODE LOG RECORD TO TRANSACTION
C INTERNAL FORMAT.
C
C QUICK VERSION FOR SAVDRW ONLY....
C
C CALLING SEQUENCE:
C     CALL QLOGTRA(TRABUF,LOGBUF)
C INPUT
C     LOGBUF - TRANSACTION LOG RECORD
C OUTPUT
C     TRALOG - INTERNAL TRANSACTION FORMAT
C
C
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE QLOGTRA(TRABUF,LOGBUF)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:DESTRA.DEF'
	INCLUDE 'INCLIB:DESLOG.DEF'
	INCLUDE 'INCLIB:PRMLOG.DEF'
C
	INTEGER*4 LOGBUF(LREC*3)
C
	INTEGER*4 I4TEMP
	INTEGER*2 I2TEMP(2)
	BYTE      I1TEMP(4)
	EQUIVALENCE (I4TEMP, I2TEMP, I1TEMP)
C
	INTEGER*4   X
C
C
C DECODE INFORMATION NEEDED FOR SAVDRW ONLY
C
	I4TEMP         = LOGBUF(5)
        X              = ZEXT(I1TEMP(4))
        TRABUF(TGAM)   = IAND (X,'7F'X )
C
	I4TEMP         = LOGBUF(6)
	TRABUF(TSTAT)  = ZEXT(I1TEMP(1))
        X              = ZEXT (I1TEMP(2))
        TRABUF(TTYP)   = ISHFT( X, -4 )
        TRABUF(TTRN)   = IAND ( X, '0F'X )
        X              = ZEXT (I1TEMP(3))
        TRABUF(TSIZE)  = ISHFT( X, -4 )
	X              = ZEXT ( I1TEMP(4) )
        TRABUF(TGAMTYP)  = ISHFT( X, -3)
        TRABUF(TGAMIND)  = IAND ( X,'07'X )

	RETURN
	END
