C
C SUBROUTINE XXXYESNO
C $Log:   GXAFXT:[GOLS]XXXYESNO.FOV  $
C  
C     Rev 1.2   17 Apr 2001 16:48:16   CS
C  INCLUDED 'S[im]' (YES) FOR PORTUGUESE MESSAGES
C
C     Rev 1.1   17 Apr 1996 16:48:16   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 18:39:52   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - nrm_inpyesno.for **
C
C
C
C
	SUBROUTINE XXXYESNO(PRMFLG, OUTPUTSTRING, YESNOFLAG)
	IMPLICIT NONE
C
	INCLUDE	    'INCLIB:SYSPARAM.DEF'
	INCLUDE	    'INCLIB:SYSEXTRN.DEF'
C
	LOGICAL	    PRMFLG
	CHARACTER   OUTPUTSTRING*(*)
	INTEGER*4   YESNOFLAG
C
	CHARACTER   INPUTSTRING*(60)
	INTEGER*4   INPUTLEN
C
	CHARACTER   BELL/Z07/
C
C
C
1000	CONTINUE
	IF(PRMFLG)THEN
	  CALL PRMTEXT(OUTPUTSTRING, INPUTSTRING, INPUTLEN)
	ELSE
	  CALL INPTEXT(OUTPUTSTRING, INPUTSTRING, INPUTLEN)
	ENDIF
C
	IF( INPUTSTRING(1:1).EQ.'Y' .OR. INPUTSTRING(1:1).EQ.'y' .OR.
     *      INPUTSTRING(1:1).EQ.'S' .OR. INPUTSTRING(1:1).EQ.'s'     ) THEN
	  YESNOFLAG = 1
	ELSE IF(INPUTSTRING(1:1).EQ.'N' .OR. INPUTSTRING(1:1).EQ.'n')THEN
	  YESNOFLAG = 2
	ELSE IF(INPUTSTRING(1:1).EQ.'E' .OR. INPUTSTRING(1:1).EQ.'e')THEN
	  YESNOFLAG = 3
	ELSE
	  TYPE *,IAM(),BELL,BELL,'*** Invalid - Y, N, or E please ***'
	  GOTO 1000
	ENDIF
C
	RETURN
	END
