C
C FUNCTION FRAMT
C $Log:   GXAFXT:[GOLS]FRAMT.FOV  $
C  
C     Rev 1.0   17 Apr 1996 13:13:04   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 16:20:26   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - nrm_bigamt.for **
C
C
C FUNCTION TO CALCULATE FRACTIONAL SHARE AMOUNT FROM
C # OF FRACTIONS PAID AND WHOLE SHARE VALUE.
C
C
	FUNCTION FRAMT(MAXFRC,FRACT,SHARE)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	REAL*8 SPAID
	INTEGER*4 MAX, FRAMT, SHARE, FRACT, MAXFRC
	MAX=MAXFRC
	IF(MAX.EQ.0) MAX=1
	SPAID=DFLOAT(FRACT)/DFLOAT(MAX)
	FRAMT=IDNINT(SPAID*DFLOAT(SHARE))
	RETURN
	END
