C
C SUBROUTINE PRMMONYI8
C $Log:   GXAFXT:[GOLS]PRMMONYI8.FOV  $
C  
C     Rev 1.0   17 Apr 1996 14:31:12   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 17:21:50   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - nrm_inpmod.for **
C
C
C SUBROUTINE TO INPUT MONEY AMOUNTS
C
C NOTE: THE NUMBER(1) THAT IS PASSED BACK WILL BE THE AMOUNT/BASEUNIT
C           NUMBER(2) THAT IS PASSED BACK WILL BE MOD(AMOUNT,BASEUNIT)
C	TO DISPLAY THIS AMOUNT CORRECTLY, USE THE ROUTINES CMONYI8 & CSMONYI8
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE PRMMONYI8(STRING,NUM,FACTOR,EXT)
	IMPLICIT NONE
C
	CHARACTER   STRING*(*)
	INTEGER*4   NUM(2),FACTOR,EXT
C
	CALL XXXMONYI8(.TRUE., STRING,NUM,FACTOR,EXT)
	RETURN
	END
