C
C SUBROUTINE READW
C $Log:   GXAFXT:[GOLS]READW.FOV  $
C  
C     Rev 1.0   17 Apr 1996 14:39:12   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 17:27:46   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - nrm_diskio.for **
C
C
C
C
C *** READL       <<<READ BLOCK WITH LOCK>>>
C		BLOCK IS TO BE UNLOCKED WITH SUBSEQUENT 'WRITE'
C		OPERATION BY THE SAME PROCESS
C
 
C***	SUBROUTINE READL(FDB, BLOCK, BUFFER, STATUS, RECSTS)
C***	IMPLICIT NONE
C
C***	INCLUDE	'INCLIB:SYSPARAM.DEF'
C***	INCLUDE 'INCLIB:DISKIO.DEF'
C
C***	INTEGER*4   FDB(FDB_LENGTH)
C***	INTEGER*4   BLOCK
C***	INTEGER*4   BUFFER(*)
C***	INTEGER*4   STATUS
C***	INTEGER*4   RECSTS
C
C***	INTEGER*4   FOR$RAB
C***	INTEGER*4   LUN
C***	INTEGER*4   BEGBLK
C
C
C***	LUN    = FDB(FDB_LUN)
C***	BEGBLK = (BLOCK-1)*FDB(FDB_BLKSZ) + 2
C
C***	CALL LCKNREAD(%VAL(FOR$RAB(LUN)), FDB, BEGBLK, BUFFER, STATUS)
C***	IF (STATUS .EQ. 0) THEN
C***	    RECSTS = 1	! RECORD LOCKED
C***	ELSE
C***	    RECSTS = 0  ! RECORD NOT LOCKED
C***	ENDIF
C
C***	RETURN
C***	END
C
C
C
C *** READW       <<<READ and wait for completion>>>
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE READW(FDB, BLOCK, BUFFER, STATUS)
	IMPLICIT NONE
C
	INCLUDE	'INCLIB:SYSPARAM.DEF'
	INCLUDE	'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:DISKIO.DEF'
C
	INTEGER*4   FDB(FDB_LENGTH)
	INTEGER*4   BLOCK
	INTEGER*4   BUFFER(*)
	INTEGER*4   STATUS
C
	INTEGER*4   FOR$RAB
	INTEGER*4   LUN
	INTEGER*4   BEGBLK
C
C
	LUN    = FDB(FDB_LUN)
	BEGBLK = (BLOCK-1)*FDB(FDB_BLKSZ) + 2
C
	CALL READXX(%VAL(FOR$RAB(LUN)), FDB, BEGBLK, BUFFER, STATUS)
C
	RETURN
	END
