C
C SUBROUTINE GETWED
C $Log:   GXAFXT:[GOLS]GETWED.FOV  $
C  
C     Rev 1.0   17 Apr 1996 13:23:42   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 16:29:32   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - nrm_getoff.for **
C
C
C
C SUBROUTINE TO GET EXTRA LOTTO/KICKER DRAW DAYS
C

C=======OPTIONS /CHECK=NOOVERFLOW
        SUBROUTINE GETWED(TRABUF,WTAB)
        IMPLICIT NONE
C
        INCLUDE 'INCLIB:SYSPARAM.DEF'
        INCLUDE 'INCLIB:SYSEXTRN.DEF'
        INCLUDE 'INCLIB:GLOBAL.DEF'
        INCLUDE 'INCLIB:DESTRA.DEF'
        INCLUDE 'INCLIB:CONCOM.DEF'
        INCLUDE 'INCLIB:LTOCOM.DEF'
C
        INTEGER*4 IND, GIND, WOFF, I
	BYTE WTAB(*)
C
C
	WOFF=0
	WTAB(1)='FF'X
	WTAB(2)='FF'X
	GIND=TRABUF(TGAMIND)
	IF(TRABUF(TGAMTYP).NE.TLTO) RETURN
C
C
        DO 10 I=1,TRABUF(TWDUR)
	IND=TRABUF(TWBEG)-LTODRW(GIND)+I
	IF(LTODAT(IND,GIND).EQ.LTOWED(1,GIND).AND.WOFF.LT.2) THEN
	  WOFF=WOFF+1
	  WTAB(WOFF)=LTOWED(1,GIND)-DAYCDC
	  GOTO 10
	ENDIF
C
        IF(LTODAT(IND,GIND).EQ.LTOWED(2,GIND).AND.WOFF.LT.2) THEN
          WOFF=WOFF+1
          WTAB(WOFF)=LTOWED(2,GIND)-DAYCDC
          GOTO 10
        ENDIF
10	CONTINUE
	RETURN
	END
