C
C SUBROUTINE WRITEIO
C $Log:   GXAFXT:[GOLS]WRITEIO.FOV  $
C  
C     Rev 1.0   17 Apr 1996 16:03:52   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 18:08:08   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - nrm_diskio.for **
C
C
C
C
C *** WRITEIO       <<<WRITE and wait for completion>>>
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE WRITEIO(FDB, BEGBLK, BUFFER, NUMBYTES, STATUS)
	IMPLICIT NONE
C
	INCLUDE	    'INCLIB:SYSPARAM.DEF'
	INCLUDE	    'INCLIB:SYSEXTRN.DEF'
	INCLUDE	    'INCLIB:DISKIO.DEF'
C
	INTEGER*4   FDB(FDB_LENGTH)
	INTEGER*4   BEGBLK
	INTEGER*4   BUFFER(*)
	INTEGER*4   NUMBYTES
	INTEGER*4   STATUS
C
	INTEGER*4   FOR$RAB
	INTEGER*4   LUN
	INTEGER*4   SIZHOLD
C
C
C
	LUN = FDB(FDB_LUN)
	SIZHOLD = FDB(FDB_BYTSZ)
	FDB(FDB_BYTSZ) = NUMBYTES
C
	CALL WRITEXX(%VAL(FOR$RAB(LUN)),FDB,BEGBLK+1, BUFFER, STATUS) !**V07*
	FDB(FDB_BYTSZ) = SIZHOLD
C
	RETURN
	END
