C
C SUBROUTINE ICLOSB
C $Log:   GXAFXT:[GOLS]ICLOSB.FOV  $
C  
C     Rev 1.0   17 Apr 1996 13:34:56   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 16:37:32   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - nrm_hshfili4.for **
C
C
C
C
C *** ICLOSB
C
C This will first flush out BIGBUF, then will close the file
C
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE ICLOSB(LUN,BIGBUF,IOBUF,STATUS)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
C
	INCLUDE 'INCLIB:HSHCOM.DEF'
C
	INTEGER*4 LUN                       !  INPUT: LOGICAL UNIT #
	INTEGER*4 BIGBUF(*)                 !SCRATCH: BIG BUFFER ARRAY
	INTEGER*4 IOBUF(*)                  !SCRATCH: I/O BUFFER
	INTEGER*4 STATUS                    ! OUTPUT: 0=OK, ELSE ERROR #
C
C
C
C
C
	IF(FCB(FCBLUN,LUN).NE.LUN .OR.
     *	   FCB(FCBBIG,LUN).EQ.0)THEN
	  STATUS=ERRERR
	  GO TO 9000
	ENDIF
C
	CALL IFLUSH(LUN,BIGBUF,IOBUF,STATUS)
	IF(STATUS.EQ.0)THEN
	  CALL ICLOSE(LUN,IOBUF,STATUS)
	  IF(STATUS.EQ.0)BIGBUF(BUFLUN)=0       !RELEASE BIGBUF
	ENDIF
C
9000	CONTINUE
	RETURN
	END
