C
C FUNCTION INANYR
C $Log:   GXAFXT:[GOLS]INANYR.FOV  $
C  
C     Rev 1.0   17 Apr 1996 13:35:56   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 16:38:44   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - nrm_strings.for **
C
C
C
C **** INANYR
C
	INTEGER*4 FUNCTION INANYR(STRING,LOOK)
	IMPLICIT NONE
C
	CHARACTER	STRING*(*)
	CHARACTER	LOOK*(*)
C
	INTEGER*4	LENSTRING, LENLOOK
	INTEGER*4	STRINGOFF, LOOKOFF
C
C
	LENSTRING = LEN(STRING)
	LENLOOK   = LEN(LOOK)
C
	DO 1900 STRINGOFF = LENSTRING, 1, -1
	  DO 1800 LOOKOFF = LENLOOK,   1, -1
	    IF(STRING(STRINGOFF:STRINGOFF).EQ.LOOK(LOOKOFF:LOOKOFF))THEN
	      GOTO 1900
	    ENDIF
1800	  CONTINUE
	  GOTO 2000
1900	CONTINUE
	STRINGOFF = 0
C
2000	CONTINUE
	INANYR = STRINGOFF
C
	RETURN
	END
