C
C SUBROUTINE SETNIBLE
C $Log:   GXAFXT:[GOLS]SETNIBLE.FOV  $
C  
C     Rev 1.0   17 Apr 1996 15:02:20   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 17:36:24   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - nrm_nibble.for **
C
C
C     ++++++++++++++++++++++++++++++++++++++
C
C     SET NIBBLE
C     SETNIBLE(VALUE,TAB,OFF)
C     IN:
C     TAB - TABLES OF NIBLES
C     OFF - NIBBLE OFFSET (STARTING FROM 1)
C     VALUE - NIBBLE
C
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE SETNIBLE(VALUE,TAB,OFF)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INTEGER*2 TAB(*)
	INTEGER*4 DATA, OFFSET, OFF, VALUE
C
	IF (OFF.LE.0) RETURN
	OFFSET=(OFF+1)/2-1
	CALL ILBYTE(DATA,TAB,OFFSET)
	IF (MOD(OFF,2).NE.0) THEN
	   DATA=IAND(DATA,15)+IAND(VALUE,15)*16
	ELSE
	   DATA=IAND(DATA,'000000F0'X)+IAND(VALUE,15)
	ENDIF
	CALL ISBYTE(DATA,TAB,OFFSET)
	RETURN
	END
