C
C SUBROUTINE WRITASF
C $Log:   GXAFXT:[GOLS]WRITASF.FOV  $
C  
C     Rev 1.0   17 Apr 1996 16:03:44   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 18:07:54   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - nrm_asfsubs.for **
C
C
C
C     ========================================================
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE WRITASF(AGT,RECBUF,ST)
C
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
C
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:ASFSUBS.DEF'
C
	INTEGER*4 RECBUF(64*ASFSEC), NDX, BLK, ST, AGT
C
	ST=0
	BLK=(AGT-1)/RECSPERBKT + 1
	NDX=MOD(AGT-1,RECSPERBKT) + 1
C
	IF(BLK.NE.BKTNUM)THEN
	  IF(BKTCHG.NE.0)THEN
	    CALL WRITEW(FDB,BKTNUM,BUCKET,ST)
	    IF(ST.NE.0)THEN
	      CALL FILERR(SFNAMES(1,ASF),3,ST,BKTNUM)
	      BKTNUM=-1
	      BKTCHG=0
	      RETURN
	    ENDIF
	  ENDIF
C
	  CALL READW(FDB,BLK,BUCKET,ST)
	  IF(ST.NE.0)THEN
	    CALL FILERR(SFNAMES(1,ASF),2,ST,BLK)
	    BKTNUM=-1
	    BKTCHG=0
	    RETURN
	  ENDIF
	  BKTNUM=BLK
	ENDIF
C
	CALL FASTMOV(RECBUF,BUCKET(1,NDX),64*ASFSEC)
	BKTCHG=1
C
	RETURN
	END
