C
C SUBROUTINE OPENQX
C $Log:   GXAFXT:[GOLS]OPENQX.FOV  $
C  
C     Rev 1.0   17 Apr 1996 14:18:46   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 17:12:20   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - nrm_diskqio.for **
C
C*********************************************************************
C
C**********************************************************************
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE OPENQX(LUN, FILENAME, SHRIND, DUM1, DUM2, ST)
	IMPLICIT NONE
C
	INCLUDE	    'INCLIB:SYSPARAM.DEF'
	INCLUDE	    'INCLIB:SYSEXTRN.DEF'
	INCLUDE	    'INCLIB:DISKQIO.DEF'
	INCLUDE	'($SYSSRVNAM)'
	INCLUDE '($STSDEF)'
	INCLUDE '($RMSDEF)'
C
	INTEGER*4   LUN
	CHARACTER   FILENAME*(*)
	INTEGER*4   SHRIND
	INTEGER*4   DUM1
	INTEGER*4   DUM2
	INTEGER*4   ST
	
	LOGICAL*1   ISTHERE
	CHARACTER*20 ISDIRECT
	CHARACTER*20 ORGTYPE
	CHARACTER*20 RECTYPE
C
	INTEGER*4   DISKQOPEN
	EXTERNAL    DISKQOPEN
D	INTEGER*4   STAT, FABADR
C
C
C
	CALL CHKQINIT()
C
	IF(LUN.LT.1 .OR. LUN.GT.MAXLUNARRAY)THEN
	  TYPE *,IAM(), 'BAD LUN IN VAX_DISKQIO/OPENQX,X = ',LUN
	  GOTO 9000
	ENDIF
C
	IF(LUNARRAY(LUN) .GE. 0)THEN
	  TYPE *,IAM(),'CHANNEL NOT CLOSED IN DISKQIO/OPENQX,LUN = ',LUN
	  GOTO 9000
	ENDIF
C
	LUNARRAY(LUN) = -1
C
C
C If the file doesn't exist, just return with status = -1
C
D	TYPE *,IAM(),'OPENQX FOR FILE = ',FILENAME
	INQUIRE(FILE=FILENAME, EXIST=ISTHERE,
     *	            IOSTAT=ST,
     *	          DIRECT=ISDIRECT,
     *	          ORGANIZATION=ORGTYPE,
     *	          RECORDTYPE=RECTYPE)
	IF(.NOT.ISTHERE)THEN
	  ST = -1
	  TYPE *,IAM(), 'FILE NOT FOUND: ', FILENAME
C***	  CALL LIB$SIGNAL(%VAL(RMS$_FNF))
	  GOTO 9000
	ENDIF
C
C Now open the file
C
	IF(ISDIRECT.EQ.'YES' .AND.
     *	     ORGTYPE.EQ.'RELATIVE' .AND.
     *	     RECTYPE.EQ.'FIXED')THEN
C
	  IF(SHRIND.EQ.0)THEN
	    CALL OPENQ(LUN, FILENAME, FABARRAY(LUN), QREAD, ST)
C***   	    OPEN(UNIT=LUN, FILE=FILENAME, ORGANIZATION='RELATIVE',
C***     1	           ACCESS='DIRECT', STATUS='OLD', IOSTAT=ST,
C***     2	           USEROPEN=DISKQOPEN, READONLY)
	  ELSE
	    CALL OPENQ(LUN, FILENAME, FABARRAY(LUN), QWRITE, ST)
C***   	    OPEN(UNIT=LUN, FILE=FILENAME, ORGANIZATION='RELATIVE',
C***     1	           ACCESS='DIRECT', STATUS='OLD', IOSTAT=ST,
C***     2	           USEROPEN=DISKQOPEN)
C
	  ENDIF
	ELSE
	  IF(SHRIND.EQ.0)THEN
	    OPEN(UNIT=LUN, FILE=FILENAME, STATUS='OLD',
     *	           IOSTAT=ST, SHARED, READONLY)
	  ELSE
	    OPEN(UNIT=LUN, FILE=FILENAME, STATUS='OLD',
     *	           IOSTAT=ST, SHARED)
	  ENDIF
	  IF(LUN.GE.1 .AND. LUN.LE.MAXLUNARRAY)LUNARRAY(LUN)=0
	ENDIF
C
	IF(ST)THEN
	    ST = 0
	ENDIF
C
C
9000	CONTINUE
	  RETURN
	END
