C
C FUNCTION CENT
C $Log:   GXAFXT:[GOLS]CENT.FOV  $
C  
C     Rev 1.0   17 Apr 1996 12:30:32   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 15:47:26   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - nrm_bigamt.for **
C
C
C
C
C SUBROUTINE TO CONVERT 4 BYTE UNSIGNED INTEGER TO CENT
C
	DOUBLE PRECISION FUNCTION CENT(NUM)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	DOUBLE PRECISION BIG,SBIT
	INTEGER*4 TEMP, HMASK, LMASK, NUM
	DATA LMASK/Z7FFFFFFF/,HMASK/Z80000000/
	DATA SBIT/2147483648.0D0/
C
C
	TEMP=IAND(NUM,LMASK)
	BIG=DFLOAT(TEMP)
	IF(IAND(NUM,HMASK).NE.0) BIG=BIG+SBIT
	CENT=BIG/100.0D0
	RETURN
	END
