C
C SUBROUTINE CFILX
C $Log:   GXAFXT:[GOLS]CFILX.FOV  $
C  
C     Rev 1.0   17 Apr 1996 12:30:42   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 15:47:42   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - nrm_cfilw.for **
C
C
C
C *** CFILX
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE CFILX(FILENAME, FILTYP, RECLEN, SIZE, ISIZE,
     *                   DUM1, DUM2, ST)
	IMPLICIT NONE
C
	INCLUDE	    'INCLIB:SYSPARAM.DEF'
	INCLUDE	    'INCLIB:SYSEXTRN.DEF'
C
	CHARACTER   FILENAME*(*)
	INTEGER*4   FILTYP
	INTEGER*4   RECLEN
	INTEGER*4   SIZE
	INTEGER*4   ISIZE
	INTEGER*4   DUM1
	INTEGER*4   DUM2
	INTEGER*4   ST
	
	LOGICAL*1   ISTHERE
C
	INTEGER*4   LOLUN/1/	    !SMALLEST LUN TO LOOK AT
	INTEGER*4   HILUN/14/	    !HIGHEST  LUN TO LOOK AT
C
	INTEGER*4   LUN
	INTEGER*4   SECTORS
C
	INTEGER*4   CFILCNTG
	EXTERNAL    CFILCNTG	    !USEROPEN FOR CONTIGUOUS FILE
C
C
C
C If the file doesn't exist, just return with status = -1
C
	INQUIRE(FILE=FILENAME, EXIST=ISTHERE)
	IF(ISTHERE)THEN
	  TYPE *,IAM(), 'CFILX: File ', FILENAME, ' already exists.'
	  ST = -1
	  GOTO 9000
	ENDIF
C
C Find a free lun to use for the open
C
	DO 1100 LUN = LOLUN, HILUN
C
C ISTHERE is set to true if LU is already used.
C
	  INQUIRE(UNIT=LUN, OPENED=ISTHERE, IOSTAT=ST)
	  IF(.NOT.ISTHERE) GOTO 1200
C
1100	CONTINUE
	TYPE *,IAM(),'CFILX - NO LUN AVAIL FOR CREATE'
	ST = -1		    ! NO AVAILABLE LUN
	GOTO 9000
C
C
C
1200	CONTINUE
C
	IF(FILTYP.EQ.0)THEN
	  SECTORS = (SIZE+1)/2
	  OPEN(LUN, FILE=FILENAME, ACCESS='DIRECT',
	1     INITIALSIZE=SECTORS+1, STATUS='NEW', RECL=512/4,
	1     ORGANIZATION='RELATIVE', IOSTAT=ST, USEROPEN=CFILCNTG)
	ELSE
	  OPEN(LUN, FILE=FILENAME, ACCESS='SEQUENTIAL',
	1      STATUS='NEW', RECL=RECLEN, IOSTAT=ST)
	ENDIF
C
	CALL USRCLOS1(LUN)
C
9000	CONTINUE
	RETURN
	END
