C
C SUBROUTINE IFLUSH
C $Log:   GXAFXT:[GOLS]IFLUSH.FOV  $
C  
C     Rev 1.0   17 Apr 1996 13:35:18   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 16:37:48   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - nrm_hshseqi4.for **
C
C
C
C *** IFLUSH
C
C This will flush a big buffer to disk using ISWRIT
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE IFLUSH(LUN,BIGBUF,IOBUF,STATUS)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
C
	INCLUDE 'INCLIB:HSHCOM.DEF'
C
	INTEGER*4 LUN                    !  INPUT: LOGICAL UNIT #
	INTEGER*4 BIGBUF(*)              !SCRATCH: BUFFER AREA
	INTEGER*4 IOBUF(*)               !SCRATCH: I/O BUFFER
	INTEGER*4 STATUS                 ! OUTPUT: 0=OK, ELSE ERROR #
C
	INTEGER*4 NEWOFF, OLDOFF, THSOFF, K
C
	INTEGER*4 I4TEMP
	INTEGER*2 I2TEMP(2)
	EQUIVALENCE (I4TEMP,I2TEMP)
C
C
C
	IF(BIGBUF(BUFLUN) .NE.LUN)THEN
	  STATUS=ERRUNT
	  GO TO 9000
	ENDIF
C
C REARRANGE BLOCKS INTO THE ORDER THEY CAME IN.
C
	DO 1500 K=1,BIGBUF(BUFBKS)
	  THSOFF=BIGBUF(BUFCNT+K)
	  IF(THSOFF.EQ.0)GO TO 1500
C
	  OLDOFF=0
1100	  CONTINUE
	  NEWOFF=BIGBUF(THSOFF)
	  BIGBUF(THSOFF)=OLDOFF
	  IF(NEWOFF.NE.0)THEN
	    OLDOFF=THSOFF
	    THSOFF=NEWOFF
	    GO TO 1100
	  ENDIF
	  BIGBUF(BUFCNT+K)=THSOFF
1500	CONTINUE
C
C
C Now write all blocks to disk
C
	DO 2500 K=1,BIGBUF(BUFBKS)
	  THSOFF=BIGBUF(BUFCNT+K)
	  IF(THSOFF.EQ.0)GO TO 2500
C
	  BIGBUF(BUFCNT+K)=0
2100	  CONTINUE
	  NEWOFF=BIGBUF(THSOFF)
	  BIGBUF(THSOFF)=0
	  CALL ISWRIT(BIGBUF(THSOFF+1),LUN,IOBUF,STATUS)
	  IF(STATUS.NE.0)GO TO 9000
	  IF(NEWOFF.NE.0)THEN
	    THSOFF=NEWOFF
	    GO TO 2100
	  ENDIF
C
2500	CONTINUE
	BIGBUF(BUFFRE)=BUFCNT+BIGBUF(BUFBKS)+1     !RESTORE NEXT AVAIL
C
	STATUS=0
C
9000	CONTINUE
	RETURN
	END
