C
C FUNCTION SNIF
C $Log:   GXAFXT:[GOLS]SNIF.FOV  $
C  
C     Rev 1.0   17 Apr 1996 15:10:22   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 17:39:24   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - nrm_snif.for **
C
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C	INTEGER*4 FUNCTION  SNIF(LOCK_FLAG)
C
C	THIS FUNCTION ACCESSES THE SECOND LONG WORD OF EACH PAGE
C	IN THE PROCESSE'S ADDRESS SPACE BY USING ABSOLUTE ADDRESSES
C	OF THE 'P0', WHEN SS$_ACCVIO FAULT OCCURS IT IS
C	INTERCEPTED AND CONTROL RETURNED TO THE ROUTINE THAT COUNTS
C	PAGES. SINCE THERE ARE 'HOLES' IN THE ADDRESS SPACE,
C	'SNIF_FAULTS' CONSEQUITIVE FAULTS HAS TO OCCUR IN ORDER
C	TO CONSIDER ONE OF THE MENTIONED ADDRESS SPACES TO BE COMPLETED.
C
C	IT WAS DECIDED THAT 'P1' AND 'S0' ADDRESS SPACES DO NOT HAVE
C	TO BE SNIFED.
C
C-----------------------------------------------------------------------
C
C=======OPTIONS /CHECK=NOOVERFLOW
	INTEGER*4 FUNCTION  SNIF(LOCK_FLAG)
	IMPLICIT    NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
C
	INTEGER*4   LOCK_FLAG
C
	INTEGER*4   SNIF_FORWARD
	EXTERNAL    SNIF_FORWARD
C
	INTEGER*4   TOTAL_SNIFED, PAGES_DONE, PAGES_FAILED
	INTEGER*4   ERR
C
	INTEGER*4   BASE_LOW
	INTEGER*4   BASE_HIGH
C
C	THE VALUE OF THE FOLLOWING PARAMETER DEFINES THE SIZE OF THE
C	'NO_PAGES_HOLE' IN THE ADDRESS SPACE THAT CAUSES THE SNIF PROCESS
C	TO COMPLETE. SMALLER 'HOLES' ARE SKIPPED AND SNIF  PROCESS
C	CONTINUES. THE VALUE IS NEEDED SINCE IT TAKES TOO LONG TO SCAN
C	THE ENTIRE ADDRESS SPACE.
C	THE VALUE EFFECTS THE TIME OF RUNNING 'SNIF' VS. ACCURACY OF THE
C	SCAN. HIGHER VALUE RUNS SLOWER BUT HAS GREATER ACCURACY.
C	EXPERIMENT 
C
	INTEGER*4   SNIF_MAX_FAULTS
	PARAMETER   (SNIF_MAX_FAULTS=2000)
C
	INTEGER*4   SNIF_FAULTS
	INTEGER*4   PAGE_SIZE/512/
	INTEGER*4   SKIP_PAGES/1/
C
C
C	ERROR CODE MAY BE RETURNDE AS 0 IF 'SNIF_FORWARD' COMPLETES
C	WITHOUT FAULTS OR AS ERROR CODE IF FAULTS OCCURS AND
C	'LIB$SIG_TO_RET' IS CALLED FROM THE 'ACCVIO_SIGNAL' ROUTINE.
C
C	DO P0 ADDRESS SPACE - ADDRESSES ARE PASSED AS ABSOLUTE VALUES
C
	TOTAL_SNIFED = 0
	SNIF_FAULTS = SNIF_MAX_FAULTS
	BASE_LOW = PAGE_SIZE * 1	! FIRST PAGE IS ALWAYS SKIPPED
					! (LINKER PARAMETER)
	BASE_HIGH = '3FFFFFFF'X		! LAST ADDRESS OF THE 'P0'
1000	CONTINUE
	PAGES_FAILED = 0
1100	CONTINUE
	ERR = SNIF_FORWARD
     1	  (BASE_LOW, BASE_HIGH-BASE_LOW, PAGES_DONE, LOCK_FLAG)
C
C	IF THIS IS A NEW 'HOLE' - OPTIONALLY REPORT THE SIZE 
C	OF THE PREVIOUS ONE AND GO BACK
C
D	IF(PAGES_DONE.GT.0 .AND. PAGES_FAILED .GT. 0) THEN
D	    TYPE *,IAM(), 'PAGES FAILED: ', PAGES_FAILED
D	ENDIF
C
C	WITH ERROR OR WITHOUT THERE ARE COULD BE PAGES_DONE
C
	IF (PAGES_DONE .GT.0) THEN
D	    TYPE *,IAM(),'NUMBER OF P0 PAGES SNIFFED: ', PAGES_DONE
	    TOTAL_SNIFED = TOTAL_SNIFED + PAGES_DONE
	ENDIF
C
C	ERR NOT EQUAL 0 MEANS THAT THIS WAS RETURN FROM SIGNAL HANDLER OF
C	'ACCVIO' EXCEPTION. ERR = 0 MEANS THAT PAGES ARE SNIFED WITHOUT
C	PAGE FAULTS AND ROUTINE CAN RETURN.
C
	IF (ERR .EQ. 0) GOTO 10000
C
	BASE_LOW = BASE_LOW + PAGE_SIZE*SKIP_PAGES
	PAGES_FAILED = PAGES_FAILED + SKIP_PAGES
C
C	IF THE HOLE IS LARGER THAN 'SNIF_FAULTS',
C	MOST LIKELY THERE ARE NO MORE VALID PAGES -
C	IT TAKES TOO LONG TO SCAN THE ENTIRE ADDRESS SPACE.
C
	IF (PAGES_FAILED .GE. SNIF_FAULTS) GOTO 10000
C
	IF (PAGES_DONE .LE. 0) GOTO 1100	! CONTINUATION OF A 'HOLE'
C
C	START OF A NEW 'HOLE'
C
	GOTO 1000
C
10000	CONTINUE
	SNIF = TOTAL_SNIFED
C
	RETURN
	END
