C
C SUBROUTINE ISREAD1
C $Log:   GXAFXT:[GOLS]ISREAD1.FOV  $
C  
C     Rev 1.0   17 Apr 1996 13:41:16   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 16:43:10   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - nrm_hshseqi4.for **
C
C
C
C
C
C *** ISREAD1
C
C This will return the next record in the hash file (dummy or not)
C
C Note that we declare the record as I*4 even though it was
C passed as I*2.  This is for speed & it works...don't knock it.
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE ISREAD1(I4REC,LUN,IOBUF,STATUS)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
C
	INCLUDE 'INCLIB:HSHCOM.DEF'
C
	INTEGER*4 I4REC(*)             ! OUTPUT: TO HOLD RECORD
	INTEGER*4 LUN                  !  INPUT: LOGICAL UNIT #
	INTEGER*4 IOBUF(*)             !SCRATCH: I/O BUFFER
	INTEGER*4 STATUS               ! OUTPUT: 0=OK, ELSE ERROR #
C
	INTEGER*4 DIFF, NRMBLK, K, LENREC, NUMREC, RECI4KEY
	INTEGER*4 OFFSET, TUBOFF
C
C
C
C Be sure that this file is open and that for sequential access
C we either always read or always write.
C
	IF(FCB(FCBLUN,LUN).NE.LUN)THEN
	  STATUS=ERRUNT
	  GO TO 9000
	ENDIF
C
	IF(FCB(FCBMOD,LUN).EQ.SEQRED)THEN
	  GO TO 2000
	ELSE IF(FCB(FCBMOD,LUN).EQ.0)THEN
	  FCB(FCBMOD,LUN)=SEQRED
	  FCB(FCBBLK,LUN)=0
	ELSE
	  STATUS=ERRMOD
	  GO TO 9000
	ENDIF
C
C Come here to read a new buffer
C
C
1000	CONTINUE
	FCB(FCBBLK,LUN)=FCB(FCBBLK,LUN)+1
	IF(FCB(FCBBLK,LUN).GT.FCB(FCBHSH,LUN))THEN
	  STATUS=ERREND
	  GO TO 9000
	ENDIF
	FCB(FCBOFF,LUN)=0
	CALL READHASH(LUN,FCB(FCBBLK,LUN),IOBUF,STATUS)
	IF(STATUS.NE.0)GO TO 9000
C
2000	CONTINUE
	TUBOFF=FCB(FCBTUBOFF,LUN)
	OFFSET=FCB(FCBOFF,LUN)
	IF(OFFSET.GT.FCB(FCBLOF,LUN))GO TO 1000
C
	RECI4KEY=IOBUF(TUBOFF+OFFSET+FCB(FCBI4K,LUN))
	IF(RECI4KEY.EQ.0)GO TO 1000
C
	NUMREC=ISHFT(RECI4KEY,-30) + 1
	LENREC=NUMREC*FCB(FCBLN4,LUN)
	DO 2100 K=1,LENREC
	  I4REC(K)=IOBUF(TUBOFF+OFFSET+K)
2100	CONTINUE
C
	FCB(FCBOFF,LUN)=OFFSET+LENREC
	STATUS=0
C
C Accumulate some statistics
C
	FCB(FCBHIT,LUN)=FCB(FCBHIT,LUN)+1
	FCB(FCBUSD,LUN)=FCB(FCBUSD,LUN)+NUMREC
	RECI4KEY=IAND(RECI4KEY,INDMSK)
	NRMBLK=MOD(RECI4KEY,FCB(FCBHSH,LUN)) + 1
	IF(NRMBLK.NE.FCB(FCBBLK,LUN))THEN
	  DIFF=FCB(FCBBLK,LUN)-NRMBLK
	  IF(DIFF.LT.0)DIFF=FCB(FCBHSH,LUN)+DIFF
	  FCB(FCBOVR,LUN)=FCB(FCBOVR,LUN)+1
	  FCB(FCBTOV,LUN)=FCB(FCBTOV,LUN)+DIFF
	ENDIF
C
9000	CONTINUE
	RETURN
	END
