C SUBROUTINE GETRAF2CONF
C  
C V01 11-MAR-2016 SCML CREATION (M16 PROJECT)
C
C SUBROUTINE TO GET THE RAF2 CONFIGURATION RECORD FROM THE RAF2CF.FIL
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C Copyright 2016 SCML Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW
        SUBROUTINE GETRAF2CONF(RECORD,ST)
        IMPLICIT NONE
C
        INCLUDE 'INCLIB:SYSPARAM.DEF'
        INCLUDE 'INCLIB:SYSEXTRN.DEF'
        INCLUDE 'INCLIB:GLOBAL.DEF'
        INCLUDE 'INCLIB:RECRAF2CF.DEF'
C
        INTEGER*4 RAF2LU
        LOGICAL*4 ISTHERE
C
        INTEGER*4 RAF2FDB(7)
        INTEGER*4 RECORD(*), I, ST
C
        ST=-1
C
C       FIND A FREE LUN TO USE
C
        DO 10 RAF2LU = 1, 200
          INQUIRE(UNIT=RAF2LU, OPENED=ISTHERE, IOSTAT=ST)
          IF(ST.EQ.0.AND..NOT.ISTHERE) GOTO 20
10      CONTINUE
        TYPE*,IAM(),'GETRAF2CONF(): NO LUN AVAILABLE BETWEEN 1..200!'
        RETURN
20      CONTINUE
C
C       OPEN THE RAF2F.FIL AND READ THE CONFIGURATION
C
        CALL OPENW(RAF2LU,RAF2CFNAM,4,0,0,ST)
        IF(ST.NE.0) THEN
          CALL FILERR(RAF2CFNAM,1,ST,0)
          RETURN
        ENDIF
        CALL IOINIT(RAF2FDB,RAF2LU,RAF2CF_SEC*256)
        CALL READW(RAF2FDB,1,RAF2CF_REC,ST)
        IF(ST.NE.0) THEN
           CALL FILERR(RAF2CFNAM,2,ST,1)
           CALL CLOSEFIL(RAF2FDB)
           RETURN
        ENDIF
        CALL CLOSEFIL(RAF2FDB)
C
C       MOVE RECORD OVER TO OUTPUT RECORD
C
        CALL FASTMOV(RAF2CF_REC,RECORD,RAF2CF_LEN)
C
        ST=0
        RETURN
        END
C
C END NRM_GETRAF2CONF.FOR
C
