C
C SUBROUTINE WRKSET
C WRKSET.FOR
C
C V08 25-JUL-2000 UXN OPS() added.
C V07 30-JUL-1999 UXN NEW WORKING SET SIZE CANNOT BE SMALLER THAN DEFAULT 
C                     WORKING SET.
C V06 15-AUG-1991 MP  FIXED PROPER TERMINATION OF THE 'ITEMLIST'
C V05 07-MAY-1991 MP  CHNGED TO BE ABLE TO DECREASE WORKING SET
C
C V04 01-MAY-1991 MP  ELIMINATED 'LIB$SIGNAL' CALL IF ADJWSL FAILED
C		    MESSAGES ABOUT NOT BEING ABLE TO
C		    INCREASE WORKING SET ARE STILL PRINTED.
C		    THE FAILURE TO INCREASE WORKING SET EFFECTS PERFORMANCE
C		    BUT SHOWS-UP ONLY IF ENVIRONMENT IS NOT CORRECT -
C		    MOSTLY DURING IN-HOSE TESTING WHEN IT IS DESIRABLE TO
C		    OPERATE WITH REDUCED MEMORY LIMITS.
C
C V03 23-APR-1991 MP  ADDED CALLS TO LIB$ESTABLISH IN 'LKPMEM'
C	   	      AND 'LKPWRK'
C
C V02 22-APR-1991 MP  UNCOMMENTED CALL TO SYS$LCKPAG...
C
C V01 06-SEP-1990 XXX RELEASED FOR VAX
C
C Modify working set routines:
C	WRKSET(NEWSIZE) - SET SIZE OF THE WORKING SET
C	LKPWRK(FSTPAG, LSTPAG) - LOCK PAGE IN WORKING SET
C	LKPMEM(FSTPAG, LSTPAG) - LOCK PAGE IN MEMORY
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C This item is the property of GTECH Corporation, Providence, Rhode
C Island, and contains confidential and trade secret information. It
C may not be transferred from the custody or control of GTECH except
C as authorized in writing by an officer of GTECH. Neither this item
C nor the information it contains may be used, transferred,
C reproduced, published, or disclosed, in whole or in part, and
C directly or indirectly, except as expressly authorized by an
C officer of GTECH, pursuant to written agreement.
C
C Copyright 1991 GTECH Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE WRKSET (NEWSIZE)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE '($SYSSRVNAM)'
C
	INTEGER*4   NEWSIZE
	INTEGER*4   OLDSIZE
	INTEGER*4   DEFAULT
	INTEGER*4   STAT
	INTEGER*4   ADJUST
	INTEGER*4   ADJUSTED
C
C INCREASE WORKING SET SIZE
C
	STAT = SYS$ADJWSL (,OLDSIZE)
	IF (.NOT. STAT) THEN
	    CALL OPSTXT('FAILED TO OBTAIN OLD WORKING SET SIZE')
C*** V04	    CALL LIB$SIGNAL(%VAL(STAT))
	    RETURN
	ENDIF
C
	CALL GET_WSDEFAULT(DEFAULT)    ! V07
C
	NEWSIZE = MAX(NEWSIZE,DEFAULT) ! V07
C 
	ADJUST = NEWSIZE - OLDSIZE
C
	IF (ADJUST .EQ. 0) RETURN	    ! V05
C
	STAT = SYS$ADJWSL (%VAL(ADJUST),ADJUSTED)
	IF (.NOT. STAT .OR. ADJUSTED .NE. NEWSIZE) THEN
	    CALL OPS('FAILED TO INCREASE WORKING SET BY ', ADJUST,0)
C*** V04	    CALL LIB$SIGNAL(%VAL(STAT))
	ENDIF
C
	RETURN
	END
