C
C SUBROUTINE TO BUILD GVT INSTALL REQUEST/CONFIRM OUTPUT MESSAGES.
C
C
C V02 03-JAN-95 SMH On successful confirmation result code 1 is 0
C                   On bad confirmation result code 1 is 1
C                   Made checksum 2 bytes
C
C V01 01-SEP-94 XXX Initial Release for UK
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C This item is the property of GTECH Corporation, Providence, Rhode
C Island, and contains confidential and trade secret information. It
C may not be transferred from the custody or control of GTECH except
C as authorized in writing by an officer of GTECH. Neither this item
C nor the information it contains may be used, transferred,
C reproduced, published, or disclosed, in whole or in part, and
C directly or indirectly, except as expressly authorized by an
C officer of GTECH, pursuant to written agreement.
C
C Copyright 1996 GTECH Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE OINSGVT(TRABUF,OUTTAB,OUTLEN,DUMMY)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:AGTCOM.DEF'
	INCLUDE 'INCLIB:AGTINF.DEF'
	INCLUDE 'INCLIB:INSCOM.DEF'
	INCLUDE 'INCLIB:DESTRA.DEF'
	INCLUDE 'INCLIB:TASKID.DEF'
	INCLUDE 'INCLIB:CHKSUMCM.DEF'
	INCLUDE 'INCLIB:X2XCOM.DEF'
        INCLUDE 'INCLIB:X2XSTN.DEF'
        INCLUDE 'INCLIB:X2BLDNET.DEF'
C
C
        INTEGER*4 MYCHKSUM, CHKLEN, IND, I
        INTEGER*4 ERRTYP, ST, CHKDIG, HR, MIN, SEC, GVTID(2), STATION
        INTEGER*4 BCDHR, BCDMIN, BCDSEC, TNUM, ACTION, REAL
        INTEGER*2 DUMMY
	INTEGER*4 DIG(2),I4BUF(4)
	INTEGER*4 DUMMY_START, DUMMY_END, CONFIRMED
	CHARACTER*1 I1BUF(16)
	EQUIVALENCE (I4BUF,I1BUF)
C
	BYTE      BLANKS(200)
	DATA      BLANKS/200*' '/
C
	BYTE      OUTTAB(*)
	INTEGER*2 OUTLEN
C
	BYTE	  TEMP_BTAB(512)
	CHARACTER TEMP_CTAB(512)
	EQUIVALENCE (TEMP_BTAB,TEMP_CTAB)
C
	INTEGER*4   I4TEMP
	INTEGER*2   I2TEMP(2)
	BYTE	    I1TEMP(4)
	EQUIVALENCE (I4TEMP,I2TEMP,I1TEMP)
	DATA ERRTYP/Z90/
	
	INTEGER*4 NON_DIAL

	NON_DIAL = 0 ! SHOULD BE X2X_NONDIAL_STATIONS
C
C CHECK FOR FILE ACCESS SUPPRESSED.  IF SO, REJECT SUPPRESSED.
C
	IF(P(SUPFIL).EQ.1) THEN
 	  TRABUF(TSTAT)=REJT
	  TRABUF(TERR)=SUPR
	ENDIF
C
C IF TRANSACTION STATUS IS NOT GOOD
C BUILD ERROR MESSAGE.
C
        IF(TRABUF(TSTAT).NE.GOOD) THEN
          OUTTAB(2) = ERRTYP
          OUTTAB(5) = TRABUF(TERR)
          OUTLEN=5
          GOTO 1000
        ELSE
	  OUTTAB(2)='DE'X
	ENDIF
C
C PROCESS GVT INSTALL REQUEST
C TIME IN BCD
C
        IND=5
        SEC=TRABUF(TTIM)+10
        HR=SEC/3600
        MIN=(SEC-HR*3600)/60
        SEC=SEC-(HR*3600+MIN*60)
C
C GET HOURS INTO BCD
C
        DO 100 I=1,2
           DIG(I)=MOD(HR,10)
           HR=HR/10
100     CONTINUE
        BCDHR=16*DIG(2)+DIG(1)
C
C GET MINUTES INTO BCD
C
        DO 200 I=1,2
           DIG(I)=MOD(MIN,10)
           MIN=MIN/10
200     CONTINUE
        BCDMIN=16*DIG(2)+DIG(1)
C
C GET SECONDS INTO BCD
C
        DO 300 I=1,2
           DIG(I)=MOD(SEC,10)
          SEC=SEC/10
300     CONTINUE
        BCDSEC=16*DIG(2)+DIG(1)
        I4TEMP=BCDHR
        OUTTAB(IND+0) = I1TEMP(1)   !HOURS
        I4TEMP=BCDMIN
        OUTTAB(IND+1) = I1TEMP(1)   !MINS
        I4TEMP=BCDSEC
        OUTTAB(IND+2) = I1TEMP(1)   !SECONDS
        IND=IND+3
C
C JULIAN DATE
C
        I4TEMP=DAYJUL
        OUTTAB(IND+0) = I1TEMP(2)
        OUTTAB(IND+1) = I1TEMP(1)
        IND=IND+2
C
C SERIAL NUMBER AND CHECK DIGITS
C
        CALL OUTGEN(TRABUF(TCDC),TRABUF(TSER),I4TEMP,CHKDIG)
        OUTTAB(IND+0) = I1TEMP(3)
        OUTTAB(IND+1) = I1TEMP(2)
        OUTTAB(IND+2) = I1TEMP(1)
        OUTTAB(IND+3) = CHKDIG
        IND=IND+4
C
C CHECK IF THIS IS A CONFIRMATION
C
	IF(TRABUF(TII_CLASS).EQ.1) THEN
	  ACTION = TRABUF(TII_ACTION)
          
	  CALL FIND_AGENT(TRABUF(TII_AGENT),TNUM,ST)
	  TRABUF(TII_TERNUM)=TNUM
	  IF(ST.NE.0) THEN
            ACTION=0     !REJECT CONFIRMATION
            CONFIRMED = 0
	  ELSE
	    TRABUF(TII_TERNUM)=TNUM
            CONFIRMED = 1 
	  ENDIF
C
C SET THE PARAMETERS FOR THE CALL TO X2ASSGVT.
C

          REAL=X2XT_STATION_NO(TRABUF(TII_TERNUM))
	  IF(REAL.LT.1.OR.REAL.GT.NON_DIAL.OR.
     *       DUMMY.LT.1.OR.DUMMY.GT.NON_DIAL) THEN !CHECK STN INFO
	    REAL=0
            ACTION=0                  !REJECT CONFIRMATION
            CONFIRMED = 0
          ELSE
	    I4BUF(1)=TRABUF(TII_GVTID)
	    I4BUF(2)=TRABUF(TII_GVTID+1)
	    I4BUF(3)=TRABUF(TII_GVTID+2)
	    I4BUF(4)=TRABUF(TII_GVTID+3)
  	    CALL ATOH(I1BUF,1,12,GVTID,ST)
	    IF(ST.LT.0) THEN
	      REAL=0
	      ACTION=0                  !REJECT CONFIRMATION
              CONFIRMED = 0
	    ENDIF
	  ENDIF
	  CALL X2ASSGVT(ACTION,REAL,DUMMY,GVTID,ST)
	  IF(ST.NE.0) THEN	!IF BAD STATUS, THEN CANCEL CONFIRM
	      CONFIRMED = 0	    
	  ENDIF
C
C FINISHING PACKING THE OUTPUT MESSAGE.
C
          !!! If Confirmation good then result code 1 should be 0 
          !!! If Confirmation bad then result code 1 should be 1
          !!! - SMH 03-JAN-1994
          IF (CONFIRMED .EQ. 0) THEN
              OUTTAB(IND+0)=1
          ELSE IF (CONFIRMED .EQ.1) THEN
              OUTTAB(IND+0)=0
	  ELSE !!! assume error
              OUTTAB(IND+0)=1
          END IF

	  OUTTAB(IND+1)='FF'X           !RESULT CODE 2
	  IND=IND+2
	  OUTLEN=IND-1
	  OUTTAB(2)='DE'X
	  IF(TRABUF(TII_ACTION).EQ.1) 
     *      CALL BSET(AGTTAB(AGTTYP,TRABUF(TII_TERNUM)),AGTISF)
	  GOTO 1000
	ENDIF	
C
C CONTINUE PROCESSING INSTALL REQUEST
C FIND TERMINAL NUMBER AND READ AGENT RECORD
C
	CALL FIND_AGENT(TRABUF(TII_AGENT),TNUM,ST)
	IF(ST.EQ.0) CALL READW(ASFFDB,TNUM,ASFREC,ST)
C
C TERMINAL NUMBER NOT FOUND OR ASF READ ERROR
C
	IF(ST.NE.0) THEN
	  TRABUF(TSTAT)=REJT
	  TRABUF(TERR)=INVL
	  OUTTAB(IND+0)=1		    !RETAILER NOT FOUND
	  OUTTAB(IND+1)='FF'X
	  OUTTAB(IND+2)=TRABUF(TII_CLASS)
	  IND=IND+3
	  CALL MOVBYT(BLANKS,1,OUTTAB,IND,107)
	  IND=IND+107
	  OUTLEN=IND-1
	  OUTTAB(2)='DE'X
	  GOTO 1000
	ENDIF
C
C DJO - CHECK FOR RETAILER FOUND, BUT ALREADY HAS A GVTID ASSIGNED AND
C       ALSO CHECK TO MAKE SURE THAT THE REQUESTING STATION IS A VALID 
C       DUMMY STATION.
C
        STATION=X2XT_STATION_NO(TNUM)
        DUMMY_START=X2XC_DUMMY_START_STN(CLASS_X28)
        DUMMY_END=X2XC_DUMMY_END_STN(CLASS_X28)
        IF(DUMMY.LT.DUMMY_START.OR.DUMMY.GT.DUMMY_END.OR.
     *     X2XS_EVSN(1,STATION).NE.0.OR.X2XS_EVSN(2,STATION).NE.0) THEN
	  TRABUF(TSTAT)=REJT
	  TRABUF(TERR) =INVL
	  OUTTAB(IND+0)=2		    !RETAILER ALREADY INSTALLED
	  OUTTAB(IND+1)='FF'X
	  OUTTAB(IND+2)=TRABUF(TII_CLASS)
	  IND=IND+3
	  CALL MOVBYT(BLANKS,1,OUTTAB,IND,107)
	  IND=IND+107
	  OUTLEN=IND-1
	  OUTTAB(2)='DE'X
	  GOTO 1000
	ENDIF
C
C BUILD GOOD INSTALLATION REQUEST MESSAGE
C
	TRABUF(TII_TERNUM)=TNUM
	OUTTAB(IND+0)=0
        OUTTAB(IND+1)='FF'X
        OUTTAB(IND+2)=TRABUF(TII_CLASS)
	IND=IND+3
	CALL MOVBYT(BLANKS,1,OUTTAB,IND,107)
	CALL MOVBYT(ASFINF,SNAME,OUTTAB,IND,LNAME)  
	IND=IND+30
	CALL MOVBYT(ASFINF,SSTRT,OUTTAB,IND,LSTRT)
	IND=IND+30
	CALL MOVBYT(ASFINF,SCITY,OUTTAB,IND,LCITY)
	IND=IND+20
	CALL MOVBYT(ASFINF,SSTTE,OUTTAB,IND,LSTTE)
	IND=IND+20
	CALL MOVBYT(ASFINF,SZIPC,OUTTAB,IND,LZIPC)
	IND=IND+7
	OUTLEN=IND-1
	OUTTAB(2)='DE'X
	GOTO 1000
C
C CALCULATE CHECKSUM
C
1000	CONTINUE
	I4CCITT = TRABUF(TCHK)
	OUTTAB(3) = I1CCITT(2)
	OUTTAB(4) = I1CCITT(1)  !!! V02
	CHKLEN=OUTLEN-1
	CALL GETCCITT(OUTTAB,1,CHKLEN,MYCHKSUM)
	I4CCITT = MYCHKSUM
	OUTTAB(3) = I1CCITT(2)
	OUTTAB(4) = I1CCITT(1)  !!! V02
	RETURN
	END
