C  GXSRC:OIORD.FOR
C
C V12 10-JUN-2005 FRP Modify for IPS Distribution.
C V11 10-OCT-2000 UXN AlphaIPS release.
C V10 26-FEB-1997 HXK Reversed text for game names
C V09 11-FEB-1997 RXK IMNU=instant supply message, IORD=instant games names 
C                     request message
C V08 28-JAN-1997 HXK LOTGEN changes for IPS
C V07 18-DEc-1996 HXK Major changes for Finland IPS release
C V06 05-DEC-1996 HXK Updated for Finland IPS pre-release
C V05 01-FEB-1995 JJOLY UPDATED TO MATCH NEW ERROR MESSAGE MAPPING
C V04 10-FEB-1992 JPJ ADDED (GVT)
C V03 05-FEB-1992 NJA ADDED (GVT REVBYT)
C V02 04-FEB-1992 NJA ADDED (2 BYTE CHECKSUM)
C V01 13-NOV-1991 JPJ RELEASED FOR VAX (INSTANTS)
C
C SUBROUTINE TO BUILD INSTANT GAME PARAMETERS REQUEST OUTPUT MESSAGES.
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C This item is the property of GTECH Corporation, Providence, Rhode
C Island, and contains confidential and trade secret information. It
C may not be transferred from the custody or control of GTECH except
C as authorized in writing by an officer of GTECH. Neither this item
C nor the information it contains may be used, transferred,
C reproduced, published, or disclosed, in whole or in part, and
C directly or indirectly, except as expressly authorized by an
C officer of GTECH, pursuant to written agreement.
C
C Copyright 1996 GTECH Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE OIORD(TRABUF,OUTTAB,OUTLEN,CRSBUF)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:DESTRA.DEF'
	INCLUDE 'INCLIB:CRSBUF.DEF'
	INCLUDE 'INCLIB:CHKSUMCM.DEF'
C
	INCLUDE 'INCLIB:INSNAM.DEF'
C
        INTEGER*4 MYCHKSUM, CHKLEN, IND
        INTEGER*4 ERRTYP, I
	INTEGER*4 CHKDIG

	BYTE      OUTTAB(*)
	INTEGER*2 OUTLEN
C
	INTEGER*4   I4TEMP
	INTEGER*2   I2TEMP(2)
	BYTE	    I1TEMP(4)
	EQUIVALENCE (I4TEMP,I2TEMP,I1TEMP)
C
	DATA ERRTYP/Z90/
C
C CONTROL AND SEQUENCE NUMBER
C
	OUTTAB(1) = '20'X+TRABUF(TTRN)
C
C IF TRANSACTION STATUS IS NOT GOOD
C BUILD ERROR MESSAGE.
C
	IF(TRABUF(TSTAT).NE.GOOD.AND.TRABUF(TERR).NE.BCRS) THEN
	  OUTTAB(2) = ERRTYP
	  OUTTAB(5) = TRABUF(TERR)
	  OUTLEN=5
	  GOTO 1000
	ENDIF
C
C TYPE AND SUBTYPE
C
	OUTTAB(2) = 'D7'X
C
C TIME
C
	IND=5
	CALL HOST_TO_TERM(OUTTAB(IND),TRABUF(TTIM),3)
	IND=IND+3
C
C JULIAN DATE
C
	CALL HOST_TO_TERM(OUTTAB(IND),DAYJUL,2)
	IND=IND+2
C
C SERIAL NUMBER AND CHECK DIGITS
C
	CALL OUTGEN(TRABUF(TCDC),TRABUF(TSER),I4TEMP,CHKDIG)
	CALL HOST_TO_TERM(OUTTAB(IND),I4TEMP,3)
	OUTTAB(IND+3) = CHKDIG
	IND=IND+4
C
C INSTANT RESULT CODE ONE
C
        OUTTAB(IND+0) = 0
	IF(TRABUF(TIERR).NE.INOER) OUTTAB(IND+0) = 1
	IND=IND+1
C
C INSTANT RESULT CODE TWO (NUMBER OF GAMES)
C
	OUTTAB(IND+0) = CRSBUF(NBRENT)
	IF(TRABUF(TIERR).NE.INOER) OUTTAB(IND+0) = TRABUF(TIERR)
	IND=IND+1
C
C MORE FLAG
C
        IF(CRSBUF(NXTGAM).NE.0) THEN
          OUTTAB(IND+0) = '01'X
        ELSE
          OUTTAB(IND+0) = '00'X
        ENDIF
        IND=IND+1
C
C SET CHECKSUM
C
        CALL HOST_TO_TERM(OUTTAB(IND), CRSBUF(GTBCHK), 2)
        IND = IND + 2
C
C SET RETAILER CREDIT LIMIT
C
        CALL HOST_TO_TERM(OUTTAB(IND), CRSBUF(GTBRCL), 4)
        IND = IND + 4
C
C SET NEXT GAME
C
        CALL HOST_TO_TERM(OUTTAB(IND), CRSBUF(NXTGAM), 2)
        IND = IND + 2
C
C GAME PARAMETERS INFORMATION
C
	DO I=0,CRSBUF(NBRENT)-1
C
C GAME NUMBER
C
          CALL HOST_TO_TERM(OUTTAB(IND),CRSBUF(GTBGAM+I),2)
      	  IND=IND+2
C
C SHORT GAME NAME
C
	  CALL MOVBYT(CRSBUF(GTBNM1+I),1,OUTTAB,IND,4)
	  IND=IND+4

	  CALL MOVBYT(CRSBUF(GTBNM2+I),1,OUTTAB,IND,2)
	  IND=IND+2
C
C LONG GAME NAME
C
	  CALL MOVBYT(CRSBUF(GTBNM3+I),1,OUTTAB,IND,4)
	  IND=IND+4

	  CALL MOVBYT(CRSBUF(GTBNM4+I),1,OUTTAB,IND,4)
	  IND=IND+4

	  CALL MOVBYT(CRSBUF(GTBNM5+I),1,OUTTAB,IND,4)
	  IND=IND+4

	  CALL MOVBYT(CRSBUF(GTBNM6+I),1,OUTTAB,IND,4)
	  IND=IND+4

	  CALL MOVBYT(CRSBUF(GTBNM7+I),1,OUTTAB,IND,4)
	  IND=IND+4
C
C GAME FLAGS
C
	  CALL HOST_TO_TERM(OUTTAB(IND),CRSBUF(GTBFLG+I),2)
	  IND=IND+2
C
C TICKET COST
C
          CALL HOST_TO_TERM(OUTTAB(IND),CRSBUF(TKTPRC+I),4)
          IND=IND+4
C
C TICKETS PER PACK
C
          CALL HOST_TO_TERM(OUTTAB(IND),CRSBUF(TKTPCK+I),2)
          IND=IND+2
	ENDDO
	OUTLEN=IND-1
C
C CALCULATE CHECKSUM
C
1000	CONTINUE
	I4CCITT = TRABUF(TCHK)
	CALL HOST_TO_TERM(OUTTAB(3),I4CCITT,2)
	CHKLEN=OUTLEN-1
	CALL GETCCITT(OUTTAB,1,CHKLEN,MYCHKSUM)
	I4CCITT = MYCHKSUM
	CALL HOST_TO_TERM(OUTTAB(3),I4CCITT,2)
	RETURN
	END
