C
C SUBROUTINE OPNRPC
C $Log:   GXAFXT:[GOLS]OPNRPC.FOV  $
C  
C     Rev 1.0   17 Apr 1996 14:19:34   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.1   13 Jun 1993 13:37:26   HXK
C   added AGTINF.DEF, PRMAGT.DEF
C  
C     Rev 1.0   21 Jan 1993 17:13:04   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - repcan.for **
C
C
C
C SUBROUTINE TO OPEN FILES FOR REPCAN
C
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE OPNRPC(FDB)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:TASKID.DEF'
        INCLUDE 'INCLIB:AGTINF.DEF'
        INCLUDE 'INCLIB:PRMAGT.DEF'
	INCLUDE 'INCLIB:RECAGT.DEF'
	INTEGER*4 FDB(7), ST
C
C OPEN ASF
C
	CALL OPENW(1,SFNAMES(1,ASF),4,0,0,ST)
	CALL IOINIT(FDB,1,ASFSEC*256)
	IF(ST.NE.0) CALL FILERR(SFNAMES(1,ASF),1,ST,0)
	RETURN
	END
