C
C SUBROUTINE POOLREAD
C $Log:   GXAFXT:[GOLS]POOLREAD.FOV  $
C  
C     Rev 1.0   17 Apr 1996 14:25:36   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 17:18:52   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - poolmgr.for **
C
C
C     POOLREAD
C
C     READ POOL INFO INTO MEMORY
C
C+++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE POOLREAD
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:POOLLTO.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:RECSCF.DEF'
	INTEGER*4 PFDB(7),FDB(7), ST
C
C
	CALL OPENX(1,'SCF.FIL',4,0,0,ST)
	CALL IOINIT(FDB,1,SCFSEC*256)
	IF(ST.NE.0) THEN
	  TYPE*,'SCF.FIL open error > ',ST
	  CALL GPAUSE
	ENDIF
	CALL READW(FDB,1,SCFREC,ST)
	IF(ST.NE.0) THEN
	  TYPE*,'SCF.FIL read error > ',ST
	  CALL GPAUSE
	ENDIF
C
	CALL CLOSEFIL(FDB)
C
C
C CHANGE SYSTEM FILE SIZES/VOLUME NAMES
C
10	CONTINUE
	IF(SCFSFN(1,LP1).EQ.'    ') CALL SYSVOL(SCFSFN(1,LP1))
	CALL OPENQW(3,SCFSFN(1,LP1),4,0,0,ST)
	IF(ST.NE.0) THEN
	  CALL FILERR(SCFSFN(1,LP1),1,ST,0)
	  CALL GPAUSE
	  GOTO 10
	ENDIF
	CALL IOQINIT(PFDB,3,LTOSEC*256)
C
C
	CALL READQW(PFDB,LTNUMPAG+1,LTOVR,ST)
	IF (ST.NE.0) THEN
	   TYPE *,IAM(),'Could not read pool1 file ',ST
	ENDIF
	CALL CLOSEQFIL(PFDB)
C
	RETURN
	END
