C  GXSRC:PRTTCBUF.FOR
C
C V04 28-OCT-2013 SCML Display new fields of Instant Validation, regarding
C                      new bank validation mode
C V03 16-MAR-2000 UXN Log output to GTECH$DEBUG
C V02 31-MAR-1995 DJO Changed to use a more robust output format.
C V01 19-NOV-1991 KWP INITIAL RELEASE FOR VAX
C
C Routine to display a TCBUF to the system console
C
C Input parameters:
C
C     TCBUF    Int*4   Data Buffer to be Displayed
C
C Output parameters:
C
C     None
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C This item is the property of GTECH Corporation, Providence, Rhode
C Island, and contains confidential and trade secret information. It
C may not be transferred from the custody or control of GTECH except
C as authorized in writing by an officer of GTECH. Neither this item
C nor the information it contains may be used, transferred,
C reproduced, published, or disclosed, in whole or in part, and
C directly or indirectly, except as expressly authorized by an
C officer of GTECH, pursuant to written agreement.
C
C Copyright 1995 GTECH Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE PRTTCBUF(TBUF,START,LEN,FLAG)
	IMPLICIT NONE
C
        INCLUDE '(LIB$ROUTINES)'
        INCLUDE '($FORIOSDEF)'
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:PROCOM.DEF'
	INCLUDE 'INCLIB:CRSCOM.DEF'
C
	INTEGER*4  MAXLIN,START,LEN,TBUF,FLAG
	PARAMETER (MAXLIN=40)
C
	INTEGER*4 J, K, OUTBEG, OUTPNT, LU, ST, WST
C
C
	ST = LIB$GET_LUN(LU)

        ST = FOR$IOS_OPEFAI
        DO WHILE(ST.EQ.FOR$IOS_OPEFAI)
           OPEN (UNIT        = LU,
     .        FILE        = 'GTECH$DEBUG',
     .        ACCESS      = 'APPEND',
     .        STATUS      = 'UNKNOWN',
     .        SHARED,
     .        IOSTAT      = ST)
           CALL XWAIT(50,1,WST)
        ENDDO

	WRITE(LU,*) IAM() 
	IF(FLAG.EQ.1) THEN
	  WRITE(LU, *) IAM(),'OUTGOING PACKET:  BUFLEN --> ',LEN
	ELSE
	  WRITE(LU,*) IAM(),'INCOMING PACKET:  BUFLEN --> ',LEN
	ENDIF         
	OUTPNT=1
	OUTBEG=1
	DO 2200 K=START,START+LEN, 20
          WRITE(LU,'(3X, I3, '':'', 20(X, Z2.2))')
     .          K-START+1, (B_TCBUF(J, TBUF), J=K,
     .                MIN(K+19, START+LEN-1))
2200	CONTINUE
C
C
C DECODE MESSAGES
C
	WRITE (LU, *)
	CALL PRTDETAILS(LU,B_TCBUF(START,TBUF),FLAG)
	WRITE (LU,*)

        CLOSE (LU)

        ST = LIB$FREE_LUN(LU)

7703	FORMAT(Z2)
7704	FORMAT(X,A18,I3.3,':',5(8A1,1X))
	RETURN
	END
C
C DECODE MESSAGES
C
C=======OPTIONS/CHECK=NOOVERFLOW
	SUBROUTINE PRTDETAILS(LU,BUF,FLAG)
	IMPLICIT NONE

	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INTEGER*4 LU, FLAG
	BYTE      BUF(*)
	INTEGER*4 IND, VAL, TRATYP, CNT, I, J

	IND = 1
	WRITE(LU,*) 'Start End  Size Description                          Value'
	CALL PRT(LU,'LENGTH',BUF,IND,VAL,2)
	CALL PRT(LU,'GTECH SLOT ID', BUF,IND,VAL,2) 
	CALL PRT(LU,'GTECH CROSS REF #',BUF,IND,VAL,4) 
	CALL PRT(LU,'TRANSACTION TYPE',BUF,IND,VAL,2) 
	TRATYP = VAL

	IF(FLAG.EQ.1) GOTO 500
C
C DECODE INCOMING PACKET
C	
	IF(TRATYP.EQ.4) THEN
	   CALL PRT(LU,'# OF ENTRIES',BUF,IND,VAL,2)
	   CNT = VAL
	   CALL PRT(LU,'RESULT CODE',BUF,IND,VAL,2)
	   CALL PRT(LU,'NEXT GAME TO REQUEST',BUF,IND,VAL,2)
	   CALL PRT(LU,'NEXT PACK TO REQUEST',BUF,IND,VAL,4)

	   DO I=1, CNT
	       WRITE(LU,*) I,'. ENTRY'
	       CALL PRT(LU,'GAME #',BUF,IND,VAL,2)
	       CALL PRT(LU,'PACK NUMBER',BUF,IND,VAL,4)
	       CALL PRT(LU,'STATUS',BUF,IND,VAL,2)
           ENDDO
        ELSEIF(TRATYP.EQ.3) THEN
	   CALL PRT(LU,'# OF ENTRIES',BUF,IND,VAL,2)
	   CNT = VAL
	   CALL PRT(LU,'RESULT CODE',BUF,IND,VAL,2)
	   CALL PRT(LU,'NEXT GAME TO REQUEST',BUF,IND,VAL,2)

	   DO I=1, CNT	    
	       WRITE(LU,*) I,'. ENTRY'
	       
	       CALL PRT(LU,'GAME #',BUF,IND,VAL,2)
	       CALL PRT(LU,'PACKS ON ORDER',BUF,IND,VAL,2)
      	       CALL PRT(LU,'PACK QUOTA MAXIMUM',BUF,IND,VAL,2)
      	       CALL PRT(LU,'PACKS ON HAND',BUF,IND,VAL,2)
      	       CALL PRT(LU,'REORDER MINIMUM',BUF,IND,VAL,2)
           ENDDO
	ELSEIF(TRATYP.EQ.5) THEN
	   CALL PRT(LU,'RESERVED',BUF,IND,VAL,2) 
	   CALL PRT(LU,'RESULT CODE',BUF,IND,VAL,2) 
	   CALL PRT(LU,'FILLER',BUF,IND,VAL,2) 
	   CALL PRT(LU,'TOTAL PACKS SOLD COUNT',BUF,IND,VAL,4) 
	   CALL PRT(LU,'TOTAL PACKS SOLD AMOUNT',BUF,IND,VAL,4) 
	   CALL PRT(LU,'CASHED COUNT',BUF,IND,VAL,4) 
	   CALL PRT(LU,'CASHED AMOUNT',BUF,IND,VAL,4) 
	   CALL PRT(LU,'RETURN AMOUNT',BUF,IND,VAL,4) 
	   CALL PRT(LU, 'SALES COMMISSION AMOUNT',BUF,IND,VAL,4) 
	   CALL PRT(LU,'PRIZE COMMISSION AMOUNT',BUF,IND,VAL,4) 
	   CALL PRT(LU,'ADJUSTMENT AMOUNT', BUF,IND,VAL,4) 
	   CALL PRT(LU,'TOTAL AMOUNT DUE',BUF,IND,VAL,4) 
	   CALL PRT(LU,'DATE MONTH',BUF,IND,VAL,2) 
	   CALL PRT(LU,'DATE DAY',BUF,IND,VAL,2) 
	   CALL PRT(LU,'DATE YEAR',BUF,IND,VAL,2) 
	   CALL PRT(LU,'BEGIN INVOICE MONTH',BUF,IND,VAL,2) 
	   CALL PRT(LU,'BEGIN INVOICE DAY',BUF,IND,VAL,2) 
	   CALL PRT(LU,'BEGIN INVOICE YEAR',BUF,IND,VAL,2) 
	   CALL PRT(LU,'END INVOICE MONTH',BUF,IND,VAL,2) 
	   CALL PRT(LU,'END INVOICE DAY',BUF,IND,VAL,2) 
	   CALL PRT(LU,'END INVOICE YEAR',BUF,IND,VAL,2) 
	   CALL PRT(LU,'FILLER',BUF,IND,VAL,2) 
	   CALL PRT(LU,'DOCUMENT NUMBER',BUF,IND,VAL,4) 
	ELSEIF(TRATYP.EQ.13) THEN
        CALL PRT(LU,'VALIDATION MODE TYPE',BUF,IND,VAL,2)
        IF(VAL.EQ.IBVMT) THEN
          CALL PRT(LU,'NUMBER OF TICKETS IN BATCH',BUF,IND,VAL,2) 
          CNT = VAL
	        CALL PRT(LU,'VALIDATION MODE',BUF,IND,VAL,2)
          DO I=1, CNT
            WRITE(LU,*) I,'.TICKET IN THE BATCH'
            CALL PRT(LU,'TICKET RESULT CODE',BUF,IND,VAL,2)
            CALL PRT(LU,'PRIZE AMOUNT IN CENTS',BUF,IND,VAL,4) 
            CALL PRT(LU,'NET PRIZE AMOUNT IN CENTS',BUF,IND,VAL,4) 
            CALL PRT(LU,'PACK STATUS',BUF,IND,VAL,2)
            CALL PRTSTR(LU,'PRIZE DESCRIPTION',BUF,IND,20)
          ENDDO
        ELSEIF(VAL.EQ.IRVMT) THEN
          CALL PRT(LU,'NUMBER OF TICKETS IN BATCH',BUF,IND,VAL,2) 
          CNT = VAL
	        CALL PRT(LU,'VALIDATION TYPE',BUF,IND,VAL,2)
          IF(VAL.EQ.0) THEN
            DO I=1, CNT
              WRITE(LU,*) I,'.TICKET IN THE BATCH'
              CALL PRT(LU,'TICKET RESULT CODE',BUF,IND,VAL,2) 
              CALL PRT(LU,'PRIZE AMOUNT IN CENTS',BUF,IND,VAL,4) 
              CALL PRT(LU,'PACK STATUS',BUF,IND,VAL,2)
            ENDDO
          ELSE
            CALL PRT(LU,'TICKET RESULT CODE',BUF,IND,VAL,2)
            CALL PRT(LU,'PACK STATUS',BUF,IND,VAL,2)
            CALL PRTSTR(LU,'PRIZE DESCRIPTION',BUF,IND,20)
          ENDIF
        ELSE
          WRITE(LU,*) 'UNKNOWN VALIDATION MODE TYPE: ',VAL
        ENDIF
	ELSEIF(TRATYP.EQ.2) THEN
	   CALL PRT(LU,'RESERVED',BUF,IND,VAL,2)
	   CALL PRT(LU,'RESULT CODE',BUF,IND,VAL,2)
	   CALL PRT(LU,'AMOUNT SOLD',BUF,IND,VAL,4)
	   CALL PRT(LU,'COMMISSION AMOUNT',BUF,IND,VAL,4)
	ELSEIF(TRATYP.EQ.15) THEN
           CALL PRT(LU,'RESULT CODE',BUF,IND,VAL,2)
	   CALL PRT(LU,'CLASS',BUF,IND,VAL,2)
	   IF(VAL.EQ.1) THEN
	      DO I=1,40
                 WRITE(LU,*) I,'. GAME'
	         CALL PRT(LU,'GAME REVISION',BUF,IND,VAL,2)
              ENDDO
	   ELSE
              DO I=1,2
                 CALL PRT(LU,'GAME #',BUF,IND,VAL,2)
                 DO J=1,20
		    WRITE(LU,*) J,'.PRIZE CODE AMOUNT'
                    CALL PRT(LU,'PRIZE CODE AMOUNT',BUF,IND,VAL,2)
		 ENDDO
              ENDDO
	   ENDIF
        ELSEIF(TRATYP.EQ.12) THEN
	   CALL PRT(LU,'RESERVED',BUF,IND,VAL,2)
	   CALL PRT(LU,'RESULT CODE',BUF,IND,VAL,2)
        ELSEIF(TRATYP.EQ.25) THEN
           CALL PRT(LU,'# OF ENTRIES',BUF,IND,VAL,2)
 	   CNT = VAL

	   CALL PRT(LU,'RESULT CODE',BUF,IND,VAL,2) 
	   CALL PRT(LU,'NEXT GAME TO REQUEST',BUF,IND,VAL,2) 
	   CALL PRT(LU,'NEXT PACK TO REQUEST',BUF,IND,VAL,4) 
	   CALL PRT(LU,'RETAILER #',BUF,IND,VAL,4) 
	   CALL PRT(LU,'BEGIN INVOICE MONTH',BUF,IND,VAL,2) 
	   CALL PRT(LU,'BEGIN INVOICE DAY',BUF,IND,VAL,2) 
	   CALL PRT(LU,'BEGIN INVOICE YEAR',BUF,IND,VAL,2) 
	   CALL PRT(LU,'END INVOICE MONTH',BUF,IND,VAL,2) 
	   CALL PRT(LU,'END INVOICE DAY',BUF,IND,VAL,2) 
	   CALL PRT(LU,'END INVOICE YEAR', BUF,IND,VAL,2) 
	   CALL PRT(LU,'TOTAL AMOUNT (LAST TRANSACTION)',BUF,IND,VAL,4) 
	   DO I=1,CNT
	       WRITE(LU,*), I, '.ENTRY'
	       CALL PRT(LU, 'PACK #',BUF,IND,VAL,4) 
	       CALL PRT(LU,'ORDER # (FIRST 9 DIGITS)',BUF,IND,VAL,4)
	       CALL PRT(LU,'ORDER # (LAST 4 DIGITS)',BUF,IND,VAL,2)
 	       CALL PRT(LU,'GAME #',BUF,IND,VAL,2)
	       CALL PRT(LU,'MONTH',BUF,IND,VAL,2)
 	       CALL PRT(LU,'DAY',BUF,IND,VAL,2)
 	       CALL PRT(LU,'YEAR',BUF,IND,VAL,2)
 	       CALL PRT(LU,'AUTO SETTLED FLAG',BUF,IND,VAL,2)
           ENDDO
        ELSEIF(TRATYP.EQ.29) THEN
           CALL PRT(LU,'OFFICE NUMBER',BUF,IND,VAL,2)
	   CALL PRTSTR(LU,'FSE NAME',BUF,IND,25)
           CALL PRT(LU,'RESULT CODE',BUF,IND,VAL,2)
	ELSEIF(TRATYP.EQ.26) THEN
           CALL PRT(LU,'# OF ENTRIES',BUF,IND,VAL,2)
	   CNT = VAL
           CALL PRT(LU,'RESULT CODE',BUF,IND,VAL,2)
           CALL PRT(LU,'RETAILER #',BUF,IND,VAL,4)
           CALL PRT(LU,'MORE FLAG',BUF,IND,VAL,1)
           CALL PRT(LU,'CONTINUATION DATE',BUF,IND,VAL,4)
           CALL PRT(LU,'CONTINUATION TIME',BUF,IND,VAL,4)
           CALL PRT(LU,'CONTINUATION TYPE',BUF,IND,VAL,2)
           CALL PRT(LU,'BEGIN INVOICE CDC',BUF,IND,VAL,2)
           CALL PRT(LU,'END INVOICE CDC',BUF,IND,VAL,2)
           CALL PRT(LU,'TOTAL ADJUSTMENT AMOUNT',BUF,IND,VAL,4)
 	   DO I=1,CNT
	      WRITE(LU,*) I,'. ENTRY'
              CALL PRT(LU, 'ADJUSTMENT CDC',BUF,IND,VAL,2)
	      CALL PRTSTR(LU,'ADJUSTMENT TEXT',BUF,IND,16)
              CALL PRT(LU,'ADJUSTMENT AMOUNT',BUF,IND,VAL,4)
	   ENDDO
	ELSEIF(TRATYP.EQ.21) THEN   
	   CALL PRT(LU, 'RESERVED',BUF,IND,VAL,2)
	   CALL PRT(LU, 'RESULT CODE',BUF,IND,VAL,2)
	ELSEIF(TRATYP.EQ.22) THEN
	   CALL PRT(LU, 'RESERVED',BUF,IND,VAL,2)
	   CALL PRT(LU, 'RESULT CODE',BUF,IND,VAL,2)
	ELSEIF(TRATYP.EQ.16.OR.TRATYP.EQ.17) THEN
	   CALL PRT(LU, 'RESERVED',BUF,IND,VAL,2)
	   CALL PRT(LU, 'RESULT CODE',BUF,IND,VAL,2)	 
	ELSEIF(TRATYP.EQ.20) THEN
	   CALL PRT(LU, 'PASS # UPDATED',BUF,IND,VAL,2)
	   CALL PRT(LU, 'RETAILER #',BUF,IND,VAL,4)	 
	   CALL PRT(LU, 'TERMINAL #',BUF,IND,VAL,4)	 
	   CALL PRT(LU, 'PASS #',BUF,IND,VAL,4)	 
	ELSEIF(TRATYP.EQ.23) THEN
	   CALL PRT(LU, 'RESERVED',BUF,IND,VAL,2)
	   CALL PRT(LU, 'RETAILER #',BUF,IND,VAL,4)	 
	   CALL PRT(LU, 'TERMINAL #',BUF,IND,VAL,4)	 
	   CALL PRTSTR(LU, 'GVTID',BUF,IND,12)	 
	ENDIF
	RETURN
C
C DECODE OUTGOING PACKET
C
500	CONTINUE
	IF(TRATYP.EQ.13) THEN
	   CALL PRT(LU,'VALIDATION MODE TYPE',BUF,IND,VAL,2) !V04
	   CALL PRT(LU,'TICKET INDICATION',BUF,IND,VAL,2)
	   CALL PRT(LU,'# OF TICKETS IN BATCH',BUF,IND,VAL,2)
	   CNT = VAL

	   CALL PRT(LU,'RETAILER #',BUF,IND,VAL,4)
	   CALL PRT(LU,'VALIDATION MODE',BUF,IND,VAL,2)
	   CALL PRT(LU,'VALIDATING RETAILER #',BUF,IND,VAL,4)
	   CALL PRT(LU,'ENVELOPE ID',BUF,IND,VAL,4)
	   CALL PRT(LU,'PLAYER ID TYPE',BUF,IND,VAL,2)       !V04
	   CALL PRT(LU,'PLAYER ID',BUF,IND,VAL,4)            !V04
	   CALL PRT(LU,'BANK BRANCH',BUF,IND,VAL,2)          !V04
	   CALL PRT(LU,'BANK OFFICE',BUF,IND,VAL,2)          !V04
	   CALL PRT(LU,'BANK ACCOUNT (PART1)',BUF,IND,VAL,4) !V04
	   CALL PRT(LU,'BANK ACCOUNT (PART2)',BUF,IND,VAL,4) !V04
	   CALL PRT(LU,'BANK CHECK DIGITS',BUF,IND,VAL,2)    !V04
	   DO I=1,CNT
	       WRITE(LU,*) I,'. TICKET IN THE BATCH'
	       CALL PRT(LU,'GAME #',BUF,IND,VAL,2)
	       CALL PRT(LU,'CDC OF TICKET SWIPED',BUF,IND,VAL,2)
	       CALL PRT(LU,'PACK #',BUF,IND,VAL,4)
	       CALL PRT(LU,'VIRN # (9 DIGITS)',BUF,IND,VAL,4)
	       CALL PRT(LU,'VIRN CHECK DIGITS', BUF,IND,VAL,2)
	       CALL PRTTIM(LU,'TIME OF TICKET SWIPED',BUF,IND,4)
	   ENDDO
        ELSEIF(TRATYP.EQ.12) THEN
	   CALL PRT(LU,'RESERVED',BUF,IND,VAL,2)
	   CALL PRT(LU,'RESULT CODE',BUF,IND,VAL,2)
	ELSEIF(TRATYP.EQ.2) THEN
	   CALL PRT(LU,'CLASS',BUF,IND,VAL,2)
	   CALL PRT(LU,'RETAILER #',BUF,IND,VAL,4)
	   CALL PRT(LU,'SALES REP NUMBER',BUF,IND,VAL,4)
	   CALL PRT(LU,'SALES REP PASS CODE',BUF,IND,VAL,2)
	   CALL PRT(LU,'AGENT PASS CODE',BUF,IND,VAL,2)
	   CALL PRT(LU,'GAME #',BUF,IND,VAL,2)
	   CALL PRT(LU,'PACK #',BUF,IND,VAL,4)
	   CALL PRT(LU,'STARTING TICKET #',BUF,IND,VAL,2)
	   CALL PRT(LU,'ENDING TICKET #',BUF,IND,VAL,2)
	ELSEIF(TRATYP.EQ.3) THEN
	   CALL PRT(LU,'CLASS',BUF,IND,VAL,2)
	   CALL PRT(LU,'RETAILER #',BUF,IND,VAL,4)
	   CALL PRT(LU,'GAME #',BUF,IND,VAL,2)
	   CALL PRT(LU,'CONTINUATION GAME #',BUF,IND,VAL,2)
	ELSEIF(TRATYP.EQ.4) THEN
	   CALL PRT(LU,'CLASS',BUF,IND,VAL,2)
	   CALL PRT(LU,'RETAILER #',BUF,IND,VAL,4)
	   CALL PRT(LU,'GAME #',BUF,IND,VAL,2)
	   CALL PRT(LU,'CONTINUATION GAME #',BUF,IND,VAL,2)
	   CALL PRT(LU,'CONTINUATION PACK #',BUF,IND,VAL,4)
	ELSEIF(TRATYP.EQ.5) THEN
	   CALL PRT(LU,'CLASS',BUF,IND,VAL,2)
	   CALL PRT(LU,'RETAILER #',BUF,IND,VAL,4)
	   CALL PRT(LU,'REPORT TYPE',BUF,IND,VAL,2)
	   CALL PRT(LU,'REQUEST TYPE',BUF,IND,VAL,2)
	   CALL PRT(LU,'REQUESTED RETAILER #',BUF,IND,VAL,4)
	   CALL PRT(LU,'PASS #',BUF,IND,VAL,4)
	ELSEIF(TRATYP.EQ.15) THEN
	   CALL PRT(LU,'CLASS',BUF,IND,VAL,2)
	   CALL PRT(LU,'GAME # 1',BUF,IND,VAL,2)
	   CALL PRT(LU,'GAME # 2',BUF,IND,VAL,2)
	ELSEIF(TRATYP.EQ.16.OR.TRATYP.EQ.17) THEN
	   CALL PRT(LU,'CDC DATE',BUF,IND,VAL,2)
	   CALL PRT(LU,'CASHING JULIAN DATE',BUF,IND,VAL,2)
	   CALL PRT(LU,'CASHING SERIAL #',BUF,IND,VAL,4)
	   CALL PRT(LU,'CASHING CHECK DIGITS',BUF,IND,VAL,4)
	   CALL PRT(LU,'CASHING RETAILER #',BUF,IND,VAL,4)
	   CALL PRT(LU,'SELLING RETAILER #',BUF,IND,VAL,4)
	   CALL PRT(LU,'AMOUNT WON (IN DIMES)',BUF,IND,VAL,4)
	   CALL PRT(LU,'GAME #',BUF,IND,VAL,2)
	   CALL PRT(LU,'DRAW DATE',BUF,IND,VAL,2)
	   CALL PRT(LU,'SELLING JULIAN DATE',BUF,IND,VAL,2)
	   CALL PRT(LU,'SELLING SERIAL #',BUF,IND,VAL,4)
	   CALL PRT(LU,'SELLING CHECK DIGITS',BUF,IND,VAL,4)
	   CALL PRT(LU,'PRIZE REPAYMENT',BUF,IND,VAL,2)
	ELSEIF(TRATYP.EQ.21) THEN
	   CALL PRT(LU,'GAME #',BUF,IND,VAL,2)
	   CALL PRT(LU,'WAGER SALES COUNT',BUF,IND,VAL,4)
	   CALL PRT(LU,'CANCELLATION COUNT',BUF,IND,VAL,4)
	   CALL PRT(LU,'INTERNAL CANCELS COUNT',BUF,IND,VAL,4)
	   CALL PRT(LU,'VALIDATION COUNT',BUF,IND,VAL,4)
	   CALL PRT(LU,'CLAIM COUNT',BUF,IND,VAL,4)
	   CALL PRT(LU,'WAGER SALES AMOUNT',BUF,IND,VAL,4)
	   CALL PRT(LU,'CANCELLATION AMOUNT',BUF,IND,VAL,4)
	   CALL PRT(LU,'INTERNAL CANCELS AMOUNT',BUF,IND,VAL,4)
	   CALL PRT(LU,'VALIDATION AMOUNT',BUF,IND,VAL,4)
	   CALL PRT(LU,'CLAIM AMOUNT',BUF,IND,VAL,4)
	   CALL PRT(LU,'RESERVED',BUF,IND,VAL,4)    
	ELSEIF(TRATYP.EQ.22) THEN
	   CALL PRT(LU,'RETAILER #',BUF,IND,VAL,4)
	   CALL PRT(LU,'TERMINAL #',BUF,IND,VAL,4)
	   CALL PRTSTR(LU,'GVTID',BUF,IND,12)
	ENDIF
	RETURN
	END
C **************************************************************************
C **************************************************************************

C=======OPTIONS/CHECK=NOOVERFLOW
	SUBROUTINE GETVAL(MSG, IND, VAL, NR_BYTES)
	IMPLICIT NONE
	BYTE MSG(*)
	INTEGER*4 IND, VAL, NR_BYTES
	INTEGER*4 I4TEMP
	BYTE      I1TEMP(4)
	EQUIVALENCE (I4TEMP,I1TEMP)
	
	I4TEMP = 0
	IF(NR_BYTES.EQ.4) THEN
  	   I1TEMP(1) = MSG(IND+0)
	   I1TEMP(2) = MSG(IND+1)
	   I1TEMP(3) = MSG(IND+2)
	   I1TEMP(4) = MSG(IND+3)
	ELSEIF(NR_BYTES.EQ.3) THEN
  	   I1TEMP(1) = MSG(IND+0)
	   I1TEMP(2) = MSG(IND+1)
	   I1TEMP(3) = MSG(IND+2)
	ELSEIF(NR_BYTES.EQ.2) THEN
  	   I1TEMP(1) = MSG(IND+0)
	   I1TEMP(2) = MSG(IND+1)
	ELSEIF(NR_BYTES.EQ.1) THEN
  	   I1TEMP(1) = MSG(IND)
	ELSE
	   CALL OPS('GETVAL: invalid NR_BYTES', NR_BYTES, 0)
	ENDIF
	IND = IND + NR_BYTES
	VAL = I4TEMP
	END

C **************************************************************************
C **************************************************************************
C=======OPTIONS/CHECK=NOOVERFLOW
	SUBROUTINE PRT(LU,TXT,BUF,IND,VAL,LEN)
	IMPLICIT NONE

	INTEGER*4 LU
	CHARACTER*(*) TXT
	BYTE BUF(*)
	INTEGER*4 IND, VAL, LEN

	CALL GETVAL(BUF,IND,VAL,LEN)
	WRITE(LU,900) IND-LEN,IND-1,LEN,TXT, VAL, VAL

900	FORMAT(3X,I3,1X,I3,3X,I3,1X,A,':',T50,I10,' HEX: ',Z8.8)
	END
C **************************************************************************
C **************************************************************************

C=======OPTIONS/CHECK=NOOVERFLOW
	SUBROUTINE PRTSTR(LU,TXT,BUF,IND,LEN)
	IMPLICIT NONE

	INTEGER*4 LU
	CHARACTER*(*) TXT
	BYTE BUF(*)
	INTEGER*4 IND, LEN, I

	WRITE(LU,900) IND,IND+LEN-1,LEN,TXT, (BUF(I),I=IND,IND+LEN-1)
	IND = IND + LEN

900	FORMAT(3X,I3,1X,I3,3X,I3,1X,A,':',T50,<LEN>A1)

	END
C **************************************************************************
C **************************************************************************

C=======OPTIONS/CHECK=NOOVERFLOW
	SUBROUTINE PRTTIM(LU,TXT,BUF,IND,LEN)
	IMPLICIT NONE
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INTEGER*4 LU
	CHARACTER*(*) TXT
	BYTE BUF(*)
	INTEGER*4 IND, LEN, VAL

	CALL GETVAL(BUF,IND,VAL,LEN)
	WRITE(LU,900) IND-LEN,IND-1,LEN,TXT, DISTIM(VAL)

900	FORMAT(3X,I3,1X,I3,3X,I3,1X,A,':',T52,A8)
	END
