C
C     FILE   : PUT_WEEK_YEAR_DRAWS.FOR
C     AUTHOR : J.H.R
C     VERSION: 01            DATE: 30 / 02 / 2001
C
C
C V01 JHR INITIAL RELEASE FOR PORTUGAL PROJECT
C
C FUNCTION TO PUT WEEK YEAR DRAWS IN OUTPUT MESSAGES TO TERMINAL
C
C     **************************************************************************
C
C        THIS ITEM IS THE PROPERTY OF GTECH CORPORATION, POVIDENCE, RHODE
C     ISLAND, AND CONTAINS CONFIDENTIAL AND TRADE SECRET INFORMATION. IT MAY
C     NOT BE TRANSFERRED FROM THE CUSTODY OR CONTROL OF GTECH EXCEPT AS AUTO -
C     RIZED IN WRITING BY AN OFFICER OF GTECH. NEITHER THIS ITEM NOR THE
C     INFORMATION IT CONTAINS MAY BE USED, TRANSFERRED, REPRODUCED, PUBLISHED
C     OR DISCLOSED, IN WHOLE OR IN PART, AND DIRECTLY OR INDIRECTLY, EXCEPT AS
C     EXPRESSLY AUTHORIZED BY AN OFFICER OR GTECH, PURSUANT TO WRITTEN AGREEMENT
C
C     Copyright 2000 GTECH Corporation. All Rigth Reserved
C
C     **************************************************************************
C
C THIS FUNCTION GETS WEEK YEAR DRAWS AND PUT IN OUTPUT MESSAGES
C
C=======OPTIONS /CHECK = NOOVERFLOW /EXT
      SUBROUTINE PUT_WEEK_YEAR_DRAWS(TRABUF, OUTMSG, IDXMSG)
      IMPLICIT NONE
C
C INCLUDES DEFINITION TO PUT WEEK YEAR DRAWS IN OUTPUT MESSAGE
C
      INCLUDE 'INCLIB:GLOBAL.DEF'
      INCLUDE 'INCLIB:CONCOM.DEF'
      INCLUDE 'INCLIB:LTOCOM.DEF'
      INCLUDE 'INCLIB:KIKCOM.DEF'
      INCLUDE 'INCLIB:SPTCOM.DEF'
      INCLUDE 'INCLIB:TGLCOM.DEF'
      INCLUDE 'INCLIB:DESTRA.DEF'
C
C PARAMETEST DEFINITION TO PUT WEEK YEAR DRAWS IN OUTPUT MESSAGE
C
      INTEGER * 4 IDXMSG                ! INDEX MESSAGE 
C
      BYTE OUTMSG(*)                    ! OUTPUT MESSAGE
C
C VARIABLES DEFINITION TO PUT WEEK YEAR DRAWS IN OUTPUT MESSAGE
C
      INTEGER * 4 FSTS                  ! FUNCTION STATUS
      INTEGER * 4 WEEK                  ! WEEK 
      INTEGER * 4 YEAR                  ! YEAR

C
C NOT USED, FOR THIS REASON WE HAVE TRABUF
C****************************************************
C      INTEGER * 4 DRAW                  ! DRAW ACTUAL / END DRAW
C      INTEGER * 4 GIND                  ! GAME INDEX
C      INTEGER * 4 GTYP                  ! GAME TYPE
C 
C GET DRAW DATES FOR EACH GAME
C
C      GIND = TRABUF(TGAMIND)
C      GTYP = TRABUF(TGAMTYP)
C      IF(GTYP .EQ. TLTO) DRAW = LTODRW(GIND)
C      IF(GTYP .EQ. TSPT) DRAW = SPTDRW(GIND)
C      IF(GTYP .EQ. TTGL) DRAW = TGLDRW(GIND)
C      IF(GTYP .EQ. TKIK) DRAW = KIKDRW(GIND)  
C*****************************************************
C
C CALCULATE WEEK / YEAR FOR FIRST DRAW DATE
C
      CALL GETWEK(TRABUF(TWBEG), TRABUF(TGAM), WEEK, YEAR, FSTS)
C
C PUT FIRST OFFSET WEEK / YEAR IN OUTPUT MESSAGE
C
      OUTMSG(IDXMSG + 0) = WEEK
      OUTMSG(IDXMSG + 1) = YEAR - 2000
      IDXMSG = IDXMSG + 2
C
C CALCULATE OFFSET WEEK / YEAR FOR SECOND OFFSET CDC DATE
C
      CALL GETWEK(TRABUF(TWEND), TRABUF(TGAM), WEEK, YEAR, FSTS)
C
C PUT SECOND OFFSET WEEK / YEAR IN OUTPUT MESSAGE
C
      OUTMSG(IDXMSG + 0) = WEEK
      OUTMSG(IDXMSG + 1) = YEAR - 2000
      IDXMSG = IDXMSG + 2     
C
C THIS IS THE END TO PUT WEEK YEAR DRAWS IN OUTPUT MESSAGE
C
      END

