C
C SUBROUTINE REPROTRA
C
C REPROTRA.FOR
C
C V26 19-OCT-2016 SCML Fix. Replace special function reprocessing
C V25 01-APR-2016 SCML M16 PROJECT: reprocess EUR transactions
C                      Ignore EUR connection switches
C V24 21-MAR-2014 SCML Project Placard - added new trasaction type TIGS
C V23 31-MAR-2010 RXK Changes for ePassive
C V22 26-FEB-2001 UXN GLOBAL RFSS #189 for reprocessing instants.
C V21 27-DEC-2001 CS  ADDED PASSIVE GAME FOR PORTUGAL
C V20 22-SEP-2000 UXN TAGTINF added.
C V19 03-JUN-1999 UXN Fix for KIKREP.
C V18 14-MAY-1999 UXN Super Triple added.
C V17 01-FEB-1999 UXN VSCREEN command reprocessing removed.
C V16 28-JAN-1999 UXN Fix for fraction reprocessing
C V15 09-SEP-1998 RXK Kicker pool update added 
C V14 30-JAN-1997 HXK Fix for inappropriate use of AGTBTB instead of AGTHTB
C V13 12-JAN-1997 HXK Added Instant games
C V12 10-JUN-1996 HXK Fix for fraction reprocessing
C V11 17-MAY-1996 HXK Update from Wojtek, Siew Mun
C V10 10-NOV-1995 HXK Further changes for Double, Couple
C V09 04-AUG-1995 HXK Batch fix for RAVI v5 install
C V08 03-MAY-1995 HXK Changed UPDV65 call
C V07 15-OCT-1994 HXK Adding /developing Bingo (15.Oct.94)
C V06 16-NOV-1993 GXA Added Reprocessing of Opinion Poll transactions.
C V05 17-SEP-1993 GXA Added Restoring of the Second Kicker Number in Wager 
C                     Reprocessing
C V04 26-JUN-1993 GXA Released for Finland Dec Conversion / Oddset.
C                     Added Speden, Ravi, Fractioning, and updating of 
C                     screening files.
C V03 24-MAY-1992 HDB ADDED UPDSTA (STATISTICS)
C V02 01-NOV-1991 MTK INITAL RELEASE FOR NETHERLANDS
C V01 01-AUG-1990 XXX RELEASED FOR VAX
C
C
C SUBROUTINE TO REPROCESS 1 TRANSACTION
C FOR SYSTEM RESTART.
C
C
C
C CALLING SEQUENCE:
C     CALL REPROTRA(LBUF,LSTTIM,LSTTYP,EOF)
C     IN - TRABUF- TRANSACTION BODY IN LOG FORMAT
C         LSTTIM  - TIME OF LAST TRANSACTION
C         LSTTYP  - TYPE OF LAST TRANSACTION
C         EOF     - INCREMENTED IF EMPTY TRANSACTION, ZEROED IF USED
C
C
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C This item is the property of GTECH Corporation, Providence, Rhode
C Island, and contains confidential and trade secret information. It
C may not be transferred from the custody or control of GTECH except
C as authorized in writing by an officer of GTECH. Neither this item
C nor the information it contains may be used, transferred,
C reproduced, published, or disclosed, in whole or in part, and
C directly or indirectly, except as expressly authorized by an
C officer of GTECH, pursuant to written agreement.
C
C Copyright 1999 GTECH Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW/EXT
	SUBROUTINE REPROTRA(LBUF,LSTTIM,LSTTYP,EOF)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:DESTRA.DEF'
	INCLUDE 'INCLIB:AGTCOM.DEF'
	INCLUDE 'INCLIB:DESLOG.DEF'
	INCLUDE 'INCLIB:TASKID.DEF'
	INCLUDE 'INCLIB:LOGCOM.DEF'
	INCLUDE 'INCLIB:SLOCOM.DEF'
	INCLUDE 'INCLIB:POOLLTO.DEF'
	INCLUDE 'INCLIB:X2XPTL.DEF'
	INCLUDE 'INCLIB:X2STMES.DEF'
	INCLUDE 'INCLIB:X2FEMES.DEF'
	INCLUDE 'INCLIB:KIKCOM.DEF'
        INCLUDE 'INCLIB:BNGCOM.DEF'
C
C
	INTEGER*4 PASSOFFSET, ST
	INTEGER*4 TER, EOF, LSTTYP, LSTTIM, BETOFF
	INTEGER*4 MESS(EDLEN)
	INTEGER*4 LBUF(*)
	LOGICAL WARN
C
C
	CALL LOGTRA(TRABUF,LBUF)
	IF(TRABUF(TSTAT).EQ.NUSD) THEN
	  EOF=EOF+1
	  RETURN
	ELSE
	  EOF=0
	ENDIF
C
C CHECK CDC DATE
C
	IF(TRABUF(TCDC).NE.DAYCDC) THEN
	  CALL OPS('Tmf - Memory date discrepancy',TRABUF(TCDC),DAYCDC)
	  CALL TSKABORT(8HNETLOG  ,ST)
	  CALL TSKABORT(8HDCNPRO  ,ST)
	  CALL GSTOP(GEXIT_FATAL)
	ENDIF
C
C REPROCESS ALL GOOD TRANSACTIONS
C
	TER=TRABUF(TTER)
	IF(TER.GE.1.AND.TER.LE.NUMAGT.AND.TRABUF(TINTRA).EQ.0) THEN
	  AGTHTB(ATRNUM,TER)=TRABUF(TTRN)
	  AGTHTB(ACHKSM,TER)=-1
	ENDIF
	IF(TRABUF(TSTAT).EQ.VOID) TRABUF(TSTAT)=GOOD
	IF(TRABUF(TSTAT).EQ.INCA) TRABUF(TSTAT)=GOOD
	IF(TRABUF(TSTAT).EQ.XCHD) TRABUF(TSTAT)=GOOD
	IF(TRABUF(TSTAT).EQ.CASH) TRABUF(TSTAT)=GOOD
	IF(TRABUF(TSTAT).EQ.XCSH) TRABUF(TSTAT)=GOOD
	IF(TRABUF(TSTAT).EQ.CLAM) TRABUF(TSTAT)=GOOD
	IF(TRABUF(TSTAT).EQ.XCLM) TRABUF(TSTAT)=GOOD
	IF(TRABUF(TSTAT).EQ.FRAC) TRABUF(TSTAT)=GOOD
	LSTTIM=TRABUF(TTIM)
	LSTTYP=TRABUF(TTYP)
C
C UPDATE TRANSACTION COUNT AND PERFORMANCE DATA
C
	IF(NXTSER.GE.P(COMSER)) THEN
	  P(NXTTRA)=P(NXTTRA)+1
	  PERFRM(1,PERTRA)=PERFRM(1,PERTRA)+1
	  IF(TRABUF(TTYP).EQ.TWAG.AND.TRABUF(TGAM).GT.0)
     *	    PERFRM(1,TRABUF(TGAM))=PERFRM(1,TRABUF(TGAM))+1
	  IF(TRABUF(TTYP).EQ.TCAN)
     *	    PERFRM(1,PERCAN)=PERFRM(1,PERCAN)+1
	  IF(TRABUF(TTYP).EQ.TVAL)
     *	    PERFRM(1,PERVAL)=PERFRM(1,PERVAL)+1
	  IF(TRABUF(TTYP).EQ.TCRS)
     *	    PERFRM(1,PERINS)=PERFRM(1,PERINS)+1
	ENDIF

        IF( (TRABUF(TERR).EQ.NOER.OR.TRABUF(TERR).EQ.BCRS) .AND.
     *       TRABUF(TTYP).EQ.TCRS) THEN
           CALL UPDXRF(TRABUF(TIXRF))
	ENDIF
C
C----+---+-------------+------------------------------------------------
C V25|BEG| M16 PROJECT | UPDATE MSQ REFERENCE # OF EUROMILLIONS SYSTEM
C----+---+-------------+------------------------------------------------
        IF (TRABUF(TTYP) .EQ. TEUR) THEN
          CALL UPDEURXRF(TRABUF(TEUMESSQ))
        ELSEIF(TRABUF(TTYP).EQ.TSPE) THEN
          IF(TRABUF(TSFUN).EQ.TSREP) THEN                                       !SALES REPORTS
            IF(TRABUF(TSDT1).EQ.1.OR.TRABUF(TSDT1).EQ.2.OR.
     *         TRABUF(TSDT1).EQ.4.OR.TRABUF(TSDT1).EQ.8) THEN
              CALL UPDEURXRF(TRABUF(TSDT3))
            ENDIF
          ELSEIF(TRABUF(TSFUN).EQ.TGREP) THEN                                   !GAME RESULT REPORT
            IF(TRABUF(TSDT1).EQ.TEUM .OR.TRABUF(TSDT1).EQ.TRAF) THEN
              CALL UPDEURXRF(TRABUF(TSDT3))
            ENDIF
          ELSEIF(TRABUF(TSFUN).EQ.TNAP) THEN                                    !BILLING REPORT
            CALL UPDEURXRF(TRABUF(TSDT6))
          ENDIF
CV26          RETURN
        ENDIF
C----+---+-------------+------------------------------------------------
C V25|END| M16 PROJECT | UPDATE MSQ REFERENCE # OF EUROMILLIONS SYSMTEM
C----+---+-------------+------------------------------------------------
C
	IF(TRABUF(TSTAT).NE.GOOD) RETURN
C
C PROJECT EURO MIL - DO NOT REPROCESS EURO MIL TRANSACTIONS
C	
CV25        IF (TRABUF(TTYP) .EQ. TEUR) RETURN
        IF (TRABUF(TTYP) .EQ. TEUR) THEN
          CALL UPDEUR(TRABUF)
          RETURN
        ENDIF
C
C PROJECT PLACARD - DO NOT REPROCESS IGS TRANSACTIONS
C	
        IF (TRABUF(TTYP) .EQ. TIGS) THEN !V24
          IF (TRABUF(TSTAT) .EQ. GOOD) CALL UPDIGS(TRABUF)
          RETURN !V24
        ENDIF
C
C DO NOT REPROCESS ANY TERMINAL INQUIRE FOR
C PASSIVE TICKETS VALIDATION
C
        IF(TRABUF(TGAMTYP).EQ.TPAS.AND.TRABUF(TERR).EQ.VINQ) RETURN
C
C REPROCESS KICKER SEED HERE (FOR ALL WAGERS).WE DO NOT HAVE IT TO PASSIVE BUT
C KIKREP WILL TAKE CARE OF IT.
C
	IF(TRABUF(TTYP).EQ.TWAG) CALL KIKREP(TRABUF)
C
C
	GOTO (100,200,300,400,450,400,500,600,700) TRABUF(TTYP)
	CALL OPS('Invalid transaction type, ser',TRABUF(TTYP),TRABUF(TSER))
	RETURN
C
C REPROCESS WAGERS
C
100	CONTINUE
	IF(TRABUF(TWFFLG).NE.0) THEN
           LRCCNT(TRABUF(TGAM)) = LRCCNT(TRABUF(TGAM)) + TRABUF(TSIZE) 
           RETURN
	ENDIF
	IF((TRABUF(TSTAT).EQ.EXCH).AND.(TRABUF(TTYP).EQ.TWAG))
     *     LRCCNT(TRABUF(TGAM))=LRCCNT(TRABUF(TGAM))+TRABUF(TSIZE)
	IF(NXTSER.GE.P(COMSER)) THEN
	  AGTHTB(ACHKSM,TER)=TRABUF(TCHK)
	  AGTTAB(AGTLKN,TER)=TRABUF(TWKICK)
	  AGTTAB(AGTLKN2,TER)=TRABUF(TWKICK2)
          AGTTAB(AGTBSED,TER)=TRABUF(TWBSED)
          AGTTAB(AGTEPS,TER)=TRABUF(TWEPSD)
          IF(TRABUF(TGAMTYP).EQ.TPAS) THEN              
             CALL SNDTRA(TRABUF,PST)         !SENT TO PASPRO TASK  
             RETURN
          ENDIF
	  CALL UPDSUB(TRABUF)
  	  CALL UPDSTA(TRABUF)
	  IF(TRABUF(TGAMTYP).EQ.TSCR.OR.TRABUF(TGAMTYP).EQ.TWIT.OR.
     *       TRABUF(TGAMTYP).EQ.TDBL.OR.TRABUF(TGAMTYP).EQ.TCPL.OR.
     *       TRABUF(TGAMTYP).EQ.TSSC.OR.TRABUF(TGAMTYP).EQ.TTRP.OR.
     *       TRABUF(TGAMTYP).EQ.TTSL.OR.TRABUF(TGAMTYP).EQ.TSTR) 
     *       CALL UPDPOL(TRABUF)
	  IF(TRABUF(TGAMTYP).EQ.TNBR)
     *      CALL UPLIAB(TRABUF,.TRUE.,BETOFF,WARN)
          IF(TRABUF(TGAMTYP).EQ.TBNG) BNGSED(TRABUF(TGAMIND)) = TRABUF(TWBSED)
	ENDIF
	IF(NXTSER.GE.P(POLSER).AND.TRABUF(TGAMTYP).EQ.TLTO)
     *	   CALL UPDLPL(TRABUF,0,ST)
	IF(NXTSER.GE.P(POLSER).AND.TRABUF(TGAMTYP).EQ.TSPT)
     *	   CALL UPDSPT(TRABUF,0,ST)
	RETURN
C
C REPROCESS CANCELS AND DELETIONS
C
200	CONTINUE
300	CONTINUE
	IF(NXTSER.GE.P(COMSER)) THEN
          IF(TRABUF(TGAMTYP).EQ.TPAS) THEN              
             CALL SNDTRA(TRABUF,PST)         !SENT TO PASPRO TASK  
             CALL SNDTRA(TRABUF,RPC)
             RETURN
          ENDIF
	  CALL UPDSUB(TRABUF)
	  CALL UPDSTA(TRABUF)
          IF(TRABUF(TGAMTYP).EQ.TNBR)
     *       CALL UPLIAB(TRABUF,.TRUE.,BETOFF,WARN)
          IF(TRABUF(TGAMTYP).EQ.TSCR.OR.TRABUF(TGAMTYP).EQ.TWIT.OR.
     *       TRABUF(TGAMTYP).EQ.TDBL.OR.TRABUF(TGAMTYP).EQ.TCPL.OR.
     *       TRABUF(TGAMTYP).EQ.TSSC.OR.TRABUF(TGAMTYP).EQ.TTRP.OR.
     *       TRABUF(TGAMTYP).EQ.TTSL.OR.TRABUF(TGAMTYP).EQ.TSTR) 
     *       CALL UPDPOL(TRABUF)
	  CALL SNDTRA(TRABUF,RPC)
	ENDIF
	IF(NXTSER.GE.P(POLSER).AND.TRABUF(TGAMTYP).EQ.TLTO)
     *	   CALL UPDLPL(TRABUF,0,ST)
	IF(NXTSER.GE.P(POLSER).AND.TRABUF(TGAMTYP).EQ.TSPT)
     *	   CALL UPDSPT(TRABUF,0,ST)
	RETURN
C
C REPROCESS VALIDATIONS / REFUNDS
C
400	CONTINUE
	IF(NXTSER.LT.P(COMSER)) RETURN
	CALL UPDSUB(TRABUF)

        IF  (TRABUF(TGAMTYP).EQ.TPAS) THEN
            CALL SNDTRA(TRABUF,PSV)         !SENT TO PASVAL TASK
        ELSE
            CALL SNDTRA(TRABUF,VAL)
        ENDIF

	RETURN
C
C REPROCESS PPASSIVE RETURNS
C
450     CONTINUE
	IF(NXTSER.LT.P(COMSER)) RETURN
        IF(TRABUF(TGAMTYP).EQ.TPAS) THEN
           CALL SNDTRA(TRABUF,PST)         !SENT TO PASPRO TASK
        ENDIF
        RETURN 
C
C REPROCESS SPECIAL FUNCTIONS
C
500	CONTINUE
	TER=TRABUF(TTER)
	IF(NXTSER.LT.P(COMSER)) RETURN
	IF(TRABUF(TSFUN).EQ.TSON) THEN
	  AGTTAB(AGTSC1,TER)=TRABUF(TSNEW)
	  AGTTAB(AGTSC2,TER)=TRABUF(TSOLD)
	  AGTHTB(ASONCT,TER)=AGTHTB(ASONCT,TER)+1
	  AGTHTB(AOPSTS,TER)=SIGNON
	  AGTTAB(AGTOCL,TER)=AGTTAB(AGTNCL,TER)
	  AGTTAB(AGTNCL,TER)=TRABUF(TSSGN)
	  AGTHTB(AINRPT,TER)=0
	  IF(P(CLRKACT).EQ.0) THEN
	    PASSOFFSET=TRABUF(TSSGN)-1
	    AGTHTB(AGTPASOFF,TER)=TRABUF(TSSGN)
	    CALL ENCINI1(AGTTAB(APSNUM+PASSOFFSET,TER),TER)
	    CALL REPCLERK(TRABUF(TSER),TER,AGTTAB(AGTOCL,TER),
     *	                   AGTTAB(AGTNCL,TER))
	  ENDIF
	ENDIF
C
C
	IF(TRABUF(TSFUN).EQ.TSOFF) THEN
	   AGTHTB(AOPSTS,TER)=SIGNOF
	ENDIF
	IF(TRABUF(TSFUN).EQ.THASF)   CALL SNDTRA(TRABUF,RPC)
	IF(TRABUF(TSFUN).EQ.TAGTINF) CALL SNDTRA(TRABUF,RPC)
	IF(TRABUF(TSFUN).EQ.TUNFRC) CALL SNDTRA(TRABUF,RPC)
	IF(TRABUF(TSFUN).EQ.TFRC)   CALL SNDTRA(TRABUF,RPC)
C
	IF(TRABUF(TSFUN).EQ.TSX2X) THEN
	   P(X2XIDX)=TRABUF(TXIDX)       !LAST USED INDEX INTO X2X FILE
	   RETURN
	ENDIF
C
C REPROCESS COM ERROR TRANSACTIONS
C
	IF(TRABUF(TSFUN).EQ.TSLOW) THEN
	  IF(TRABUF(TSNEW).EQ.1) CALL BCLR(SLOBIT,TRABUF(TTER))
	  IF(TRABUF(TSNEW).EQ.2) CALL BSET(SLOBIT,TRABUF(TTER))
	ENDIF
C
C REPROCESS OPINION POLLS
C
	IF(TRABUF(TSFUN).EQ.TPOLL) THEN
	   KIKSED(1,1) = TRABUF(TSDT1)
	ENDIF
C
C REPROCESS MISCELLANEOUS TRANSACTIONS
C
	CALL UPDMIS(TRABUF)
C
	RETURN
C
C REPROCESS COMMANDS
C
600	CONTINUE
	IF(NXTSER.LT.P(COMSER)) RETURN
	IF(TRABUF(TCMTYP).EQ.TCGEN.AND.     !IGNORE CHECKPOINT
     *	   TRABUF(TCMNUM).EQ.1) RETURN
	IF(TRABUF(TCMTYP).EQ.TCPAR.AND.     !IGNORE TAPE SWITCH
     *	   TRABUF(TCMNUM).EQ.TAPESW) RETURN
	IF(TRABUF(TCMTYP).EQ.TCSPE.AND.     !IGNORE BROADCASTS
     *	   TRABUF(TCMNUM).EQ.5) RETURN
	IF(TRABUF(TCMTYP).EQ.TCNET.AND.     !IGNORE BACKUP ID COMMANDS
     *	   TRABUF(TCMNUM).EQ.3) RETURN
	IF(TRABUF(TCMTYP).EQ.TCNET.AND.     !IGNORE SET MASTER COMMANDS
     *	   TRABUF(TCMNUM).EQ.7) RETURN
	IF(TRABUF(TCMTYP).EQ.TCSPE.AND.     !IGNORE CONTROL BROADCASTS
     *	   TRABUF(TCMNUM).EQ.6) RETURN
        IF(TRABUF(TCMTYP).EQ.TCPAR.AND.     !IGNORE STRATUS SWITCHES
     *     TRABUF(TCMNUM).EQ.PRMSTR) RETURN
	IF(TRABUF(TCMTYP).EQ.TCX2X.AND.     !SKIP X2X GAME STATE CHANGE
     *	   TRABUF(TCMNUM).EQ.1.AND.
     *	   TRABUF(TCMDT1).EQ.XGBL.AND.
     *	   TRABUF(TCMDT2).EQ.22) RETURN
C----+-----------------------------------------------------------------
C V24| Adding support for IGS - Placard
C----+------------------------------------------------------------------
        IF(TRABUF(TCMTYP).EQ.TCPAR.AND.     !IGNORE IGS Connection SWITCHES
     *     TRABUF(TCMNUM).EQ.IGSCONF) RETURN
C----+-----------------------------------------------------------------
C V24| Adding support for IGS - Placard
C----+------------------------------------------------------------------
C
C----+---+-------------+------------------------------------------------
C V25|BEG| M16 PROJECT | IGNORE EUR Connection SWITCHES
C----+---+-------------+------------------------------------------------
        IF(TRABUF(TCMTYP).EQ.TCPAR.AND.
     *     TRABUF(TCMNUM).EQ.EUMILF) RETURN
C----+---+-------------+------------------------------------------------
C V25|END| M16 PROJECT | IGNORE EUR Connection SWITCHES
C----+---+-------------+------------------------------------------------
C
	CALL CMDROU(TRABUF,MESS)
	RETURN
C
C REPROCESS CROSS SYSTEMS
C
700     CONTINUE
        IF(NXTSER.GE.P(COMSER)) THEN
          IF(TRABUF(TITYP).EQ.ISON) THEN
            AGTHTB(ASONCT,TER)=AGTHTB(ASONCT,TER)+1
            AGTHTB(AOPSTS,TER)=SIGNON
            AGTTAB(AGTOCL,TER)=AGTTAB(AGTNCL,TER)
            AGTTAB(AGTNCL,TER)=TRABUF(TISGN)
            IF(AGTHTB(AGTPASCDC,TER).LE.0) AGTHTB(AGTPASCDC,TER)=DAYCDC
            IF(AGTHTB(AGTCDC,TER).EQ.0) THEN
               AGTHTB(AGTCDC,TER)=DAYCDC
               IF(TSBIT(AGTTAB(AGTTYP,TER),AGTISF).NE.0)
     *            GVTS_INSTALLED = GVTS_INSTALLED + 1
            ENDIF
            PASSOFFSET=TRABUF(TISGN)-1
            AGTHTB(AGTPASOFF,TER)=TRABUF(TISGN)
            CALL ENCINI1(AGTTAB(APSNUM+PASSOFFSET,TER),TER)
            IF(P(CLRKACT).EQ.0) THEN
              CALL REPCLERK(TRABUF(TSER),TER,AGTTAB(AGTOCL,TER),
     *                      AGTTAB(AGTNCL,TER))
            ENDIF
          ENDIF
C
          IF(TRABUF(TITYP).EQ.ISOF) THEN
             AGTHTB(AOPSTS,TER)=SIGNOF
          ENDIF
C
C DJO - REMOVED THE UPDATE OF THE 'AGTCDC' VARIABLE FOR THE ESTABLISHMENT
C       MESSAGE BECAUSE NOW IT IS DONE IN THE SIGN-ON HANDLER.
C
          IF(TRABUF(TITYP).EQ.IEST) THEN
             AGTTAB(AGTROM,TER) = TRABUF(TISFT)
CCC          AGTHTB(AGTCDC,TER)=DAYCDC
          ENDIF
C
          IF(TRABUF(TITYP).EQ.IFIN.AND.TRABUF(TRTYP).EQ.9) THEN  !INVOICE REPORT
            CALL BCLR(AGTBTB(AGTPAR,TER),AGTRINV)
          ENDIF
C
          CALL UPDSUB(TRABUF)
        ENDIF
	RETURN
C
903	FORMAT(1X,'*   Invalid transaction type ',I4,' ser ',I9,' *')
	END
