C
C     FILE   : SALVALINS.FOR
C     AUTHOR : J.H.R
C     VERSION: 01            DATE: 08 / 05 / 2001
C
C V01 JHR INITIAL RELEASE FOR PORTUGAL PROJECT
C
C SALES VALIDATION FOR INSTANT GAME ( IPS -  VALIDATIONS )
C
C     **************************************************************************
C
C        THIS ITEM IS THE PROPERTY OF GTECH CORPORATION, POVIDENCE, RHODE
C     ISLAND, AND CONTAINS CONFIDENTIAL AND TRADE SECRET INFORMATION. IT MAY
C     NOT BE TRANSFERRED FROM THE CUSTODY OR CONTROL OF GTECH EXCEPT AS AUTO -
C     RIZED IN WRITING BY AN OFFICER OF GTECH. NEITHER THIS ITEM NOR THE
C     INFORMATION IT CONTAINS MAY BE USED, TRANSFERRED, REPRODUCED, PUBLISHED
C     OR DISCLOSED, IN WHOLE OR IN PART, AND DIRECTLY OR INDIRECTLY, EXCEPT AS
C     EXPRESSLY AUTHORIZED BY AN OFFICER OR GTECH, PURSUANT TO WRITTEN AGREEMENT
C
C     Copyright 2000 GTECH Corporation. All Rigth Reserved
C
C     **************************************************************************
C
C
C THIS PROCEDURE CALCULATE TOTAL INSTANT VALIDATIONS ( IPS VALIDATIONS )
C
C=======OPTIONS /CHECK = NOOVERFLOW /EXT
      SUBROUTINE SALVALINS(SALES, SALIND, RTER, SUBCLASS, MANAGER)
      IMPLICIT NONE
C
C INCLUDES DEFINITION TO CALCULATE INSTANT VALIDATIONS
C
        INCLUDE 'INCLIB:SYSPARAM.DEF'
        INCLUDE 'INCLIB:SYSEXTRN.DEF'
        INCLUDE 'INCLIB:GLOBAL.DEF'
        INCLUDE 'INCLIB:AGTINF.DEF'
        INCLUDE 'INCLIB:AGTCOM.DEF'
        INCLUDE 'INCLIB:SPECOM.DEF'
C
C PARAMETERES DEFINITION TO CALCULATE INSTANT VALIDATIONS
C
      INTEGER * 4 SALES(*)           ! SALES ARRAY FOR ALL INFORMATION
      INTEGER * 4 SALIND             ! INSTANT POSITION IN SALES ARRAY
      INTEGER * 4 RTER               ! REQUEST TERMINAL
      INTEGER * 4 SUBCLASS           ! SUBCLASS ( REPORT TYPE )
C
      LOGICAL MANAGER                ! MANAGER FLAG
C
C VARIABLES DEFINITION TO TO CALCULATE INSTANT VALIDATIONS
C
      INTEGER * 4 CLRKNUM            ! NUMBER OF CLERK COUNTER
      INTEGER * 4 DAY                ! DAY OF THE WEEK
C
C IF REPORT TYPE IT'S ASKING FOR ONE DAY OF THE WEEK GOTO SPECIFIC DAY
C
      IF(SUBCLASS .NE. 0 .AND. SUBCLASS .NE. 8) GOTO 1000
C
C CALCULATE CLERK NUMBER POSITION ( FOR TODAY OR WEEKLY REPORT )
C
      CLRKNUM = AGTHTB(AGTPASOFF, RTER)
      IF(CLRKNUM .LE. 0) CLRKNUM = 1
C
C CALCULATE VALIDATIONS COUNT / VALIDATIONS AMOUNT
C
      SALES(SALIND + 0) = SALES(SALIND + 0) + AGTMIS(CLRKNUM, 1, RTER)
      SALES(SALIND + 1) = SALES(SALIND + 1) + AGTMIS(CLRKNUM, 2, RTER)
C
C GET VALIDATIONS FOR WEEKLY REPORT
C
1000  CONTINUE
C
C CALCULATE VALIDATIONS COUNT / AMOUNT FROM PREVIOUS DAYS ( NOT FOR TODAY )
C
      IF(MANAGER) THEN
        DO CLRKNUM = 2, 8
          SALES(SALIND + 0) = SALES(SALIND + 0) + CLRKMIS(CLRKNUM, 1, CLRKNUM)
          SALES(SALIND + 1) = SALES(SALIND + 1) + CLRKMIS(CLRKNUM, 2, CLRKNUM)
        ENDDO
       ENDIF

C
C IF NOT WEELY REPORT GOTO DAY REPORT
C
      IF(SUBCLASS .NE. 8) GOTO 2000
C
C CALCULATE VALIDATONS FOR WEELY REPORT
C
      DO 10000 DAY = 1, 9
        IF(ASFDAT(ASFCDC, DAY) .LE. ASFINV(ASFEND,1)) GOTO 10000
        DO CLRKNUM = 1, NUMCLERK
          IF(AGTTAB((APSNUM + CLRKNUM) - 1, RTER) .EQ. 0) GOTO 100
          SALES(SALIND + 0) = SALES(SALIND + 0) + ASFMIS(CLRKNUM, 1, DAY)
          SALES(SALIND + 1) = SALES(SALIND + 1) + ASFMIS(CLRKNUM, 2, DAY)
100       CONTINUE
        ENDDO
10000 CONTINUE
C
C GET VALIDATION FOR SPECIFIC DAY REPORT ( IF NOT SPECIFIC DAY RETURN )
C
2000  CONTINUE
      IF(SUBCLASS .LE. 0 .OR. SUBCLASS .GE. 8) RETURN
C
C GET VALIDATIONS COUNTS / AMOUNT FOR SPECIFIC DAY
C
      DO DAY = 1, 9
        IF(ASFDAT(ASFDOW, DAY) .EQ. SUBCLASS) GOTO 11000
      ENDDO
11000 CONTINUE
      DO CLRKNUM = 1, NUMCLERK
        IF(AGTTAB((APSNUM + CLRKNUM) - 1, RTER) .EQ. 0) GOTO 200
        SALES(SALIND + 0) = SALES(SALIND + 0) + ASFMIS(CLRKNUM, 1, DAY)
        SALES(SALIND + 1) = SALES(SALIND + 1) + ASFMIS(CLRKNUM, 2, DAY)
200     CONTINUE
      ENDDO
C
C THIS IS THE END TO CALCULATE INSTANT VALIDATIONS
C
      END

