C
C SUBROUTINE SAVSYS
C $Log:   GXAFXT:[GOLS]SAVSYS.FOV  $
C  
C     Rev 1.0   17 Apr 1996 14:50:52   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 17:34:00   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - sptsys.for **
C
C
C
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE SAVSYS(SYS,STYP,TRI,DBL,SGL,ROWS,BROWS,ROWTAB,ST)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:RECSSF.DEF'
C
	INTEGER*4 J, I, IND, ST, BROWS, ROWS, SGL, DBL, TRI, STYP, SYS
	INTEGER*4 ROWTAB(SPGNBR,1296)
	COMMON /SCOMON/SSFREC
C
C
	ST=0
	IND=SSFFPT
	IF(IND.EQ.0) IND=1
	SSFATR(SYS)=STYP
	SSFNUM(4,SYS)=BROWS
	IF(STYP.EQ.FULSYS) RETURN
	SSFPTR(SYS)=IND
	SSFNUM(1,SYS)=1
	SSFNUM(2,SYS)=SSFNUM(1,SYS)+TRI
	SSFNUM(3,SYS)=SSFNUM(2,SYS)+DBL
	SSFNUM(5,SYS)=SGL
	SSFTAB(IND)=ROWS
	IND=IND+1
	IF(IND.GT.SFTABMAX) GOTO 200
C
C
	DO 100 I=1,ROWS
	DO 100 J=1,BROWS
	SSFTAB(IND)=ROWTAB(J,I)
	IND=IND+1
	IF(IND.GT.SFTABMAX) GOTO 200
100	CONTINUE
C
C
	SSFFPT=IND
	RETURN
C
C
200	CONTINUE
	ST=-1
	TYPE*,'System table full - system definition not saved'
	CALL XWAIT(2,2,ST)
	RETURN
	END
