C
C SUBROUTINE SCANLIST
C $Log:   GXAFXT:[GOLS]SCANLIST.FOV  $
C  
C     Rev 1.0   17 Apr 1996 14:51:28   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 17:34:26   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - checklist.for **
C
C
C
	SUBROUTINE SCANLIST(QNUM, LIST, BUFCHK)
	IMPLICIT NONE
C
	INCLUDE	'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:PROCOM.DEF'
	INCLUDE 'INCLIB:GLIST.DEF'
C
	INTEGER*4   QNUM
	INTEGER*4   LIST(*)
	INTEGER*4   BUFCHK(NUMPRO)
C
	INTEGER*4   BUF,XTOP,XBOT
C
C
	IF(LIST(GLIST_MAX_OFFSET).NE.NUMPRO+GLIST_START)THEN
	  TYPE *,'QUE ' ,QNUM,' MAX OFFSET = ',LIST(GLIST_MAX_OFFSET)
	ENDIF
C
	XTOP = LIST(GLIST_TOP)
	XBOT = LIST(GLIST_BOT)
1000	CONTINUE
	IF(XTOP.EQ.XBOT)GOTO 9000
C
	XTOP = XTOP+1
	IF(XTOP .GT. LIST(GLIST_MAX_OFFSET))THEN
	  XTOP = GLIST_START
	ENDIF
C
	BUF  = LIST(XTOP)
	IF(BUF.LT.1 .OR. BUF.GT.NUMPRO)THEN
	  TYPE *,'QUE ',QNUM,' BUFFER = ',BUF
	ELSE
	  IF(BUFCHK(BUF).NE.0)THEN
	    TYPE *,'QUE ',QNUM,' BUFFER ',BUF,' ALREADY IN QUE ',
     *             BUFCHK(BUF)
	  ELSE
	    BUFCHK(BUF) = QNUM
	  ENDIF
	ENDIF
	GOTO 1000
C
9000	CONTINUE
	RETURN
	END
