C
C SUBROUTINE SENDBUF
C $Log:   GXAFXT:[GOLS]SENDBUF.FOV  $
C  
C     Rev 1.0   17 Apr 1996 14:54:14   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 17:35:48   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - net_wnet.for;1 **
C
C
C     SEND BUFFER
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE SENDBUF(BUF)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:DESNET.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:TASKID.DEF'
	INTEGER*4 STATUS, LINK, BUF
	INTEGER*4 ID/2000000/
C
C MARK END OF LIST
C
	IF(BUF.EQ.0) RETURN
	IF (NETBUF(NEXT,BUF).EQ.HDRSIZ+1) RETURN !NOTHING IN THE BUF
	LINK=NETBUF(NEXT,BUF)
	NETBUF(LINK,BUF)=0
	NETBUF(PPORG,BUF)=NODEID
	NETBUF(PDEST,BUF)=0
	NETBUF(FDEST,BUF)=0
	NETBUF(MODE,BUF)=TRNMD
	NETBUF(BUFTYP,BUF)=INP
	NETBUF(WAYNR,BUF)=WAYINP
C
C INSERT INTO EXECUTE QUEUE
C
C     CALCULATE CRC - JUST FOR CHECKING
C
	NETBUF(USEID,BUF)=ID+NODEID*10000000
	ID=ID+1
	CALL ABL(BUF,NETEXEC(1,WAYINP),STATUS)
C
	BUF=0              !RESET BUF NR
	RETURN
	END
