C SHCOMMON.FOR
C
C V09 17-MAR-2016 SCML M16 PROJECT: EURCOM added.
C V08 05-JAN-2001 CS  PASCOM added.
C V07 01-DEC-2000 UXN TGLCOM ADDED.
C V06 05-JAN-2000 OXK SSOCOM added.
C V05 26-NOV-1999 OXK TSPCOM added.
C V04 13-OCT-1999 RXK WRLCOM added.
C V03 13-MAY-1999 UXN STRCOM,STROCOM ADDED.
C V02 03-AUG-1998 RXK Added KIPCOM
C V01 01-JUN-1994 PXN INITIAL RELEASE FOR ICELAND DEC
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C This item is the property of GTECH Corporation, Providence, Rhode
C Island, and contains confidential and trade secret information. It
C may not be transferred from the custody or control of GTECH except
C as authorized in writing by an officer of GTECH. Neither this item
C nor the information it contains may be used, transferred,
C reproduced, published, or disclosed, in whole or in part, and
C directly or indirectly, except as expressly authorized by an
C officer of GTECH, pursuant to written agreement.
C
C Copyright 2000 GTECH Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++C
C
C=======OPTIONS /CHECK=NOOVERFLOW
        PROGRAM SHCOMMON
        IMPLICIT NONE
C
        INCLUDE 'INCLIB:SYSPARAM.DEF'
        INCLUDE 'INCLIB:SYSEXTRN.DEF'
C
        INCLUDE 'INCLIB:MSGCOM.DEF'
        INCLUDE 'INCLIB:PROCOM.DEF'
        INCLUDE 'INCLIB:CHKPNT.DEF'
C
        INCLUDE 'INCLIB:LTOCOM.DEF'
        INCLUDE 'INCLIB:SPTCOM.DEF'
C        INCLUDE 'INCLIB:NBRCOM.DEF'
        INCLUDE 'INCLIB:WITCOM.DEF'
        INCLUDE 'INCLIB:TGLCOM.DEF'
        INCLUDE 'INCLIB:SCRCOM.DEF'
        INCLUDE 'INCLIB:TSLCOM.DEF'
        INCLUDE 'INCLIB:KIKCOM.DEF'
        INCLUDE 'INCLIB:BNGCOM.DEF'
        INCLUDE 'INCLIB:DBLCOM.DEF'
        INCLUDE 'INCLIB:CPLCOM.DEF'
        INCLUDE 'INCLIB:PASCOM.DEF'
C
        INCLUDE 'INCLIB:AGTCOM.DEF'
        INCLUDE 'INCLIB:CONCOM.DEF'
        INCLUDE 'INCLIB:SLOCOM.DEF'
C        INCLUDE 'INCLIB:POLCOM.DEF'
        INCLUDE 'INCLIB:POOLLTO.DEF'
        INCLUDE 'INCLIB:CHKCOM.DEF'
        INCLUDE 'INCLIB:TASKID.DEF'
        INCLUDE 'INCLIB:CTLCOM.DEF'
        INCLUDE 'INCLIB:DESNET.DEF'
        INCLUDE 'INCLIB:X2XCOM.DEF'
        INCLUDE 'INCLIB:SLOCOM1.DEF'
        INCLUDE 'INCLIB:X2FCOM.DEF'
        INCLUDE 'INCLIB:X2NETCOM.DEF'
        INCLUDE 'INCLIB:X2XREL.DEF'
        INCLUDE 'INCLIB:STACOM.DEF'
        INCLUDE 'INCLIB:SSCCOM.DEF'
        INCLUDE 'INCLIB:SSPCOM.DEF'
        INCLUDE 'INCLIB:TRPCOM.DEF'
        INCLUDE 'INCLIB:TROCOM.DEF'
        INCLUDE 'INCLIB:STRCOM.DEF'
        INCLUDE 'INCLIB:STROCOM.DEF'
        INCLUDE 'INCLIB:HASHMEM.DEF'
        INCLUDE 'INCLIB:SSOCOM.DEF'
C
C
        INTEGER*4 IND
        INTEGER*4 LAST,FIRST,NUMBYTES,NUMBER_OF_CSB
C
        CALL COPYRITE()
        TYPE*,IAM()
        TYPE*,IAM(),'<<<<< SHCOMMON >>>>>>'
        TYPE*,IAM()
C
C CHECKPOINT CONCOM
C
        IND=2
        IND=IND+CONCSB	
        TYPE*,IAM(),' CONCOM ',CONCSB,CONCSB*8,CONCSB*16
C
C CHECKPOINT AGENT COMMON
C
C
        IND=IND+AGTCSB
        TYPE*,IAM(),' AGTCOM ',AGTCSB,AGTCSB*8,AGTCSB*16
C
C CHECKPOINT SLOCOM
C
C====== IND=IND+SLOCSB	!CHECKPOINT SLOCOM
C====== TYPE*,IAM(),' SLOCOM ',SLOCSB,SLOCSB*8,SLOCSB*16
C
C CHECKPOINT LTOCOM
C
        IND=IND+LTOCSB	!CHECKPOINT LTOCOM
        TYPE*,IAM(),' LTOCOM ',LTOCSB,LTOCSB*8,LTOCSB*16
C
C CHECKPOINT SPTCOM
C
        IND=IND+SPTCSB	!CHECKPOINT SPTCOM
        TYPE*,IAM(),' SPTCOM ',SPTCSB,SPTCSB*8,SPTCSB*16
C
C CHECKPOINT TGLCOM
C
        IND=IND+TGLCSB	!CHECKPOINT TGLCOM
        TYPE*,IAM(),' TGLCOM ',TGLCSB,TGLCSB*8,TGLCSB*16
C
C CHECKPOINT KIKCOM
C
        IND=IND+KIKCSB	!CHECKPOINT KIKCOM
        TYPE*,IAM(),' KIKCOM ',KIKCSB,KIKCSB*8,KIKCSB*16
C
C CHECKPOINT NBRCOM
C
C	IND=IND+NBRCSB	!CHECKPOINT NBRCOM
C	TYPE*,IAM(),' NBRCOM ',NBRCSB,NBRCSB*8,NBRCSB*16
C
C CHECKPOINT SCRCOM
C
C====== IND=IND+SCRCSB	!CHECKPOINT SCRCOM
C====== TYPE*,IAM(),' SCRCOM ',SCRCSB,SCRCSB*8,SCRCSB*16
C
C CHECKPOINT WITCOM
C
C====== IND=IND+WITCSB	!CHECKPOINT WITCOM
C====== TYPE*,IAM(),' WITCOM ',WITCSB,WITCSB*8,WITCSB*16
C
C CHECKPOINT TSLCOM
C
C====== IND=IND+TSLCSB	!CHECKPOINT TSLCOM
C====== TYPE*,IAM(),' TSLCOM ',TSLCSB,TSLCSB*8,TSLCSB*16
C
C CHECKPOINT BNGCOM
C
C====== IND=IND+BNGCSB	!CHECKPOINT BNGCOM
C====== TYPE*,IAM(),' BNGCOM ',BNGCSB,BNGCSB*8,BNGCSB*16
C
C CHECKPOINT DBLCOM
C
C====== IND=IND+DBLCSB	!CHECKPOINT DBLCOM
C====== TYPE*,IAM(),' DBLCOM ',DBLCSB,DBLCSB*8,DBLCSB*16
C
C CHECKPOINT CPLCOM
C
C====== IND=IND+CPLCSB	!CHECKPOINT CPLCOM
C====== TYPE*,IAM(),' CPLCOM ',CPLCSB,CPLCSB*8,CPLCSB*16
C
C CHECKPOINT POLCOM
C
C	IND=IND+POLCSB	!CHECKPOINT POLCOM
C	TYPE*,IAM(),' POLCOM ',POLCSB,POLCSB*8,POLCSB*16
C
C CHECKPOINT SSCCOM
C
C====== IND=IND+SSCCSB	!CHECKPOINT SSCCOM
C====== TYPE*,IAM(),' SSCCOM ',SSCCSB,SSCCSB*8,SSCCSB*16
C
C CHECKPOINT SSPCOM
C
C====== IND=IND+SSPCSB	!CHECKPOINT SSPCOM
C====== TYPE*,IAM(),' SSPCOM ',SSPCSB,SSPCSB*8,SSPCSB*16
C
C CHECKPOINT TRPCOM
C
C====== IND=IND+TRPCSB	!CHECKPOINT TRPCOM
C====== TYPE*,IAM(),' TRPCOM ',TRPCSB,TRPCSB*8,TRPCSB*16
C
C CHECKPOINT TROCOM
C
C====== IND=IND+TROCSB	!CHECKPOINT TROCOM
C====== TYPE*,IAM(),' TROCOM ',TROCSB,TROCSB*8,TROCSB*16
C
C CHECKPOINT STACOM
C
C====== IND=IND+STACSB	!CHECKPOINT STACOM
C====== TYPE*,IAM(),' STACOM ',STACSB,STACSB*8,STACSB*16
C
C CHECKPOINT STRCOM
C
C====== IND=IND+STRCSB	!CHECKPOINT STRCOM
C====== TYPE*,IAM(),' STRCOM ',STRCSB,STRCSB*8,STRCSB*16
C
C CHECKPOINT STROCOM
C
C====== IND=IND+STROCSB	!CHECKPOINT STROCOM
C====== TYPE*,IAM(),' STROCOM',STROCSB,STROCSB*8,STROCSB*16
C
C CHECKPOINT TSPCOM
C
C====== IND=IND+TSPCSB	!CHECKPOINT TSPCOM
C====== TYPE*,IAM(),' TSPCOM',TSPCSB,TSPCSB*8,TSPCSB*16
C
C CHECKPOINT SSOCOM
C
C====== IND=IND+SSOCOMCSB	!CHECKPOINT SSOCOM
C====== TYPE*,IAM(),' SSOCOM ',SSOCOMCSB,SSOCOMCSB*8,SSOCOMCSB*16

C THE FOLLOWING CALCULATES PASCOM PASCSB DEFINITION
C
        LAST=%LOC(LAST_PASCOM_ELEMENT)+4
        FIRST=%LOC(FRST_PASCOM)
        NUMBYTES=(LAST-FIRST)
        NUMBER_OF_CSB=((NUMBYTES-1)/8192)+1       !NUMBER OF 2K WORDS
        IF (NUMBER_OF_CSB.NE.PASCSB) TYPE*,IAM(),' PASCOM ',PASCSB,' defined but should be: '
C
C CHECKPOINT PASCOM
C
        IND=IND+NUMBER_OF_CSB   !CHECKPOINT PASCOM
        TYPE*,IAM(),' PASCOM ',NUMBER_OF_CSB,NUMBER_OF_CSB*8,NUMBER_OF_CSB*16
C
C
        IND = IND - 1
        TYPE*,IAM(),' ==========================================='
        TYPE*,IAM(),' TOTAL  ',IND,IND*8,IND*16
        TYPE*,IAM(),' '
        TYPE*,IAM(),' CHKCOM ',IND+1,(IND+1)*8,(IND+1)*16
        TYPE*,IAM(),' CHKCSB ',CHKCSB,CHKCSB*8,CHKCSB*16
        TYPE*,IAM(),' '
        TYPE*,IAM(),' '
C
        CALL DISIMG()
C
        END
C
C
C
C=======OPTIONS /CHECK=NOOVERFLOW
        SUBROUTINE DISIMG
        IMPLICIT NONE
C
        INCLUDE 'INCLIB:SYSPARAM.DEF'
        INCLUDE 'INCLIB:SYSEXTRN.DEF'
CPXN        INCLUDE 'INCLIB:GLOBAL.DEF'
        INCLUDE 'INCLIB:MSGCOM.DEF'
        INCLUDE 'INCLIB:PROCOM.DEF'
        INCLUDE 'INCLIB:CHKPNT.DEF'
C
        INCLUDE 'INCLIB:LTOCOM.DEF'
C        INCLUDE 'INCLIB:NBRCOM.DEF'
        INCLUDE 'INCLIB:WITCOM.DEF'
        INCLUDE 'INCLIB:SCRCOM.DEF'
        INCLUDE 'INCLIB:TSLCOM.DEF'
        INCLUDE 'INCLIB:KIKCOM.DEF'
        INCLUDE 'INCLIB:BNGCOM.DEF'
        INCLUDE 'INCLIB:DBLCOM.DEF'
        INCLUDE 'INCLIB:CPLCOM.DEF'
        INCLUDE 'INCLIB:PASCOM.DEF'
C
        INCLUDE 'INCLIB:AGTCOM.DEF'
        INCLUDE 'INCLIB:CONCOM.DEF'
        INCLUDE 'INCLIB:SLOCOM.DEF'
        INCLUDE 'INCLIB:SPTCOM.DEF'
        INCLUDE 'INCLIB:TGLCOM.DEF'
C        INCLUDE 'INCLIB:POLCOM.DEF'
        INCLUDE 'INCLIB:POOLLTO.DEF'
        INCLUDE 'INCLIB:LTOPOL.DEF'
        INCLUDE 'INCLIB:CHKCOM.DEF'
        INCLUDE 'INCLIB:CTLCOM.DEF'
        INCLUDE 'INCLIB:DESNET.DEF'
        INCLUDE 'INCLIB:ENCCOM.DEF'
        INCLUDE 'INCLIB:LANCOM.DEF'
        INCLUDE 'INCLIB:LOGCOM.DEF'
        INCLUDE 'INCLIB:LSYSCOM.DEF'
        INCLUDE 'INCLIB:STACOM.DEF'
        INCLUDE 'INCLIB:QUECOM.DEF'
        INCLUDE 'INCLIB:X2XCOM.DEF'
        INCLUDE 'INCLIB:SLOCOM1.DEF'
        INCLUDE 'INCLIB:X2FCOM.DEF'
        INCLUDE 'INCLIB:X2NETCOM.DEF'
        INCLUDE 'INCLIB:X2XREL.DEF'
        INCLUDE 'INCLIB:HASHMEM.DEF'
C
        INCLUDE 'INCLIB:APUCOM.DEF'
        INCLUDE 'INCLIB:CRSCOM.DEF'
        INCLUDE 'INCLIB:SSCCOM.DEF'
        INCLUDE 'INCLIB:SSPCOM.DEF'
        INCLUDE 'INCLIB:TRPCOM.DEF'
        INCLUDE 'INCLIB:TROCOM.DEF'
        INCLUDE 'INCLIB:SSOCOM.DEF'
C
        INCLUDE 'INCLIB:EURCOM.DEF'                                             !V09
C
C
        CALL SHOWPAGES('AGTCOM  ', FRST_AGTCOM, LAST_AGTCOM,AGTCSB)
C
        CALL SHOWPAGES('BNGCOM  ', FRST_BNGCOM, LAST_BNGCOM,BNGCSB)
C
        CALL SHOWPAGES('CHKCOM  ', FRST_CHKCOM, LAST_CHKCOM,CHKCSB)
        CALL SHOWPAGES('CTLCOM  ', FRST_CTLCOM, LAST_CTLCOM,-1)
        CALL SHOWPAGES('CPLCOM  ', FRST_CPLCOM, LAST_CPLCOM,CPLCSB)
        CALL SHOWPAGES('CHKPNT  ', FRST_CHKPNT, LAST_CHKPNT,-1)
        CALL SHOWPAGES('CONCOM  ', FRST_CONCOM, LAST_CONCOM,CONCSB)
C
        CALL SHOWPAGES('DBLCOM  ', FRST_DBLCOM, LAST_DBLCOM,DBLCSB)
C
        CALL SHOWPAGES('ENCCOM  ', FRST_ENCCOM, LAST_ENCCOM,-1)
C
        CALL SHOWPAGES('KIKCOM  ', FRST_KIKCOM, LAST_KIKCOM,KIKCSB)
C
        CALL SHOWPAGES('LSYSCOM ', FRST_LSYSCOM, LAST_LSYSCOM,-1)
        CALL SHOWPAGES('LTOCOM  ', FRST_LTOCOM, LAST_LTOCOM,LTOCSB)
        CALL SHOWPAGES('LANCOM  ', FRST_LANCOM, LAST_LANCOM,-1)
        CALL SHOWPAGES('LOGCOM  ', FRST_LOGCOM, LAST_LOGCOM,LOGCSB)
C
        CALL SHOWPAGES('PASCOM  ', FRST_PASCOM, LAST_PASCOM,PASCSB)
C
        CALL SHOWPAGES('MSGCOM  ', FRST_MSGCOM, LAST_MSGCOM,MSGCSB)
C
        CALL SHOWPAGES('NETCOM  ', FRST_NETCOM, LAST_NETCOM,-1)
C        CALL SHOWPAGES('NBRCOM  ', FRST_NBRCOM, LAST_NBRCOM,NBRCSB)
C
C        CALL SHOWPAGES('POLCOM  ', FRST_POLCOM, LAST_POLCOM,POLCSB)
        CALL SHOWPAGES('POOLLTO ', FRST_POOLLTO, LAST_POOLLTO,-1)
        CALL SHOWPAGES('PROCOM  ', FRST_PROCOM, LAST_PROCOM,-1)
C
        CALL SHOWPAGES('QUECOM  ', FRST_QUECOM, LAST_QUECOM,-1)
C
        CALL SHOWPAGES('SCRCOM  ', FRST_SCRCOM, LAST_SCRCOM,SCRCSB)
        CALL SHOWPAGES('SLOCOM  ', FRST_SLOCOM, LAST_SLOCOM,SLOCSB)
        CALL SHOWPAGES('SLOCOM1 ', FRST_SLOCOM1, LAST_SLOCOM1,-1)
        CALL SHOWPAGES('TGLCOM  ', FRST_TGLCOM, LAST_TGLCOM,TGLCSB)
C
        CALL SHOWPAGES('TSLCOM  ', FRST_TSLCOM, LAST_TSLCOM,TSLCSB)
C
        CALL SHOWPAGES('WITCOM  ', FRST_WITCOM, LAST_WITCOM,WITCSB)
C        CALL SHOWPAGES('WINCOM  ', FRST_WINCOM, LAST_WINCOM,-1)
C
        CALL SHOWPAGES('X2FCOM  ', FRST_X2FCOM, LAST_X2FCOM,-1)
        CALL SHOWPAGES('X2NETCOM', FRST_X2NETCOM, LAST_X2NETCOM,-1)
        CALL SHOWPAGES('X2XCOM  ', FRST_X2XCOM, LAST_X2XCOM,X2XCSB)
        CALL SHOWPAGES('X2XREL  ', FRST_X2XREL, LAST_X2XREL,X2RCSB)
C
        CALL SHOWPAGES('APUCOM  ', FRST_APUCOM, LAST_APUCOM,-1)
        CALL SHOWPAGES('CRSCOM  ', FRST_CRSCOM, LAST_CRSCOM,-1)
        CALL SHOWPAGES('SSCCOM  ', FRST_SSCCOM, LAST_SSCCOM,-1)
        CALL SHOWPAGES('SSPCOM  ', FRST_SSPCOM, LAST_SSPCOM,-1)
        CALL SHOWPAGES('TRPCOM  ', FRST_TRPCOM, LAST_TRPCOM,-1)
        CALL SHOWPAGES('TROCOM  ', FRST_TROCOM, LAST_TROCOM,-1)
        CALL SHOWPAGES('TSPCOM  ', FRST_TSPCOM, LAST_TSPCOM,-1)
        CALL SHOWPAGES('SSOCOM  ', FRST_SSOCOM, LAST_SSOCOM,-1)
C
        CALL SHOWPAGES('EURCOM  ', FRST_EURCOM, LAST_EURCOM,-1)                 !V09
C
        CALL SHOWPAGES('** TOTAL **',0,0,0)
C
        RETURN
C
        END
C
C
C
C=======OPTIONS /CHECK=NOOVERFLOW
        SUBROUTINE SHOWPAGES( NAME, FIRST, LAST, BLOCKS)
        IMPLICIT NONE
C
        INCLUDE	'INCLIB:SYSPARAM.DEF'
        INCLUDE 'INCLIB:SYSEXTRN.DEF'
C
        CHARACTER   NAME*(*)
        INTEGER*4   FIRST
        INTEGER*4   LAST
C
        REAL*8	    KBYTES
        INTEGER*4   BYTES, PAGES
        INTEGER*4   TOTPAGES/0/
C
        INTEGER*4   BLOCKS
        INTEGER*4   CSBS
C
C
C
        IF(NAME.NE.'** TOTAL **')THEN
          BYTES    = (%LOC(LAST)+3 - %LOC(FIRST)) + 1
          PAGES    = ( (BYTES+511)/512)
          CSBS     = (PAGES/16)
          TOTPAGES = TOTPAGES + PAGES
        ELSE
          PAGES    = TOTPAGES
          CSBS     = (PAGES/16)
          TYPE*,IAM(),' '
        ENDIF
C
        KBYTES = DFLOAT(PAGES)/2.0D0
        TYPE 9000, IAM(),NAME, KBYTES, PAGES,CSBS,BLOCKS
C
        RETURN
C
C
9000    FORMAT(1X,A,' ',A10,F10.1,' KBYTES ',I8,
     *            ' PAGES >',I8,'<>',I8,'<CSBS')
C
        END
