C SUBROUTINE SPTCHK
C  
C V10 10-NOV-2003 FRP Modify for Batch2 Totobola Changes.
C V09 03-MAR-2000 OXK SPGNBR used with SPSTAB, not NUMROWS
C V08 08-FEB-2000 OXK Parametrisized # of rows (Vakio changes)
C V07 17 Apr 1996 HXK Release of Finland for X.25, Telephone Betting, 
C			Instant Pass Thru Phase 1
C V06 21 Jan 1993 DAB Initial Release
C  			Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  			DEC Baseline
C V05 01-AUG-1990 XXX RELEASED FOR VAX
C V04 26-JUN-1990 SWB CHANGED TRANSFORMATION TABLE TO WORK FOR
C     			U BETS WHERE KEY IS STORED AS SINGLES SOMETIMES
C     		        AND ADDED DOCUMENTATION ON TRANSFORMATIONS
C V03 05-MAY-1990 WS MODIFIED FOR DUBLE U BETS AND MATHEMATICAL BETS
C V02 01-FEB-1989 WS INITIAL RELEASE FOR SWEDEN
C V01 26 JUL 1988 WS INITIAL RELEASE FOR ICELAND
C
C     SYSTEM BET CHECKING ROUTINES
C
C     SPTCHK - CHECK SYSTEM BETS (FULL, REDUCED, U SYSTEMS)
C     NSPTCHK - CHECK REGULAR BET (NOT A SYSTEM BET)
C     SPTDSP - DISPLAY INFORMATION ABOUT THE SYSTEM
C     FULLCHK - CHECK FULL SYSTEM (ONLY)
C     FULLANL - DISPLAY INFORMATION ABOUT THE FULL SYSTEM BET
C     GETNIBLE - GET NIBLE OF DATA
C     SETNIBLE - SET NIBLE OF DATA
C     SPTODDS  - ANALYZE SYSTEM BET (CALCULATE ODDS)
C
C
C     IF YOUR WINNER'S CRITERIAS CHANGE, YOU WILL HAVE TO MODIFY
C     FULLCHK ROUTINES. WINNING CRITIRIAS IN BETWEEN !!!!+ AND !!!!-
C     CURRENTLY FULLCHK WILL USE CRITERIAS BELOW:
C        - HIGHEST SHARE AND NEXT TO HIGHEST SHARES ARE  CALCULATED
C
C     IF NUMBER OF SHARES CHANGES, CHANGE SPGNBR, UPDATE POWER2 AND
C     POWER3 TABLES AND ALL TESTING I/O INSTRUCTIONS
C
C+++++++++++++++++++++++++++++
C
C SPTCHK(SYSBET,USYSBET,SYSNR,WIN,HISHR,SHARES,NUMROWS,NUMRROWS) ;REDUCED
C                                         AND U SYSTEM CHECKING
C     IN:
C     SYSBET - SYSTEM BET
C     USYSBET - U SYSTEM BET
C     SYSNR  - SYSTEM NR
C     WIN    - WIN MASK
C     NUMROWS - NUMBER OF TOTAL ROWS
C     NUMRROWS - NUMBER OF RESULTS ROWS
C     OUT:
C     SHARES - SHARES WON
C     HISHR  - HIGHEST SHARE WON BY BET
C              LOGIC IS SET BY INTERNALY CALLED SUBROUTINE FULLCHK
C
C
C     EVERY BET IS TREATED AS GENERIC BET (AS IF ONLY 1-ST POSITIONS
C     WERE BET). TO CHECK NUMBER OF WINNERS WINNING NUMBERS ARE
C     TRANSFORMED SO, NUMBER OF SHARES IS CORRECT.
C
C     EVERY COMBINATION IS REPRESENTED AS A 4 BIT NIBBLE
C     8 4 2 1   BIT VALUES
C     M 2 X 1   TRANSLATIONS
C    M2X1 - M - MATH, 1 - BET FOR HOME, X - FOR TIE, 2 - FOR GUESTS
C    IF BET IS MARKED AS MATH, IT MEANS THAT THIS PORTION OF THE BET
C    IS TREATED AS MATHEMATICAL BET
C
C     WIN IS REPRESENTED BY I*4 TABLE, LOW NIBBLE IS SAME AS
C     COMBINATION NIBBLE
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C This item is the property of GTECH Corporation, Providence, Rhode
C Island, and contains confidential and trade secret information. It
C may not be transferred from the custody or control of GTECH except
C as authorized in writing by an officer of GTECH. Neither this item
C nor the information it contains may be used, transferred,
C reproduced, published, or disclosed, in whole or in part, and
C directly or indirectly, except as expressly authorized by an
C officer of GTECH, pursuant to written agreement.
C
C Copyright 2000 GTECH Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE SPTCHK(SYSBET,USYSBET,SYSNR,WIN,HISHR,SHARES,NUMROWS,NUMRROWS)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:SPTCOM.DEF'
	INTEGER*2 SYSBET(*)             !SYSTEM BET PLAYED
	INTEGER*2 USYSBET(*)               !UBET ADDITION (2-ND BOARD)
	INTEGER*4 WIN(*)                !NUMBERS WON
	INTEGER*4 SHARES(0:SPGNBR)          !SHARES WON
	INTEGER*4 SYSNR                 !SYSTEM NR
	INTEGER*4 HISHR                !MINIMUM # OF SHARES TO CHECK
	INTEGER*4 LOCALWIN(SPGNBR)             !CONVERTED WINNERS TAB
	INTEGER*4 NUMROWS		!# OF TOTAL ROWS IN BOARDS
	INTEGER*4 NUMRROWS		!# OF RESULTS ROWS IN BOARDS
C
	INTEGER*4 II, NWORD, LASTBET, FIRSTBET, TIMES, PTR, SECONDU
	INTEGER*4 SECONDWIN, FIRSTU, UBET, FIRSTWIN, CNT, SECOND
	INTEGER*4 FIRST, BET, OFF, OFF1, FMT504, FMT95
C
	INTEGER*4  SPGNBR1
	PARAMETER (SPGNBR1=SPGNBR+1)
C
	INTEGER*2 LOCALBET(SPGNBR1)  !USED TO CONVERT FULL SYSTEM BET
	INTEGER*4 TRIPLENUM,DUBLENUM,SINGLENUM !# TRIPLE,DUBLE,SINGLE
	INTEGER*4 BETNUM(3)     !TO SERVE AS EQUIVALENCE FOR ***NUMS
	EQUIVALENCE (BETNUM(1),SINGLENUM)
	EQUIVALENCE (BETNUM(2),DUBLENUM)
	EQUIVALENCE (BETNUM(3),TRIPLENUM)
	INTEGER*4 CNTMARK(0:15)      !COUNT OF BITS FOR VALS 0:15
	DATA CNTMARK/0,1,1,2,1,2,2,3,0,7*1/
	INTEGER*4 NEWWIN(0:15,4)   !TABLE FOR NEW WINNER TRANSFORMATION
	DATA NEWWIN/0,1,2,1,2,1,4,1,0,0,0,03,0,05,06,07
     *	           ,0,2,1,2,4,4,1,2,0,0,0,03,0,06,03,07
     *	           ,8*0,8*0
     *	           ,0,4,4,4,1,2,2,4,0,0,0,06,0,03,03,07/
C
C
C     LOCAL TRANSFORMATION OF DOUBLE U BETS
C
C    BET     U  WIN  XFORMED WINNER
C     1X     1  1     1
C     1X     1  X     X
C     1X     1  2     2
C     1X     X  1     X
C     1X     X  X     1
C     1X     X  2     2
C     12     1  1     1
C     12     1  X     2
C     12     1  2     X
C     12     2  1     X
C     12     2  X     2
C     12     2  2     1
C     X2     X  1     2
C     X2     X  X     1
C     X2     X  2     X
C     X2     2  1     2
C     X2     2  X     X
C     X2     2  2     1
C
C LOCAL TRANSFORMATION OF TRIPLE U BETS
C
C   BET  U   WIN XFORMED WINNER
C   1X2  1   1         1
C   1X2  1   X         X
C   1X2  1   2         2
C   1X2  X   1         X
C   1X2  X   X         1
C   1X2  X   2         2
C   1X2  2   1         X
C   1X2  2   X         2
C   1X2  2   2         1
C
C LOCAL TRANSFORMATION OF REDUCED BETS
C
C   BET  U   WIN XFORMED WINNER
C    1X  -   1         1
C    1X  -   X         X
C    1X  -   2         2
C    12  -   1         1
C    12  -   X         2
C    12  -   2         X
C    X2  -   1         2
C    X2  -   X         1
C    X2  -   2         X
C   1X2  -   1         1
C   1X2  -   X         X
C   1X2  -   2         2
C
	INTEGER*4 XFORM2(4,4,3:6)    !WIN/U/BET XFORM WIN TO LOCAL WIN
	DATA XFORM2/
     *	               1,2,0,4, 2,1,0,4, 0,0,0,0, 0,0,0,0,
     *	               0,0,0,0, 0,0,0,0, 0,0,0,0, 0,0,0,0,
     *	               1,4,0,2, 0,0,0,0, 0,0,0,0, 2,4,0,1,
     *	               0,0,0,0, 4,1,0,2, 0,0,0,0, 4,2,0,1/
	CHARACTER*53 FMT950
     *	/'(1X,13I2,'' ** '',13I2,'' && '',4(1X,Z4),'' XX '',4(1X,Z4))'/
	EQUIVALENCE (FMT95,FMT950)
	CHARACTER*2 FMT9501,FMT9502
	CHARACTER*1 FMT9504
	EQUIVALENCE (FMT950(5:5),FMT9501),(FMT950(17:17),FMT9502)
	EQUIVALENCE (FMT950(29:29),FMT504),(FMT950(45:45),FMT9504)
	INTEGER*4 IND
C
	CALL FASTSET(0,SHARES,SPGNBR+1)    !INITIALIZE SHARES
	HISHR=0
C
	IF (SPSATR(SYSNR).EQ.FULSYS) THEN  !CHECK FOR FULL SYSTEM BETS
C
C if TRABUF(TWSPFRG)=0, position IND=0 corresponds to start of sports bet data;
C if TRABUF(TWSPFRG)=1, position IND=0 corresponds to SUPER14 (results) bet data
C                     and position IND=1 corresponds to start of sports bet data
	   IND = NUMRROWS
C
	   OFF1=1
	   DO 10, OFF=1,(NUMROWS+1)/2
	      CALL ILBYTE(BET,SYSBET,OFF-1+IND)
	      FIRST=BET/16
	      SECOND=IAND(BET,15)
	      LOCALBET(OFF1)=FIRST
	      OFF1=OFF1+1
	      IF (OFF1.LE.NUMROWS-NUMRROWS) THEN
		LOCALBET(OFF1)=SECOND
		OFF1=OFF1+1
	      ENDIF
10	   CONTINUE
C
	   CALL FULLCHK(LOCALBET,WIN,NUMROWS-NUMRROWS,HISHR,SHARES)
	   RETURN
	ENDIF
C
C
C     CHECK FOR VALID BETS, UPDATE LOCAL TRIPLE, DUBLE AND SINGLE
C     TABLES, UPDATE LOCAL WIN TABLE
C
	SINGLENUM=SPSNUM(3,SYSNR)-1
	DUBLENUM=SPSNUM(2,SYSNR)-1
	TRIPLENUM=SPSNUM(1,SYSNR)-1
C
	DO 20, OFF=1,(NUMROWS+1)/2
C
	   CALL ILBYTE(BET,SYSBET,OFF-1+IND)           !GET NEXT 2 ROWS
	   FIRST=BET/16
	   SECOND=IAND(BET,15)
C
	   CNT=CNTMARK(FIRST)
	   IF (CNT.EQ.0) RETURN         !INVALID BET
	   BETNUM(CNT)=BETNUM(CNT)+1    !NR OF SINGLES, DUBLESM TRPLES
	   FIRSTWIN=WIN(OFF*2-1)        !WIN MASK
C
	   IF (SPSATR(SYSNR).NE.USYS .OR. CNT.EQ.1) THEN
	      LOCALWIN(BETNUM(CNT))=NEWWIN(FIRST,FIRSTWIN)
	   ELSE
	      CALL ILBYTE(UBET,USYSBET,OFF-1)
	      FIRSTU=UBET/16
	      IF (CNT.EQ.3) THEN
	         LOCALWIN(BETNUM(CNT))=NEWWIN(FIRSTU,FIRSTWIN)
	      ELSE
	         LOCALWIN(BETNUM(CNT))=XFORM2(FIRSTWIN,FIRSTU,FIRST)
	      ENDIF
	   ENDIF
C
C     CHECK LOW NIBBLE
C
	   CNT=CNTMARK(SECOND)
	   IF (CNT.EQ.0) THEN
	      IF (OFF*2.GT.NUMROWS-NUMRROWS) GOTO 20
C***        TYPE *,'Invalid bet'    ;!!!!!
	      RETURN               !INVALID
	   ENDIF
C
	   BETNUM(CNT)=BETNUM(CNT)+1    !NR OF SINGLES, DUBLESM TRPLES
	   SECONDWIN=WIN(OFF*2)
C
C     UPDATE LOCAL WINNERS TABLE
C
	   IF (SPSATR(SYSNR).NE.USYS .OR. CNT.EQ.1) THEN
	      LOCALWIN(BETNUM(CNT))=NEWWIN(SECOND,SECONDWIN)
	   ELSE                !U SYSTEM, U MARK RAW
	      CALL ILBYTE(UBET,USYSBET,OFF-1)
	      SECONDU=IAND(UBET,15)
	      IF (CNT.EQ.3) THEN
	        LOCALWIN(BETNUM(CNT))=NEWWIN(SECONDU,SECONDWIN)
	      ELSE
	        LOCALWIN(BETNUM(CNT))=XFORM2(SECONDWIN,SECONDU,SECOND)
	      ENDIF
	   ENDIF
C
	   IF (BETNUM(CNT).GE.SPSNUM(5-CNT,SYSNR)) THEN   !BAD MARKS
	      IF(CNT.NE.1.OR.CNT.EQ.1.AND.BETNUM(1).GT.NUMROWS-NUMRROWS) RETURN
	   ENDIF
20	CONTINUE
C
C     WE HAVE LOCALWIN TABLE SET FOR NEW WINNER
C     AND WE PROCESS USYSS AND REDUCED SYSTEMS NOW
C     ALL U SYSTEMS SHOULD BE NOW LOOKING AS REDUCED SYSTEMS.
C
	PTR=SPSPTR(SYSNR)
	IF (PTR.LE.0) RETURN
	TIMES=SPSTAB(PTR)
	FIRSTBET=PTR+1
	LASTBET=FIRSTBET+TIMES*SPGNBR-1
C
	IF (SPSTST.LT.0) THEN
	NWORD=(NUMROWS-NUMRROWS+3)/4
	CALL ISBYTE((NUMROWS-NUMRROWS)/10+'00000030'X,FMT95,4)
	CALL ISBYTE(MOD(NUMROWS-NUMRROWS,10)+'00000030'X,FMT95,5)
	CALL ISBYTE((NUMROWS-NUMRROWS)/10+'00000030'X,FMT95,16)
	CALL ISBYTE(MOD(NUMROWS-NUMRROWS,10)+'00000030'X,FMT95,17)

      WRITE(6,FMT950)(WIN(II),II=1,NUMROWS-NUMRROWS)
     *              ,(LOCALWIN(II),II=1,NUMROWS-NUMRROWS)
     *	            ,(SYSBET(II),II=1,NWORD),(USYSBET(II),II=1,NWORD)
	ENDIF
C
	DO 30, BET=FIRSTBET,LASTBET,SPGNBR    !CHECK EACH BET
	   CALL FULLCHK(SPSTAB(BET),LOCALWIN,NUMROWS-NUMRROWS,HISHR,SHARES)
30	CONTINUE
	IF (SPSTST.LT.0) THEN
	 TYPE *,' *',NUMROWS-NUMRROWS,'*',SHARES(NUMROWS-NUMRROWS),
     *          ' *',NUMROWS-NUMRROWS-1,'*',SHARES(NUMROWS-NUMRROWS-1),
     *          ' *',NUMROWS-NUMRROWS-2,'*',SHARES(NUMROWS-NUMRROWS-2)
	ENDIF
C
	RETURN
C
	END
