C
C SUBROUTINE SPTROW
C $Log:   GXAFXT:[GOLS]SPTROW.FOV  $
C  
C V04 30-MAR-2015 MTK Modified Super 14 game
C V03 30-MAY-2011 FJG NFASTSET
C V02 10-NOV-2003 FRP Modify for Batch2 Totobola Changes.
C
C     Rev 1.0   17 Apr 1996 15:16:10   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 17:42:04   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - winsub.for **
C
C
C
C  SUBROUTINE TO EXPAND SPORT BETS FOR WINSEL
C
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE SPTROW(TRABUF,ROWS,RROWS)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:DESTRA.DEF'
	INTEGER*2 ROWS(SPGNBR,12),RROWS(2,TGGNBR,12)
	INTEGER*4 ROW, NUM, I, RCNT, J, LIMIT, IND
	INTEGER*4 BCNT
C
C       CALL FASTSET(0,ROWS,SIZEOF(ROWS)/2)
C       CALL FASTSET(0,RROWS,SIZEOF(RROWS)/2)
C
	CALL NFASTSET(ROWS,SIZEOF(ROWS))
        CALL NFASTSET(RROWS,SIZEOF(RROWS))
C
	BCNT = 0
	IF(TRABUF(TWSPFRG).NE.0) BCNT = 1

        IND = BCNT
	LIMIT=(TRABUF(TWSRW)+1)/2
	DO 20 J=1,TRABUF(TWNBET)
  	  RCNT=0
	  DO 10 I=1,LIMIT
	    CALL ILBYTE(NUM,TRABUF(TWBORD),IND)
	    IND=IND+1
	    ROW=ISHFT(NUM,-4)
	    RCNT=RCNT+1
	    ROWS(RCNT,J)=ROW
	    IF(RCNT.EQ.TRABUF(TWSRW)-BCNT) GOTO 20
	    ROW=IAND(NUM,'0F'X)
	    RCNT=RCNT+1
	    ROWS(RCNT,J)=ROW
10	  CONTINUE
20	CONTINUE

        IF(TRABUF(TWSPFRG).EQ.1) THEN
          IND = 0
          CALL ILBYTE(NUM,TRABUF(TWBORD),IND)
          ROW = ISHFT(NUM,-4)
          RROWS(1,1,1) = ROW
          ROW = IAND(NUM,'0F'X)
          RROWS(2,1,1) = ROW
        ENDIF

        IF(TRABUF(TWSPFRG).EQ.2) THEN
          IND = 0
          CALL ILBYTE(NUM,TRABUF(TWBORD),IND)
          ROW = IAND(NUM,'0F'X)
          RROWS(1,1,1) = ROW
          ROW = 0
          RROWS(2,1,1) = ROW
        ENDIF

	RETURN
	END
