C
C SUBROUTINE SSEXP
C $Log:   GXAFXT:[GOLS]SSEXP.FOV  $
C  
C     Rev 1.0   17 Apr 1996 15:17:54   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 17:43:20   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - swinsub.for **
C
C
C
C SUBROUTINE TO EXPAND MATCHEN SYSTEM BETS
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE SSEXP(TRABUF,BETS,COUNT)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:DESTRA.DEF'
	INTEGER*4 BETS(2,100)
	INTEGER*4 I, J, COUNT
C
C
	IF(TRABUF(TWSYST).EQ.NOSYS) THEN
	  COUNT=TRABUF(TWNBET)
	  DO 10 I=1,COUNT
	  BETS(1,I)=TRABUF(TWSSCR1+(I-1)*TWSBLEN)
	  BETS(2,I)=TRABUF(TWSSCR2+(I-1)*TWSBLEN)
10	  CONTINUE
	  RETURN
	ENDIF
C
C EXPAND SYSTEM BETS
C
	COUNT=0
	DO 100 I=0,TRABUF(TWNBET)-1
	DO 100 J=0,TRABUF(TWNBET)-1
	IF(TRABUF(TWSSCR1+I*TWSBLEN).EQ.'FF'X) GOTO 100
	IF(TRABUF(TWSSCR2+J*TWSBLEN).EQ.'FF'X) GOTO 100
	COUNT=COUNT+1
	BETS(1,COUNT)=TRABUF(TWSSCR1+I*TWSBLEN)
	BETS(2,COUNT)=TRABUF(TWSSCR2+J*TWSBLEN)
100	CONTINUE
	RETURN
	END
