C
C SUBROUTINE SSWIN_OPNDRW
C
C V01 27-APR-99 RXK STOPSYS optimization (PRMTEXT used instead of WIMG).
C
C
C SUBROUTINE TO OPEN DRAW FILES FOR WINSEL.
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE SSWIN_OPNDRW(FILE,UNT)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'

	INTEGER*4 FILE(5)
	INTEGER*4 ST, UNT
        INTEGER*4   VOL, INPLEN
        CHARACTER*4 CVOL
        EQUIVALENCE (VOL,CVOL)
C
10	CONTINUE
	CALL USRCLOS1(     UNT)
	CALL OPENW(UNT,FILE,5,0,0,ST)
	IF(ST.EQ.0) RETURN
C
	WRITE(5,900) IAM(),FILE,ST
        CALL PRMTEXT('Enter new draw pack volume name: ',CVOL,INPLEN)
        FILE(1) = VOL
	WRITE(5,920) FILE(1)
	PAUSE
	GOTO 10
C
900	FORMAT(1X,A,1X,5A4,' open error> ',I4)
910	FORMAT(A4)
920	FORMAT(1X,A,' Mount ',A4,' pack and continue SSWINSEL')
	END
