C
C SUBROUTINE SYSPRICE
C $Log:   GXAFXT:[GOLS]SYSPRICE.FOV  $
C  
C     Rev 1.0   17 Apr 1996 15:25:26   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 17:47:16   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - sysbets.for **
C
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++
C     SYSPRICE.FTN
C
C     CALCULATE PRICE OF SYSTEM BETS
C+
C+    CALL SYSPRICE(BASEBET,HIGHNR,SYSTEM,PRICE)
C+    IN -
C+    BASEBET  - BASIC BET    (6 FOR THE GAME 6/49)
C+    HIGHNR    - HIGHEST # BET  (49 FOR THE GAME 6/49)
C+                                NEEDED ONLY IF SYSTEM.LT.BASEBET
C+    SYSTEM   - ACTUAL NUMBER BET (8 FOR SYSTEM 8)
C+    OUT-
C+    PRICE - PRICE AS NUMBER OF BASEBETS THAT HAVE TO BE PLAYED
C+
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE SYSPRICE(BASEBET,HIGHNR,SYSTEM,PRICE)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
C
	INTEGER*4 BASEBET                   !BASE BET
	INTEGER*4 HIGHNR                    !HIGH NR THAT MAY BE PLAYED
	INTEGER*4 SYSTEM                    !NUMBER OF NUMBERS BET
	INTEGER*4 PRICE                !NUMBER OF ASEBETS FOR SYSTEM BET
	INTEGER*4 TO_BET, NON_BET, FASTBIN
C
C
	IF (SYSTEM.GE.BASEBET) THEN
	   PRICE=FASTBIN(SYSTEM,BASEBET)
	   RETURN
	ENDIF
C
C     BETS WITH SYSTEM SMALLER THAN NUMBER OF BETS
C
	NON_BET=HIGHNR-SYSTEM
	TO_BET=BASEBET-SYSTEM
C
	PRICE=FASTBIN(NON_BET,TO_BET)
	RETURN
	END
