C
C SUBROUTINE TEXP
C $Log:   GXAFXT:[GOLS]TEXP.FOV  $
C  
C     Rev 1.0   17 Apr 1996 15:33:10   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 17:50:54   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - twinsub.for **
C
C
C SUBROUTINE TO EXPAND TOTO SELECT SYSTEM BETS
C
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE TEXP(TRABUF,OFF,BETS,SIMPLE,AMT,COUNT)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:DESTRA.DEF'
	INTEGER*4 BETS(2,6,20),TAB(6,40,5),CMB(5)
	INTEGER*4 COUNT, IND, OFF, AMT, SIMPLE, I, SYS, SELECT, J
	LOGICAL FIRST/.TRUE./
C
C IF FIRST TIME THE EXPAND SYSTEM BET TABLES
C
	IF(FIRST) THEN
	  FIRST=.FALSE.
	  CALL TSLSYS(TAB(1,1,1),4,3,CMB(1))
	  CALL TSLSYS(TAB(1,1,2),5,3,CMB(2))
	  CALL TSLSYS(TAB(1,1,3),6,3,CMB(3))
	  CALL TSLSYS(TAB(1,1,4),5,4,CMB(4))
	  CALL TSLSYS(TAB(1,1,5),6,4,CMB(5))
	ENDIF
	COUNT=0
	IF(TRABUF(TWSYST).NE.NOSYS) GOTO 1000
C
C PROCESS NON-SYSTEM BETS
C
	IF(OFF.LT.1.OR.OFF.GT.3) RETURN
	COUNT=1
C
C
	IF(OFF.EQ.1) THEN
	  AMT=TRABUF(TWTAMT1)
	  SIMPLE=TRABUF(TWTSEL1)
	  DO 10 I=1,SIMPLE
	  BETS(1,I,1)=TRABUF(TWTROW1+(I-1)*TWTBLEN)
	  BETS(2,I,1)=TRABUF(TWTPOL1+(I-1)*TWTBLEN)
10	  CONTINUE
	  RETURN
	ENDIF
C
C
	IF(OFF.EQ.2) THEN
	  AMT=TRABUF(TWTAMT2)
	  SIMPLE=TRABUF(TWTSEL2)
	  DO 20 I=1,SIMPLE
	  BETS(1,I,1)=TRABUF(TWTROW2+(I-1)*TWTBLEN)
	  BETS(2,I,1)=TRABUF(TWTPOL2+(I-1)*TWTBLEN)
20	  CONTINUE
	  RETURN
	ENDIF
C
C
	IF(OFF.EQ.3) THEN
	  AMT=TRABUF(TWTAMT3)
	  SIMPLE=TRABUF(TWTSEL3)
	  DO 30 I=1,SIMPLE
	  BETS(1,I,1)=TRABUF(TWTROW3+(I-1)*TWTBLEN)
	  BETS(2,I,1)=TRABUF(TWTPOL3+(I-1)*TWTBLEN)
30	  CONTINUE
	  RETURN
	ENDIF
	RETURN
C
C
C EXPAND SYSTEM BETS
C
1000	CONTINUE
	SYS=0
	SIMPLE=TRABUF(TWSYSN)
	SELECT=TRABUF(TWTSEL1)
	IF(SIMPLE.EQ.3.AND.SELECT.EQ.4) SYS=1
	IF(SIMPLE.EQ.3.AND.SELECT.EQ.5) SYS=2
	IF(SIMPLE.EQ.3.AND.SELECT.EQ.6) SYS=3
	IF(SIMPLE.EQ.4.AND.SELECT.EQ.5) SYS=4
	IF(SIMPLE.EQ.4.AND.SELECT.EQ.6) SYS=5
	IF(SYS.EQ.0) RETURN
C
C
	AMT=TRABUF(TWTAMT1)
	COUNT=CMB(SYS)
	DO 1010 I=1,COUNT
	DO 1010 J=1,SIMPLE
	IND=TAB(J,I,SYS)-1
	BETS(1,J,I)=TRABUF(TWTROW1+IND*TWTBLEN)
	BETS(2,J,I)=TRABUF(TWTPOL1+IND*TWTBLEN)
1010	CONTINUE
	RETURN
	END
