C
C SUBROUTINE TGCHKWIN
C
C V01 02-DEC-2000 UXN INITIAL RELEASE.
C
C SUBROUTINE TO CHECK IF TOTOGOLO TICKET IS A WINNER
C AND UPDATE VALIDATION RECORDS
C
C
C
C     CALL TGCHKWIN(TRABUF,V4BUF,WIN)
C INPUT
C          TRABUF - TRANSACTION BODY
C          V4BUF  - VALIDATION RECORD
C OUTPUT
C          V4BUF  - UPDATED FOR NEW WINNER (IF ANY)
C          WIN    - ZERO -> NOT A WINNER
C
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C This item is the property of GTECH Corporation, Providence, Rhode
C Island, and contains confidential and trade secret information. It
C may not be transferred from the custody or control of GTECH except
C as authorized in writing by an officer of GTECH. Neither this item
C nor the information it contains may be used, transferred,
C reproduced, published, or disclosed, in whole or in part, and
C directly or indirectly, except as expressly authorized by an
C officer of GTECH, pursuant to written agreement.
C
C Copyright 2000 GTECH Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE TGCHKWIN(TRABUF,V4BUF,WIN)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:DESTRA.DEF'
	INCLUDE 'INCLIB:WINCOM.DEF'
	INCLUDE 'INCLIB:DESVAL.DEF'
	INCLUDE 'INCLIB:VALFIL.DEF'
	INCLUDE 'INCLIB:VDETAIL.DEF'
C
	INTEGER*4 SHARES(TGGDIV)	!
	INTEGER*4 PRZIND		!
	INTEGER*4 DIV			!
	INTEGER*4 GIND			!
	INTEGER*4 ST			!
	INTEGER*4 WIN			!
	INTEGER*4 FRCS			!# of Fractions.
	LOGICAL	  CXLED			!
	LOGICAL   UPDATE		!
	LOGICAL	  YESKIK		!True if ticket participates in Kicker.
C
C
	UPDATE=.TRUE.
	GOTO 10
C
C ENTRY TO CHECK IF WINNER ONLY (NO UPDATE)
C
	ENTRY TGIFWIN(TRABUF,WIN)
	UPDATE=.FALSE.
C
C
10	CONTINUE
	WIN=0
	CXLED=.FALSE.
	ST=TRABUF(TSTAT)
	GIND=TRABUF(TGAMIND)
	IF(LTGDRW(GIND).LT.0) RETURN
	IF(TGDELAY(GIND).EQ.2) RETURN
	IF(ST.NE.GOOD.AND.ST.NE.VOID.AND.
     *	   ST.NE.INCA.AND.ST.NE.EXCH) RETURN
	IF(TRABUF(TWBEG).GT.LTGDRW(GIND)) RETURN
	IF(TRABUF(TWEND).LT.LTGDRW(GIND)) RETURN
	IF(TRABUF(TSTAT).EQ.VOID.OR.TRABUF(TSTAT).EQ.INCA) CXLED=.TRUE.
C
C CHECK IF TICKET IS A WINNER
C
	CALL TGWINLOS(TRABUF,SHARES,WIN)
	IF(WIN.EQ.0.OR.MAILSCAN) RETURN
	IF(.NOT.UPDATE) RETURN
C
C CHECK IF TICKET IS PARTICIPATING IN KICKER.
C
	YESKIK = .FALSE.
	IF(TRABUF(TWKFLG).NE.0.OR.TRABUF(TWKFLG2).NE.0) YESKIK = .TRUE.
	  
C
C UPDATE VALIDATION RECORD
C
	IF(V4BUF(VFSSER).NE.0) THEN
	  CALL LOGVAL(VALREC,V4BUF)
	  CALL DLOGVAL(VALREC,VDETAIL)
	ELSE
	  CALL FASTSET(0,VALREC,VALLEN)
	  CALL FASTSET(0,VDETAIL,VPLEN*VMAX)
	ENDIF
C
C
	FRCS = TRABUF(TFRAC)
	IF(FRCS.LT.1) FRCS = MAX(MAXFRC(TRABUF(TGAM)),1)
	DO 20 DIV=1,TGGDIV
	IF(SHARES(DIV).EQ.0) GOTO 20
	IF(.NOT.CXLED) LTGSHR(DIV,GIND)=LTGSHR(DIV,GIND)+SHARES(DIV)*FRCS
	VALREC(VPZOFF)=VALREC(VPZOFF)+1
	PRZIND=VALREC(VPZOFF)
	IF(PRZIND.GT.VMAX) THEN
	  TYPE*,IAM(),' Prize table overflow ',
     *          TRABUF(TCDC),TRABUF(TSER)
	  CALL GPAUSE
	  VALREC(VSTAT)=VHOLD
	  VALREC(VPZOFF)=VMAX
	  GOTO 20
	ENDIF
C
C
	VDETAIL(VKIK,PRZIND)=0
	VDETAIL(VKI2,PRZIND)=0
	VDETAIL(VPRG,PRZIND)=0
	VDETAIL(VBDR,PRZIND)=0
	VDETAIL(VUPD,PRZIND)=0
	VDETAIL(VDIV,PRZIND)=DIV
	VDETAIL(VSHR,PRZIND)=SHARES(DIV)
	VDETAIL(VDRW,PRZIND)=LTGDRW(GIND)
20	CONTINUE
	VALREC(VWCDC)=DAYCDC
C
C UPDATE VALIDATION HEADER IF NEW WINNER
C
	IF(VALREC(VSTAT).EQ.VNOWIN) THEN
	  VALREC(VSCDC)=TRABUF(TCDC)
	  VALREC(VSTER)=TRABUF(TTER)
	  VALREC(VSSER)=TRABUF(TSER)
	  VALREC(VEXP )=TRABUF(TWEND)
	  VALREC(VGAM )=TRABUF(TGAM)
	  VALREC(VGTYP)=TRABUF(TGAMTYP)
	  VALREC(VGIND)=TRABUF(TGAMIND)
	  VALREC(VFRAC)=TRABUF(TFRAC)
	  VALREC(VBNKNUM)=TRABUF(TWBNKNM)
	  VALREC(VBNKID)=TRABUF(TWBNKID)
          VALREC(VKGME)=TRABUF(TWKGME)
	  IF(YESKIK) THEN
	     VALREC(VKEXP)=TRABUF(TWKEND)
	  ENDIF
	ENDIF
C
        IF(VALREC(VSTAT).EQ.VPRPAY.OR.VALREC(VSTAT).EQ.VPRPOST) THEN
          VALREC(VSTAT)=VPPNPZ
        ELSEIF(VALREC(VSTAT).NE.VHOLD) THEN
          VALREC(VSTAT)=VNOPRZ
        ENDIF
	IF(TRABUF(TSTAT).EQ.VOID) VALREC(VSTAT)=VCXL
	IF(TRABUF(TSTAT).EQ.INCA) VALREC(VSTAT)=VDEL
	CALL DVALLOG(VALREC,VDETAIL)
	CALL VALLOG (VALREC,V4BUF  )
	RETURN
	END
