C
C     FILE   : TGLANL
C     AUTHOR : J.H.R
C     VERSION: 01            DATE: 01 / 12 / 2000
C
C
C V01 JHR FUNCTION TO ANALYZE RESULTS SYSTEM BET TABLES ( PORTURGAL PROJECT )
C
C
C RESULTS SYSTEM BET DEFINITION ( TOTOGOLO )
C
C     **************************************************************************
C        THIS ITEM IS THE PROPERTY OF GTECH CORPORATION, POVIDENCE, RHODE
C     ISLAND, AND CONTAINS CONFIDENTIAL AND TRADE SECRET INFORMATION. IT MAY
C     NOT BE TRANSFERRED FROM THE CUSTODY OR CONTROL OF GTECH EXCEPT AS AUTO -
C     RIZED IN WRITING BY AN OFFICER OF GTECH. NEITHER THIS ITEM NOR THE
C     INFORMATION IT CONTAINS MAY BE USED, TRANSFERRED, REPRODUCED, PUBLISHED
C     OR DISCLOSED, IN WHOLE OR IN PART, AND DIRECTLY OR INDIRECTLY, EXCEPT AS
C     EXPRESSLY AUTHORIZED BY AN OFFICER OR GTECH, PURSUANT TO WRITTEN AGREEMENT
C
C     Copyright 2000 GTECH Corporation. All Rigth Reserved
C
C     **************************************************************************
C
C FUNCTION TO ANALYZE SYSTEM BETS TABLES ( ONLY FULL OPTION, NOT REDUCED )
C
C=======OPTIONS /CHECK = NOOVERFLOW /EXT
      SUBROUTINE TGLANL(SYSBETFILE,GIND)
      IMPLICIT NONE
C
C INCLUDES DEFINITION TO ANALYZE SYSTEM BETS TABLES
C
      INCLUDE 'INCLIB:SYSPARAM.DEF'
      INCLUDE 'INCLIB:SYSEXTRN.DEF'
      INCLUDE 'INCLIB:GLOBAL.DEF'
      INCLUDE 'INCLIB:TGLCOM.DEF'
      INCLUDE 'INCLIB:RECTGSF.DEF'
C
C FUNCTION PARAMETERS DEFINITION TO ANALYZE SYSTEM BETS TABLES
C
      INTEGER * 4 SYSBETFILE(5)          ! SYSTEM BETS FILE NAME
      INTEGER * 4 GIND
C
C CONSTANTS PARAMETERES DEFINITION TO ANALYZE SYSTEM BETS TABLES
C
      INTEGER * 4 IDGAMFIL               ! IDENTIFICATION GAME FILE
C
C INITIATE CONSTANTS PARAMETERES DEFINITION TO ANALYZE SYSTEM BETS TABLES
C
      PARAMETER(IDGAMFIL = 2)            ! IDENTIFICATION GAME FILE
C
C VARIABLES DEFINITION TO ENTER/DISPLAY SYSTEM BETS TABLES
C
      INTEGER * 4 I,J,K
      INTEGER * 4 NUMDSP                 ! DISPLAY COUNTER
      INTEGER * 4 FSTS                   ! FUNCTION STATUS
      INTEGER * 4 SFDB(7)                ! SYSTEM FILE DESCRIPTION BLOCK
C
      CHARACTER * 2 USRTXT               ! USER SELECTION ( TEXT )
C
C OPEN RESULTS SYSTEM FILE
C
      CALL OPENQW(IDGAMFIL, SYSBETFILE, 4, 0, 0, FSTS)
      CALL IOQINIT(SFDB, IDGAMFIL, TGSFSEC * 256)
      IF(FSTS .NE. 0) CALL FILERR(SYSBETFILE, 1, FSTS, 0)
C
C READ RESULTS SYSTEM FILE
C
      CALL READQW(SFDB, 1, TGSFREC, FSTS)
      IF(FSTS .NE. 0) CALL FILERR(SYSBETFILE, 2, FSTS, 1)
C
C DISPALY ACTUAL SYSTEM BET TABLE
C
2000  CONTINUE
      NUMDSP = 0
      TYPE *, '  '
      DO I=0,15
         DO J=0,15
            DO K=0,15
               IF(TGSFFSF(I,J,K,GIND).EQ.1) THEN
                  WRITE(6, 100) I,J,K, (2**I)*(3**J)*(4**K)
                  NUMDSP = NUMDSP + 1
               ENDIF
	    ENDDO
         ENDDO   
      ENDDO
C
C IF THERE IS NOT ANY ELEMENT ON SYSTEM TABLE DISPALY A MESSAGE
C
      IF(NUMDSP .EQ. 0) THEN
        TYPE *, '  '
        TYPE *, '  There Are Not System Bets Information'
        TYPE *, '  '
        CALL XWAIT(3, 2, FSTS)
      ENDIF
C
C END TO DISPALY ACTUAL SYSTEM BET TABLE
C
      TYPE *, '  '
      CALL INPTEXT('Press ENTER Key To Continue', USRTXT, FSTS)
      CALL CLOSEQFIL(SFDB)
      RETURN
C
C FORMATS DEFINITION TO ANALYZE SYSTEM BETS TABLES
100   FORMAT(X,'Dbl: ',I2.2,' Trpl: ',I2.2,' Qdpl: ',I2.2,' Combinations:',I)
C
C END OF FILE TO ANALIZE SYSTEM BETS TABLES
C
      END
