C
C     FILE   : TGLSYS.FOR
C     AUTHOR : J.H.R
C     VERSION: 01            DATE: 01 / 12 / 2000
C
C
C V01 JHR FUNCTION TO ENTER RESULTS SYSTEM BET TABLES ( PORTURGAL PROJECT )
C
C
C RESULTS SYSTEM BET DEFINITION ( TOTOGOLO )
C
C     **************************************************************************
C        THIS ITEM IS THE PROPERTY OF GTECH CORPORATION, POVIDENCE, RHODE
C     ISLAND, AND CONTAINS CONFIDENTIAL AND TRADE SECRET INFORMATION. IT MAY
C     NOT BE TRANSFERRED FROM THE CUSTODY OR CONTROL OF GTECH EXCEPT AS AUTO -
C     RIZED IN WRITING BY AN OFFICER OF GTECH. NEITHER THIS ITEM NOR THE
C     INFORMATION IT CONTAINS MAY BE USED, TRANSFERRED, REPRODUCED, PUBLISHED
C     OR DISCLOSED, IN WHOLE OR IN PART, AND DIRECTLY OR INDIRECTLY, EXCEPT AS
C     EXPRESSLY AUTHORIZED BY AN OFFICER OR GTECH, PURSUANT TO WRITTEN AGREEMENT
C
C     Copyright 2000 GTECH Corporation. All Rigth Reserved
C
C     **************************************************************************
C
C FUNCTION TO ENTER SYSTEM BETS TABLES ( ONLY FULL OPTION, NOT REDUCED )
C
C=======OPTIONS /CHECK = NOOVERFLOW /EXT
      SUBROUTINE TGLSYS(SYSBETFILE,GIND)
      IMPLICIT NONE
C
C INCLUDES DEFINITION TO ENTER/DISPLAY SYSTEM BETS TABLES
C
      INCLUDE 'INCLIB:SYSPARAM.DEF'
      INCLUDE 'INCLIB:SYSEXTRN.DEF'
      INCLUDE 'INCLIB:GLOBAL.DEF'
      INCLUDE 'INCLIB:TGLCOM.DEF'
      INCLUDE 'INCLIB:RECTGSF.DEF'
C
C FUNCTION PARAMETERS DEFINITION TO ENTER/DISPLAY SYSTEM BETS TABLES
C
      INTEGER * 4 SYSBETFILE(5)          ! SYSTEM BETS FILE NAME
      INTEGER * 4 GIND
C
C CONSTANTS PARAMETERES DEFINITION TO ENTER/DISPLAY SYSTEM BETS TABLES
C
      INTEGER * 4 IDGAMFIL               ! IDENTIFICATION GAME FILE
C
C INITIATE CONSTANTS PARAMETERES DEFINITION TO ENTER/DISPLAY SYSTEM BETS TABLES
C
      PARAMETER(IDGAMFIL = 2)            ! IDENTIFICATION GAME FILE
C
C VARIABLES DEFINITION TO ENTER/DISPLAY SYSTEM BETS TABLES
C
      INTEGER * 4 NUMSYS                 ! NUMBER SYSTEM COUNTER
      INTEGER * 4 NUMDSP                 ! DISPLAY COUNTER
      INTEGER * 4 FSTS                   ! FUNCTION STATUS
      INTEGER * 4 USRSEL                 ! USER SELECTION
      INTEGER * 4 SFDB(7)                ! SYSTEM FILE DESCRIPTION BLOCK
      INTEGER * 4 DBLS                   ! NUMBER OF DOUBLES
      INTEGER * 4 TPLS                   ! NUMBER OF TRIPLES
      INTEGER * 4 QDRP                   ! NUMBER OF CUADRUPLES
      INTEGER * 4 I, J, K
C
      CHARACTER * 2 USRTXT               ! USER SELECTION ( TEXT )
C
C OPEN RESULTS SYSTEM FILE
C
      CALL OPENQW(IDGAMFIL, SYSBETFILE, 4, 0, 0, FSTS)
      CALL IOQINIT(SFDB, IDGAMFIL, TGSFSEC * 256)
      IF(FSTS .NE. 0) CALL FILERR(SYSBETFILE, 1, FSTS, 0)
C
C READ RESULTS SYSTEM FILE
C
      CALL READQW(SFDB, 1, TGSFREC, FSTS)
      IF(FSTS .NE. 0) CALL FILERR(SYSBETFILE, 2, FSTS, 1)
C
C DISPLAY MAIN MENU TO ENTER/DISPLAY SYSTEM BETS TABLES
C
10000 CONTINUE
      CALL CLRSCR(5)
      TYPE *, '  '
      TYPE *, ' 1.- Enter New System Bet Table'
      TYPE *, ' 2.- Display Actual System Bet Table'
      TYPE *, ' 3.- Save System Bet Table'
      TYPE *, ' E.- Return To Main Menu'
      TYPE *, '  '
      CALL INPNUM('Enter Function Number:', USRSEL, 1, 3, FSTS)
      IF(FSTS.LT.0) THEN
        CALL CLOSEQFIL(SFDB)
        RETURN
      ENDIF
C
C GO TO USER SELECTION ENTRY
C
      GOTO(1000, 2000, 3000) USRSEL
C
C ENTER A NEW SYSTEM BET TABLE
C
1000  CONTINUE
      NUMSYS = 1    
      CALL FASTSET(0, TGSFFSF(0,0,0,GIND), 16*16*16)
C
C DIPLAY NUMBER OF SYSTEM COMBINATIONS HAVE BEEN ENTERED
C
20000 CONTINUE
      TYPE *, '  '
      WRITE(6, 200) NUMSYS
      TYPE *, '  '
C
C ASK FOR NUMBER OF DOUBLES
C
      CALL INPNUM('Enter Number Of Doubles [E:Exit]:', DBLS, 0, TGGNBR, FSTS)
      IF(FSTS .LT. 0) GOTO 10000
C
C ASK FOR NUMBER OF TRIPLES
C
      CALL INPNUM('Enter Number Of Triples [E:Exit]:', TPLS, 0, TGGNBR, FSTS)
      IF(FSTS .LT. 0) GOTO 10000
C
C ASK FOR NUMBER OF QUADRUPLES
C
      CALL INPNUM('Enter Number Of Quadruples [E:Exit]:', QDRP, 0, TGGNBR, FSTS)
      IF(FSTS .LT. 0) GOTO 10000
C
C SET NUMBER OF DOUBLES, TRIPLES AND QUADRUPLES
C
      TGSFFSF(DBLS,TPLS,QDRP,GIND)  = 1
      NUMSYS = NUMSYS + 1
C
C ASK TO USER IF HE/SHE WANTS ENTER ANOTHER COMBINATION
C
      CALL INPYESNO('Do You Want To Enter Another Combination ? [Y/N]',USRSEL)
      IF(USRSEL .EQ. 1) GOTO 20000
C
C END TO ENTER A NEW SYSTEM BET TABLE
C
      GOTO 10000
C
C DISPALY ACTUAL SYSTEM BET TABLE
C
2000  CONTINUE
      NUMDSP = 0
      TYPE *, '  '
      DO I = 0, 15
         DO J = 0, 15
	    DO K = 0, 15
	       IF(TGSFFSF(I, J, K, GIND).EQ.1) THEN
                  WRITE(6, 100) I, J, K, (2**I) * (3**J) * (4**K)
                  NUMDSP = NUMDSP + 1
               ENDIF
	    ENDDO
         ENDDO
      ENDDO
C
C IF THERE IS NOT ANY ELEMENT ON SYSTEM TABLE DISPALY A MESSAGE
C
      IF(NUMDSP .EQ. 0) THEN
        TYPE *, '  '
        TYPE *, '  There Are Not System Bets Information'
        TYPE *, '  '
        CALL XWAIT(3, 2, FSTS)
      ENDIF
C
C END TO DISPALY ACTUAL SYSTEM BET TABLE
C
      TYPE *, '  '
      CALL INPTEXT('Press ENTER Key To Continue', USRTXT, FSTS)
      GOTO 10000
C
C SAVE ACTUAL SYSTEM BET TABE TO SYSTEM BET FILE
C
3000  CONTINUE
      CALL WRITEQW(SFDB, 1, TGSFREC, FSTS)
      IF(FSTS .NE. 0) THEN
        TYPE *, '  '
        TYPE *, '  Error Saving System Bet Table In System Bet File'
        TYPE *, '  '
        CALL XWAIT(2, 2, FSTS)
      ENDIF
C
C END TO SAVE ACTUAL SYSTEM BET TABE TO SYSTEM BET FILE
C
      GOTO 10000
C
C FORMATS DEFINITION TO ENTER/DISPLAY SYSTEM BETS TABLES
C
100   FORMAT(' Dbl: ', I2.2, ' Trpl: ', I2.2, ' Qdpl: ', I2.2, ' Comb: ', I)
200   FORMAT(X, ' System Table Combination It''s: ', I3.3)
C
C THIS IS THE END TO ENTER/DISPLAY SYSTEM BETS TABLES
C
      END




