C PROGRAM TSTGAM
C
C TSTGAM.FOR
C
C V11 29-NOV-2000 UXN Totogolo added.
C V10 13-OCT-1999 RXK World Tour added.
C V09 20-MAR-1999 UXN Triple changed to TRIO. Super Triple added.
C V08 17-APR-1996 HXK Release of Finland for X.25, Telephone Betting, 
C                     Instant Pass Thru Phase 1
C V07 06-NOV-1995 PXB Super double and Todays Couple added.
C V06 16-OCT-1994 HXK Added new fields for Winsel, fixed tstgam bugs
C V05 02-OCT-1994 HXK Added Bingo
C V04 09-JUN-1993 HXK Added Ravi game (V65)
C V03 10-MAY-1993 HXK Added Spede game. (TPPP)
C V02 21-JAN-1993 DAB Initial Release
C                     Based on Netherlands Bible, 12/92, and Comm 1/93 update
C                     DEC Baseline
C V01 01-AUG-1990 XXX RELEASED FOR VAX
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C This item is the property of GTECH Corporation, Providence, Rhode
C Island, and contains confidential and trade secret information. It
C may not be transferred from the custody or control of GTECH except
C as authorized in writing by an officer of GTECH. Neither this item
C nor the information it contains may be used, transferred,
C reproduced, published, or disclosed, in whole or in part, and
C directly or indirectly, except as expressly authorized by an
C officer of GTECH, pursuant to written agreement.
C
C Copyright 1999 GTECH Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW/EXT
	PROGRAM TSTGAM
	IMPLICIT NONE

	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:LLTREC.DEF'
	INCLUDE 'INCLIB:DLTREC.DEF'
	INCLUDE 'INCLIB:LSPREC.DEF'
	INCLUDE 'INCLIB:DSPREC.DEF'
	INCLUDE 'INCLIB:LKKREC.DEF'
	INCLUDE 'INCLIB:DKKREC.DEF'
	INCLUDE 'INCLIB:LNBREC.DEF'
	INCLUDE 'INCLIB:DNBREC.DEF'
        INCLUDE 'INCLIB:LTSREC.DEF'
        INCLUDE 'INCLIB:DTSREC.DEF'
        INCLUDE 'INCLIB:LWIREC.DEF'
        INCLUDE 'INCLIB:DWIREC.DEF'
        INCLUDE 'INCLIB:LSCREC.DEF'
        INCLUDE 'INCLIB:DSCREC.DEF'
        INCLUDE 'INCLIB:LBNREC.DEF'
        INCLUDE 'INCLIB:DBNREC.DEF'

        INCLUDE 'INCLIB:LDBREC.DEF'
        INCLUDE 'INCLIB:DDBREC.DEF'

        INCLUDE 'INCLIB:LCPREC.DEF'
        INCLUDE 'INCLIB:DCPREC.DEF'

        INCLUDE 'INCLIB:LTRREC.DEF'
        INCLUDE 'INCLIB:DTRREC.DEF'

        INCLUDE 'INCLIB:LSSREC.DEF'
        INCLUDE 'INCLIB:DSSREC.DEF'

        INCLUDE 'INCLIB:LSTREC.DEF'
        INCLUDE 'INCLIB:DSTREC.DEF'

        INCLUDE 'INCLIB:LTGREC.DEF'
        INCLUDE 'INCLIB:DTGREC.DEF'

	INTEGER*4 LBUF(LLTRECLEN)
	INTEGER*4 SBUF(LSPRECLEN)
	INTEGER*4 KBUF(LKKRECLEN)
	INTEGER*4 NBUF(LNBRECLEN)
        INTEGER*4 TBUF(LTSRECLEN)
        INTEGER*4 WBUF(LWIRECLEN)
        INTEGER*4 CBUF(LSCRECLEN)
        INTEGER*4 BBUF(LBNRECLEN)

        INTEGER*4 DBBUF(LDBRECLEN)
        INTEGER*4 CPBUF(LCPRECLEN)
        INTEGER*4 SSBUF(LSSRECLEN)
        INTEGER*4 TRBUF(LTRRECLEN)
        INTEGER*4 STBUF(LSTRECLEN)
        INTEGER*4 TGBUF(LTGRECLEN)

	INTEGER*4 I


	TYPE*,'LOTTO '  
	DO 70 I=1,LLTRECLEN
	LLTREC(I)=I
70	CONTINUE
	DO 80 I=1,NUMLTO
	CALL GAMLOG(TLTO,I,DLTREC,LLTREC)
	CALL LOGGAM(TLTO,I,DLTREC,LBUF)
80	CONTINUE
	DO 90 I=1,LLTRECLEN
	IF(LLTREC(I).NE.LBUF(I)) TYPE*,I,LLTREC(I),LBUF(I)
90	CONTINUE


	TYPE*,'SPORTS '
	DO 100 I=1,LSPRECLEN
	LSPREC(I)=I
100	CONTINUE
	DO 110 I=1,NUMSPT
	CALL GAMLOG(TSPT,I,DSPREC,LSPREC)
	CALL LOGGAM(TSPT,I,DSPREC,SBUF)
110	CONTINUE
	DO 120 I=1,LSPRECLEN
	IF(LSPREC(I).NE.SBUF(I)) TYPE*,I,LSPREC(I),SBUF(I)
120	CONTINUE


	TYPE*,'JOKER '              
	DO 160 I=1,LKKRECLEN
	LKKREC(I)=I
160	CONTINUE
	DO 170 I=1,NUMKIK
	CALL GAMLOG(TKIK,I,DKKREC,LKKREC)
	CALL LOGGAM(TKIK,I,DKKREC,KBUF)
170	CONTINUE
	DO 180 I=1,LKKRECLEN
	IF(LKKREC(I).NE.KBUF(I)) TYPE*,I,LKKREC(I),KBUF(I)
180	CONTINUE


	TYPE*,'NUMBERS '
	DO 190 I=1,LNBRECLEN
	LNBREC(I)=I
190	CONTINUE
	DO 200 I=1,NUMNBR
	CALL GAMLOG(TNBR,I,DNBREC,LNBREC)
	CALL LOGGAM(TNBR,I,DNBREC,NBUF)
200	CONTINUE
	DO 210 I=1,LNBRECLEN
	IF(LNBREC(I).NE.NBUF(I)) TYPE*,I,LNBREC(I),NBUF(I)
210	CONTINUE


        TYPE*,'TOTO SELECT '
        DO 220 I=1,LTSRECLEN
        LTSREC(I)=I
220     CONTINUE
        DO 230 I=1,NUMTSL
        CALL GAMLOG(TTSL,I,DTSREC,LTSREC)
        CALL LOGGAM(TTSL,I,DTSREC,TBUF)
230     CONTINUE
        DO 240 I=1,LTSRECLEN
        IF(LTSREC(I).NE.TBUF(I)) TYPE*,I,LTSREC(I),TBUF(I)
240     CONTINUE


        TYPE*,'WINNERS TIP '
        DO 250 I=1,LWIRECLEN
        LWIREC(I)=I
250     CONTINUE
        DO 260 I=1,NUMWIT
        CALL GAMLOG(TWIT,I,DWIREC,LWIREC)
        CALL LOGGAM(TWIT,I,DWIREC,WBUF)
260     CONTINUE
        DO 270 I=1,LWIRECLEN
        IF(LWIREC(I).NE.WBUF(I)) TYPE*,I,LWIREC(I),WBUF(I)
270     CONTINUE


        TYPE*,'SCORE '      
        DO 280 I=1,LSCRECLEN
        LSCREC(I)=I
280     CONTINUE
        DO 290 I=1,NUMSCR
        CALL GAMLOG(TSCR,I,DSCREC,LSCREC)
        CALL LOGGAM(TSCR,I,DSCREC,CBUF)
290     CONTINUE
        DO 300 I=1,LSCRECLEN
        IF(LSCREC(I).NE.CBUF(I)) TYPE*,I,LSCREC(I),CBUF(I)
300     CONTINUE

        TYPE*,'BINGO'       
        DO 510 I=1,LBNRECLEN
        LBNREC(I)=I
510     CONTINUE
        DO 520 I=1,NUMBGO
        CALL GAMLOG(TBNG,I,DBNREC,LBNREC)
        CALL LOGGAM(TBNG,I,DBNREC,BBUF)
520     CONTINUE
        DO 530 I=1,LBNRECLEN
        IF(LBNREC(I).NE.BBUF(I)) TYPE*,I,LBNREC(I),BBUF(I),DBNREC(I)
530     CONTINUE


        TYPE*,'SUPER DOUBLE '
        DO 610 I=1,LDBRECLEN
        LDBREC(I)=I
610     CONTINUE
        DO 620 I=1,NUMDBL
        CALL GAMLOG(TDBL,I,DDBREC,LDBREC)
        CALL LOGGAM(TDBL,I,DDBREC,DBBUF)
620     CONTINUE
        DO 630 I=1,LDBRECLEN
        IF(LDBREC(I).NE.DBBUF(I)) TYPE*,I,LDBREC(I),DBBUF(I)
630     CONTINUE


        TYPE*,'TODAYS COUPLE '
        DO 710 I=1,LCPRECLEN
        LCPREC(I)=I
710     CONTINUE
        DO 720 I=1,NUMCPL
        CALL GAMLOG(TCPL,I,DCPREC,LCPREC)
        CALL LOGGAM(TCPL,I,DCPREC,CPBUF)
720     CONTINUE
        DO 730 I=1,LCPRECLEN
        IF(LCPREC(I).NE.CPBUF(I)) TYPE*,I,LCPREC(I),CPBUF(I)
730     CONTINUE

        TYPE*,'SUPERSCORE '   
        DO 880 I=1,LSSRECLEN
        LSSREC(I)=I
880     CONTINUE
        DO 890 I=1,NUMSSC
        CALL GAMLOG(TSSC,I,DSSREC,LSSREC)
        CALL LOGGAM(TSSC,I,DSSREC,SSBUF)
890     CONTINUE
        DO 895 I=1,LSSRECLEN
        IF(LSSREC(I).NE.SSBUF(I)) TYPE*,I,LSSREC(I),SSBUF(I)
895     CONTINUE

        TYPE*,'TODAYS TRIO '
        DO 980 I=1,LTRRECLEN
        LTRREC(I)=I
980     CONTINUE
        DO 990 I=1,NUMTRP
        CALL GAMLOG(TTRP,I,DTRREC,LTRREC)
        CALL LOGGAM(TTRP,I,DTRREC,TRBUF)
990     CONTINUE
        DO 995 I=1,LTRRECLEN
        IF(LTRREC(I).NE.TRBUF(I)) TYPE*,I,LTRREC(I),TRBUF(I)
995     CONTINUE

        TYPE*,'SUPER TRIPLE '
        DO 1000 I=1,LSTRECLEN
        LSTREC(I)=I
1000    CONTINUE
        DO 1005 I=1,NUMSTR
        CALL GAMLOG(TSTR,I,DSTREC,LSTREC)
        CALL LOGGAM(TSTR,I,DSTREC,STBUF)
1005    CONTINUE
        DO 1010 I=1,LSTRECLEN
        IF(LSTREC(I).NE.STBUF(I)) TYPE*,I,LSTREC(I),STBUF(I)
1010    CONTINUE

        TYPE*,'TotoGolo '
        DO 1100 I=1,LTGRECLEN
        LTGREC(I)=I
1100    CONTINUE
        DO 1105 I=1,NUMTGL
        CALL GAMLOG(TTGL,I,DTGREC,LTGREC)
        CALL LOGGAM(TTGL,I,DTGREC,TGBUF)
1105    CONTINUE
        DO 1110 I=1,LTGRECLEN
        IF(LTGREC(I).NE.TGBUF(I)) TYPE*,I,LTGREC(I),TGBUF(I)
1110    CONTINUE

	CALL GSTOP(GEXIT_SUCCESS)

	END
