C SUBROUTINE UPDIGS
C
C V01 01-AUG-2014 SCML Placard Project
C
C SUBROUTINE TO UPDATE AGENT IGS TRANSACTION SERIAL NUMBER
C
C
C=======OPTIONS /CHECK=NOOVERFLOW/EXT
        SUBROUTINE UPDIGS(TRABUF)
        IMPLICIT NONE
C
        INCLUDE 'INCLIB:SYSPARAM.DEF'
        INCLUDE 'INCLIB:SYSEXTRN.DEF'
        INCLUDE 'INCLIB:GLOBAL.DEF'
        INCLUDE 'INCLIB:DESTRA.DEF'
        INCLUDE 'INCLIB:AGTCOM.DEF'
C
C
        INTEGER*4  IGSTYP ! IGS TRANSACTION TYPE
        INTEGER*4  GTYP   ! GAME TYPE
        INTEGER*4  GIND   ! GAME INDEX
        INTEGER*4  TER    ! TERMINAL NUMBER
C
        IGSTYP =  TRABUF(TIGS_TTYP)
        GTYP   =  TRABUF(TGAMTYP)
        GIND   =  TRABUF(TGAMIND)
        TER    =  TRABUF(TTER)
C
        IF(IGSTYP .EQ. IGSWAG) GOTO 100     !TIGS WAG UPDATE
        IF(IGSTYP .EQ. IGSVAL) GOTO 200     !TIGS VAL UPDATE
        IF(IGSTYP .EQ. IGSPAY) GOTO 300     !TIGS PAY UPDATE
        IF(IGSTYP .EQ. IGSCAN) GOTO 400     !TIGS CAN UPDATE
C
        RETURN
C
C TIGS WAG UPDATE
C
100     CONTINUE
C
C UPDATE AGENT TRANSACTION SERIAL NUMBER
C
        IF (GTYP .EQ. TODS .AND. GIND .EQ. 1) THEN !PLACARD
           AGTTAB(ALSTRA,TER) = TRABUF(TSER)
           AGTTAB(ALSWAG,TER) = TRABUF(TSER)
        ENDIF
        RETURN
C
C TIGS VAL UPDATE
C
200     CONTINUE
C
C UPDATE AGENT TRANSACTION SERIAL NUMBER
C
        IF (GTYP .EQ. TODS .AND. GIND .EQ. 1) THEN !PLACARD
           AGTTAB(ALSTRA,TER) = TRABUF(TSER)
        ENDIF
        RETURN
C
C TIGS PAY UPDATE
C
300     CONTINUE
C
C UPDATE AGENT TRANSACTION SERIAL NUMBER
C
        IF (GTYP .EQ. TODS .AND. GIND .EQ. 1) THEN !PLACARD
           AGTTAB(ALSTRA,TER) = TRABUF(TSER)
           AGTTAB(ALSVAL,TER) = TRABUF(TSER)
        ENDIF
        RETURN
C
C TIGS CAN UPDATE
C
400     CONTINUE
C
C UPDATE AGENT TRANSACTION SERIAL NUMBER
C
        IF (GTYP .EQ. TODS .AND. GIND .EQ. 1) THEN !PLACARD
           AGTTAB(ALSTRA,TER) = TRABUF(TSER)
           AGTTAB(ALSCAN,TER) = TRABUF(TSER)
        ENDIF
        RETURN
C
        END
