C
C SUBROUTINE VALSUP
C $Log:   GXAFXT:[GOLS]VALSUP.FOV  $
C  
C     Rev 1.0   17 Apr 1996 15:49:32   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.2   02 Sep 1994 18:38:16   HXK
C  Merge of May,June RFSS batch
C  
C     Rev 1.2   27 Jun 1994  9:59:24   HXK
C  ALLOW SUPPRESSION OF GAMES WITHOUT KICKER (E.G. LONGEN)
C  
C     Rev 1.1   08 Feb 1993 17:00:38   EBD
C  dded check to determine if Kicker game is participating
C  
C     Rev 1.0   21 Jan 1993 18:00:44   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - valupd.for **
C
C
C
C SUBROUTINE TO CHECK IF VALIDATIONS ARE SUPRESSED BY GAME
C
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE VALSUP(TRABUF,ST)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:AGTCOM.DEF'
	INCLUDE 'INCLIB:DESTRA.DEF'
C
	INTEGER*4 AGAME, TER, GAME, KGAME, ST
C
	ST=0
	GAME=TRABUF(TGAM)
	TER =TRABUF(TTER)
	AGAME=AGTGAM(GFLAGS,GAME,TER)
	IF(TSBIT(AGTTAB(AGTTYP,TER),AGTVAL))   TRABUF(TERR)=SUPR
	IF(TSBIT(AGAME,AGTVAL))                TRABUF(TERR)=SUPR
	IF(TSBIT(P(SUPGVA),GAME))              TRABUF(TERR)=SUPR
C
C ALSO CHECK COMPANION GAME (KICKER) IF PARTICIPATING.
C
	KGAME = TRABUF(TVKGME)
        IF(KGAME .GT. 0) THEN
           AGAME = AGTGAM(GFLAGS,KGAME,TER)
           IF(TSBIT(AGAME,AGTVAL))                TRABUF(TERR)=SUPR
           IF(TSBIT(P(SUPGVA),GAME))              TRABUF(TERR)=SUPR
        ENDIF
	IF(TRABUF(TERR).EQ.SUPR) ST=-1
	RETURN
	END
