C
C SUBROUTINE ACTSNP
C $Log:   GXAFXT:[GOLS]ACTSNP.FOV  $
C  
C  V06 31-MAY-2000 PXO Changed subroutine name from ACTAGT -> ACTSNP
C  V05 17 May 1996 11:41:34   HXK
C  Update from Wojtek, Siew Mun
C  
C  V04 11 Jun 1993 16:21:12   HXK
C  ADDED AGTINF.DEF, MOVED AGTCOM.DEF.
C  
C  V03 21 Jan 1993 15:34:38   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C
C VIS_ACTSNP.FOR
C
C V02 01-AUG-90 XXX RELEASED FOR VAX
C
C V01 01-MAR-90 XXX INITIAL RELEASE FOR DENMARK
C
C
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C This item is the property of GTECH Corporation, Providence, Rhode
C Island, and contains confidential and trade secret information. It
C may not be transferred from the custody or control of GTECH except
C as authorized in writing by an officer of GTECH. Neither this item
C nor the information it contains may be used, transferred,
C reproduced, published, or disclosed, in whole or in part, and
C directly or indirectly, except as expressly authorized by an
C officer of GTECH, pursuant to written agreement.
C
C Copyright 1991 GTECH Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE ACTSNP(AGT,LKEY)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
        INCLUDE 'INCLIB:AGTINF.DEF'
        INCLUDE 'INCLIB:AGTCOM.DEF'
	INCLUDE 'INCLIB:VISCOM.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:TASKID.DEF'
	INCLUDE 'INCLIB:DESTRA.DEF'
	INCLUDE 'INCLIB:PRMLOG.DEF'
C
	INTEGER*4 MIN/0/,HR/0/,SEC/0/,SER/0/
	INTEGER*4 ASTAT(4,54),BUF(LREC*3),BLANK
	INTEGER*4 L, TOTON, IND, SAGT, J, I, DUMMY, ST
	INTEGER*4 OFFSET, LKEY, AGT
	DATA	  BLANK/'    '/
C
C
C CACULATE BLOCK AND INDEX FOR TRANSACTION
C
	IF(LKEY.EQ.8) GOTO 5
	OFFSET=PERFRM(3,PERTRA)+1
	OFFSET=OFFSET*10
	SER=NXTSER-OFFSET
	IF(SER.LE.0.OR.SER.EQ.NXTSER) SER=1
C
C OPEN TM FILE
C
	CALL OPENW(1,SFNAMES(1,PTMF),4,0,0,ST)
	IF(ST.NE.0) THEN
	  WRITE(CLIN23,800) ST
	  CALL USRCLOS1(     1)
	  RETURN
	ENDIF
	CALL TOPEN(1)
C
C READ TRANSACTION
C
1	CONTINUE
	CALL RLOG(SER,BUF,DUMMY,ST)
	IF(ST.GT.0) THEN
	  SER=SER-1
	  GOTO 1
	ENDIF
	CALL USRCLOS1(     1)
	IF(ST.LT.0) THEN
	  WRITE(CLIN23,801) ST,SER
	  RETURN
	ENDIF
C
C CONVERT TRANSACTION FROM LOG FORMAT TO INTERNAL FORMAT
C
	CALL LOGTRA(TRABUF,BUF)
C
C CACULATE TIME
C
	SEC=TRABUF(TTIM)
	HR=SEC/3600
	MIN=(SEC-HR*3600)/60
	SEC=SEC-(HR*3600+MIN*60)
C
C CLEAR PAGE IMAGE
C
5	CONTINUE
	CALL FASTSET(BLANK,NEW(1,1),480)
C
C GET STARTING AGENT
C
	SAGT=AGT
	IF(SAGT.LT.1.OR.SAGT.GT.NUMAGT) SAGT=1
	DO 20 I=1,54
	DO 20 J=1,4
	ASTAT(J,I)=0
20	CONTINUE
C
C GET AGENT DATA
C
	IND=0
	IF(SAGT+53.GT.NUMAGT) SAGT=NUMAGT-53
	DO 30 I=SAGT,SAGT+53
	IND=IND+1
	ASTAT(1,IND)=I
	ASTAT(2,IND)=AGTTAB(ALSTRA,I)
	ASTAT(3,IND)=AGTHTB(AOPSTS,I)
	IF(ASTAT(3,IND).NE.2) ASTAT(3,IND)=1
	ASTAT(4,IND)=2
	IF(AGTTAB(ALSTRA,I).GE.SER) ASTAT(4,IND)=1
30	CONTINUE
C
C GET TOTAL NUMBER OF AGENTS SIGNED ON
C
	TOTON=0
	DO 35 I=1,NUMAGT
	IF(AGTHTB(AOPSTS,I).EQ.SIGNON) TOTON=TOTON+1
35	CONTINUE
C
C ENCODE SNAPSHOT
C
	WRITE(CLIN1,901) TOTON
	WRITE(CLIN2,902) HR,MIN,SEC
	WRITE(CLIN3,903)
	L=3
	DO 40 I=1,52,3
	L=L+1
	CALL ENCACT(NEW(1,L),ASTAT,I)
40	CONTINUE
	RETURN
C
C
800	FORMAT('TMF assign error - ',I4)
801	FORMAT('TMF read error - ',I4,' serial - ',I4)
901	FORMAT('Agents signed on',I6)
902	FORMAT('Base time ',I2.2,':',I2.2,':',I2.2)
903	FORMAT(3(' Serial    Ter    Status ',2X))
	END
