C SUBROUTINE SLISNP
C
C V12 12-APR-2000 OXK Refunds NOT substracted from payouts!
C V11 15-MAR-2000 OXK Added printing of counts for sales
C V10 27-NOV-1997 UXN Changes for PITKA (singles,doubles etc...)
C V09 17 Apr 1996 HXK Release of Finland for X.25, Telephone Betting, 
C			Instant Pass Thru Phase 1
C V08 03 Jan 1996 PXB Fixed percentage display
C V07 18 Oct 1993 GXA Use expanded DTSSBD.
C V06 17 Oct 1993 GXA Corrected Percentage overflows.
C V05 24 Sep 1993 GXA Increased display of amounts to 10 charaters.
C V04 14 Jun 1993 HXK added AGTINF.DEF, PRMAGT.DEF
C V03 21 Jan 1993 DAB Initial Release
C  			Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  			DEC Baseline
C V02 23-OCT-1991 GCAN INITIAL RELEASE FOR THE NETHERLANDS
C V01 01-AUG-1990 XXX  RELEASED FOR VAX
C
C TOTO SELECT LIABILITY SNAPSHOT
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C This item is the property of GTECH Corporation, Providence, Rhode
C Island, and contains confidential and trade secret information. It
C may not be transferred from the custody or control of GTECH except
C as authorized in writing by an officer of GTECH. Neither this item
C nor the information it contains may be used, transferred,
C reproduced, published, or disclosed, in whole or in part, and
C directly or indirectly, except as expressly authorized by an
C officer of GTECH, pursuant to written agreement.
C
C Copyright 2000 GTECH Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE SLISNP(DRAW,GIND)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'

	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:TSLCOM.DEF'
	INCLUDE 'INCLIB:DTSREC.DEF'
        INCLUDE 'INCLIB:AGTINF.DEF'
        INCLUDE 'INCLIB:PRMAGT.DEF'
	INCLUDE 'INCLIB:VISCOM.DEF'
	INCLUDE 'INCLIB:DATBUF.DEF'
	INCLUDE 'INCLIB:GTNAMES.DEF'
C
C
	INTEGER*4 CNT, AMT
	PARAMETER(CNT = 1)
	PARAMETER(AMT = 2)
C
	REAL*4    TOTPCT
	REAL*4    DSTPCT(TSLDIV)
C
	INTEGER*2 BDATE(LDATE_LEN),EDATE(LDATE_LEN)
	INTEGER*4 FDB(7)
	INTEGER*4 DSTSBD(TSLDIV,NUMTOT),DSTWBD(TSLDIV,NUMTOT)
	INTEGER*4 DRAW,CDRAW,GIND,GNUM,ST
	INTEGER*4 TOTSBD,TOTSBDCNT,TOTWBD
	INTEGER*4 I,K,S
C
C CHECK THE GAME INDEX
C
	IF(GIND.LT.1.OR.GIND.GT.NUMTSL) THEN
	   WRITE(CLIN23,3000) GTNAMES(TTSL)
	   RETURN
	ENDIF
C
C GET THE GAME NUMBER
C
	GNUM=GTNTAB(TTSL,GIND)
	IF(GNUM.LT.1) THEN
	   WRITE(CLIN23,3010) GTNAMES(TTSL),GIND
	   RETURN
	ENDIF
C
C CHECK WHAT DRAW NUMBER TO USE
C
	IF(DRAW.LT.1) DRAW=DAYDRW(GNUM)
	IF(DRAW.EQ.0.OR.DRAW.GT.DAYHDR(GNUM)) DRAW=DAYHDR(GNUM)
	IF(DRAW.LT.1) DRAW=1
	IF(DRAW.EQ.CDRAW) GOTO 100
C
	TOTSBD=0
	TOTSBDCNT=0
	TOTWBD=0
C
C OPEN GAME FILE AND READ CORRECT DRAW, IF NOT EQUAL TO CURREN DRAW
C
	CALL OPENW(1,GFNAMES(1,GNUM),4,0,0,ST)
	CALL IOINIT(FDB,1,DTSSEC*256)
	IF(ST.NE.0) THEN
	   WRITE(CLIN23,3020) (GFNAMES(K,GNUM),K=1,5),ST
	   CALL CLOSEFIL (FDB)
	   RETURN
	ENDIF
C
	CALL READW(FDB,DRAW,DTSREC,ST)
	IF(ST.NE.0) THEN
	   WRITE(CLIN23,3030) (GFNAMES(K,GNUM),K=1,5),ST
	   CALL CLOSEFIL (FDB)
	   RETURN
	ENDIF
C
	IF(DTSSTS.EQ.GAMNUL) THEN
	   WRITE(CLIN23,3040) GTNAMES(TTSL),GIND,DRAW
	   CALL CLOSEFIL (FDB)
	   RETURN
	ENDIF
	CALL CLOSEFIL (FDB)
C
C STORE FILE VARIABLES IN TEPMORARILY VARIABLES AND
C CALCULATE TOTALS WITHOUT REFUNDS AND WIN PAYED PERCENTAGES
C
	CDRAW=DRAW
	DO 10 I=1,TSLDIV
	   DSTSBD(I,CNT)=DTSSBD(I,CNT)-DTSRBD(I,CNT)
	   DSTSBD(I,AMT)=DTSSBD(I,AMT)-DTSRBD(I,AMT)
	   DSTWBD(I,AMT)=DTSWBD(I,AMT)			    ! -DTSRBD(I,AMT)
	   DSTPCT(I) = 0.0
	   IF(DSTSBD(I,AMT).GT.0) 
     *        DSTPCT(I) = (FLOAT(DSTWBD(I,AMT))/DSTSBD(I,AMT))*100
	   TOTSBD=TOTSBD+DSTSBD(I,AMT)
	   TOTSBDCNT=TOTSBDCNT+DSTSBD(I,CNT)
	   TOTWBD=TOTWBD+DSTWBD(I,AMT)
10	CONTINUE
	TOTPCT = 0.0
	IF(TOTSBD.GT.0) TOTPCT = (FLOAT(TOTWBD)/TOTSBD)*100
C
	BDATE(VCDC)=DTSBSD
	EDATE(VCDC)=DTSESD
	CALL LCDATE(BDATE)
	CALL LCDATE(EDATE)
C
C ENCODE VISION SNAPSHOT
C
100	CONTINUE
	WRITE(CLIN1,1001) DRAW,(BDATE(S),S=9,11),(EDATE(S),S=9,13)
	WRITE(CLIN2,1002) GTNAMES(TTSL),GIND
	WRITE(CLIN4,1003)
	WRITE(CLIN5,1010) DSTSBD(5,CNT), DSTSBD(6,CNT), DSTSBD(1,CNT)
	WRITE(CLIN6,1005) CSMONY(DSTSBD(5,AMT),11,BETUNIT),
     *			  CSMONY(DSTSBD(6,AMT),11,BETUNIT),
     *			  CSMONY(DSTSBD(1,AMT),11,BETUNIT)
	WRITE(CLIN7,1006) CSMONY(DSTWBD(5,AMT),11,VALUNIT),
     *			  CSMONY(DSTWBD(6,AMT),11,VALUNIT),
     *			  CSMONY(DSTWBD(1,AMT),11,VALUNIT)
	WRITE(CLIN8,1007) DSTPCT(5),DSTPCT(6),DSTPCT(1)
	WRITE(CLIN10,1009)
	WRITE(CLIN11,1010) DSTSBD(2,CNT), DSTSBD(3,CNT), DSTSBD(4,CNT)
	WRITE(CLIN12,1005) CSMONY(DSTSBD(2,AMT),11,BETUNIT),
     *			   CSMONY(DSTSBD(3,AMT),11,BETUNIT),
     *			   CSMONY(DSTSBD(4,AMT),11,BETUNIT)
	WRITE(CLIN13,1006) CSMONY(DSTWBD(2,AMT),11,VALUNIT),
     *			   CSMONY(DSTWBD(3,AMT),11,VALUNIT),
     *			   CSMONY(DSTWBD(4,AMT),11,VALUNIT)
	WRITE(CLIN14,1007) DSTPCT(2),DSTPCT(3),DSTPCT(4)
	WRITE(CLIN16,1015)
	WRITE(CLIN17,1010) TOTSBDCNT
	WRITE(CLIN18,1005) CSMONY(TOTSBD,11,BETUNIT)
	WRITE(CLIN19,1006) CSMONY(TOTWBD,11,VALUNIT)
	WRITE(CLIN20,1008) TOTPCT
	WRITE(CLIN21,2000)
	RETURN
C
C FORMAT STATEMENTS FOR SLISNP
C
1001	FORMAT('SLISNP  Event: ',I3,1X,3A2,'- ',5A2,' *')
1002	FORMAT(2X,A8,I2,'   Payout Percentage')
1003	FORMAT(28X,'SINGLES',12X,'DOUBLES',12X,'THREES')
1005	FORMAT(' NET SALES           :',2X,A11,8X,A11,8X,A11)
1006	FORMAT(' PAYOUTS             :',2X,A11,8X,A11,8X,A11)
1007	FORMAT(' PAYOUT PERCENTAGE   :',5X,F8.2,'%',10X,F8.2,'%',10X,F8.2,'%')
1008	FORMAT(' PAYOUT PERCENTAGE   :',5X,F8.2)
1009	FORMAT(28X,'FOURS  ',12X,'FIVES  ',12X,'SIXES')
1010	FORMAT(' NET COUNT           :',2X,I11,8X,I11,8X,I11)
1015	FORMAT(29X,'TOTAL')
2000	FORMAT(1X,'Net sales (count) = total sales (count) - refunds')
3000	FORMAT('Enter !',A8,' game index ')
3010	FORMAT(A8,1X,I1,' game not active')
3020	FORMAT(5A4,' Open error ',I4)
3030	FORMAT(5A4,' Read error ',I4,' record - ',I4)
3040	FORMAT(A8,1X,I1,' game not initialized, event - ',I4)
	END
