C
C SUBROUTINE EURMILSNP
C
C
C VIS_EURMILSNP.FOR
C
C V03 30-MAR-2016 SCML M16 PROJECT
C V02 20-JUL-2015 SCML Adding support for IGS internal cancel flags
C V01 08-APR-2014 SCML Placard Project
C
C EUR SYSTEM CONTROL SNAPSHOT
C
C
C ERROR MESSAGE #  DESCRIPTION
C ---------------  -----------------------------------------------------
C       5          PASSWORD ERROR WHILE TRYING TO CHANGE EM TIMEOUT
C       6          PASSWORD ERROR WHILE TRYING TO CHANGE EM FIN TIMEOUT
C
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C Copyright 2016 SCML Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW/EXT
        SUBROUTINE EURMILSNP(CLINE, EGAM)
        IMPLICIT NONE
C
        INCLUDE 'INCLIB:SYSPARAM.DEF'
        INCLUDE 'INCLIB:SYSEXTRN.DEF'
C
        INCLUDE 'INCLIB:GLOBAL.DEF'
        INCLUDE 'INCLIB:PRMLOG.DEF'
        INCLUDE 'INCLIB:AGTINF.DEF'
        INCLUDE 'INCLIB:PRMAGT.DEF'
        INCLUDE 'INCLIB:VISCOM.DEF'
        INCLUDE 'INCLIB:CONCOM.DEF'
        INCLUDE 'INCLIB:PROCOM.DEF'
        INCLUDE 'INCLIB:TASKID.DEF'
        INCLUDE 'INCLIB:ENCCOM.DEF'
        INCLUDE 'INCLIB:QUECOM.DEF'
        INCLUDE 'INCLIB:X2XQUE.DEF'
        INCLUDE 'INCLIB:GTNAMES.DEF'
        INCLUDE 'INCLIB:EURCOM.DEF'
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       INPUT ARGUMENTS
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        INTEGER*4  CLINE(20)
        INTEGER*4  EGAM                                                         !EXTERNAL GAME NUMBER (IN EUROMILLIONS SYSTEM)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       LOCAL VARIABLES
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
        INTEGER*4  GSWAG                                                        !GAME SUPRESS WAGER
        INTEGER*4  GSGRR                                                        !GAME SUPRESS GAME RESULTS REPORT
        INTEGER*4  GSICA                                                        !GAME SUPRESS INTERNAL CANCELLATION
C
        INTEGER*4  ST
        INTEGER*4  BITMAP1
        INTEGER*4  KEYNUM
        INTEGER*4  POS
        INTEGER*4  GIND
        INTEGER*4  GTYP
        INTEGER*4  BUF(CDLEN)
        INTEGER*4  TEMP
        INTEGER*4  VALUE
        INTEGER*4  TSKST
C
        INTEGER*4  EURQUE_LIST(3)
        INTEGER*4  MESS(EDLEN)
C
        INTEGER*4  MAXPRM
        PARAMETER (MAXPRM=13)
C
        REAL*8       K(MAXPRM)                                                  !SNAPSHOT PARAMETER DESCRIPTION
C
        CHARACTER*9  EGAMNAM                                                    !EUROMILLIONS SYSTEM GAME NAME
        CHARACTER    CTEMP(4)                                                   !
        CHARACTER*20 PASPAS                                                     !
        CHARACTER*7  DEFTPASS                                                   !DEFAULT PASSWORD
        CHARACTER*7  PASSENT                                                    !ENTERED PASSWORD
C
        EQUIVALENCE(TEMP,CTEMP)
        EQUIVALENCE(PASPAS,PASSENT)
C
        DATA   K/'INMGR   ','COMMGR  ','OUTMGR  ','EURCOn  ',
     *           'EURTMo  ','FINTMo  ','SUPWAg  ','SUPCAn  ',
     *           'SUPVAl  ','SUPGRrep','SUPFIrep','SUPBIrep',
     *           'SUPICan '/
C
        DATA DEFTPASS/'SUPORTE'/
C
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       BEGIN PROCESS
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        MESS(1) = 63
        MESS(2) = TEEUM
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       GET GAME NUMBER
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        IF(EGAM.LT.1.OR.EGAM.GT.EMAXGAM) THEN
          EGAM = 0
        ELSE
          GTYP = EGNTTAB(GAMTYP,EGAM)
          GIND = EGNTTAB(GAMIDX,EGAM)
          IF(GTYP.LT.1.OR.GTYP.GT.MAXTYP) THEN
            WRITE(CLIN23,9000) EGAM
            RETURN
          ENDIF
          WRITE(EGAMNAM,700) GTNAMES(GTYP), GIND
700     FORMAT(A8,I1)
        ENDIF
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C EURSNP INPUT
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        VALUE = 0
        TEMP  = 0
        POS   = 1
        CALL KEY(CLINE,K,MAXPRM,POS,KEYNUM)
C
        IF(POS.GT.40) GOTO 300                                                  !NO INPUT
        IF(KEYNUM.EQ.0)GOTO 200                                                 !INPUT ERROR
C
        CALL NUMB(CLINE,POS,VALUE)                                              !GET VALUE
        IF(VALUE.LT.0)  GOTO 205
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       CLEAR COMMAND MESSAGE BUFFER
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
2       CONTINUE
        CALL FASTSET(0,BUF,CDLEN)
        GOTO(200,200,200,504,
     *       505,506,507,508,
     *       509,510,511,512,
     *       513) KEYNUM
C
        GOTO 200
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       EURCOn CHANGE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
504     CONTINUE
        IF(VALUE.NE.0.AND.VALUE.NE.1) GOTO 205
        BUF(1)=EUMILF
        BUF(2)=VALUE
        BUF(3)=TCPAR
        GOTO 250
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       EURTMo CHANGE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
505     CONTINUE
        CALL PASSWORD(5,PASPAS)
        IF (PASSENT .NE. DEFTPASS) THEN
          MESS(3) = 5
          CALL QUEMES(MESS)
          GOTO 206
        ENDIF
        IF(VALUE.LT.1.OR.VALUE.GT.50) GOTO 2051
        BUF(1)=EUTIMOUT                                                         !EUROMILLIONS SYSTEM MESSAGES TIMEOUT
        BUF(2)=VALUE
        BUF(3)=TCPAR
        GOTO 250
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       FINTMo CHANGE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
506     CONTINUE
        CALL PASSWORD(5,PASPAS)
        IF (PASSENT .NE. DEFTPASS) THEN
          MESS(3) = 6
          CALL QUEMES(MESS)
          GOTO 206
        ENDIF
        IF(VALUE.LT.1.OR.VALUE.GT.50) GOTO 2052
        BUF(1)=EUFINTO                                                          !EUROMILLIONS FINANCIAL REPORTS TIMEOUT
        BUF(2)=VALUE
        BUF(3)=TCPAR
        GOTO 250
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SUPWAg CHANGE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
507     CONTINUE
        IF(VALUE.NE.0.AND.VALUE.NE.1) GOTO 205
        IF(EGAM.EQ.0) THEN
          BUF(1)=EUSPWAG                                                        !EUROMILLIONS SYSTEM WAGERS
          BUF(2)=VALUE
        ELSE
          BITMAP1=P(EUSPGWAG)
          IF(VALUE.EQ.0) THEN
            CALL BCLR(BITMAP1,EGAM-1)
          ELSE
            CALL BSET(BITMAP1,EGAM-1)
          ENDIF
          BUF(1)=EUSPGWAG
          BUF(2)=BITMAP1
        ENDIF
        BUF(3)=TCPAR
        GOTO 250
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SUPCAn CHANGE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
508     CONTINUE
        IF(VALUE.NE.0.AND.VALUE.NE.1) GOTO 205
        BUF(1)=EUSPCAN                                                          !EUROMILLIONS SYSTEM CANCELLATIONS
        BUF(2)=VALUE
        BUF(3)=TCPAR
        GOTO 250
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SUPVAl CHANGE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
509     CONTINUE
        IF(VALUE.NE.0.AND.VALUE.NE.1) GOTO 205
        BUF(1)=EUSPVAL                                                          !EUROMILLIONS SYSTEM VALIDATIONS
        BUF(2)=VALUE
        BUF(3)=TCPAR
        GOTO 250
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SUPGRrep CHANGE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
510     CONTINUE
        IF(VALUE.NE.0.AND.VALUE.NE.1) GOTO 205
        IF(EGAM.EQ.0) THEN
          BUF(1)=EUSPGRR                                                        !EUROMILLIONS SYSTEM GAME RESULTS REPORT
          BUF(2)=VALUE
        ELSE
          BITMAP1=P(EUSPGGRR)
          IF(VALUE.EQ.0) THEN
            CALL BCLR(BITMAP1,EGAM-1)
          ELSE
            CALL BSET(BITMAP1,EGAM-1)
          ENDIF
          BUF(1)=EUSPGGRR
          BUF(2)=BITMAP1
        ENDIF
        BUF(3)=TCPAR
        GOTO 250
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SUPFIrep CHANGE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
511     CONTINUE
        IF(VALUE.NE.0.AND.VALUE.NE.1) GOTO 205
        BUF(1)=EUSPFIR                                                          !EUROMILLIONS SYSTEM FINANCIAL REPORTS (OTHER THAN BILLING REPORTS)
        BUF(2)=VALUE
        BUF(3)=TCPAR
        GOTO 250
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SUPBIrep CHANGE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
512     CONTINUE
        IF(VALUE.NE.0.AND.VALUE.NE.1) GOTO 205
        BUF(1)=EUSPBIR                                                          !EUROMILLIONS SYSTEM BILLING REPORTS
        BUF(2)=VALUE
        BUF(3)=TCPAR
        GOTO 250
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       SUPICan CHANGE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
513     CONTINUE
        IF(VALUE.NE.0.AND.VALUE.NE.1) GOTO 205
        IF(EGAM.EQ.0) THEN
          BUF(1)=EUSPICA                                                        !EUROMILLIONS SYSTEM AUTOMATIC CANCELS
          BUF(2)=VALUE
        ELSE
          BITMAP1=P(EUSPGICA)
          IF(VALUE.EQ.0) THEN
            CALL BCLR(BITMAP1,EGAM-1)
          ELSE
            CALL BSET(BITMAP1,EGAM-1)
          ENDIF
          BUF(1)=EUSPGICA
          BUF(2)=BITMAP1
        ENDIF
        BUF(3)=TCPAR
        GOTO 250
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       INPUT ERROR
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
200     CONTINUE
        WRITE(CLIN23,800)
800     FORMAT('Input error')
C
        RETURN
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       VALUE ERROR
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
205     CONTINUE
        WRITE(CLIN23,801)
801     FORMAT('Value error')
C
        RETURN
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       VALUE ERROR EURTMo
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
2051    CONTINUE
        WRITE(CLIN23,8011)
8011    FORMAT('Value error - Does not fall within interval 1 to 50')
C
        RETURN
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       VALUE ERROR FINTMo
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
2052    CONTINUE
        WRITE(CLIN23,8012)
8012    FORMAT('Value error - Does not fall within interval 1 to 50')
C
        RETURN
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       INVALID PASSWORD
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
206     CONTINUE
        WRITE(CLIN23,802)
802     FORMAT('Invalid Password')
C
        RETURN
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       QUEUE COMMAND BUFFER TO SYSTEM INPUT INPUT QUEUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
250     CONTINUE
        BUF(6)=IDNUM
        CALL VISCMD(BUF,ST)
        CALL XWAIT(2,1,ST)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       BUILD EURSNP SCREEN IMAGE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
300     CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       GET BUFFER UTILIZATION INFORMATION
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        CALL LISTSIZE(QUETAB(1,EUI), EURQUE_LIST(1))                            !INMGR
        CALL LISTSIZE(QUETAB(1,EUC), EURQUE_LIST(2))                            !COMMGR
        CALL LISTSIZE(QUETAB(1,EUO), EURQUE_LIST(3))                            !OUTMGR
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C      GET GAME FLAGS
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        IF(EGAM.NE.0) THEN
          GSWAG = 0
          GSGRR = 0
          GSICA = 0
          IF(TSBIT(P(EUSPGWAG),EGAM-1)) GSWAG = 1
          IF(TSBIT(P(EUSPGGRR),EGAM-1)) GSGRR = 1
          IF(TSBIT(P(EUSPGICA),EGAM-1)) GSICA = 1
        ENDIF
        WRITE(CLIN1,901)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       DISPLAY EUR SYSTEM APP QUEUES
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        WRITE(CLIN3,903) K(1), EURQUE_LIST(1),
     *                   K(2), EURQUE_LIST(2),
     *                   K(3), EURQUE_LIST(3)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       DISPLAY EUR SYSTEM PARAMETERS
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        ST = 0
        CALL STTSK(8HCOMMGR  ,TSKST,ST)                                         !VERIFY IF COMMGR IS OK
        IF(ST.NE.4) THEN                                                        !IF COMMGR OK
          IF(EURS_ATTACHSTS.NE.0) THEN                                          !ATTACH HAS BEEN DONE
            WRITE(CLIN6,910)  K(4), P(EUMILF)                                   !EURCOn PARAMETER
            WRITE(CLIN7,9101) K(5), P(EUTIMOUT),                                !EUR TIMEOUT (SEC)
     *                        EURS_ATTACHDAT(3),                                !DAY ATTACHED (DD)
     *                        EURS_ATTACHDAT(2),                                !MONTH ATTACHED (MM)
     *                        EURS_ATTACHDAT(1),                                !YEAR ATTACHED (YYYY)
     *                        EURS_ATTACHTIM                                    !TIME ATTACHED (H24:MI:SS)
          ELSE                                                                  !ATTACH HAS NOT BEEN DONE
            WRITE(CLIN6,9102) K(4), P(EUMILF)                                   !EURCOn PARAMETER
            WRITE(CLIN7,9103) K(5), P(EUTIMOUT)                                 !EUR TIMEOUT (SEC)
          ENDIF
C
          IF(EURS_DETACHFLG.NE.0) THEN                                          !A DETACH HAS OCCURRED
            WRITE(CLIN8,9104) K(6), P(EUFINTO),                                 !FIN TIMEOUT (SEC)
     *                        EURS_DETACHDAT(3),                                !LAST DAY DETACHED (DD)
     *                        EURS_DETACHDAT(2),                                !LAST MONTH DETACHED (MM)
     *                        EURS_DETACHDAT(1),                                !LAST YEAR DETACHED (YYYY)
     *                        EURS_DETACHTIM                                    !LAST TIME DETACHED (H24:MI:SS)
          ELSE                                                                  !DETACH HAS NOT BEEN DONE
            WRITE(CLIN8,9105) K(6), P(EUFINTO)                                  !FIN TIMEOUT (SEC)
          ENDIF
        ELSE                                                                    !IF COMMGR NOT RUNNING DO NOT DISPLAY ATTACH AND DETACH TIME STAMP
          WRITE(CLIN6,9102) K(4), P(EUMILF)                                     !EURCOn PARAMETER
          WRITE(CLIN7,9103) K(5), P(EUTIMOUT)                                   !EUR TIMEOUT (SEC)
          WRITE(CLIN8,9105) K(6), P(EUFINTO)                                    !FIN TIMEOUT (SEC)
        ENDIF
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C-      DISPLAY EUR SYSTEM GAMES GLOBAL PARAMETERS
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
        IF(EGAM.EQ.0) THEN
          WRITE(CLIN12,911) K(7), P(EUSPWAG),K(8) , P(EUSPCAN),
     *                      K(9), P(EUSPVAL),K(10), P(EUSPGRR)
          WRITE(CLIN13,9111) K(11), P(EUSPFIR), 
     *                       K(12), P(EUSPBIR),
     *                       K(13), P(EUSPICA)
        ELSE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       DISPLAY EUR SYSTEM GAMES SPECIFIC PARAMETERS
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
          IF(GTYP.EQ.TEUM) THEN
            WRITE(CLIN12,912) EGAMNAM,
     *                        K(7) , GSWAG,
     *                        K(10), GSGRR,
     *                        K(13), GSICA
            WRITE(CLIN13,900)
          ELSEIF(GTYP.EQ.TRAF) THEN
            WRITE(CLIN12,913) EGAMNAM,
     *                        K(10), GSGRR
            WRITE(CLIN13,900)
          ENDIF
        ENDIF
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       DISPLAY SYSTEM STATS
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
        WRITE(CLIN16,950)
        WRITE(CLIN17,9501) EURS_NXTXRF,                                         !NEXT CROSS REFERENCE NUMBER
     *                     EURS_TOTEURTMO,                                      !TOTAL # OF MESSAGES TIMED OUT
     *                     EURS_TOTEURATO                                       !TOTAL # OF MESSAGES ALREADY TIMED OUT
        WRITE(CLIN18,9502) EURS_TOTOKYPUT,                                      !TOTAL # OF MESSAGES SENT TO EUROMILLIONS SYSTEM
     *                     EURS_TOTOKYGET,                                      !TOTAL # OF MESSAGES RECEIVED FROM EUROMILLIONS SYSTEM
     *                     EURS_TOTWAGTMO,                                      !TOTAL # OF WAGERS TIMED OUT
     *                     EURS_TOTWAGATO                                       !TOTAL # OF WAGERS ALREADY TIMED OUD
        WRITE(CLIN19,9503) EURS_TOTERRPUT,                                      !TOTAL # OF ERRORS WHILE SENDING MESSAGES TO EUROMILLIONS SYSTEM
     *                     EURS_TOTERRGET,                                      !TOTAL # OF ERRORS WHILE GETTING MESSAGES FROM EUROMILLIONS SYSTEM
     *                     EURS_TOTCANTMO,                                      !TOTAL # OF CANCELS TIMED OUT
     *                     EURS_TOTCANATO                                       !TOTAL # OF CANCELS ALREADY TIMED OUT
        WRITE(CLIN20,9504) EURS_TOTICANOK,                                      !TOTAL # OF INTERNAL CANCELS MESSAGES SENT
     *                     EURS_TOTICANER,                                      !TOTAL # OF INTERNAL CANCELS MESSAGES FAILED TO SEND
     *                     EURS_TOTVALTMO,                                      !TOTAL # OF VALIDATIONS TIMED OUT
     *                     EURS_TOTVALATO                                       !TOTAL # OF VALIDATIONS ALREADY TIMED OUT
        WRITE(CLIN21,9505) EURS_TOTICANNS,                                      !TOTAL # OF INTERNAL CANCELS MESSAGES NOT SENT
     *                     EURS_TOTPAYTMO,                                      !TOTAL # OF PAYMENTS TIMED OUT
     *                     EURS_TOTPAYATO                                       !TOTAL # OF PAYMENTS ALREADY TIMED OUT
        WRITE(CLIN22,9506) EURS_TOTFINTMO,                                      !TOTAL # OF FINANCIAL REPORTS TIMED OUT (OTHER THAN THE BILLING REPORT)
     *                     EURS_TOTFINATO                                       !TOTAL # OF FINANCIAL REPORTS ALREAYD TIMED OUT (OTHER THAN THE BILLING REPORT)
C
        RETURN
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C       FORMAT STATEMENTS
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
900     FORMAT(80(' '))
901     FORMAT('**** Euro Milhoes snapshot ****')
903     FORMAT('QUEUES   >  ',3('',A7,I7,3X))
C
910     FORMAT('         >  ',1('*',A7,I6,3X)
     *          1X,'COMMGR Attached?',2X,'Yes')                                 !IS COMMGR ATTACHED TO MESSAGEQ SERVER?
9101    FORMAT('            ',1('*',A7,I6,3X)
     *          1X,'Time Attached',5X,I2.2,'.',I2.2,'.',I4.4,1X,2A4)            !TIME COMMGR ATTACHED TO MESSAGEQ SERVER IN EUROMILLIONS SYSTEM
9102    FORMAT('         >  ',1('*',A7,I6,3X)
     *          1X,'COMMGR Attached?',2X,'No')                                  !IS COMMGR ATTACHED TO MESSAGEQ SERVER?
9103    FORMAT('            ',1('*',A7,I6,3X)
     *          1X,'Time Attached',5X,'??.??.???? ??:??:??')                    !COMMGR IS NOT ATTACHED

9104    FORMAT('            ',1('*',A7,I6,3X),
     *          1X,'Time Last Detach',2X,I2.2,'.',I2.2,'.',I4.4,1X,2A4)         !LAST TIME COMMGR DETACHED FROM MESSAGEQ SERVER IN EUROMILLIONS SYSTEM
9105    FORMAT('            ',1('*',A7,I6,3X),
     *          1X,'Time Last Detach',2X,'??.??.???? ??:??:??')                 !LAST TIME COMMGR DETACHED FROM MESSAGEQ SERVER IN EUROMILLIONS SYSTEM
C
911     FORMAT('EUR      >  ',4('*',A7,I6,3X))
9111    FORMAT('            ',3('*',A7,I6,3X))
C
912     FORMAT(A9      ,'>  ',3('*',A7,I6,3X))
C
913     FORMAT(A9      ,'>  ',1('*',A7,I6,3X))
C
950     FORMAT(19('-'),2X,'E U R   S Y S   S T A T I S T I C S',2X,19('-'))
9501    FORMAT('Next Cross Ref #',2X,I0,                                        !NEXT CROSS SYSTEM REFERENCE #
     *         T36,'Msg TIMO/Alrdy TIMO',2X,I0,'/',I0)                          !TOTAL # OF MESSAGES TIMED OUT/ALREADY TIMED OUT
9502    FORMAT('Msg  PutQ/GetQ',4X,I0,'/',I0,                                   !TOTAL # OF MESSAGES SENT TO/RECEIVED FROM EUROMILLIONS SYSTEM
     *         T37,'Wagers',14X,I0,'/',I0)                                      !TOTAL # OF WAGERS TIMED OUT/ALREADY TIMED OUT
9503    FORMAT('Err  PutQ/GetQ',4X,I0,'/',I0,                                   !TOTAL # OF ERRORS SENDING TO/RECEIVING FROM EUROMILLIONS SYSTEM
     *         T37,'Cancels',13X,I0,'/',I0)                                     !TOTAL # OF CANCELS TIMED OUT/ALREADY TIMED OUT
9504    FORMAT('Ican Sent/Failed',2X,I0,'/',I0,                                 !TOTAL # OF INTERNAL CANCELS SENT/FAILED
     *         T37,'Validations',9X,I0,'/',I0)                                  !TOTAL # OF VALIDATIONS TIMED OUT/ALREADY TIMED OUT (OTHER THAN THE BILLING REPORT)
9505    FORMAT('Ican Not Sent',5X,I0,                                           !TOTAL # OF INTERNAL CANCELS NOT SENT (E.G., INTERNAL CANCEL WAS SUPRESSED)
     *         T37,'Payments',12X,I0,'/',I0)                                    !TOTAL # OF PAYMENTS TIMED OUT/ALREADY TIMED OUT
9506    FORMAT(T37,'Fin Reports',9X,I0,'/',I0)                                  !TOTAL # OF FINANCIAL REPORTS TIMED OUT (OTHER THAN THE BILLING REPORT)
C
9000    FORMAT('Sorry, EUR game ',I2,' not active ')
C
        END
C
C END VIS_EURMILSNP.FOR
C

