C
C SUBROUTINE WDRAW
C $Log:   GXAFXT:[GOLS]WDRAW.FOV  $
C  
C     Rev 1.0   17 Apr 1996 15:58:46   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 18:04:20   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - witver.for **
C
C
C  V01 05-JAN-93 TD  COMBINED WITENT.FOR VERSION OF WDRAW AND THE WITVER.FOR
C		     VERSION OF WDRAW.   THE NDWI INDEX PASSED INTO THIS
C		     ROUTINE DETERMINES THE SUBROUTINE THAT CALLED THIS ROUTINE
C		     NDWI = 1 FOR WITENT CALLS
C		     NDWI = 2 FOR WITVER CALLS
C
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE WDRAW(TIES,NDWI)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:RESCOM.DEF'
C
	INTEGER*4 I, TIES, ROW, EXT, FLAG, K, NDWI
	CHARACTER*54 BUF
	CHARACTER*6 ENTRY(4)
	DATA ENTRY/'first ','second','third ','forth '/
C
C
	DO 100 I=1,TIES
	WRITE (BUF,900) ENTRY(I)
10	CONTINUE
	CALL INPNUM(BUF,ROW,1,MAXWRW,EXT)
	IF(EXT.NE.0.AND.EXT.NE.-5) GOTO 10
	IF(EXT.EQ.-5) THEN
	   TYPE *,' Event will be cancelled '
	   CALL WIMG(5,'Is this correct <Y/N> ')
	   CALL YESNO(FLAG)
	   IF(FLAG.NE.1) GOTO 10
	   IF (NDWI .EQ. 1) THEN
	    DWIWIN(1) = -1
	   ELSE IF (NDWI .EQ. 2) THEN
	    DWIHLD(1) = -1
	   ENDIF
	   GOTO 110
	ENDIF
	WRITE(5,901) ROW,(DWINMS(K,ROW),K=1,3)
	CALL WIMG(5,'Is this correct [Y/N] ')
	CALL YESNO(FLAG)
	IF(FLAG.NE.1) GOTO 10
	IF(WROWSTS(ROW,NDWI).EQ.GAMCAN.OR.WROWSTS(ROW,NDWI).EQ.GAMREF) THEN
	  WRITE(5,902) ROW,(DWINMS(K,ROW),K=1,3)
	  GOTO 10
	ENDIF
	IF (NDWI .EQ. 1) THEN
	  DWIWIN(I) = ROW
	ELSE IF (NDWI .EQ. 2) THEN
	  DWIHLD(I) = ROW
	ENDIF
100	CONTINUE
110	CONTINUE
C
900   FORMAT('Enter ',A6,' winning row number < C to Cancel Event > ')
901	FORMAT(' Row ',I2,1X,3A4)
902	FORMAT(' Sorry row ',I2,1X,3A4,' has been cancelled')
	END
