C
C SUBROUTINE WIN_OPNDRW
C $Log:   GXAFXT:[GOLS]WIN_OPNDRW.FOV  $
C  
C     Rev 1.0   17 Apr 1996 16:01:12   HXK
C  Release of Finland for X.25, Telephone Betting, Instant Pass Thru Phase 1
C  
C     Rev 1.0   21 Jan 1993 18:05:58   DAB
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - winsub.for **
C
C
C
C
C SUBROUTINE TO OPEN DRAW FILES FOR WINSEL.
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE WIN_OPNDRW(FILE,UNT)
	IMPLICIT NONE
C
 	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INTEGER*4 FILE(5), ST, UNT
C
	INTEGER*4   INPLEN
	INTEGER*4   I4FILE
	CHARACTER*4 CXFILE
	EQUIVALENCE (I4FILE,CXFILE)
C
10	CONTINUE
	CALL USRCLOS1(     UNT)
	CALL OPENW(UNT,FILE,5,0,0,ST)
	IF(ST.EQ.0) RETURN
C
C
	WRITE(5,900) IAM(),FILE,ST
	CALL PRMTEXT('Enter new draw pack volume name: ',CXFILE,INPLEN)
	FILE(1) = I4FILE
	WRITE(5,920) IAM(),FILE(1)
	CALL GPAUSE
	GOTO 10
C
C
900	FORMAT(1X,A,1X,5A4,' open error> ',I4)
920	FORMAT(1X,A,'Mount ',A4,' pack and continue WINSEL')
	END
