C
C SUBROUTINE WWIN_WININT
C
C V13 03-JUL-2000 UXN LWILAT added.
C V12 15-FEB-2000 UXN P(ODD_DRWPCK) added.
C V11 29-DEC-1999 OXK DRWSTS checking added.
C V10 13-DEC-1999 OXK MULTIWIN changes.
C V09 12-JUL-1999 UXN More variables initialized making possible to re-run
C                     WINSEL
C V08 27-APR-1999 RXK Call of INPNUM replaced with call of PRMNUM.
C                     Event # asked only if manual winner selection.
C V07 10-NOV-1997 UXN WINREP_AUTO,BKKREP_AUTO ADDED FOR AUTOMATED 
C	  	      WINRPT,BKKREP
C V06 03-JAN-1994 HXK INIT LWIWPO.
C V05 14-MAY-1992 GCAN CHANGED ROLL POOL AND BREAKAGE CALCULATION (PSTGDF)
C V04 22-APR-1992 GCAN FIXED BUG WITH VHOLD SETTING (WCHKWIN).
C V03 16-APR-1992 GCAN RE-RELEASED FOR THE NETHERLANDS.
C V02 07-OCT-1991 MTK  INITAL RELEASE FOR NETHERLANDS
C V01 01-AUG-1990 XXX  RELEASED FOR VAX
C
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C This item is the property of GTECH Corporation, Providence, Rhode
C Island, and contains confidential and trade secret information. It
C may not be transferred from the custody or control of GTECH except
C as authorized in writing by an officer of GTECH. Neither this item
C nor the information it contains may be used, transferred,
C reproduced, published, or disclosed, in whole or in part, and
C directly or indirectly, except as expressly authorized by an
C officer of GTECH, pursuant to written agreement.
C
C Copyright 1999 GTECH Corporation. All rights reserved.
C+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE WWIN_WININT(FILES,FILCNT)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:GLOBAL.DEF'
	INCLUDE 'INCLIB:CONCOM.DEF'
	INCLUDE 'INCLIB:WITCOM.DEF'
	INCLUDE 'INCLIB:WINCOM.DEF'
	INCLUDE 'INCLIB:DWIREC.DEF'
	INCLUDE 'INCLIB:RECDAF.DEF'
	INCLUDE 'INCLIB:GTNAMES.DEF'
	INCLUDE 'INCLIB:PRMAGT.DEF'
	INCLUDE 'INCLIB:STOPCOM.DEF'
C
	INTEGER*4 FDB(7)
	INTEGER*4 FILCNT, WVOL, GIND, DRAW, EXT, GNUM, ST, I, K
	INTEGER*4 CDC, INPLEN
	CHARACTER FILES(200)*20   
	CHARACTER STRING*50
	CHARACTER CXWVOL*4
	EQUIVALENCE (WVOL,CXWVOL)
	INTEGER*4 AWNTAB(2,NUMAGT)
	COMMON/BIGWIN/ AWNTAB
C
C
	CALL FASTSET(0,AWNTAB,2*NUMAGT)
	CALL FASTSET(-1000,LWIDRW,NUMWIT)
	FILCNT=0
	WVOL=P(ODD_DRWPCK)
C
C
	DO 100 GIND=1,NUMWIT
	   GNUM=GTNTAB(TWIT,GIND)
	   IF(GNUM.LT.1.OR.GNUM.GT.MAXGAM) GOTO 100
	   WREFUND(GIND)=.FALSE.

           IF(STOPMOD.EQ.WINMANUAL) THEN
	      WRITE (STRING,800) (GLNAMES(K,GNUM),K=1,4),GIND
	      CALL PRMNUM(STRING,DRAW,1,999999,EXT)
	      IF(EXT.LT.0) GOTO 100
           ELSE
              DRAW = DRWGAM(MLWININD,GNUM)
              IF ((DRWSTS(MLWININD,GNUM).NE.WINYES).AND.
     *            (DRWSTS(MLWININD,GNUM).NE.WINPRV)) DRAW=0
              IF(DRAW.EQ.0) GOTO 100
           ENDIF

	   WRITE(6,930) IAM(),GTNAMES(TWIT),GIND,DRAW
	   CALL OPENW(1,GFNAMES(1,GNUM),4,0,0,ST)
	   CALL IOINIT(FDB,1,DWISEC*256)
	   IF(ST.NE.0) CALL FILERR(GFNAMES(1,GNUM),1,ST,0)
	   CALL READW(FDB,DRAW,DWIREC,ST)
	   IF(ST.NE.0) CALL FILERR(GFNAMES(1,GNUM),2,ST,DRAW)
	   CALL LOGGAM(TWIT,GIND,DWIREC,LWISTS)
	   IF(LWISTS(GIND).EQ.GAMCAN.OR.
     *        LWISTS(GIND).EQ.GAMREF) THEN
	      WREFUND(GIND)=.TRUE.
	   ELSE
	      DO 105 I=1,MAXWRW
		 IF(LWISTA(I,GIND).EQ.GAMCAN.OR.
     *		    LWISTA(I,GIND).EQ.GAMREF) THEN
		    WREFUND(GIND)=.TRUE.
		    WRITE(6,910) IAM(),GTNAMES(TWIT),GIND,I
		 ENDIF
105	      CONTINUE
	   ENDIF
	   IF( LWISTS(GIND).LT.GAMENV.OR.
     *	       LWISTS(GIND).EQ.GFINAL.OR.
     *	       LWISTS(GIND).EQ.GAMREF) THEN
	       WRITE(6,920) IAM(),GTNAMES(TWIT),GIND,LWISTS(GIND),GAMENV
	       CALL GPAUSE
	   ENDIF

           IF(LWISTS(GIND).EQ.GAMREF) LWISTS(GIND) = GAMCAN

           IF(LWILAT(LATCDC,GIND).GT.0) WREFUND(GIND) = .TRUE.	    
	   LWILAT(LATCNT,GIND) = 0
	   LWILAT(LATAMT,GIND) = 0

	   LWISAL(GIND)=0
	   LWITAX(GIND)=0

           LWIREF(GIND)   = 0
           LWIWON(GIND)   = 0

           CALL FASTSET(0,LWIWRA(1,1,GIND),NUMTOT*2)
           CALL FASTSET(0,LWIWPR(1,1,GIND),NUMTOT*2)
           CALL FASTSET(0,LWIWRO(1,1,GIND),NUMTOT*2)
           CALL FASTSET(0,LWIWPA(1,1,GIND),NUMTOT*2)

           CALL FASTSET(0,LWIWPO(1,1,GIND),NUMTOT*2)
	   CALL FASTSET(0,LWISBR(1,GIND),MAXWRW)
	   IF(WVOL.EQ.0) THEN
	      WRITE(STRING,810) (GLNAMES(K,GNUM),K=1,4),GIND
	      CALL PRMTEXT(STRING,CXWVOL,INPLEN)
	   ENDIF
	   CALL CLOSEFIL(FDB)
C
C
	   CALL OPENW(1,SFNAMES(1,DAF),4,0,0,ST)
	   CALL IOINIT(FDB,1,DAFSEC*256)
	   IF(ST.NE.0) CALL FILERR(SFNAMES(1,DAF),1,ST,0)
	   DO 90 CDC=LWIBSD(GIND),LWIESD(GIND)
	      CALL READW(FDB,CDC,DAFREC,ST)
	      IF(ST.NE.0) CALL FILERR(SFNAMES(1,DAF),2,ST,CDC)
	      IF(DAFSTS.EQ.DNOSAL) GOTO 90
	      IF(DAFSTS.EQ.DSOPEN) GOTO 90
	      FILCNT=FILCNT+1
	      WRITE (FILES(FILCNT),900) WVOL,GSNAMES(GNUM),CDC
90	   CONTINUE
	   CALL CLOSEFIL(FDB)
	   WINREP_AUTO(GNUM) = DRAW
	   BKKREP_AUTO(GNUM) = DRAW
100	CONTINUE
C
C
800	FORMAT('Enter ',4A4,I1,' event code (E-none)    ')
810	FORMAT('Enter ',4A4,I1,' draw pack volume name: ')
900	FORMAT(A4,':',A4,I4.4,'.FIL')
910	FORMAT(1X,A,1X,A8,I1,' refund scan for row ',I2)
920	FORMAT(1X,A,1X,A8,I1,' invalid game status> ',I4,' should be> ',I4)
930	FORMAT(1X,A,1X,'Loading game date for ',A8,I1,' event> ',I4,
     *	       ' winner selection')
940	FORMAT(A4)
	END
