C
C SUBROUTINE X2FCLOS1
C  Initial Release
C  Based on Netherlands Bible, 12/92, and Comm 1/93 update
C  DEC Baseline
C
C ** Source - x2xfile.for;1 **
C
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE X2FCLOS1(FDB)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
	INCLUDE 'INCLIB:X2FCOM.DEF'
C
	INTEGER*4 FDB(*)
C
	CALL USRCLOS1(X2FRLUN)
	RETURN
	END
