C
C SUBROUTINE X2TES_UPDSTN
C
C*************************** START X2X PVCS HEADER ****************************
C
C  $Logfile::   GXAFXT:[GOLS]X2TES_UPDSTN.FOV                             $
C  $Date::   17 Apr 1996 16:38:46                                         $
C  $Revision::   1.0                                                      $
C  $Author::   HXK                                                        $
C
C**************************** END X2X PVCS HEADER *****************************
C
C ** Source - x2tesnet.for **
C
C V04 12-DEC-94 DAS Integrate UK changes into X2X Baseline
C
C ===========================================================
C X2TES_UPDSTN
C
C This routine will update the station record.
C
C=======OPTIONS /CHECK=NOOVERFLOW
	SUBROUTINE X2TES_UPDSTN(STN,STNADR,STNCLS,GROUP,PVC_PORT,
     *                          BROENA,STYPE,DNIC,X2XSCL_LOC)
	IMPLICIT NONE
C
	INCLUDE 'INCLIB:SYSPARAM.DEF'
	INCLUDE 'INCLIB:SYSEXTRN.DEF'
C
	INCLUDE 'INCLIB:X2XCOM.DEF'
	INCLUDE 'INCLIB:X2XSTN.DEF'
	INCLUDE 'INCLIB:X2XSCL.DEF'
C
	INTEGER*4    ERR, GROUP, STNCLS, STNADR, STN
	INTEGER*4    PVC_PORT,OFF
	INTEGER*4    X2XSCL_LOC(128)
	CHARACTER    STNADD*16
	INTEGER*4    DNIC, BROENA, STYPE
	CHARACTER    CHRSTR(16)*1
	EQUIVALENCE (STNADD,CHRSTR)
C
C
C FILL IN ALL STATION FIELDS.
C
	DO 100 OFF=1,128
	X2XSCL_REC(OFF)=X2XSCL_LOC(OFF)
100	CONTINUE
C
	DO 110 OFF=1,16
	CHRSTR(OFF)=' '
110 	CONTINUE
C
	X2XSTN_STN = STN
	X2XSTN_ADDLEN  = X2XSCL_ADDLEN
	X2XSTN_ADDRES(1) = 0
	X2XSTN_ADDRES(2) = 0
	IF(X2XSTN_ADDLEN.EQ.8) THEN
	  WRITE (STNADD,'(I4.4,I4.4,I8.8)') DNIC,STNADR,0
	  CALL ATOH(CHRSTR,1,8,X2XSTN_ADDRES,ERR)
	ELSE IF(X2XSTN_ADDLEN.EQ.9) THEN
	  WRITE (STNADD,'(I4.4,I5.5,I7.7)') DNIC,STNADR,0
	  CALL ATOH(CHRSTR,1,9,X2XSTN_ADDRES,ERR)
	ELSE IF(X2XSTN_ADDLEN.EQ.10) THEN
	  WRITE (STNADD,'(I4.4,I6.6,I6.6)') DNIC,STNADR,0
	  CALL ATOH(CHRSTR,1,10,X2XSTN_ADDRES,ERR)
	ELSE IF(X2XSTN_ADDLEN.EQ.11) THEN
	  WRITE (STNADD,'(I4.4,I7.7,I5.5)') DNIC,STNADR,0
	  CALL ATOH(CHRSTR,1,11,X2XSTN_ADDRES,ERR)
	ELSE IF(X2XSTN_ADDLEN.EQ.12) THEN
	  WRITE (STNADD,'(I4.4,I8.8,I4.4)') DNIC,STNADR,0
	  CALL ATOH(CHRSTR,1,12,X2XSTN_ADDRES,ERR)
	ELSE IF(X2XSTN_ADDLEN.EQ.13) THEN
	  WRITE (STNADD,'(I4.4,I9.9,I3.3)') DNIC,STNADR,0
	  CALL ATOH(CHRSTR,1,13,X2XSTN_ADDRES,ERR)
	ELSE IF(X2XSTN_ADDLEN.EQ.14) THEN
	  WRITE (STNADD,'(I4.4,I10.10,I2.2)') DNIC,STNADR,0
	  CALL ATOH(CHRSTR,1,14,X2XSTN_ADDRES,ERR)
	ELSE IF(X2XSTN_ADDLEN.EQ.15) THEN
	  WRITE (STNADD,'(I4.4,I11.11,I1.1)') DNIC,STNADR,0
	  CALL ATOH(CHRSTR,1,15,X2XSTN_ADDRES,ERR)
	ELSE IF(X2XSTN_ADDLEN.EQ.16) THEN
	  WRITE (STNADD,'(I4.4,I12.12)') DNIC,STNADR
	  CALL ATOH(CHRSTR,1,16,X2XSTN_ADDRES,ERR)
	ELSE
	  WRITE (STNADD,'(I16.16)') 0
	  CALL ATOH(CHRSTR,1,16,X2XSTN_ADDRES,ERR)
	ENDIF
C
	X2XSTN_SERIAL  = STN
        X2XSTN_GROUP   = GROUP
	X2XSTN_STNCLS  = STNCLS
	X2XSTN_PVC     = 0
	X2XSTN_PVCPORT = PVC_PORT
	X2XSTN_TYPE    = X2XSCL_TYPE
	X2XSTN_DELACK  = X2XSCL_DELACK
	X2XSTN_ERRREP  = X2XSCL_ERRREP
	X2XSTN_STNDIS  = X2XSCL_STNDIS
	X2XSTN_FEDIS   = X2XSCL_FEDIS
	X2XSTN_NETPT1  = X2XSCL_NETPT1
	X2XSTN_NETPT2  = X2XSCL_NETPT2
	X2XSTN_NETPT3  = X2XSCL_NETPT3
	X2XSTN_NETPT4  = X2XSCL_NETPT4
	X2XSTN_NETPT5  = X2XSCL_NETPT5
	X2XSTN_NETPT6  = X2XSCL_NETPT6
	X2XSTN_NETPT7  = X2XSCL_NETPT7
	X2XSTN_NETSTAT = X2XSCL_NETSTAT
	X2XSTN_AUTOUPD = X2XSCL_AUTOUPD
        X2XSTN_DEF_PORT1 = X2XSCL_NETPT1
        X2XSTN_DEF_PORT2 = X2XSCL_NETPT2
	X2XSTN_DIAL_PORT1 = X2XSCL_DIAL_PORT1
        X2XSTN_DIAL_PORT2 = X2XSCL_DIAL_PORT2
        X2XSTN_EVSN_LEN = X2XSCL_EVSN_LEN
        X2XSTN_PRTFLG  = X2X_NONE_PRINT
        X2XSTN_STATE   = X2XS_IDLE
	X2XSTN_BCST_ENABLE = BROENA
	X2XSTN_STATION_TYPE = STYPE
        X2XSTN_BITMAP  = 0
        X2XSTN_BITMAP2 = 0
        X2XSTN_BITMAP3 = 0
	RETURN
	END
